on player walk:
	if metadata value "Stun" of player is true:
		cancel event
	if {zolnierze::%player%::*} is set:
		set {_yaw} to player's yaw
		set {_pitch} to player's pitch
		loop {zolnierze::%player%::*}:
			set {_loc} to location of loop-value
			set y-coordinate of {_loc} to (y-coordinate of {_loc} - 0.4)
			teleport {zolnierz::owner::%uuid of loop-value%} to {_loc}
			wait 1 tick
			if {conqueringsands::%uuid of loop-value%} is not true:
				if loop-value is on ground:
					set {_loc} to location of loop-value
					set yaw of {_loc} to {_yaw}
					set pitch of {_loc} to {_pitch}
					teleport loop-value to {_loc}
	if {chatbubbles::%player%::*} is set:
		set {_locThen} to location of player
		wait 1 tick
		set {_locNow} to location of player
		loop {chatbubbles::%player%::*}:
			set {_x} to (x-coordinate of {_locNow}) - (x-coordinate of {_locThen})
			set {_y} to (y-coordinate of {_locNow}) - (y-coordinate of {_locThen})
			set {_z} to (z-coordinate of {_locNow}) - (z-coordinate of {_locThen})
			move entity with id loop-value by {_x}*4096 {_y}*4096 {_z}*4096 for all players
on rightclick:
	set yaml value "Model Types.Short.Level" in "ModelHeights" to 0.5
	set yaml value "Model Types.Short.HP" in "ModelHeights" to -0.15
	save yaml "ModelHeights"

on entity move:
	if metadata value "Stun" of event-entity is set:
		cancel event
	set {_entity} to string tag "ECTextAbove" of custom nbt of event-entity parsed as entity
	if {_entity} is set:
		set {_loc} to location of event-entity
		set {_eyeLoc} to event-entity.getEyeLocation()

		set {_entityType} to "%type of event-entity%"
		
		loop yaml node keys "Model Types" in "ModelHeights":
			if yaml list "Model Types.%loop-value%.List" in "ModelHeights" contains {_entityType}:
				set {_hpBarOffset} to yaml value "Model Types.%loop-value%.HP" in "ModelHeights"
				set {_levelOffset} to yaml value "Model Types.%loop-value%.Level" in "ModelHeights"
				stop loop

		increase {_eyeLoc}'s y-coordinate by {_hpBarOffset}
		teleport {_entity} to {_eyeLoc}

		if boolean tag "ECMob" of custom nbt of event-entity is set:
			if boolean tag "ECDungeonMob" of custom nbt of event-entity is set:
				if metadata value "ECPulled" of event-entity is not set:
					cancel event

		if string tag "ECTextAboveLevel" of custom nbt of event-entity is set:
			set {_entity} to string tag "ECTextAboveLevel" of custom nbt of event-entity parsed as entity
			
			increase {_eyeLoc}'s y-coordinate by {_levelOffset}
			teleport {_entity} to {_eyeLoc}
			
		if string tag "ECTextAboveCastBar" of custom nbt of event-entity is set:
			wait 1 tick
			set {_loc} to location of event-entity
			set {_entity} to string tag "ECTextAboveCastBar" of custom nbt of event-entity parsed as entity
			if long tag "ECModelHeight" of custom nbt of event-entity is set:
				set {_increase} to 1
				if long tag "ECCastBarExtraHeight" of custom nbt of event-entity is set:
					add long tag "ECCastBarExtraHeight" of custom nbt of event-entity to {_increase}
				increase {_loc}'s y-coordinate by (long tag "ECModelHeight" of custom nbt of event-entity) + {_increase}
			else:
				increase {_loc}'s y-coordinate by 2.05
			teleport {_entity} to {_loc}
	if any:
		uuid tag "ECEntityTitle" of custom nbt of event-entity is set
		{ECEntityTitle::%uuid of event-entity%} is set
	then:
		set {_title} to (uuid tag "ECEntityTitle" of custom nbt of event-entity) parsed as entity
		set {_y} to (double tag "ECEntityTitleHeight" of custom nbt of event-entity) + y-coordinate of event-entity + 2.35
		if {_title} is not set:
			set {_title} to {ECEntityTitle::%uuid of event-entity%} parsed as entity
			set {_y} to {_y}-1.25
		set {_loc} to location((x-coordinate of event-entity), {_y}, (z-coordinate of event-entity), world "%event-entity's world%")
		teleport {_title} to {_loc}
	if metadata value "Rider" of event-entity is set:
		set {_rider} to (metadata value "Rider" of event-entity) parsed as entity
		set {_loc} to location of {_rider}
		set {_entity} to string tag "ECTextAboveLevel" of custom nbt of {_rider} parsed as entity
		if long tag "ECModelHeight" of custom nbt of {_rider} is set:
			increase {_loc}'s y-coordinate by (long tag "ECModelHeight" of custom nbt of {_rider}) + 0.5
		else:
			increase {_loc}'s y-coordinate by 2.05
		teleport {_entity} to {_loc}
		set {_entity} to string tag "ECTextName" of custom nbt of {_rider} parsed as entity
		if long tag "ECModelHeight" of custom nbt of {_rider} is set:
			increase {_loc}'s y-coordinate by (long tag "ECModelHeight" of custom nbt of {_rider}) - 0.25
		else:
			increase {_loc}'s y-coordinate by 1.80
		teleport {_entity} to {_loc}
		set {_entity} to string tag "ECTextAbove" of custom nbt of {_rider} parsed as entity
		if long tag "ECModelHeight" of custom nbt of {_rider} is set:
			increase {_loc}'s y-coordinate by (long tag "ECModelHeight" of custom nbt of {_rider}) - 0.25
		else:
			increase {_loc}'s y-coordinate by 1.55
		teleport {_entity} to {_loc}
	if boolean tag "WinterPet" of custom nbt of event-entity is set:
		if cooldown "JingleSound%event-entity%" is finished:
			create cooldown "JingleSound%event-entity%" for 0.25 seconds
			play sound "pet.winterpet_jingle" with volume 2 and pitch 1 at event-entity
			play sound "pet.winterpet_bell" with volume 2 and pitch 1 at event-entity
		if cooldown "FootstepSound%event-entity%" is finished:
			create cooldown "FootstepSound%event-entity%" for 0.25 seconds
			play sound "pet.winterpet_footstep" with volume 1.5 and pitch 1 at event-entity
	else if boolean tag "ECFrostKnight" of custom nbt of event-entity is set:
		if cooldown "ClingSound%event-entity%" is finished:
			create cooldown "ClingSound%event-entity%" for 0.5 seconds
			play sound "item.armor.equip_iron" with volume 1.75 and pitch 0.5 at event-entity
	else if boolean tag "ECMingHua" of custom nbt of event-entity is set:
		if cooldown "WaterTentacleSound%event-entity%" is finished:
			set {_pitch} to a random number between 0.8 and 1.2
			set {_cd} to a random number between 0.5 and 0.75
			set {_cd} to "%{_cd}% seconds" parsed as timespan
			create cooldown "WaterTentacleSound%event-entity%" for {_cd}
			play sound "block.water.ambient" with volume 1.75 and pitch {_pitch} at event-entity
	if event-entity is a sheep:
		if "%region at block under event-entity%" contains "DreamcatcherPlatforms":
			loop all blocks in radius 6 around the event-entity where [input = blue glazed terracotta]:
				if ("%regions at loop-block%") = ("%regions at block under event-entity%"):
					add loop-block to {_blocks::*}
			if {_blocks::*} is set:
				play sound "block.stone_pressure_plate.click_off" with volume 4 and pitch 1 at block under event-entity
				loop {_blocks::*}:
					set block at loop-value to yellow wool
				wait 1.25 second
				play sound "block.stone_pressure_plate.click_off" with volume 4 and pitch 1.5 at block under event-entity
				loop {_blocks::*}:
					set block at loop-value to orange wool
				wait 1.25 seconds
				play sound "block.stone_pressure_plate.click_off" with volume 4 and pitch 2 at block under event-entity
				loop {_blocks::*}:
					set block at loop-value to red wool
				wait 1.25 second
				play sound "block.stone.break" with volume 3 and pitch 0.8 at block under event-entity
				loop {_blocks::*}:
					set block at loop-value to air
					spawn falling block of blue glazed terracotta at loop-value
					FallingBlockDelete(last spawned falling blue glazed terracotta)
				play sound "block.lava.extinguish" with volume 3 and pitch 1 at block under event-entity
				wait 5 seconds
				loop {_blocks::*}:
					set block at loop-value to blue glazed terracotta
	#else if name of event-entity = "Homing Missile":
		#if event-entity is a bee:
			#push event-entity in event-entity's direction with speed 0.075

on damage:
	if damage cause is suffocation:
		victim is a player:
			cancel event

function canBeCCed(e: entity) :: boolean:
	set {_canbeCCed} to true
	if boolean tag "ECBoss" of custom nbt of {_e} is true:
		set {_canbeCCed} to false
	else if boolean tag "ECMiniBoss" of custom nbt of {_e} is true:
		set {_canbeCCed} to false
	else if boolean tag "ECImmuneToCC" of custom nbt of {_e} is true:
		set {_canbeCCed} to false
	else if int tag "ECDungeonInstance" of custom nbt of {_e} is set:
		set {_instance} to int tag "ECDungeonInstance" of custom nbt of {_e}
		if {affixes%{_instance}%::*} contains "Inspiring":
			loop all entities in radius 6 around {_e} where [boolean tag "InspiringMob" of custom nbt of input is true]:
				if loop-entity != {_e}:
					broadcast "P"
					set {_canbeCCed} to false
					stop loop
	return {_canBeCCed}

on input key press:
	if metadata value "Hypercognition" of player is set:
		play sound "block.note_block.hat" with volume 3 and pitch 1 to player
		set {_completed} to metadata value "HypercognitionCompletedActions" of player
		set {_actionIndex} to {_completed} + 1
		broadcast {_actionIndex}
		set {_action} to metadata value "HypercognitionKey%{_actionIndex}%" of player
		if {_action} != "left click" or "right click":
			set {_key} to join "%event-input keys%" by ""
			if {_action} = {_key}:
				broadcast "Yup"
				hypercognitionCompletedAction(player)
			else:
				set {_fail} to true
		else:
			set {_fail} to true
		if {_fail} = true:
			broadcast "&cOkropnie! Key! %event-input keys%!"
			play sound "block.note_block.didgeridoo" with volume 1 and pitch 1 to player
			play sound "block.note_block.hat" with volume 1 and pitch 1 to player
			hypercognitionEnd(player, "fail")
	if metadata value "mining" of player is set:
		set {_keys} to join "%event-input keys%" by ""
		set {_cancelAction::*} to "forward movement key", "backward movement key", "left movement key", "right movement key"
		if {_keys} contains any of {_cancelAction::*}:
			clear metadata value "mining" of player