command /adm:
	trigger:
		#give light blue dye named "&bOriblase" with lore "&8Gem" and "&9Poziom Przedmiotu 2" and "<##11d7d8>+1 Kontrola Tłumu" and "" and "&fWymaga 1 poziomu na karcie" with nbt "{CustomModelData:1}" to player
		#give {szlifiarka} to player
		#broadcast "%{kamieniesz::*}%"
		#remove "Jubilerstwo" from {profesje::%player%::*}
		#add "JUBILERSTWO" to {profesje::%player%::*}
		#set {jubilerstwo::delikatny::%player%} to 
		#loop all entities in radius 3 around the player:
			#loop-entity is armor stand:
				#kill loop-entity
				#set tool of loop-entity to air
				#set helmet of loop-entity to air
		#spawn 1 armor stand at player
		#add nbt compound from "{Invisible:1}" to nbt of last spawned armor stand
		#add nbt compound from "{NoGravity:1}" to nbt of last spawned armor stand
		#set display name of last spawned armor stand to "GROVE OF IMMEMORIAL RUINS" 
		#stop
		spawn 1 armor stand at target pig of player
		add nbt compound from "{Invisible:1}" to nbt of last spawned armor stand
		add nbt compound from "{NoGravity:1}" to nbt of last spawned armor stand
		#add "{NoBasePlate:1b,ShowArms:1b,DisabledSlots:2039583,Pose:{LeftLeg:[0f,0f,277f],RightLeg:[0f,0f,83f]}}" to nbt of last spawned armor stand
		add nbt compound from "{NoBasePlate:1b,ShowArms:1b,Pose:{LeftLeg:[0f,0f,338f],RightLeg:[0f,0f,24f]}}" to nbt of last spawned armor stand
		#set the display name of last spawned armor stand to "'Brodaty' Zachary"
		set the display name of last spawned armor stand to "&e<Definitely not Santa>"
		set {_x} to y-coordinate of last spawned armor stand
		#set {_x} to {_x} - 0.10
		set {_x} to {_x} - 0.4
		set {_y} to x-coordinate of last spawned armor stand
		set {_z} to z-coordinate of last spawned armor stand
		broadcast "A"
		teleport the last spawned armor stand to location({_y}, {_x}, {_z}, world "%world of player%")

		stop

		

		spawn 1 armor stand at target player
		add nbt compound from "{Invisible:1}" to nbt of last spawned armor stand
		add nbt compound from "{NoGravity:1}" to nbt of last spawned armor stand
		#add "{NoBasePlate:1b,ShowArms:1b,DisabledSlots:2039583,Pose:{LeftLeg:[0f,0f,277f],RightLeg:[0f,0f,83f]}}" to nbt of last spawned armor stand
		add nbt compound from "{NoBasePlate:1b,ShowArms:1b,Pose:{LeftLeg:[0f,0f,338f],RightLeg:[0f,0f,24f]}}" to nbt of last spawned armor stand
		#set the display name of last spawned armor stand to "'Brodaty' Zachary"
		set the display name of last spawned armor stand to "&fWheat: &a4$ &7| &fSeeds: &c0.2$"
		set {_x} to y-coordinate of last spawned armor stand
		#set {_x} to {_x} - 0.10
		set {_x} to {_x} + 0.4
		set {_y} to x-coordinate of last spawned armor stand
		set {_z} to z-coordinate of last spawned armor stand
		broadcast "A"
		teleport the last spawned armor stand to location({_y}, {_x}, {_z}, world "%world of player%")
		set {festivePrices} to uuid of last spawned armor stand


		spawn 1 armor stand at target player
		add nbt compound from "{Invisible:1}" to nbt of last spawned armor stand
		add nbt compound from "{NoGravity:1}" to nbt of last spawned armor stand
		#add "{NoBasePlate:1b,ShowArms:1b,DisabledSlots:2039583,Pose:{LeftLeg:[0f,0f,277f],RightLeg:[0f,0f,83f]}}" to nbt of last spawned armor stand
		add nbt compound from "{NoBasePlate:1b,ShowArms:1b,Pose:{LeftLeg:[0f,0f,338f],RightLeg:[0f,0f,24f]}}" to nbt of last spawned armor stand
		#set the display name of last spawned armor stand to "'Brodaty' Zachary"
		set the display name of last spawned armor stand to "&fNew market prices in &b00:41"
		set {_x} to y-coordinate of last spawned armor stand
		#set {_x} to {_x} - 0.10
		set {_x} to {_x}
		set {_y} to x-coordinate of last spawned armor stand
		set {_z} to z-coordinate of last spawned armor stand
		broadcast "A"
		teleport the last spawned armor stand to location({_y}, {_x}, {_z}, world "%world of player%")
		set {festivePricesDuration} to uuid of last spawned armor stand
		#wait 5 seconds
		#spawn 1 armor stand at player
		#add "{NoBasePlate:1b,ShowArms:1b,Marker:1b,Pose:{Body:[71f,0f,0f],LeftLeg:[0f,0f,234f],RightLeg:[0f,0f,119f]}}" to nbt of last spawned armor stand
		#add "{NoBasePlate:1b,ShowArms:1b,Marker:1b,Pose:{Body:[71f,0f,0f],Head:[16f,0f,0f],LeftLeg:[242f,161f,182f],RightLeg:[247f,193f,153f],LeftArm:[303f,0f,0f],RightArm:[303f,0f,0f]}}" to nbt of last spawned armor stand
		#set {_x} to skull of "Krysta" parsed as offlineplayer
		#set last spawned armor stand's helmet to {_x}
		#set last spawned armor stand's chestplate to leather chestplate
		#set last spawned armor stand's leggings to leather leggings
		#set last spawned armor stand's boots to leather boots
		#add "{CustomNameVisible:1,NoGravity:1b,Small:1,Invisible:1,Invulnerable:1,NoBasePlate:1,DisabledSlots:2039583,Pose:{Head:[%pitch of player%f,0f,0f]}}" to nbt of last spawned armor stand
		#play sound "music.tchisismyboyfriendmelovin" with volume 2 and pitch 1.7 to player
		#give book named "&9Przepis: Pośpieszny Królewski Ametyst" with lore "&8Przepis" and "&6Poziom Przedmiotu 56" and "&aPPM: Uczy cię jak oszlifować" and "&aPośpieszny Królewski Ametyst." and "&fWymaga Jubilerstwo (30)" and "" and "&9Pośpieszny Królewski Ametyst" and "&6Poziom Przedmiotu 56" and "<##ae78d0>+4 Użyteczność" and "<##187a2f>+4 Pośpiech" and "" and "&fWymaga 22 poziomu na karcie" and "&6''Pasuje na każdą kartę.''" and "&fSprzedaż: 8" and "" and "&fCena: 120" with nbt "{CustomModelData:2}" to player
on rightclick on armor stand:
	if name of event-entity is set:
		cancel event
#on rightclick on sign:
#	if line 2 of clicked block = "Clear level":
#		clear {poziomjubilerstwo::%player%}
#		send "Ustawiono poziom jubilerstwa na 0."
#	if line 2 of clicked block = "30 level":
#		set {poziomjubilerstwo::%player%} to 30
#		send "Ustawiono poziom jubilerstwa na 30."
#	if line 2 of clicked block = "Max level":
#		set {poziomjubilerstwo::%player%} to 75
#		send "Ustawiono poziom jubilerstwa na 75."
command /adminator:
	trigger:
		loop all entities in radius 3 around player:
			if loop-entity is armor stand:
				kill loop-entity
		tornado(player, 3, 1, 4, 1)
		broadcast "%{_l::*}%"
		show 1 blue dust at {_l::*}

command /123test [<player>]:
	trigger:
		if player's name = "Pehrek" or "llamadegree":
			stop
			set tag "SkullOwner;Name" of nbt of player's tool to "953d5b82-210a-4f2f-8dc6-5e5bbe1e4caa"
			set tag "SkullOwner;Properties;textures;Signature" of nbt of player's tool to "DQQPKdl8fuSP5yaPWyHSsTm6SdpuhZ/BbgA14PGrbG1J0cLYJ/VOE8yyBUzPcHW6mv7Ujg+WCnKEtxVJoU5dJPhvM3COhNPkbiRbltir477umxHksr/6BTVtPMsa5Us2G572VNGY+5V6aFs13I1oCQ+SjbVABqBWd5+mMCF0ovyZA+q4dA+4XyqDypqwWwXvuGz98qaiq5gVMmlhfhyhpCwcEu+w30lIZmXVk7jc6PBBBWrLSUAR6uOKIVT68VaVcvQcNI9dW4SIRJ/Od3D9SYkHBbv8wIvN69amsOE36O/Vy+ewDSRYAF3jkeItevj1/6vox3YZwQzidAEsorlRqq4gm49ec90gXETDB8SBH4G7y59UXZImshhjkfJC17UVVN4sI1ASAtxIRK2AWiihhyMCO84mWSDkxjCXMl8D4mQPoWvSIeOVrv2q9bZk7d1NX8Vc6yom9NuA3JFbLarK8XFAjSveSXiSz7P31DJKXaXcMRA1Qz35/64eSsHrsxajtbTgY/l5WsXRvsBxHiXToRCy7cQbe8QdSdKnMzWoHFoGeKejuDOtQTQSJa/U5OuwGc5rb3d+ctZnv7OZ710kCgPDJZ62Fp5K4cUPF9Zj7tooGQzG9zsLMFJrf72gQTairE5K4OJ3Z+GdTq3qI3Ln+/Ianq2qSyenmoi9v1PUvvo="
			set tag "SkullOwner;Properties;textures;Value" of nbt of player's tool to "ewogICJ0aW1lc3RhbXAiIDogMTU5MDU4Mzk1NjMzNSwKICAicHJvZmlsZUlkIiA6ICI5MWYwNGZlOTBmMzY0M2I1OGYyMGUzMzc1Zjg2ZDM5ZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJTdG9ybVN0b3JteSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80ZDBhMzk3MTM1Y2E5YTlhODBhN2Y2MzNjNGFhMmQ0MTZkZDRiZDU1OWM4ZThmN2QzZDQyMjE2MzJkNmY3ZmZkIgogICAgfQogIH0KfQ="
			stop
			give player 12 of {odlamekgwiazdyEN}
			stop
			set {_ufGradient} to mini message from "<gradient:##d3449c:##433c3e>Unseen Forces Gengar Blister"
			set {_ufGradient2} to mini message from "<gradient:##d3449c:##433c3e>Unseen Forces Houndoom Blister"
			give player glass pane named {_ufGradient} with lore "&7Zanusz się w cieniach i odkryj siły ukryte w%nl%&7ciemności z trzema nowymi boosterami z rozszerzenia%nl%&7Unseen Forces, specjalną kartą promocyjną, oraz%nl%&7kolekcjonerską monetą, które możesz dodać%nl%&7do swojej kolekcji!%nl% %nl%&7Zawiera:%nl%&7- 3 Boostery z serii Unseen Forces%nl%&7- 1 karta promocyjna <##7627b7>Gengar%nl%&7- metaliczna moneta kolekcjonerska z serii Unseen Forces%nl% %nl%&7Detale:%nl%&7Wymiary przedmiotu: 19.3 cm x 1.27 cm x 17.78 cm%nl%&7Materiały: Papier / plastik%nl%&7Zalecany Wiek: 6+ Lat%nl%&7Waga: 76.5 gram"
			give player glass pane named {_ufGradient2} with lore "&7Zanusz się w cieniach i odkryj siły ukryte w%nl%&7ciemności z trzema nowymi boosterami z rozszerzenia%nl%&7Unseen Forces, specjalną kartą promocyjną, oraz%nl%&7kolekcjonerską monetą, które możesz dodać%nl%&7do swojej kolekcji!%nl% %nl%&7Zawiera:%nl%&7- 3 Boostery z serii Unseen Forces%nl%&7- 1 karta promocyjna <##9c4242>Houndoom%nl%&7- metaliczna moneta kolekcjonerska z serii Unseen Forces%nl% %nl%&7Detale:%nl%&7Wymiary przedmiotu: 19.3 cm x 1.27 cm x 17.78 cm%nl%&7Materiały: Papier / plastik%nl%&7Zalecany Wiek: 6+ Lat%nl%&7Waga: 76.5 gram"
			#give player grey glass pane named "&5Unseen Forces &2Blister Pack" with lore "&7Dive into the shadows and explore forces lurking%nl%&7in the dark with three awesome booster packs%nl%&7from the new Unseen Forces expansion, a special%nl%&7promo card, and a collector coin to add to your collection!%nl% %nl%&7Contains:%nl%&7- 3 Booster packs from the Unseen Forces expansion%nl%&7- 1 promo card featuring <##4e2e59>Crobat%nl%&7- a metallic Unseen Forces collector coin%nl% %nl%&7Details:%nl%&7Item dimensions: 19.3 cm x 1.27 cm x 17.78 cm%nl%&7Materials: Paper / plastic%nl%&7Recommended Age: 6+ Years%nl%&7Item Weight: 2.7 OZ"
			set {_ufGradient} to mini message from "<gradient:##d3449c:##433c3e>Unseen Forces Hoopa-Unbound Box"
			give player magenta glass pane named {_ufGradient} with lore "&7Zanusz się w cieniach i odkryj siły ukryte w%nl%&7ciemności z trzema nowymi boosterami z rozszerzenia%nl%&7Unseen Forces, specjalną kartą promocyjną, oraz%nl%&7kolekcjonerską monetą, które możesz dodać%nl%&7do swojej kolekcji!%nl% %nl%&7Zawiera:%nl%&7- 6 Boosterów z serii Unseen Forces%nl%&7- 1 Booster z serii Majestic Dawn%nl%&7- 1 Booster z serii Secret Wonders%nl%&7- 1 karta promocyjna <##bb3276>Hoopa-Unbound%nl%&7- 1 Odłamek Gwiazdy%nl% %nl%&7Detale:%nl%&7Wymiary przedmiotu: 53.59 cm x 3.81 cm x 22.86 cm%nl%&7Materiały: Papier / plastik%nl%&7Zalecany Wiek: 6+ Lat%nl%&7Waga: 317.5 gram"
			stop
			set {_ufGradient} to mini message from "<gradient:##d3449c:##433c3e>Unseen Forces Gengar Blister Pack"
			set {_ufGradient2} to mini message from "<gradient:##d3449c:##433c3e>Unseen Forces Houndoom Blister Pack"
			give player glass pane named {_ufGradient} with lore "&7Dive into the shadows and explore forces lurking%nl%&7in the dark with three awesome booster packs%nl%&7from the new Unseen Forces expansion, a special%nl%&7promo card, and a collector coin to add to your collection!%nl% %nl%&7Contains:%nl%&7- 3 Booster packs from the Unseen Forces expansion%nl%&7- 1 promo card featuring <##7627b7>Gengar%nl%&7- a metallic Unseen Forces collector coin%nl% %nl%&7Details:%nl%&7Item dimensions: 19.3 cm x 1.27 cm x 17.78 cm%nl%&7Materials: Paper / plastic%nl%&7Recommended Age: 6+ Years%nl%&7Item Weight: 2.7 OZ"
			give player glass pane named {_ufGradient2} with lore "&7Dive into the shadows and explore forces lurking%nl%&7in the dark with three awesome booster packs%nl%&7from the new Unseen Forces expansion, a special%nl%&7promo card, and a collector coin to add to your collection!%nl% %nl%&7Contains:%nl%&7- 3 Booster packs from the Unseen Forces expansion%nl%&7- 1 promo card featuring <##9c4242>Houndoom%nl%&7- a metallic Unseen Forces collector coin%nl% %nl%&7Details:%nl%&7Item dimensions: 19.3 cm x 1.27 cm x 17.78 cm%nl%&7Materials: Paper / plastic%nl%&7Recommended Age: 6+ Years%nl%&7Item Weight: 2.7 OZ"
			#give player grey glass pane named "&5Unseen Forces &2Blister Pack" with lore "&7Dive into the shadows and explore forces lurking%nl%&7in the dark with three awesome booster packs%nl%&7from the new Unseen Forces expansion, a special%nl%&7promo card, and a collector coin to add to your collection!%nl% %nl%&7Contains:%nl%&7- 3 Booster packs from the Unseen Forces expansion%nl%&7- 1 promo card featuring <##4e2e59>Crobat%nl%&7- a metallic Unseen Forces collector coin%nl% %nl%&7Details:%nl%&7Item dimensions: 19.3 cm x 1.27 cm x 17.78 cm%nl%&7Materials: Paper / plastic%nl%&7Recommended Age: 6+ Years%nl%&7Item Weight: 2.7 OZ"
			set {_ufGradient} to mini message from "<gradient:##d3449c:##433c3e>Unseen Forces Hoopa-Unbound Box"
			give player magenta glass pane named {_ufGradient} with lore "&7Dive into the shadows and explore forces lurking%nl%&7in the dark with six awesome booster packs%nl%&7from the new Unseen Forces expansion, a special%nl%&7promo card, and a star shard to add to your collection!%nl% %nl%&7Contains:%nl%&7- 6 Booster packs from the Unseen Forces expansion%nl%&7- 1 Booster pack from the Majestic Dawn expansion%nl%&7- 1 Booster pack from the Secret Wonders expansion%nl%&7- 1 promo card featuring <##bb3276>Hoopa-Unbound%nl%&7- 1 Star Shard%nl% %nl%&7Details:%nl%&7Item dimensions: 53.59 cm x 3.81 cm x 22.86 cm%nl%&7Materials: Paper / plastic%nl%&7Recommended Age: 6+ Years%nl%&7Item Weight: 0.7 LB"
			stop
			give player 10 of {odlamekgwiazdyEN}
			stop
			set {_karta} to {umbreonstarter}
			add nbt from "{Stats:{Strength:0,Health:0,Damage:0,Resistance:0,Mobility:0,Utility:0,'Crowd Control':0,Versatility:0,Mastery:0,'Critical Hit':0,Element:0,Haste:0,Avoidance:0,Total:0}}" to nbt of {_karta}
			set {_y} to data()
			set {_id} to random 8 char string from charset `0-9` `a-z`
			add "&8Id: %{_id}%" to lore of {_karta}
			add "&8Wydropiono: %{_y}%" to lore of {_karta}
			give {_karta} to player #
			set {_x} to "glow ink sac" parsed as item
			give player black dye named "<##555555>Night Hunter" with lore "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fPassive%nl%<##555555>When Umbreon kills an enemy, she%nl%<##555555>enters stealth for &f5 seconds<##555555>.%nl%<##555555>Umbreon's attacks deal &f15%% <##555555>increased damage%nl%<##555555>when she is invisible." with nbt from "{CustomModelData:2}"
			give player blaze rod named "<##555555>Night Slash" with lore "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &f3 seconds%nl%&7Use: &fRMB%nl%<##555555>Umbreon slashes her target with her claw%nl%<##555555>at short range, dealing &f3 <##333333>Dark <##555555>damage.%nl%<##555555>The enemy will take &f7.5%% <##555555>increased damage%nl%<##555555>from your upcoming Night Slash attacks for the%nl%<##555555>next &f6 seconds<##555555>." with nbt from "{CustomModelData:3}"
			give player glowstone dust named "<##555555>Moonlight Orb" with lore "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &f16 seconds%nl%&7Use: &fRMB%nl%<##555555>Umbreon creates a zone of moonlight at%nl%<##555555>target location, inflicting &f1 <##fffec8>Light <##555555>damage%nl%<##555555>to enemies caught in its radius and slowing them by &f30%%<##555555>.%nl%<##555555>Umbreon becomes invisible when she enters the zone.%nl%<##555555>Moonlight Orb lasts &f8 seconds<##555555>." with nbt from "{CustomModelData:3}"
			give player {_x} named "<##555555>End Game" with lore "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &f10 minutes%nl%&7Use: &fRMB%nl%<##555555>Umbreon executes all enemies below%nl%<##555555>&f25%% <##555555>health in an enormous radius.%nl%<##555555>All enemies in range are blinded for &f10 seconds<##555555>." with nbt from "{CustomModelData:1}"
			#set {_index} to 1
			#set {_lore::*} to uncolored lore of player's tool
			#loop {_lore::*}:
			#	set line {_index} of lore of player's tool to "<##b3d1ff>%loop-value%"
			#	add 1 to {_index}
			#
			stop
			loop all players:
				clear {weeklyStoneMined::%loop-player%}
				clear {weeklyMobsDefeated::%loop-player%}
			loop all offline players:
				clear {weeklyStoneMined::%loop-offline player%}
				clear {weeklyMobsDefeated::%loop-offline player%}
			stop
			set {_id} to tag "Id" of nbt of {_p}'s tool          
			load yaml "plugins/Skript/playerdata/karty/Ghazan/8q3s0s91.yml" as "k12"
			set {_constellation} to yaml value "Card.Constellation" in "k12"
			broadcast {_constellation}
			set {_constellation} to 0
			set yaml value "Card.Constellation" in "k12" to {_constellation}
			save yaml "k12"
			unload yaml "k12"
			stop
			#set {_cardLevel} to 48
			#set {_maxLevel} to 50
			#loop 2 times:
			#	set {_requiredExp} to 2 ^ (2.5*({_cardLevel}/{_maxLevel})+(round({_cardLevel}/({_maxLevel}/10), 0))+sqrt({_cardLevel}/(5)))+{_maxLevel}*{_cardLevel}*3
			#	broadcast "%{_requiredExp}% Required XP at Level %{_cardLevel}% (to %{_cardLevel}+1%"
			#	add 1 to {_cardLevel}
			#stop
			#loop 6 times:
			#	set yaml value "Player.Enderchests.%loop-number%" in "dataAdmin-%arg-1%" to "Owned"
			#	set yaml value "Enderchest %loop-number%.Owned" in "Enderchest%arg-1%" to "Owned"
			#save yaml "dataAdmin-%arg-1%"
			#save yaml "Enderchest%arg-1%"
			#give player 42 of {odlamekgwiazdyEN}
			#stop
			#save yaml "cardGear-%arg-1%"
			#unload yaml "cardGear-%arg-1%"
			#stop
			set {_id} to uncolored line 19 of lore of player's tool
			replace all "Id: " in {_id} with ""
			load yaml "plugins/Skript/playerdata/karty/%uncolored name of player's tool%/%{_id}%.yml" as "cardGear-%arg-1%"
			set yaml value "Card.Exp" in "cardGear-%arg-1%" to 12707.97
			set yaml value "Card.Level" in "cardGear-%arg-1%" to 6
			set tag "Level" of nbt of player's tool to 6
			save yaml "cardGear-%arg-1%"
			unload yaml "cardGear-%arg-1%"
			stop
			#stop
			#send "&aYou chose Glaceon as your starter!" to arg-1
			#set {_karta} to {glaceonstarterEN}
			#add nbt from "{Stats:{Intellect:0,Health:0,Damage:0,Resistance:0,Mobility:0,Utility:0,'Crowd Control':0,Versatility:0,Mastery:0,'Critical Hit':0,Element:0,Haste:0,Avoidance:0,Total:0}}" to nbt of {_karta}
			#set {_y} to data()
			#set {_id} to random 8 char string from charset `0-9` `a-z`
			#add "&8Id: %{_id}%" to lore of {_karta}
			#add "&8Dropped: %{_y}%" to lore of {_karta}
			#give {_karta} to arg-1
			#stop
			#set {_mastery} to 0
			#set {_shadowyApparitionsDamage} to 1
			#set {_pospiech} to 1
			#set {_SWPDamage} to 1
			#set {_tickTimeSWP} to 2/{_pospiech}
			#set {_SWPDuration} to 14
			#set {_channelTimeMF} to (3/{_pospiech})
			#set {_tickTimeMF} to ({_channelTimeMF}/4)/{_pospiech}
			#set {_MFDamage} to (0.5*4)
			#set {_MBDamage} to 2.5
			#set {_VTDamage} to 1
			#set {_tickTimeVT} to 3/{_pospiech}
			#set {_VTDuration} to 18
			#give arg-1 purple dye named "<##613e82>Shadowy Apparitions" with lore "&8Mastery Bonus%nl%<##613e82>When your Shadow Word: Pain damage%nl%<##613e82>over time critically strikes, you also create%nl%<##613e82>a shadowy version of yourself that floats%nl%<##613e82>towards the target and deals &f%{_shadowyApparitionsDamage}% <##613e82>damage." with nbt from "{CustomModelData:3}"
			#give arg-1 popped chorus fruit named "<##613e82>Voidform" with lore "&8Passive Ability%nl%&fNo cast%nl%&7Cooldown: &fnone%nl%&7Use: &fPassive%nl%<##613e82>Activated by casting Void Eruption.%nl%<##613e82>Increases all damage you deal by &f20%% <##613e82>and%nl%<##613e82>grants an additional &f1%% <##613e82>Haste every 1 sec.%nl%<##613e82>Your Insanity will drain increasingly fast until%nl%<##613e82>it reaches 0 <##613e82>and Voidform ends." with nbt from "{CustomModelData:3}"
			#give arg-1 light gray dye named "<##613e82>Mind Blast" with lore "&8Ability%nl%&f1.5 second cast%nl%&7Cooldown: &f9 seconds%nl%&7Use: &fRMB%nl%<##613e82>Blasts the target's mind for &f%{_MBDamage}%%nl%<##613e82>Shadow damage.%nl% %nl%&fGenerates 12 Insanity." with nbt from "{CustomModelData:3}"
			#give arg-1 orange dye named "<##613e82>Shadow Word: Pain" with lore "&8Ability%nl%&fInstant cast%nl%&7Global Cooldown: &f1.5 seconds%nl%&7Use: &fRMB%nl%<##613e82>A word of darkness that causes%nl%&f0.6 <##613e82>Shadow damage instantly, and an%nl%<##613e82>additional &f%(round({_SWPDuration}/{_tickTimeSWP}, 0))*{_SWPDamage}% <##613e82>Shadow damage over &f14 sec<##613e82>.%nl% %nl%&fGenerates 3 Insanity." with nbt from "{CustomModelData:5}"
			#give arg-1 gray dye named "<##613e82>Vampiric Touch" with lore "&8Ability%nl%&f1.5 second cast%nl%&7No cooldown%nl%&7Use: &fRMB%nl%<##613e82>A touch of darkness that causes &f%(round({_VTDuration}/{_tickTimeVT}, 0))*{_VTDamage}% <##613e82>Shadow%nl%<##613e82>damage over %{_VTDuration}% sec, <##613e82>and heals the priest for%nl%&f50%% <##613e82>of damage dealt.%nl% %nl%&fGenerates 6 Insanity." with nbt from "{CustomModelData:2}"
			#give arg-1 cyan dye named "<##613e82>Mind Flay" with lore "&8Ability%nl%&fChanneled%nl%&7No cooldown%nl%&7Use: &fRMB%nl%<##613e82>Assaults the target's mind with Shadow%nl%<##613e82>energy, causing &f%{_MFDamage}% <##613e82>Shadow damage over%nl%&f%{_channelTimeMF}% sec <##613e82>and slowing their movement speed%nl%<##613e82>by &f50%%<##613e82>.%nl% %nl%&fGenerates 8 Insanity over the duration." with nbt from "{CustomModelData:3}"
			#give arg-1 purple dye named "<##613e82>Void Eruption" with lore "&8Ultimate Ability%nl%&f2 second cast%nl%&7No cooldown%nl%&7Use: &fRMB%nl%<##613e82>Releases an explosive blast of pure void%nl%<##613e82>energy, activating Voidform and causing &f4%nl%<##613e82>Shadow damage to all enemies afflicted by%nl%<##613e82>your Shadow Word: Pain or Vampiric Touch.%nl% %nl%<##613e82>During Voidform, this ability is replaced%nl%<##613e82>by Void Bolt.%nl% %nl%&fRequires 90 Insanity to activate." with nbt from "{CustomModelData:9}"
			#give arg-1 black dye named "<##613e82>Void Bolt" with lore "&8Ultimate Ability%nl%&fInstant cast%nl%&7Cooldown: &f4.5 seconds%nl%&7Use: &fRMB%nl%<##613e82>Sends a bolt of pure void energy at the%nl%<##613e82>enemy, causing &f3 <##613e82>Shadow damage and%nl%<##613e82>extending the duration of Shadow Word: Pain%nl%<##613e82>and Vampiric Touch to their original duration.%nl%<##613e82>Requires Voidform.%nl% %nl%&fGenerates 16 Insanity." with nbt from "{CustomModelData:3}"
			#give player 3 of {odlamekgwiazdyEN}
			#stop
			#give player 3 of {odlamekgwiazdyEN}
			#give player brown dye named "<##b03228>Lava Wave" with lore "&8Talent Ability%nl%&fInstant cast%nl%&7Cooldown: &f1 minute%nl%&7Use: &fRMB%nl%<##b03228>Blast your target with a Lava Wave, which%nl%<##b03228>deals &f3 <##ff3014>Lava <##b03228>damage <##b03228>and applies Molten Lava%nl%<##b03228>upon reaching its target.%nl% %nl%<##b03228>Your next Lava Burst will also hit all targets%nl%<##b03228>affected by Molten Lava for 80%% of normal damage." with nbt from "{CustomModelData:4}"
			#stop
			#set {_msg} to mini message from "<gradient:##3758a6:##99c9ff>Jewelcrafting &f"
			#set {_msg} to mini message from "<gradient:##673299:##c499ff>Essences &f"
			#set {_msg} to mini message from "<gradient:##26ccff:##baf7ff>Gemstones &f"
			#set {_msg} to mini message from "<gradient:##7d7c77:##fbf9ef>Gemstones &f"
			#set {_msg} to mini message from "<gradient:##f54242:##ffa8a8>Misc &f🔥"
			#set the name of player's tool to {_msg}
			
			#stop
			#set {_lore} to "%nl%<##b03228>Transform into a Lava Ascendant for &f18 sec<##b03228>,%nl%<##b03228>removing the cooldown on Lava Burst and%nl%<##b03228>increasing the damage of Lava Burst by an%nl%<##b03228>amount equal to your critical strike chance.%nl% %nl%<##b03228>When you transform into the Lava Ascendant,%nl%<##b03228>instantly cast a Lava Burst at all enemies%nl%<##b03228>affected by your Molten Lava, and refresh%nl%<##b03228>your Molten Lava durations."
			#set {_item} to yellow dye named "<##b03228>Ascendance" with lore "                   %{_30}%%nl%                   %{_div}%%nl%&fInstant cast%nl%&7Cooldown: &f6 minutes%nl%&7Use: &fRMB%nl%&7Talent Ability%{_lore}%" with nbt from "{CustomModelData:5}"
			#give player {_item}

			#loop all offline players:
			#	clear {weeklystonemined::%loop-offline player%}
			#loop all players:
			#	clear {weeklystonemined::%loop-player%}
				#broadcast "%loop-offline player% %{totalStoneMined::%loop-player%}%"
			#stop
			#loop all players:
			#	load yaml "plugins/Skript/playerdata/admin/%uuid of loop-player%-Admin.yml" as "dataAdmin-%loop-player%"
			#	save yaml "dataAdmin-%loop-player%"
			#stop
			#set metadata value "MaterialAmount" of arg-1 to 0
			#stop
			#set the name of player's tool to "&fZach"
			#set the lore of player's tool to "&cHard%nl%&7Ahoy, you! How would you feel about a chance to%nl%&7practice your gemcutting? I was going to put on a%nl%&7display of various cuts, but it turned out we're%nl%&7short on gems. Mind lending us a hand with the%nl%&7demonstration? - Of course you'll be rewarded%nl%&7handsomely!%nl% %nl%&7Goal:%nl%&f- 0/60 Craft gems%nl% %nl%&7Reward for completing:%nl% <##a335ee>1 Illimited Diamond <##c2c2c2>★★%nl% &b300 Reputation%nl% %nl%&7Reputation:%nl%&f3 &a■■■■■■&7■■■■ &f4 &7(60%%)%nl% %nl%&7Next level reward:%nl%&c1 Star Shard"
			#stop
			#loop all players:
			#	give loop-player 3 of {odlamekgwiazdyEN}
			#loop all players:
			#	load yaml "plugins/Skript/playerdata/admin/%uuid of loop-player%-Admin.yml" as "dataAdmin-%loop-player%"
			#	save yaml "dataAdmin-%loop-player%"
			#stop
			#set {_id} to uncolored line 19 of lore of player's tool
			#replace all "Id: " in {_id} with ""
			#set tag "Id" of nbt of player's tool to {_id}
			#stop
			#clear tag "Stats" of nbt of player's tool
			
			set {_id} to uncolored line 19 of lore of player's tool
			replace all "Id: " in {_id} with ""
			load yaml "plugins/Skript/playerdata/karty/%uncolored name of player's tool%/%{_id}%.yml" as "cardGear-%player%"
			clear yaml value "Gear" in "cardGear-%player%"
			clear yaml value "Card.Gear" in "cardGear-%player%"
			save yaml "cardGear-%player%"
			unload yaml "cardGear-%player%"
			#set tag "Stats;Total" of nbt of player's tool to 426
			#set tag "Stats;Critical Hit" of nbt of player's tool to 192
			#set tag "Stats;Mastery" of nbt of player's tool to 178
			#set tag "Stats;Versatility" of nbt of player's tool to 0
			#set tag "Stats;Crowd Control" of nbt of player's tool to 0
			#set tag "Stats;Haste" of nbt of player's tool to 20
			#set tag "Stats;Damage" of nbt of player's tool to 0
			#set tag "Stats;Resistance" of nbt of player's tool to 0
			#set tag "Stats;Avoidance" of nbt of player's tool to 0
			#set tag "Stats;Element" of nbt of player's tool to 0
			#set tag "Stats;Health" of nbt of player's tool to 0
			#set tag "Stats;Mobility" of nbt of player's tool to 0
			#set tag "Stats;Utility" of nbt of player's tool to 0
			#set tag "Stats;Intellect" of nbt of player's tool to 36
			#set tag "Stats;GemsTotal" of nbt of player's tool to 126
			set tag "Stats;GearTotal" of nbt of player's tool to 7
			#loop all players:
			#	load yaml "plugins/Skript/playerdata/admin/%uuid of loop-player%-Admin.yml" as "dataAdmin-%loop-player%"
			#	save yaml "dataAdmin-%loop-player%"
			stop
			unload yaml "karta-%player%"
			set {_id} to uncolored line 19 of lore of player's tool
			replace all "Id: " in {_id} with ""
			load yaml "plugins/Skript/playerdata/karty/%uncolored name of player's tool%/%{_id}%.yml" as "karta-%player%"
			set yaml value "Card.Level" in "karta-%player%" to 19
			set tag "Level" of nbt of player's tool to 19
			set yaml value "Card.Exp" in "karta-%player%" to 6.71
			save yaml "karta-%player%"
			unload yaml "karta-%player%"
			stop
			stop
			set {_18} to line 19 of lore of player's tool
			set {_19} to line 20 of lore of player's tool
			#set {_statInt} to "&7Level: <##b03228>0 &7| &7Exp: <##b03228>0%nl%&7Statistics:%nl%&7Intellect: &7■■■■■■■■■■ &7(<##59c1e3>0&7)%nl%&7Health: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Damage: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Resistance: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobility: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Utility: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Crowd Control: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Versatility: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mastery: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Critical Hit: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Element: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Haste: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Avoidance: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
			#set lore of player's tool to "&7Master Lavabender" and {_statInt} and "&7Element: <##ff3014>Lava" and "&7Source: <##b03228>Stellar Chest" and {_18} and {_19}
			#set {_statInt} to "&7Level: <##7cafbf>0 &7| &7Exp: <##7cafbf>0%nl%&7Statistics:%nl%&7Intellect: &7■■■■■■■■■■ &7(<##7cafbf>0&7)%nl%&7Health: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Damage: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Resistance: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobility: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Utility: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Crowd Control: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Versatility: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mastery: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Critical Hit: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Element: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Haste: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Avoidance: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
			
			set {_statInt} to "&7Level: <##555555>0 &7| &7Exp: <##555555>0%nl%&7Statistics:%nl%&7Strength: &7■■■■■■■■■■ &7(<##e35959>0&7)%nl%&7Health: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Damage: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Resistance: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobility: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Utility: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Crowd Control: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Versatility: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mastery: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Critical Hit: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Element: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Haste: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Avoidance: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
			
			#set {_statInt} to "&7Level: <##555555>0 &7| &7Exp: <##555555>0%nl%&7Statistics:%nl%&7Strength: &7■■■■■■■■■■ &7(<##e35959>0&7)%nl%&7Health: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Damage: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Resistance: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobility: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Utility: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Crowd Control: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Versatility: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mastery: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Critical Hit: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Element: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Haste: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Avoidance: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
			
			#set {_statInt} to "&7Level: <##e53311>0 &7| &7Exp: <##e53311>0%nl%&7Statistics:%nl%&7Intellect: &7■■■■■■■■■■ &7(<##59c1e3>0&7)%nl%&7Health: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Damage: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Resistance: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobility: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Utility: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Crowd Control: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Versatility: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mastery: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Critical Hit: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Element: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Haste: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Avoidance: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
			
			#set lore of player's tool to "&7Night Huntress" and {_statInt} and "&7Element: <##333333>Dark" and "&7Source: <##555555>Level" and {_18} and {_19}
			#set lore of player's tool to "&7Fire Fox" and {_statInt} and "&7Element: <##ff4d00>Fire" and "&7Source: <##e53311>Level" and {_18} and {_19}

			#set {_statInt} to "&7Poziom: <##4bbfe2>0 &7| &7Exp: <##4bbfe2>0%nl%&7Statystyki:%nl%&7Intelekt: &7■■■■■■■■■■ &7(<##59c1e3>0&7)%nl%&7Zdrowie: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Obrażenia: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Wytrzymałość: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobilność: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Użyteczność: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Kontrola Tłumu: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Uniwersalność: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mistrzostwo: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Cios Krytyczny: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Żywioł: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Pośpiech: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Unik: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
			#set {_statInt} to "&7Poziom: <##7cafbf>0 &7| &7Exp: <##7cafbf>0%nl%&7Statystyki:%nl%&7Intelekt: &7■■■■■■■■■■ &7(<##59c1e3>0&7)%nl%&7Zdrowie: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Obrażenia: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Wytrzymałość: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobilność: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Użyteczność: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Kontrola Tłumu: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Uniwersalność: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mistrzostwo: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Cios Krytyczny: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Żywioł: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Pośpiech: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Unik: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
			#set {_statInt} to "&7Level: <##4bbfe2>0 &7| &7Exp: <##4bbfe2>0%nl%&7Statistics:%nl%&7Intellect: &7■■■■■■■■■■ &7(<##59c1e3>0&7)%nl%&7Health: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Damage: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Resistance: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobility: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Utility: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Crowd Control: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Versatility: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mastery: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Critical Hit: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Element: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Haste: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Avoidance: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
			#set lore of player's tool to "&7Świeży Śnieg" and {_statInt} and "&7Żywioł: <##add8e6>Lód" and "&7Źródło: <##4bbfe2>Starter" and {_18} and {_19}
			#set {_statInt} to "&7Poziom: <##555555>0 &7| &7Exp: <##555555>0%nl%&7Statystyki:%nl%&7Siła: &7■■■■■■■■■■ &7(<##e35959>0&7)%nl%&7Zdrowie: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Obrażenia: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Wytrzymałość: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobilność: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Użyteczność: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Kontrola Tłumu: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Uniwersalność: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mistrzostwo: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Cios Krytyczny: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Żywioł: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Pośpiech: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Unik: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
			#set lore of player's tool to "&7Strumień" and {_statInt} and "&7Żywioł: <##1ebbd7>Woda" and "&7Źródło: <##7cafbf>Starter" and {_18} and {_19}
			#set lore of player's tool to "&7Nocna Łowczyni" and {_statInt} and "&7Żywioł: <##333333>Mrok" and "&7Źródło: <##555555>Starter" and {_18} and {_19}

			#add nbt from "{DiamondShard:1b}" to nbt of player's tool
			#stop
			
			loop all loaded yaml:
				if loop-value does not contain "data-" or "dataAdmin" or "Enderchest" or "SOSspawnlocations":
					unload loop-value

				
			set {_id} to uncolored line 19 of lore of player's tool
			replace all "Id: " in {_id} with ""
			set {_card} to {kartaname::%player%}
			load yaml "plugins/Skript/playerdata/karty/%uncolored name of player's tool%/%{_id}%.yml" as "kartyLink-%player%"
			set yaml value "Card.Level" in "kartyLink-%player%" to 0
			set yaml value "Card.Exp" in "kartyLink-%player%" to 0
			set tag "Level" of nbt of player's tool to 0
			save yaml "kartyLink-%player%"
			unload yaml "kartyLink-%player%"


			set {_id} to line 19 of lore of player's tool
			broadcast {_id}
			broadcast {crit::kamienie::%{_id}%}
			drop {crit::kamienie::%{_id}%} of {cytrynEN} at arg-1
			clear {crit::kamienie::%{_id}%}
			set {_st} to tag "Stats;Critical Hit" of nbt of player's tool
			remove {crit::kamienie::%{_id}%} from {_st}
			set tag "Stats;Critical Hit" of nbt of player's tool to {_st}

			drop {zywiol::kamienie::%{_id}%} of {awenturynEN} at arg-1
			clear {zywiol::kamienie::%{_id}%}
			set {_st} to tag "Stats;Element" of nbt of player's tool
			remove {zywiol::kamienie::%{_id}%} from {_st}
			set tag "Stats;Element" of nbt of player's tool to {_st}

			drop {obrazenia::kamienie::%{_id}%} of {rubinEN} at arg-1
			clear {obrazenia::kamienie::%{_id}%}
			set {_st} to tag "Stats;Damage" of nbt of player's tool
			remove {obrazenia::kamienie::%{_id}%} from {_st}
			set tag "Stats;Damage" of nbt of player's tool to {_st}

			drop {zdrowie::kamienie::%{_id}%} of {perydotEN} at arg-1
			clear {zdrowie::kamienie::%{_id}%}
			set {_st} to tag "Stats;Health" of nbt of player's tool
			remove {zdrowie::kamienie::%{_id}%} from {_st}
			set tag "Stats;Health" of nbt of player's tool to {_st}

			drop {wytrzymalosc::kamienie::%{_id}%} of {topazEN} at arg-1
			clear {wytrzymalosc::kamienie::%{_id}%}
			set {_st} to tag "Stats;Resistance" of nbt of player's tool
			remove {wytrzymalosc::kamienie::%{_id}%} from {_st}
			set tag "Stats;Resistance" of nbt of player's tool to {_st}

			drop {unik::kamienie::%{_id}%} of {szafirEN} at arg-1
			clear {unik::kamienie::%{_id}%}
			set {_st} to tag "Stats;Avoidance" of nbt of player's tool
			remove {unik::kamienie::%{_id}%} from {_st}
			set tag "Stats;Avoidance" of nbt of player's tool to {_st}

			drop {mobilnosc::kamienie::%{_id}%} of {perlaEN} at arg-1
			clear {mobilnosc::kamienie::%{_id}%}
			set {_st} to tag "Stats;Mobility" of nbt of player's tool
			remove {mobilnosc::kamienie::%{_id}%} from {_st}
			set tag "Stats;Mobility" of nbt of player's tool to {_st}

			drop {uzytecznosc::kamienie::%{_id}%} of {ametystEN} at arg-1
			clear {uzytecznosc::kamienie::%{_id}%}
			set {_st} to tag "Stats;Utility" of nbt of player's tool
			remove {uzytecznosc::kamienie::%{_id}%} from {_st}
			set tag "Stats;Utility" of nbt of player's tool to {_st}

			drop {uniwersalnosc::kamienie::%{_id}%} of {opalEN} at arg-1
			clear {uniwersalnosc::kamienie::%{_id}%}
			set {_st} to tag "Stats;Versatility" of nbt of player's tool
			remove {uniwersalnosc::kamienie::%{_id}%} from {_st}
			set tag "Stats;Versatility" of nbt of player's tool to {_st}

			drop {pospiech::kamienie::%{_id}%} of {jadeitEN} at arg-1
			clear {pospiech::kamienie::%{_id}%}
			set {_st} to tag "Stats;Haste" of nbt of player's tool
			remove {pospiech::kamienie::%{_id}%} from {_st}
			set tag "Stats;Haste" of nbt of player's tool to {_st}

			drop {kontrolatlumu::kamienie::%{_id}%} of {akwamarynEN} at arg-1
			clear {kontrolatlumu::kamienie::%{_id}%}
			set {_st} to tag "Stats;Crowd Control" of nbt of player's tool
			remove {kontrolatlumu::kamienie::%{_id}%} from {_st}
			set tag "Stats;Crowd Control" of nbt of player's tool to {_st}

			drop {mistrzostwo::kamienie::%{_id}%} of {turmalinEN} at arg-1
			clear {mistrzostwo::kamienie::%{_id}%}
			set {_st} to tag "Stats;Mastery" of nbt of player's tool
			remove {mistrzostwo::kamienie::%{_id}%} from {_st}
			set tag "Stats;Mastery" of nbt of player's tool to {_st}

			clear tag "Stats" of nbt of player's tool

			
			stop
			set {_id} to line 18 of lore of player's tool
			broadcast {crit::kamienie::%{_id}%}
			stop
			stop
			#loop all offline players:
			#	set {tutorial::%loop-offline player%} to true
			#	if {poziom::%loop-offline player%} > 100:
			#		set {_levelsAbove} to ({poziom::%loop-offline player%}-100)*0.5
			#		set {poziom::%loop-offline player%} to {poziom::%loop-offline player%} - round(({poziom::%loop-offline player%}-100)*0.5, 0)
			#	if {poziom::%loop-offline player%} > 20:
			#		set {poziom::%loop-offline player%} to {poziom::%loop-offline player%} - 20
			#	set {_lvljub} to {poziomjubilerstwo::%loop-offline player%}
			#	loop {_lvljub} times:
			#		add 12*loop-number to {cosmicflux::%loop-offline player%}
			#	clear {poziomjubilerstwo::%loop-offline player%}
			#	if {poziom::%loop-offline player%} >= 20:
			#		set {_level} to 20
			#		set {_amountklejnot} to ({_level} + {_levelsAbove})*20
			#		set {_lp} to loop-offline player parsed as player
			#		giveItem(({_lp}), {_amountklejnot} of {klejnotEN})
			#		giveItem(({_lp}), {odlamekgwiazdyEN})
			stop
			
			#loop all players
			#play sound "dungeons.siegeofspawn.dreamcatcher_fight" in ambient category with volume 1 and pitch 1 to player a
			#play sound "dungeons.siegeofspawn.dreamcatcher_wind_ambient" in ambient category with volume 1 and pitch 1 to player
			#stop
			giveItem(player, Gear("Vision of the Serpent", "Helmet", 23, "<##1fef00>Uncommon", "Intellect"))
			#set tag "GemIcon" of nbt of player's tool to ""
			stop
			set {_x} to feather with nbt from "{CustomModelData:1}"
			set tag "Stats;Critical Hit" of nbt of {_x} to 1
			set tag "Stats;Haste" of nbt of {_x} to 2
			broadcast nbt of {_x}
			stop
			giveItem(player, Gear("Vision of the Serpent", "Head", 50, "<##1fef00>Uncommon", "Agility"))

on rightclick:
	if player's tool is stick named "Test Gui":
		if player's name = "llamadegree" or "nishikoru":
			#nick (negative spacje odpowiedne dlugosci nicku karta tekst)
			#gui - negative spacje - karta - negative spacja - pierwsza stata - tekst - druga stata
			set {_x} to 57
			set {_string} to "%{_x}%"
			#ZDROWIE
			replace all "1" in {_string} with ""
			replace all "2" in {_string} with ""
			replace all "3" in {_string} with ""
			replace all "4" in {_string} with ""
			replace all "5" in {_string} with ""
			replace all "6" in {_string} with ""
			replace all "7" in {_string} with ""
			replace all "8" in {_string} with ""
			replace all "9" in {_string} with ""
			replace all "0" in {_string} with ""
			set {_y} to 98
			set {_string2} to "%{_y}%"
			replace all "8" in {_string2} with ""
			replace all "9" in {_string2} with ""
			set {_z} to 12
			set {_string3} to "%{_z}%"
			set {_3length} to length of {_string3}
			if {_3length} = 3:
				set {_3} to ""
			else if {_3length} = 2:
				set {_3} to ""
			replace all "1" in {_string3} with ""
			replace all "2" in {_string3} with ""
			replace all "4" in {_string3} with ""
			set {_z1} to 22
			set {_string4} to "%{_z1}%"
			replace all "2" in {_string4} with ""
			set metadata tag "testgui" of player to chest inventory with 6 rows named "&f&f &8%{_string}%&8%{_string2}%%{_string3}%%{_3}%%{_string4}%       %{_string}%       %{_string}% &8Xilvia"
			#set slot 0 of metadata tag "testgui" of player to iron sword with nbt "{CustomModelData:5}"
			set slot 8 of metadata tag "testgui" of player to leather helmet named "<##0070dd>Shadoweave Helmet" with lore "<##efc500>Item Level 75" with lore "&fSoulbound" and "&8Head" and "&f+45 Obrażenia" and "&f+45 Pośpiech" and " " and "&7Shadoweave Set Bonus:" and " &8[2] +10%% Shadowy Apparitions Damage" and " &8[4] Critical strikes with Devouring Plague" and " &8and Void Bolt increase the damage of" and " &8the Shadowy Apparitions they conjure by 100%%."
			set slot 17 of metadata tag "testgui" of player to leather chestplate
			set slot 26 of metadata tag "testgui" of player to leather pants
			set slot 35 of metadata tag "testgui" of player to leather boots
			open metadata tag "testgui" of player to player

