function minenew(p: player, t: text, b: block):
	if {_t} = "deepslate":
		set {_blok} to 2
		add 1 to {deepslate::%{_p}%}
	else if {_t} = "stone":
		set {_blok} to 1
		add 1 to {stone::%{_p}%}
	loop {_blok} times:
		achievement("stone", {_p}, 100, "osiagniecie.100kam", "Wykop 100 kamienia", "R(o)ocky", "Mine 100 stone", "R(o)ocky")
		achievement("stone", {_p}, 1000, "osiagniecie.1000kam", "Wykop 1000 kamienia", "Adept Kamienia", "Mine 1000 stone", "Stone Adept")
		achievement("stone", {_p}, 10000, "osiagniecie.10000kam", "Wykop 10000 kamienia", "Górnik", "Mine 10000 stone", "Miner")
		achievement("stone", {_p}, 100000, "osiagniecie.100000kam", "Wykop 100000 kamienia", "Ekspert Kopania", "Mine 100000 stone", "Mining Expert")
		achievement("stone", {_p}, 1000000, "osiagniecie.1000000kam", "Wykop 1000000 kamienia", "Milion: Kopanie", "Mine 1000000 stone", "Million: Mining")
		add 1 to {exp::%{_p}%}
		add 1 to {expkopanie::%{_p}%}
		set {_data} to data()
		if {profesje::%{_p}%::*} contains "GÓRNICTWO":
			if {poziomgornictwo::%{_p}%} < 75:
				add 1 to {expgornictwo::%{_p}%}
				if {expgornictwo::%{_p}%} is bigger than or equal to (150*{poziomgornictwo::%{_p}%}):
					remove (150*{poziomgornictwo::%{_p}%}) from {expgornictwo::%{_p}%}
					add 1 to {poziomgornictwo::%{_p}%}
					add 1 to {orgpoziomgornictwo::%{_p}%}
					set {_data} to data()
					achievement("poziomgornictwo", {_p}, 75, "osiagniecie.maxlvlgornictwo", "Osiągnij maksymalny poziom na profesji Górnictwo", "MAX LVL: Górnictwo", "Achieve max level in the Mining profession", "MAX LVL: Mining")
					achievement("poziomgornictwo", {_p}, 10, "osiagniecie.10lvlgornictwo", "Osiągnij dziesiąty poziom na profesji Górnictwo", "10 LVL: Górnictwo", "Achieve level ten in the Mining profession", "10 LVL: Mining")
					achievement("poziomgornictwo", {_p}, 25, "osiagniecie.25lvlgornictwo", "Osiągnij dwudziesty pięćdziesiąty poziom na profesji Górnictwo", "25 LVL: Górnictwo", "Achieve level twenty-five in the Mining profession", "25 LVL: Mining")
					achievement("poziomgornictwo", {_p}, 50, "osiagniecie.50lvlgornictwo", "Osiągnij pięćdziesiąty poziom na profesji Górnictwo", "50 LVL: Górnictwo", "Achieve level fifty in the Mining profession", "50 LVL: Mining")
					if {poziomgornictwo::%{_p}%} is set:
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7Congratulations! You have reached level &6%{poziomgornictwo::%{_p}%}% &7in the &6 Mining &7profession!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Gratulacje! Udało Ci się osiągnąć &6%{poziomgornictwo::%{_p}%}% &7lvl na profesji &6 Górnictwo&7!" to {_p}
						loop all players:
							if {language::%loop-player%} = "English":
								send "&8[&6Earthcraft&8] &6%{_p}% &7reached level &6%{poziomgornictwo::%{_p}%}% &7in the &6 Mining &7profession!" to loop-player
							else:
								send "&8[&6Earthcraft&8] &7Gracz &6%{_p}% &7osiągnął &6%{poziomgornictwo::%{_p}%}% lvl &7na profesji &6 Górnictwo&7!" to loop-player
						send "[Earthcraft] Gracz %{_p}% osiągnął %{poziomgornictwo::%{_p}%}% lvl na profesji  Górnictwo!" to console
						play sound "ui.toast.challenge_complete" with volume 5 and pitch 1 at {_b}
						log "%{_data}% Gracz %{_p}% właśnie osiągnął %{poziomgornictwo::%{_p}%}% poziom na profesji Górnictwo!" to "logi/profesje.log"
					set {_x} to {poziomgornictwo::%{_p}%}
					if {_x} = 1:
						set {umkilof::pomdlon::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the special pickaxe skill &6Helping Hand&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz umiejętność specjalną kilofu &6Pomocna Dłoń&7!" to {_p}
					if {_x} = 3, 9, 21, 27, 33, 39, 51, 57, 63 or 69:
						add 0.03 to {bonusesencja::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock &6+0.03%% bonus chance to drop Essences&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz &6+0.03%% szans na wypadnięcie Esencji&7!" to {_p}
					if {_x} = 4, 16, 24, 28, 36, 44, 48, 52, 56, 64, 68 or 72:
						add 0.09 to {bonusklejnot::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock &6+0.09%% bonus chance to drop Klejnots&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz &6+0.09%% szans na wypadnięcie Klejnotu&7!" to {_p}
					if {_x} = 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 49, 53, 59, 61, 67, 71 or 73:
						add 0.0125 to {bonuskamieniesz::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock &6+0.0125%% bonus chance to drop Gemstones&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz &6+0.0125%% szans na wypadnięcie Kamieni Szlachetnych&7!" to {_p}
					if {_x} = 2, 6, 14, 18, 22, 26, 34, 38, 42, 46, 54, 58, 62, 66 or 74:
						add 3 to {bonusprzepalanie::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock a &6+3%% bonus to XP gain from smelting ores and stone&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz &6+3%% bonus do otrzymywanych punktów XP z przepalania&7!" to {_p}
					if {_x} = 5:
						set {gornictwo::mechanik::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the &6Mechanic&7 &7ability!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz zdolność &6Mechanik&7!" to {_p}
					if {_x} = 8:
						set {przepis::pylynaprawcze::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the recipe for <##fc3535>Better Repair Dust&7, <##fff5c4>Magic Dust &7i <##ad35fc>Instant Dust&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz przepis na <##fc3535>Lepszy Pył Naprawczy&7, <##fff5c4>Magiczny Pył &7i <##ad35fc>Instant Pył&7!" to {_p}
						add 3 to {przepisy::gornictwo::%{_p}%}
					if {_x} = 10:
						set {umkilof::eksplozja::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the special pickaxe skill &6Explosion&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz umiejętność specjalną kilofu &6Eksplozja&7!" to {_p}
					if {_x} = 12:
						set {gornictwo::rudasoli::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7From now on you can find <##e0ecff>Salt Ores &7when mining!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Od teraz możesz znajdywać <##e0ecff>Rudy Soli &7podczas kopania&7!" to {_p}
					if {_x} = 15:
						set {gornictwo::stardust::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the &6Stellar Prophecy &7ability!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz zdolność &6Gwiezdna Przepowiednia&7!" to {_p}
					if {_x} = 20:
						set {umkilof::zaplon::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the special pickaxe skill &6Short Fuse&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz umiejętność specjalną kilofu &6Zapłon&7!" to {_p}
					if {_x} = 25:
						set {gornictwo::rudaxp::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7From now on you can find <##8cff98>XP Ores &7when mining!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Od teraz możesz znajdywać <##8cff98>Rudy XP &7podczas kopania&7!" to {_p}
					if {_x} = 26:
						set {gornictwo::zylaklejnotow::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7From now on you can find <##b5e550>Klejnot Deposits &7when mining!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Od teraz możesz znajdywać <##b5e550>Żyły Klejnotów &7podczas kopania&7!" to {_p}
					if {_x} = 30:
						set {umkilof::instogrz::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the special pickaxe skill &6Heating Systems&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz umiejętność specjalną kilofu &6Instalacje Ogrzewcze&7!" to {_p}
					if {_x} = 32:
						set {gornictwo::rudaplatyny::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7From now on you can find <##5c9e71>Platinum Ores &7when mining!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Od teraz możesz znajdywać <##5c9e71>Rudy Platyny &7podczas kopania&7!" to {_p}
					if {_x} = 34:
						set {gornictwo::bonusxp::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7Your XP gain from mining ores has been increased by &f25%%&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Twoje otrzymywane punkty XP z wykopywania rud zostały zwiększone o &f25%%&7!" to {_p}
					if {_x} = 35:
						set {gornictwo::bystreoko::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the &6Sharp Eye &7ability!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz zdolność &6Bystre Oko&7!" to {_p}
					if {_x} = 40:
						set {umkilof::magnes::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the special pickaxe skill &6Magnet&7!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz umiejętność specjalną kilofu &6Magnes&7!" to {_p}
					if {_x} = 45:
						set {gornictwo::rudavoidstone::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7From now on you can find <##673a9c>Voidstone Ores &7when mining!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Od teraz możesz znajdywać <##673a9c>Rudy Voidstone &7podczas kopania&7!" to {_p}
					if {_x} = 50:
						set {gornictwo::poszukiwaczmineralow::%{_p}%} to true
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &7You unlock the &6Mineral Seeker &7ability!" to {_p}
						else:
							send "&8[&6Earthcraft&8] &7Odblokowujesz zdolność &6Poszukiwacz Minerałów&7!" to {_p}
					#if {_x} = 55:
					#	send "a" to {_p}
					#if {_x} = 60:
					#	set {gornictwo::preznal::%{_p}%} to true
					#	send "&8[&6Earthcraft&8] &7Odblokowujesz zdolność &6Prehistoryczne Znaleziska&7!" to {_p}
					#if {_x} = 65:
					#	send "a" to {_p}
					#if {_x} = 70:
					#	send "a" to {_p}
					#if {_x} = 75:
					#	send "a" to {_p}
			if {umkilof::%{_p}%} = "Zapłon":
				if {orbcount::%{_p}%} >= 20:
					remove 20 from {orbcount::%{_p}%}
					set {orbbudget::%{_p}%} to 0
					apply haste 2 without particles to {_p} for 4 seconds
					play sound "block.brewing_stand.brew" with volume 3 and pitch 0.9 to {_p}
				chance of 8%:
					spawn 1 xp orb at block 2 blocks behind {_p}
					add 1 to {orbbudget::%{_p}%}
					send action bar "&a%{orbcount::%{_p}%}%" to {_p}
		if {exp::%{_p}%} is bigger than or equal to (100*{poziom::%{_p}%}):
			remove (100*{poziom::%{_p}%}) from {exp::%{_p}%}
			add 1 to {poziom::%{_p}%}
			add {poziom::%{_p}%} to {stardust::%{_p}%}
			add {poziom::%{_p}%} to {totalstardust::%{_p}%}
			add 5*{poziom::%{_p}%} to {cosmicflux::%{_p}%}
			add 5*{poziom::%{_p}%} to {totalcosmicflux::%{_p}%}
			set {dziennylimit::stardust::%{_p}%} to {poziom::%{_p}%}
			add 1 to {orgpoziom::%{_p}%}
			set {_data} to data()
			achievement("poziom", {_p}, 10, "osiagniecie.10lvl", "Osiągnij dziesiąty poziom", "10 LVL", "Achieve level ten", "10 LVL")
			achievement("poziom", {_p}, 50, "osiagniecie.50lvl", "Osiągnij pięćdziesiąty poziom", "50 LVL", "Achieve level fifty", "50 LVL")
			achievement("poziom", {_p}, 100, "osiagniecie.100lvl", "Osiągnij setny poziom", "100 LVL", "Achieve level one hundred", "100 LVL")
			achievement("poziom", {_p}, 200, "osiagniecie.200lvl", "Osiągnij dwusetny poziom", "200 LVL", "Achieve level two hundred", "200 LVL")
			achievement("poziom", {_p}, 300, "osiagniecie.300lvl", "Osiągnij trzysetny poziom", "300 LVL", "Achieve level three hundred", "300 LVL")
			achievement("poziom", {_p}, 500, "osiagniecie.500lvl", "Osiągnij pięćsetny poziom", "500 LVL", "Achieve level five hundred", "500 LVL")
			achievement("poziom", {_p}, 1000, "osiagniecie.1000lvl", "Osiągnij tysięczny poziom", "1000 LVL", "Achieve level one thousand", "1000 LVL")
			if {poziom::%{_p}%} is divisible by 50:
				add 1 to {nagrodalvl::karta::%{_p}%}
				if {language::%{_p}%} = "English":
					send formatted "&8[&6Earthcraft&8] &7Congratulations! You may choose a new card for reaching level &6%{poziom::%{_p}%}%!" to {_p}
					send formatted "&8[&6Earthcraft&8] &7Click <command:/reward claim><tooltip:&fClick to choose a card>&6[here]<tooltip:> &7or write &6/reward claim &7in chat to claim your reward." to {_p}
				else:
					send formatted "&8[&6Earthcraft&8] &7Gratulacje! Za zdobycie &6%{poziom::%{_p}%}% &7poziomu możesz wybrać nową kartę za poziom!" to {_p}
					send formatted "&8[&6Earthcraft&8] &7Kliknij <command:/nagroda odbierz><tooltip:&fKliknij, by wybrać kartę za poziom>&6[tutaj]<tooltip:>&7, lub wpisz komendę &6/nagroda odbierz&7, by oderać nagrodę." to {_p}
			if {poziom::%{_p}%} > 90:
				set {_divis} to 5
			else:
				set {_divis} to 10
			if {poziom::%{_p}%} is divisible by {_divis}:
				if {language::%{_p}%} = "English":
					send formatted "&8[&6Earthcraft&8] &7Congratulations! You receive a &cStar Shard &7for reaching level &6%{poziom::%{_p}%}%!" to {_p}
					if {_p} has space for {odlamekgwiazdyEN}:
						give {odlamekgwiazdyEN} to {_p}
					else:
						drop {odlamekgwiazdyEN} at {_b}
					play sound "entity.player.levelup" with volume 3 and pitch 2 to {_p}
				else:
					send formatted "&8[&6Earthcraft&8] &7Gratulacje! Otrzymujesz &cOdłamek Gwiazdy &7za zdobycie poziomu &6%{poziom::%{_p}%}%!" to {_p}
					if {_p} has space for {odlamekgwiazdy}:
						give {odlamekgwiazdy} to {_p}
					else:
						drop {odlamekgwiazdy} at {_b}
					play sound "entity.player.levelup" with volume 3 and pitch 2 to {_p}
			if {poziom::%{_p}%} is set:
				loop all players:
					if {language::%loop-player%} = "English":
						if loop-player is not {_p}:
							send "&8[&6Earthcraft&8] &6%{_p}% &7reached level &6%{poziom::%{_p}%}%&7!" to loop-player
						else:
							send "&8[&6Earthcraft&8] &7Congratulations! You reached level &6%{poziom::%{_p}%}% &7lvl!" to {_p}
							send "&8[&6Earthcraft&8] &7You receive &6%5*{poziom::%{_p}%}% <##ffe17a>Cosmic Flux &7as a reward for reaching a new level!" to {_p}
							send "&8[&6Earthcraft&8] &7You receive &6%{poziom::%{_p}%}% %{stardust}'s name% &7as a reward for reaching a new level!" to {_p}
					else:
						if loop-player is not {_p}:
							send "&8[&6Earthcraft&8] &7Gracz &6%{_p}% &7osiągnął &6%{poziom::%{_p}%}% &7lvl!" to loop-player
						else:
							send "&8[&6Earthcraft&8] &7Gratulacje! Udało Ci się osiągnąć &6%{poziom::%{_p}%}% &7lvl!" to {_p}
							send "&8[&6Earthcraft&8] &7Otrzymujesz &6%5*{poziom::%{_p}%}% <##ffe17a>Cosmic Flux &7za osiągnięcie nowego poziomu!" to {_p}
							send "&8[&6Earthcraft&8] &7Otrzymujesz &6%{poziom::%{_p}%}% %{stardust}'s name%u &7za osiągnięcie nowego poziomu&7!" to {_p}
				send "Gracz %{_p}% właśnie osiągnął %{poziom::%{_p}%}% poziom!" to console
				log "%{_data}% Gracz %{_p}% właśnie osiągnął %{poziom::%{_p}%}% poziom!" to "logi/poziomy.log"
				execute console command "discord broadcast ##earthcraft %{_data}% | %{_p}% reached level %{poziom::%{_p}%}%!"
				set {_p}'s tablist name to "&8[<##7c7cff>&l%{poziom::%{_p}%}%<##9494ff>&l⭐&8] &f%{_p}%" 
				#set the {_p}'s tablist name to "&8[<##9b21ad>&l%{poziom::%{_p}%}%&f&8] &f%{_p}%"
				#set the {_p}'s tablist name to "&8[<##504cc2>&l%{poziom::%{_p}%}%&f&l&8] &f%{_p}%"
				#set the {_p}'s tablist name to "&8[<##ae7ff6>&l%{poziom::%{_p}%}%&f&l&8] &f%{_p}%"
				play sound "ui.toast.challenge_complete" with volume 5 and pitch 1 at {_b}
			if {poziom::%{_p}%} >= 40:
				if {heartofec::%{_p}%} is not set:
					wait 7 seconds
					if {language::%{_p}%} = "English":
						send "<##7aa7f5>! &8[<##7aa7f5>NPC&8] &8<<##7aa7f5>Magni&8> <##7aa7f5>Ah, there you are! Earthcraft is in need of your help! Meet me in my chamber down the spawn area. There's something you need to see." to {_p}
					else:
						send "<##7aa7f5>! &8[<##7aa7f5>NPC&8] &8<<##7aa7f5>Magni&8> <##7aa7f5>Ah, tu jesteś! Earthcraft potrzebuje twojej pomocy! Spotkajmy się na dole spawnu. Jest coś co musisz zobaczyć." to {_p}
					play sound "block.note_block.cow_bell" with volume 5 and pitch 1 to {_p}
					play sound "entity.lightning_bolt.thunder" with volume 5 and pitch 0 to {_p}
					play sound "entity.lightning_bolt.thunder" with volume 5 and pitch 1 to {_p}
					play sound "entity.lightning_bolt.impact" with volume 5 and pitch 1.6 to {_p}
		chance of 1%:
			add 1 to {skrzynka::%{_p}%}
			set {_otxp} to 6
			add {_otxp} to {exp::%{_p}%}
			add {_otxp} to {expkopanie::%{_p}%}
			if {language::%{_p}%} = "English":
				drop {skrzynkaEN} at {_b}
				send "&8[&6Earthcraft&8] &7Congratulations! You found a &9Chest&7! &7(+%{_otxp}% &7XP)" to {_p}
			else:
				drop {skrzynka} at {_b}
				send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &9Skrzynkę&7! &7(+%{_otxp}% &7XP)" to {_p}
			achievement("skrzynka", {_p}, 100, "osiagniecie.100skrzynek", "Wykop 100 Skrzynek", "Skrzynkoznajdywacz", "Find 100 Chests", "Chest Finder")
			achievement("skrzynka", {_p}, 1000, "osiagniecie.1000skrzynek", "Wykop 1000 Skrzynek", "Miłośnik Skrzynek", "Find 1000 Chests", "Chest Lover")
		chance of 0.3%:
			add 1 to {skrzynkaluksus::%{_p}%}
			set {_otxp} to 14
			add {_otxp} to {exp::%{_p}%}
			add {_otxp} to {expkopanie::%{_p}%}
			if {language::%{_p}%} = "English":
				drop {skrzynkaluksusowaEN} at {_b}
				send "&8[&6Earthcraft&8] &7Congratulations! You found a &9Luxurious Chest&7! &7(+%{_otxp}% &7XP)" to {_p}
			else:
				drop {skrzynkaluksusowa} at {_b}
				send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &9Luksusową Skrzynkę&7! &7(+%{_otxp}% &7XP)" to {_p}
			achievement("skrzynkaluksus", {_p}, 100, "osiagniecie.100luksusskrzynek", "Wykop 100 Luksusowych Skrzynek", "Znajdywacz Luksusowych Skrzynek", "Find 100 Luxurious Chests", "Luxurious Chest Finder")
			achievement("skrzynkaluksus", {_p}, 1000, "osiagniecie.1000luksusskrzynek", "Wykop 1000 Luksusowych Skrzynek", "Miłośnik Luksusowych Skrzynek", "Find 1000 Luxurious Chests", "Luxurious Chest Lover")
		chance of 1%:
			if {heartofec::%{_p}%} is set:
				set {_r} to a random integer between 1 and 35
				chance of 20%:
					set {_r} to a random integer between 1 and 50
				HeartLevelup({_p}, {_r})
		chance of 0.25%:
			if {heartofec::%{_p}%} is set:
				set {_r} to a random integer between 50 and 100
				chance of 20%:
					set {_r} to a random integer between 100 and 149
				HeartLevelup({_p}, {_r})
		chance of 0.0625%:
			if {heartofec::%{_p}%} is set:
				set {_r} to a random integer between 150 and 200
				HeartLevelup({_p}, {_r})
		if {diademdrop::%{_p}%} = "esencje":
			set {_che} to 2 + ({bonusesencja::%{_p}%}*4)
		else:
			set {_che} to 0.5 + {bonusesencja::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: Essence Reaver I":
			set {_che} to {_che}*1.04
		chance of {_che}%:
			set {_xc} to a random element of {esencje::*}
			if {language::%{_p}%} = "English":
				set {_xc} to a random element of {esencjeEN::*}
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				drop {_xc} at {_b}
				add 1 to {wykopaneesencje::%{_p}%}
				achievement("wykopaneesencje", {_p}, 100, "osiagniecie.100es", "Wykop 100 Esencji", "Żywiołak", "Find 100 Essences when mining", "Elemental")
				achievement("wykopaneesencje", {_p}, 1000, "osiagniecie.100es", "Wykop 100 Esencji", "Jeden z Żywiołami", "Find 1000 Essences when mining", "One with the Elements")
				if {_xc} is {esencjaognia} or {esencjaogniaEN}:
					add 1 to {esencjaognia::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##ff4d00>Fire Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ff4d00>Esencję Ognia&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjawody} or {esencjawodyEN}:
					add 1 to {esencjawody::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##1ebbd7>Water Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##1ebbd7>Esencję Wody&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjaziemii} or {esencjaziemiiEN}:
					add 1 to {esencjaziemii::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found an <##633200>Earth Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##633200>Esencję Ziemii&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjapowietrza} or {esencjapowietrzaEN}:
					add 1 to {esencjapowietrza::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found an &fAir Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &fEsencję Powietrza&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjanatury} or {esencjanaturyEN}:
					add 1 to {esencjanatury::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##607c3c>Nature Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##607c3c>Esencję Natury&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjaburzy} or {esencjaburzyEN}:
					add 1 to {esencjaburzy::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##fffb05>Storm Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##fffb05>Esencję Burzy&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjaducha} or {esencjaduchaEN}:
					add 1 to {esencjaducha::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##431d53>Ghost Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##431d53>Esencję Ducha&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjametalu} or {esencjametaluEN}:
					add 1 to {esencjametalu::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##cecece>Metal Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##cecece>Esencję Metalu&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjamechaniki} or {esencjamechanikiEN}:
					add 1 to {esencjamechaniki::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##ffbf00>Tech Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ffbf00>Esencję Mechaniki&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjabasni} or {esencjabasniEN}:
					add 1 to {esencjabasni::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##ff99bb>Fairy Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ff99bb>Esencję Baśni&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjamroku} or {esencjamrokuEN}:
					add 1 to {esencjamroku::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##333333>Dark Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##333333>Esencję Mroku&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjaswiatla} or {esencjaswiatlaEN}:
					add 1 to {esencjaswiatla::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##fffec8>Light Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##fffec8>Esencję Światła&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjasmoka} or {esencjasmokaEN}:
					add 1 to {esencjasmoka::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##306844>Dragon Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##306844>Esencję Smoka&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjatrucizny} or {esencjatruciznyEN}:
					add 1 to {esencjatrucizny::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##9c72b2>Poison Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##9c72b2>Esencję Trucizny&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjawalki} or {esencjawalkiEN}:
					add 1 to {esencjawalki::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##953301>Fight Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##953301>Esencję Walki&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjamagii} or {esencjamagiiEN}:
					add 1 to {esencjamagii::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##512989>Magic Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##512989>Esencję Magii&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjalodu} or {esencjaloduEN}:
					add 1 to {esencjalodu::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##add8e6>Ice Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##add8e6>Esencję Lodu&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjalawy} or {esencjalawyEN}:
					add 1 to {esencjalawy::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##ff3014>Lava Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ff3014>Esencję Lawy&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjaastralna} or {esencjaastralnaEN}:
					add 1 to {esencjaastralna::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##a99afc>Astral Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##a99afc>Astralną Esencję&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjabestii} or {esencjabestiiEN}:
					add 1 to {esencjabestii::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##7a0000>Beast Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##7a0000>Esencję Bestii&7! &7(+%{_otxp}% &7XP)" to {_p}
				if {_xc} is {esencjapsychiki} or {esencjapsychikiEN}:
					add 1 to {esencjapsychiki::%{_p}%}
					set {_otxp} to 12
					add {_otxp} to {exp::%{_p}%}
					add {_otxp} to {expkopanie::%{_p}%}
					if {language::%{_p}%} = "English":
						send "&8[&6Earthcraft&8] &7Congratulations! You found a <##d84af7>Psychic Essence&7! &7(+%{_otxp}% &7XP)" to {_p}
					else:
						send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##d84af7>Esencję Psychiki&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {klejnot}:
			set {_chk} to 8 + ({bonusklejnot::%{_p}%}*4)# + ({rangaklejnot::%{_p}%}*4)
		else:
			set {_chk} to 2 + {bonusklejnot::%{_p}%}# + {rangaklejnot::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: Treasure Seeker I":
			set {_chk} to {_chk}*1.05
		chance of {_chk}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {klejnot::%{_p}%}
				#if {klejnot::%{_p}%} = 300:
				#	set {rangaklejnot::%{_p}%} to 0.5
				#	broadcast "&8[&6Earthcraft&8] &7Gracz &6%{_p}% &7osiągnął &6rangę 1 &7[&e&l✰&8&l✰✰&7] &7na <##b5e550>Klejnocie&7!"
				#	soundRankup({_p})
				#if {klejnot::%{_p}%} = 600:
				#	set {rangaklejnot::%{_p}%} to 1
				#	broadcast "&8[&6Earthcraft&8] &7Gracz &6%{_p}% &7osiągnął &6rangę 2 &7[&e&l✰✰&8&l✰&7] &7na <##b5e550>Klejnocie&7!"
				#	soundRankup({_p})
				#if {klejnot::%{_p}%} = 1200:
				#	set {rangaklejnot::%{_p}%} to 1.5
				#	broadcast "&8[&6Earthcraft&8] &7Gracz &6%{_p}% &7osiągnął &6rangę 3 &7[&e&l✰✰✰&7] &7na <##b5e550>Klejnocie&7!"
				#	soundRankup({_p})
				achievement("klejnot", {_p}, 100, "osiagniecie.100klej", "Wykop 100 Klejnotów", "Początek Fortuny", "Find 100 Klejnots when mining", "The Beginning of Fortune")
				achievement("klejnot", {_p}, 1000, "osiagniecie.100klej", "Wykop 100 Klejnotów", "Emporium Klejnotów", "Find 1000 Klejnots when mining", "Klejnot Emporium")
				set {_otxp} to 2.5
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {klejnotEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found a <##b5e550>Klejnot&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {klejnot} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##b5e550>Klejnot&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {rubin}:
			set {_chr} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chr} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chr} to {_chr}*1.025
		chance of {_chr}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {rubin::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {rubinEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found a <##ff0000>Ruby&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {rubin} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ff0000>Rubin&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {ametyst}:
			set {_cha} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_cha} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_cha} to {_cha}*1.025
		chance of {_cha}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {ametyst::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {ametystEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found an <##ae78d0>Amethyst&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {ametyst} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ae78d0>Ametyst&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {perla}:
			set {_chp} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chp} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chp} to {_chp}*1.025
		chance of {_chp}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {perla::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {perlaEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found a <##f5d0eb>Pearl&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {perla} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##f5d0eb>Perłę&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {topaz}:
			set {_chtop} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chtop} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chtop} to {_chtop}*1.025
		chance of {_chtop}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {topaz::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {topazEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found a <##ffe505>Topaz&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {topaz} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ffe505>Topaz&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {akwamaryn}:
			set {_chakw} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chakw} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chakw} to {_chakw}*1.025
		chance of {_chakw}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {akwamaryn::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {akwamarynEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found an <##11d7d8>Aquamarine&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {akwamaryn} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##11d7d8>Akwamaryn&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {perydot}:
			set {_chper} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chper} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chper} to {_chper}*1.025
		chance of {_chper}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {perydot::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {perydotEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found a <##c0ff02>Peridot&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {perydot} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##c0ff02>Perydot&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {opal}:
			set {_chop} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chop} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chop} to {_chop}*1.025
		chance of {_chop}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {opal::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {opalEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found an <##dbd7da>Opal&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {opal} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##dbd7da>Opal&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {turmalin}:
			set {_chturm} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chturm} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chturm} to {_chturm}*1.025
		chance of {_chturm}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {turmalin::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {turmalinEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found a <##ff0d6e>Tourmaline&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {turmalin} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ff0d6e>Turmalin&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {jadeit}:
			set {_chjad} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chjad} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chjad} to {_chjad}*1.025
		chance of {_chjad}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {jadeit::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {jadeitEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found <##187a2f>Jade&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {jadeit} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##187a2f>Jadeit&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {szafir}:
			set {_chsza} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chsza} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chsza} to {_chsza}*1.025
		chance of {_chsza}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {szafir::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {szafirEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found a <##025b95>Sapphire&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {szafir} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##025b95>Szafir&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {cytryn}:
			set {_chcyt} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chcyt} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chcyt} to {_chcyt}*1.025
		chance of {_chcyt}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {cytryn::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {cytrynEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found a <##ff7926>Citrine&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {cytryn} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ff7926>Cytryn&7! &7(+%{_otxp}% &7XP)" to {_p}
		if {diademdrop::%{_p}%} = name of {awenturyn}:
			set {_chawent} to 1.2 + ({bonuskamieniesz::%{_p}%}*4)
		else:
			set {_chawent} to 0.3 + {bonuskamieniesz::%{_p}%}
		if lore of {_p}'s tool contains "&7Enchant: More Gemstones I":
			set {_chawent} to {_chawent}*1.025
		chance of {_chawent}%:
			set {_damount} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_damount} to 2
			loop {_damount} times:
				add 1 to {awenturyn::%{_p}%}
				add 1 to {wykopanekamieniesz::%{_p}%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				set {_otxp} to 8
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				if {language::%{_p}%} = "English":
					drop {awenturynEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found an <##d5ff57>Aventurine&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {awenturyn} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##d5ff57>Awenturyn&7! &7(+%{_otxp}% &7XP)" to {_p}
		set {_chbursz} to 0.2
		if lore of {_p}'s tool contains "&7Enchant: Archeologist I":
			set {_chawent} to {_chawent}*1.03
		chance of {_chbursz}%:
			set {_preznal} to 1
			if {podwojnydrop::%{_p}%} = true:
				set {_preznal} to 2
			if {gornictwo::preznal::%{_p}%} is true:
				chance of 20%:
					if {podwojnydrop::%{_p}%} = true:
						set {_preznal} to 4
					else:
						set {_preznal} to 2
			loop {_preznal} times:
				add 1 to {bursztyny::%{_p}%}
				achievement("bursztyny", {_p}, 100, "osiagniecie.100bursz", "Wykop 100 Bursztynów", "Archeolog", "Find 100 Ambers when mining", "Archeologist")
				set {_otxp} to 15
				add {_otxp} to {exp::%{_p}%}
			if {_preznal} > 1:
				if {language::%{_p}%} = "English":
					send "&8[&6Earthcraft&8] &7Congratulations! You found an <##ffab24>Amber&7! (x%{_preznal}%) &7(+%{_otxp}*{_preznal}% &7XP)" to {_p}
				else:
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ffab24>Bursztyn&7! (x%{_preznal}%) &7(+%{_otxp}*{_preznal}% &7XP)" to {_p}
			else:
				if {language::%{_p}%} = "English":
					drop {bursztynEN} at {_b}
					send "&8[&6Earthcraft&8] &7Congratulations! You found an <##ffab24>Amber&7! &7(+%{_otxp}% &7XP)" to {_p}
				else:
					drop {bursztyn} at {_b}
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##ffab24>Bursztyn&7! &7(+%{_otxp}% &7XP)" to {_p}
		#DIAMONDSHARD
		chance of 0.05%:
			add 1 to {diamondshards::%{_p}%}
			achievement("diamondshards", {_p}, 100, "osiagniecie.100diamondshards", "Wykop 100 Diamentowych Odłamków", "Diamentowy Specjalista", "Find 100 Diamond Shards when mining", "ADiamond Specialist")
			set {_otxp} to 60
			add {_otxp} to {exp::%{_p}%}
			if {language::%{_p}%} = "English":
				drop {diamondshardEN} at {_b}
				send "&8[&6Earthcraft&8] &7Congratulations! You found a &bDiamond Shard&7! &7(+%{_otxp}% &7XP)" to {_p}
			else:
				drop {diamondshard} at {_b}
				send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &bDiamentowy Odłamek&7! &7(+%{_otxp}% &7XP)" to {_p}
		#TRAITS
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Vaporeon":
					if {trait::Vaporeon::Cascade::%{_p}%} is not set:
						if {trait::Vaporeon::Cascade::%{_p}%} is not set:
							set {_color} to "<##00ff00>Cascade" 		#RANK 1
						add 1 to {trait::Vaporeon::Cascade::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Cascade}% %{_color}%&6! &6(<##7cafbf>Vaporeon&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Cascade}% %{_color}%&6! &6(<##7cafbf>Vaporeon&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Vaporeon":
					if {trait::Vaporeon::Flow of Water::%{_p}%} is not set:
						if {trait::Vaporeon::Flow of Water::%{_p}%} is not set:
							set {_color} to "<##00ff00>Flow of Water" 		#RANK 1
						add 1 to {trait::Vaporeon::Flow of Water::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Flow of Water}% %{_color}%&6! &6(<##7cafbf>Vaporeon&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Flow of Water}% %{_color}%&6! &6(<##7cafbf>Vaporeon&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Vaporeon":
					if {trait::Vaporeon::Saving Drops::%{_p}%} is not set:
						if {trait::Vaporeon::Saving Drops::%{_p}%} is not set:
							set {_color} to "<##00ff00>Saving Drops" 		#RANK 1
						add 1 to {trait::Vaporeon::Saving Drops::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Saving Drops}% %{_color}%&6! &6(<##7cafbf>Vaporeon&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Saving Drops}% %{_color}%&6! &6(<##7cafbf>Vaporeon&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Ghazan":
					if {trait::Ghazan::Erupting Lava::%{_p}%} is not set:
						if {trait::Ghazan::Erupting Lava::%{_p}%} is not set:
							set {_color} to "<##00ff00>Erupting Lava" 		#RANK 1
						add 1 to {trait::Ghazan::Erupting Lava::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Erupting Lava}% %{_color}%&6! &6(<##b03228>Ghazan&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Erupting Lava}% %{_color}%&6! &6(<##b03228>Ghazan&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Ghazan":
					if {trait::Ghazan::Molten Blast::%{_p}%} is not set:
						if {trait::Ghazan::Molten Blast::%{_p}%} is not set:
							set {_color} to "<##00ff00>Molten Blast" 		#RANK 1
						add 1 to {trait::Ghazan::Molten Blast::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Molten Blast}% %{_color}%&6! &6(<##b03228>Ghazan&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Molten Blast}% %{_color}%&6! &6(<##b03228>Ghazan&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Ghazan":
					if {trait::Ghazan::Rolling Lava::%{_p}%} is not set:
						if {trait::Ghazan::Rolling Lava::%{_p}%} is not set:
							set {_color} to "<##00ff00>Rolling Lava" 		#RANK 1
						add 1 to {trait::Ghazan::Rolling Lava::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Rolling Lava}% %{_color}%&6! &6(<##b03228>Ghazan&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Rolling Lava}% %{_color}%&6! &6(<##b03228>Ghazan&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Glaceon":
					if {trait::Glaceon::Chain Reaction::%{_p}%} is not set:
						if {trait::Glaceon::Chain Reaction::%{_p}%} is not set:
							set {_color} to "<##00ff00>Chain Reaction" 		#RANK 1
						add 1 to {trait::Glaceon::Chain Reaction::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Chain Reaction}% %{_color}%&6! &6(<##4bbfe2>Glaceon&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Chain Reaction}% %{_color}%&6! &6(<##4bbfe2>Glaceon&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Glaceon":
					if {trait::Glaceon::Frigid Grasp::%{_p}%} is not set:
						if {trait::Glaceon::Frigid Grasp::%{_p}%} is not set:
							set {_color} to "<##00ff00>Frigid Grasp" 		#RANK 1
						add 1 to {trait::Glaceon::Frigid Grasp::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Frigid Grasp}% %{_color}%&6! &6(<##4bbfe2>Glaceon&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Frigid Grasp}% %{_color}%&6! &6(<##4bbfe2>Glaceon&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Glaceon":
					if {trait::Glaceon::Whiteout::%{_p}%} is not set:
						if {trait::Glaceon::Whiteout::%{_p}%} is not set:
							set {_color} to "<##00ff00>Whiteout" 		#RANK 1
						add 1 to {trait::Glaceon::Whiteout::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Whiteout}% %{_color}%&6! &6(<##4bbfe2>Glaceon&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Whiteout}% %{_color}%&6! &6(<##4bbfe2>Glaceon&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Delphox":
					if {trait::Delphox::Pyrotechnics::%{_p}%} is not set:
						if {trait::Delphox::Pyrotechnics::%{_p}%} is not set:
							set {_color} to "<##00ff00>Pyrotechnics" 		#RANK 1
						add 1 to {trait::Delphox::Pyrotechnics::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Pyrotechnics}% %{_color}%&6! &6(<##d74327>Delphox&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Pyrotechnics}% %{_color}%&6! &6(<##d74327>Delphox&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Delphox":
					if {trait::Delphox::Controlled Destruction::%{_p}%} is not set:
						if {trait::Delphox::Controlled Destruction::%{_p}%} is not set:
							set {_color} to "<##00ff00>Controlled Destruction" 		#RANK 1
						add 1 to {trait::Delphox::Controlled Destruction::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Controlled Destruction}% %{_color}%&6! &6(<##d74327>Delphox&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Controlled Destruction}% %{_color}%&6! &6(<##d74327>Delphox&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Delphox":
					if {trait::Delphox::Firestarter::%{_p}%} is not set:
						if {trait::Delphox::Firestarter::%{_p}%} is not set:
							set {_color} to "<##00ff00>Firestarter" 		#RANK 1
						add 1 to {trait::Delphox::Firestarter::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Firestarter}% %{_color}%&6! &6(<##d74327>Delphox&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Firestarter}% %{_color}%&6! &6(<##d74327>Delphox&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Umbreon":
					if {trait::Umbreon::Moonshine::%{_p}%} is not set:
						if {trait::Umbreon::Moonshine::%{_p}%} is not set:
							set {_color} to "<##00ff00>Moonshine" 		#RANK 1
						add 1 to {trait::Umbreon::Moonshine::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Moonshine}% %{_color}%&6! &6(<##1a1a1a>Umbreon&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Moonshine}% %{_color}%&6! &6(<##1a1a1a>Umbreon&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Umbreon":
					if {trait::Umbreon::Nightstalker::%{_p}%} is not set:
						if {trait::Umbreon::Nightstalker::%{_p}%} is not set:
							set {_color} to "<##00ff00>Nightstalker" 		#RANK 1
						add 1 to {trait::Umbreon::Nightstalker::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Nightstalker}% %{_color}%&6! &6(<##1a1a1a>Umbreon&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Nightstalker}% %{_color}%&6! &6(<##1a1a1a>Umbreon&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		chance of 0.02%:
			if {osiagniecie.heart::%{_p}%} = true:
				if {kolekcja::karty::%{_p}%::*} contains "Umbreon":
					if {trait::Umbreon::Claw in the Back::%{_p}%} is not set:
						if {trait::Umbreon::Claw in the Back::%{_p}%} is not set:
							set {_color} to "<##00ff00>Claw in the Back" 		#RANK 1
						add 1 to {trait::Umbreon::Claw in the Back::%{_p}%}
						if {language::%{_p}%} = "English":
							send "&8[&6Earthcraft&8] &6Unlocked trait: &f%{Claw in the Back}% %{_color}%&6! &6(<##1a1a1a>Umbreon&6)" to {_p}
						else:
							send "&8[&6Earthcraft&8] &6Odblokowano trait: &f%{Claw in the Back}% %{_color}%&6! &6(<##1a1a1a>Umbreon&6)" to {_p}
						play sound "entity.player.levelup" with volume 5 and pitch 1.2 at {_p}
		if {szafirowafigurka::%{_p}%} is true:
			chance of 2%:
				drop {szafirowafigurka} at {_p}
				add 1 to {szafirowefigurki::%{_p}%}
				if {szafirowefigurki::%{_p}%} = 100:
					strike lightning effect at {_p}
					set {osiagniecie.100szaffig::%{_p}%} to true
					loop all players:
						send formatted "&fGracz %{_p}% właśnie zdobył osiągnięcie <tooltip:&aWykop 100 szafirowych figurek>&a[Kolekcjoner]" to loop-player
				set {_otxp} to 2.5
				add {_otxp} to {exp::%{_p}%}
				add {_otxp} to {expkopanie::%{_p}%}
				send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś <##025b95>Szafirową Figurkę&7! &7(+%{_otxp}% &7XP)" to {_p}
		UpdateScoreboard({_p})
variables:
	#{kolorek::%player%} = "&6"
	{poziom::%player%} = 0
on break of any log:
	add 1 to {%event-block%::%player%}
	add 1 to {exp::%player%}
	add 1 to {expwood::%player%}
	UpdateScoreboard(player)
on break of netherrack:
	add 1 to {netherrack::%player%}
	add 0.1 to {exp::%player%}
	add 0.1 to {expkopanie::%player%}
	UpdateScoreboard(player)
on entity breed:
	add 1 to {%event-entity%::%breeding player%}
	add 3 to {exp::%breeding player%}
	add 3 to {expbreeding::%player%}
	UpdateScoreboard(breeding player)
on break of ripe wheat plant:
	add 1 to {wheat::%player%}
	add 0.5 to {exp::%player%}
	add 0.5 to {expharvest::%player%}
	UpdateScoreboard(player)
on break of ripe carrot plant:
	add 1 to {carrot::%player%}
	add 0.5 to {exp::%player%}
	add 0.5 to {expharvest::%player%}
	UpdateScoreboard(player)
on break of ripe potato plant:
	add 1 to {potato::%player%}
	add 0.5 to {exp::%player%}
	add 0.5 to {expharvest::%player%}
	UpdateScoreboard(player)
on break of melon:
	add 1 to {melon::%player%}
	add 3 to {exp::%player%}
	add 3 to {expharvest::%player%}
	UpdateScoreboard(player)
on break of pumpkin:
	add 1 to {pumpkin::%player%}
	add 3 to {exp::%player%}
	add 3 to {expharvest::%player%}
	UpdateScoreboard(player)
on rightclick:
	if "%region at player%" does not contain "spawn" or "oldspawn":
		if player is not sneaking:
			if block data tag "age" of clicked block = 3:
				add 2 to {berry::%player%}
				add 0.4 to {exp::%player%}
				add 0.4 to {expharvest::%player%}
				UpdateScoreboard(player)
			if block data tag "age" of clicked block = 2:
				add 1 to {berry::%player%}
				add 0.2 to {exp::%player%}
				add 0.2 to {expharvest::%player%}
				UpdateScoreboard(player)
on rightclick:
	if player's tool is bonemeal:
		if block data tag "age" of clicked block < 7:
			if "%region at player%" does not contain "spawn" or "oldspawn":
				add 1 to {bonemeal::%player%}
				add 0.3 to {exp::%player%}
				add 0.3 to {expbonemeal::%player%}
				UpdateScoreboard(player)
on break of ripe beetroot plant:
	add 1 to {beetroot::%player%}
	add 0.5 to {exp::%player%}
	add 0.5 to {expharvest::%player%}
	UpdateScoreboard(player)
on mine of cobblestone:
	add 1 to {cobblestone::%player%}
	add 0.5 to {exp::%player%}
	add 0.5 to {expkopanie::%player%}
	UpdateScoreboard(player)
on mine of nether gold ore:
	add 1 to {nethergold::%player%}
	add 1.75 to {exp::%player%}
	add 1.75 to {expkopanie::%player%}
	UpdateScoreboard(player)
on mine of obsidian:
	add 1 to {obsidian::%player%}
	add 4 to {exp::%player%}
	add 4 to {expkopanie::%player%}
	UpdateScoreboard(player)
on mine of dirt:
	add 1 to {dirt::%player%}
	add 0.5 to {exp::%player%}
	add 0.5 to {expdigging::%player%}
	UpdateScoreboard(player)
on mine of gravel:
	add 1 to {gravel::%player%}
	add 0.5 to {exp::%player%}
	add 0.5 to {expdigging::%player%}
	UpdateScoreboard(player)
on mine of sand:
	add 1 to {sand::%player%}
	add 0.5 to {exp::%player%}
	add 0.5 to {expdigging::%player%}
	UpdateScoreboard(player)
on break of any leaves:
	add 1 to {%event-block%::%player%}
	add 0.25 to {exp::%player%}
	add 0.25 to {expleaves::%player%}
	UpdateScoreboard(player)
on mine of end stone:
	add 1 to {endstone::%player%}
	add 1 to {exp::%player%}
	add 1 to {expkopanie::%player%}
	UpdateScoreboard(player)
on death:
	if attacker is a player:
		if {passivemobs::*} contains "%type of victim%":
			add 2 to {exp::%victim%}
			add 1 to {%type of victim%::%attacker%}
			UpdateScoreboard(victim)
on block place:
	add 1 to {blocksplaced::%player%}
	if cooldown "place%player%" is not finished:
		stop
	else:
		create cooldown "place%player%" for 0.25 seconds
		add 1 to {exp::%player%}
		UpdateScoreboard(player)
function KolorekScoreboard(p: player) :: string:
	if {kolorek::%{_p}%} is set:
		set {_kolorek} to {kolorek::%{_p}%}
	else:
		if {poziom::%{_p}%} is smaller than 10:
			set {_kolorek} to "&6"
		if {poziom::%{_p}%} is smaller than 20:
			if {poziom::%{_p}%} is bigger than 9:
				set {_kolorek} to "&b"
		if {poziom::%{_p}%} is smaller than 30:
			if {poziom::%{_p}%} is bigger than 19:
				set {_kolorek} to "&c"
		if {poziom::%{_p}%} is smaller than 40:
			if {poziom::%{_p}%} is bigger than 29:
				set {_kolorek} to "&d"
		if {poziom::%{_p}%} is smaller than 50:
			if {poziom::%{_p}%} is bigger than 39:
				set {_kolorek} to "&a"
		if {poziom::%{_p}%} is smaller than 60:
			if {poziom::%{_p}%} is bigger than 49:
				set {_kolorek} to "&9"
		if {poziom::%{_p}%} is smaller than 70:
			if {poziom::%{_p}%} is bigger than 59:
				set {_kolorek} to "&e"
		if {poziom::%{_p}%} is smaller than 80:
			if {poziom::%{_p}%} is bigger than 69:
				set {_kolorek} to "&5"
		if {poziom::%{_p}%} is smaller than 90:
			if {poziom::%{_p}%} is bigger than 79:
				set {_kolorek} to "&3"
		if {poziom::%{_p}%} is smaller than 100:
			if {poziom::%{_p}%} is bigger than 89:
				set {_kolorek} to "&4"
	return {_kolorek}

function UpdateScoreboard(p: player):
	if {engagedc::%{_p}%} is not set:
		if {scorepl::%{_p}%} is not false:
			set {_kolorek} to KolorekScoreboard({_p})
			setup skoreboard for {_p}
			set {_e} to uncolored {kartaname::%{_p}%}
			set title of skoreboard {_p} to "&f&l«-───▬ %{_kolorek}%&lEC &f&l▬───-»"
			set slot 13 of skoreboard {_p} to ""
			if {language::%{_p}%} = "Polski":
				set slot 12 of skoreboard {_p} to " %{_kolorek}%&l* &f&lGRACZ:"
				set slot 11 of skoreboard {_p} to " &fKarta: %{_kolorek}%%{_e}%"
				set slot 10 of skoreboard {_p} to " &fWykopany kamień: %{_kolorek}%%{stone::%{_p}%}%"
				set slot 9 of skoreboard {_p} to " &fPoziom: %{_kolorek}%%{poziom::%{_p}%}%"
			else:
				set slot 12 of skoreboard {_p} to " %{_kolorek}%&l* &f&lPLAYER:"
				set slot 11 of skoreboard {_p} to " &fCard: %{_kolorek}%%{_e}%"
				set slot 10 of skoreboard {_p} to " &fStone Mined: %{_kolorek}%%{stone::%{_p}%}%"
				set slot 9 of skoreboard {_p} to " &fLevel: %{_kolorek}%%{poziom::%{_p}%}%"
			set slot 8 of skoreboard {_p} to " &fXP: %{_kolorek}%%{exp::%{_p}%}%&8/%{_kolorek}%%100*{poziom::%{_p}%}%"
			set {_c} to rounded down {exp::%{_p}%}/({poziom::%{_p}%}*100)*10
			if {_c} = 0:
				set slot 7 of skoreboard {_p} to "    &8&l■■■■■■■■■■"
			if {_c} = 1:
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■&8&l■■■■■■■■■"
			if {_c} = 2:
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■■&8&l■■■■■■■■"
			if {_c} = 3:
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■■■&8&l■■■■■■■"
			if {_c} = 4:
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■■■■&8&l■■■■■■"
			if {_c} = 5:
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■■■■■&8&l■■■■■"
			if {_c} = 6:
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■■■■■■&8&l■■■■"
			if {_c} = 7:
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■■■■■■■&8&l■■■"
			if {_c} = 8:
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■■■■■■■■&8&l■■"
			if {_c} = 9:
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■■■■■■■■■&8&l■"
			if {_c} = 10:	
				set slot 7 of skoreboard {_p} to "    %{_kolorek}%&l■■■■■■■■■■"
			set slot 6 of skoreboard {_p} to ""
			set slot 5 of skoreboard {_p} to "  &f&l«-───▬ %{_kolorek}%&lEC &f&l▬───-»"
function soundRankup(p:player):
	play sound "entity.generic.explode" with volume 5 and pitch 1 at {_p}
	play sound "block.note_block.harp" with volume 5 and pitch 2 at {_p}
on mine of stone:
	if {umkilof::%player%} = "Instalacje Ogrzewcze":
		chance of 20%:
			clear drops
			drop 1 stone at event-block
	minenew(player, "stone", event-block)
	if {gornictwo::poszumine::%player%} is true:
		chance of 1%:
			set {_f} to 1
			loop 3 times:
				play sound "block.note_block.xylophone" with volume 3 and pitch 1 to player
				add 0.3 to {_f}
				wait 0.3 seconds
			set {_czkamien} to a random integer between 1 and 11
			if {_czkamien} = 1:
				set event-block to red stained glass
			if {_czkamien} = 2:
				set event-block to lime stained glass
			if {_czkamien} = 3:
				set event-block to green stained glass
			if {_czkamien} = 4:
				set event-block to light blue stained glass
			if {_czkamien} = 5:
				set event-block to orange stained glass
			if {_czkamien} = 6:
				set event-block to yellow stained glass
			if {_czkamien} = 7:
				set event-block to magenta stained glass
			if {_czkamien} = 8:
				set event-block to purple stained glass
			if {_czkamien} = 9:
				set event-block to white stained glass
			if {_czkamien} = 10:
				set event-block to light gray stained glass
			if {_czkamien} = 11:
				set event-block to blue stained glass
			set {czystykamien::%event-block%} to true
			play sound "entity.player.levelup" with volume 3 and pitch 1 to player
			play sound "block.glass.break" with volume 3 and pitch 1.7 to player
on mine of deepslate:
	minenew(player, "deepslate", event-block)
	if {gornictwo::poszumine::%player%} is true:
		chance of 2%:
			set {_f} to 1
			loop 3 times:
				play sound "block.note_block.xylophone" with volume 3 and pitch 1 to player
				add 0.3 to {_f}
				wait 0.3 seconds
			set {_czkamien} to a random integer between 1 and 11
			if {_czkamien} = 1:
				set event-block to red stained glass
			if {_czkamien} = 2:
				set event-block to lime stained glass
			if {_czkamien} = 3:
				set event-block to green stained glass
			if {_czkamien} = 4:
				set event-block to light blue stained glass
			if {_czkamien} = 5:
				set event-block to orange stained glass
			if {_czkamien} = 6:
				set event-block to yellow stained glass
			if {_czkamien} = 7:
				set event-block to magenta stained glass
			if {_czkamien} = 8:
				set event-block to purple stained glass
			if {_czkamien} = 9:
				set event-block to white stained glass
			if {_czkamien} = 10:
				set event-block to light gray stained glass
			if {_czkamien} = 11:
				set event-block to blue stained glass
			set {czystykamien::%event-block%} to true
			play sound "entity.player.levelup" with volume 3 and pitch 1 to player
			play sound "block.glass.break" with volume 3 and pitch 1.7 to player
on mine of iron ore:
	if {umkilof::%player%} = "Magnes":
		loop all blocks in radius 4 around event-block:
			if loop-block is iron ore:
				if {placed::%loop-block%} is not true:
					set loop-block to air
					drop iron ore at loop-block
					add 1 to {_wyk}
					if {poziomgornictwo::%player%} > 44:
						set {_otxp} to 5
					else:
						set {_otxp} to 4
					add 1 to {zelazo::%player%}
					add 1 to {zelazocount::%player%}
					if {zelazocount::%player%} > 2:
						if player can hold iron ingot:
							give 1 iron ingot to player
						else:
							drop 1 iron ingot at player
						play sound "block.anvil.place" with volume 3 and pitch 1.8 to player
						remove 3 from {zelazocount::%player%}
					play sound "block.note_block.iron_xylophone" with volume 3 and pitch 0.6 at player
					if {gornictwo::stardust::%player%} is true:
						set {_dr} to a random integer between 2 and 3
						add {_dr} to {stardust::%player%}
						add {_dr} to {_otst}
		if {_wyk} is 1:
			if {language::%player%} = "English":
				send "&8[&6Earthcraft&8] &7Congratulations! You receive an &6Iron Ore&7. &7(+%{_otxp}*{_wyk}% &7XP)" to player
			else:
				send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6Rudę Żelaza&7! &7(+%{_otxp}*{_wyk}% &7XP)" to player
		else:
			if {_wyk} is set:
				if {language::%player%} = "English":
					send "&8[&6Earthcraft&8] &7Congratulations! You receive &6%{_wyk}% &6Iron Ores&7! &7(+%{_otxp}*{_wyk}% &7XP)" to player
				else:
					send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_wyk}% Rud Żelaza! &7(+%{_otxp}*{_wyk}% &7XP)" to player
		if {_wyk} is set:
			send "&8[&6Earthcraft&8] &7Otrzymujesz &6%{_otst}% &r%{stardust}'s name%u &7z wykopanych rud&7!" to player
			play sound "entity.experience_orb.pickup" with volume 3 and pitch 1.3 at player
			create a hologram at block above event-block with the id "sd-%location of event-block%"
			add line "&e+%{_otst}% <##6518ba>S<##942cce>t<##a925d9>a<##f346d1>r<##f37646>d<##f38646>u<##f18d18>s<##f3d846>t" to the hologram with id "sd-%location of event-block%"
			wait 2 seconds
			delete the hologram with the id "sd-%location of event-block%"
on block break:
	if player's gamemode is survival:
		if "%region at player%" contains "spawn":
			if event-block is not stone:
				cancel event
on rightclick:
	if player's gamemode is survival:
		if "%region at player%" contains "spawn":
			cancel event
on place of any ore:
	set {placed::%event-block%} to true
on mine of ore:
	if {placed::%event-block%} is not true:
		if event-block is diamond ore:
			set {_otxp} to 8
			add 1 to {diamenty::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Diamond Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7[&6Earthcraft&7] &7Gratulacje! Wykopałeś/aś <##bfbfff>Rudę Diamentu&7! &7(+&6%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is emerald ore:
			set {_otxp} to 16
			add 1 to {emerald::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine an <##bfbfff>Emerald Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Szmaragdu&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is coal ore:
			set {_otxp} to 2
			add 1 to {wegiel::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Coal Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Węgla&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is iron ore:	
			set {_otxp} to 4
			add 1 to {zelazo::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine an <##bfbfff>Iron Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Żelaza&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is lapis ore:
			set {_otxp} to 5
			add 1 to {lapis::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Lapis Lazuli Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Lazurytu&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is gold ore:
			set {_otxp} to 6
			add 1 to {zloto::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Gold Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Złota&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is redstone ore:
			set {_otxp} to 4
			add 1 to {redstone::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Redstone Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Redstone&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is copper ore:
			set {_otxp} to 3
			add 1 to {copper::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Copper Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Miedzi&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is deepslate diamond ore:
			set {_otxp} to 8
			add 1 to {diamenty::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Diamond Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Diamentu&7! &7(+&6%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is deepslate emerald ore:
			set {_otxp} to 16
			add 1 to {emerald::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine an <##bfbfff>Emerald Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Szmaragdu&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is deepslate coal ore:
			set {_otxp} to 2
			add 1 to {wegiel::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Coal Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Węgla&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is deepslate iron ore:	
			set {_otxp} to 4
			add 1 to {zelazo::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine an <##bfbfff>Iron Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Żelaza&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is deepslate lapis ore:
			set {_otxp} to 5
			add 1 to {lapis::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Lapis Lazuli Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Lazurytu&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is deepslate gold ore:
			set {_otxp} to 6
			add 1 to {zloto::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Gold Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Złota&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is deepslate redstone ore:
			set {_otxp} to 4
			add 1 to {redstone::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Redstone Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Redstone&7. (&6(+%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
		if event-block is deepslate copper ore:
			set {_otxp} to 3
			add 1 to {copper::%player%}
			if {language::%player%} = "English":
				send "&7[&6Earthcraft&7] You mine a <##bfbfff>Copper Ore&7. &7(+&6%{_otxp}% &7XP)" to player
			else:
				send "&7&7[&6Earthcraft&7] Wykopujesz <##bfbfff>Rudę Miedzi&7. (+&6%{_otxp}% &7XP)" to player
			add {_otxp} to {exp::%player%}
			UpdateScoreboard(player)
	else:
		clear {placed::%event-block%}
on break of red stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {rubin} at event-block
			add 1 to {rubin::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "y"
		else:
			set {_d} to ""
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##ff0000>Rubies&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##ff0000>Rubin%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of lime stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_pora} to a random integer between 1 and 2
		set {_x} to a random integer between 1 and 4
		if {_pora} = 1:
			loop {_x} times:
				drop {perydot} at event-block
				add 1 to {perydot::%player%}
				add 1 to {wykopanekamieniesz::%player%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				add 8 to {_otxp}
			add {_otxp} to {exp::%player%}
			add {_otxp} to {expkopanie::%player%}
			if {_x} > 1:
				set {_d} to "y"
			else:
				set {_d} to ""
			if {language::%{_p}%} = "English":
				send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##c0ff02>Peridots&7! &7(+%{_otxp}% &7XP)" to {_p}
			else:
				send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##c0ff02>Perydot%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		if {_pora} = 2:
			loop {_x} times:
				drop {awenturyn} at event-block
				add 1 to {awenturyn::%player%}
				add 1 to {wykopanekamieniesz::%player%}
				achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
				achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
				add 8 to {_otxp}
			add {_otxp} to {exp::%player%}
			add {_otxp} to {expkopanie::%player%}
			if {_x} > 1:
				set {_d} to "y"
			else:
				set {_d} to ""
			if {language::%{_p}%} = "English":
				send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##d5ff57>Aventurines&7! &7(+%{_otxp}% &7XP)" to {_p}
			else:
				send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##d5ff57>Awenturyn%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of green stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {jadeit} at event-block
			add 1 to {jadeit::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "y"
		else:
			set {_d} to ""
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##187a2f>Jade&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##187a2f>Jadeit%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of light blue stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {akwamaryn} at event-block
			add 1 to {akwamaryn::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "y"
		else:
			set {_d} to ""
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##11d7d8>Aquamarine&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##11d7d8>Akwamaryn%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of orange stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {cytryn} at event-block
			add 1 to {cytryn::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "y"
		else:
			set {_d} to ""
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##ff7926>Citrines&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##ff7926>Cytryn%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of yellow stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {topaz} at event-block
			add 1 to {topaz::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "y"
		else:
			set {_d} to ""
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##ffe505>Topaz&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##ffe505>Topaz%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of magenta stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {turmalin} at event-block
			add 1 to {turmalin::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "y"
		else:
			set {_d} to ""
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##ff0d6e>Tourmalines&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##ff0d6e>Turmalin%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of purple stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {ametyst} at event-block
			add 1 to {ametyst::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "y"
		else:
			set {_d} to ""
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##ae78d0>Amethysts&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##ae78d0>Ametyst%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of white stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {perla} at event-block
			add 1 to {perla::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "y"
		else:
			set {_d} to "ę"
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##f5d0eb>Pearls&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##f5d0eb>Perł%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of light gray stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {opal} at event-block
			add 1 to {opal::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "e"
		else:
			set {_d} to ""
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##dbd7da>Opals&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##dbd7da>Opal%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on break of blue stained glass:
	if {czystykamien::%event-block%} is set:
		clear {czystykamien::%event-block%}
		set {_x} to a random integer between 1 and 4
		loop {_x} times:
			drop {szafir} at event-block
			add 1 to {szafir::%player%}
			add 1 to {wykopanekamieniesz::%player%}
			achievement("wykopanekamieniesz", {_p}, 100, "osiagniecie.100kamsz", "Wykop 100 Kamieni Szlachetnych", "Kamienie Szlachetne", "Find 100 Gemstones when mining", "Gemstones")
			achievement("wykopanekamieniesz", {_p}, 1000, "osiagniecie.1000kamsz", "Wykop 1000 Kamieni Szlachetnych", "Więcej Kamieni Szlachetnych", "Find 1000 Gemstones when mining", "More Gemstones")
			add 8 to {_otxp}
		add {_otxp} to {exp::%player%}
		add {_otxp} to {expkopanie::%player%}
		if {_x} > 1:
			set {_d} to "y"
		else:
			set {_d} to ""
		if {language::%{_p}%} = "English":
			send "&8[&6Earthcraft&8] &7Congratulations! You found &6%{_x}% <##025b95>Sapphires&7! &7(+%{_otxp}% &7XP)" to {_p}
		else:
			send "&8[&6Earthcraft&8] &7Gratulacje! Wykopałeś/aś &6%{_x}% <##025b95>Szafir%{_d}%&7! &7(+%{_otxp}% &7XP)" to player
		wait 5 ticks
		loop 2 times:
			play sound "block.glass.break" with volume 1 and pitch 2 to player
			wait 5 ticks
on rightclick:
	if clicked block is stone or deepslate:
		if player's tool is pickaxe:
			if "%region at player%" does not contain "spawn":
				if {umkilof::%player%} = "PomocnaDłoń":
					set {cdpdlon::%player%} to 10 seconds
					set {pdlon::cooldown::%player%} to difference between {pdlon::use::%player%} and now
					if {pdlon::cooldown::%player%} is less than {cdpdlon::%player%}:
						set {pdlontekst::%player%} to "%difference between {cdpdlon::%player%} and {pdlon::cooldown::%player%}%"
						replace all " seconds" and "seconds" in {pdlontekst::%player%} with " sekund"
						if {tekstcd::%player%} = true:
							if {language::%player%} = "English":
								send "&7You must wait &f%{pdlontekst::%player%}%&7to use this ability again." to player
							else:
								send "&7Musisz odczekać &f%{pdlontekst::%player%}%&7, aby użyć tej umiejętności." to player
						stop
					set {pdlon::use::%player%} to now
					break target block naturally
					set the cooldown of player's held item for player to 10 seconds
					minenew(player, "%clicked block%", clicked block)
					play sound "block.stone.break" with volume 3 and pitch 1 at clicked block
					if {gornictwo::poszumine::%player%} is true:
						chance of 1%:
							set {_f} to 1
							loop 3 times:
								play sound "block.note_block.xylophone" with volume 3 and pitch 1 to player
								add 0.3 to {_f}
								wait 0.3 seconds
							set {_czkamien} to a random integer between 1 and 11
							if {_czkamien} = 1:
								set event-block to red stained glass
							if {_czkamien} = 2:
								set event-block to lime stained glass
							if {_czkamien} = 3:
								set event-block to green stained glass
							if {_czkamien} = 4:
								set event-block to light blue stained glass
							if {_czkamien} = 5:
								set event-block to orange stained glass
							if {_czkamien} = 6:
								set event-block to yellow stained glass
							if {_czkamien} = 7:
								set event-block to magenta stained glass
							if {_czkamien} = 8:
								set event-block to purple stained glass
							if {_czkamien} = 9:
								set event-block to white stained glass
							if {_czkamien} = 10:
								set event-block to light gray stained glass
							if {_czkamien} = 11:
								set event-block to blue stained glass
							set {czystykamien::%event-block%} to true
							play sound "entity.player.levelup" with volume 3 and pitch 1 to player
							play sound "block.glass.break" with volume 3 and pitch 1.7 to player
				if {umkilof::%player%} = "Eksplozja":
					set {cdeksplok::%player%} to 2 minutes
					set {eksplok::cooldown::%player%} to difference between {eksplok::use::%player%} and now
					if {eksplok::cooldown::%player%} is less than {cdeksplok::%player%}:
						set {eksploktekst::%player%} to "%difference between {cdeksplok::%player%} and {eksplok::cooldown::%player%}%"
						replace all " seconds" and "seconds" in {eksploktekst::%player%} with " sekund"
						replace all " minutes" and "minutes" in {eksploktekst::%player%} with " minut"
						replace all " minute" and "minute" in {eksploktekst::%player%} with " minuta"
						if {tekstcd::%player%} = true:
							if {language::%player%} = "English":
								send "&7You must wait &f%{eksploktekst::%player%}%&7to use this ability again." to player
							else:
								send "&7Musisz odczekać &f%{eksploktekst::%player%}%&7, aby użyć tej umiejętności." to player
						stop
					set {eksplok::use::%player%} to now
					set the cooldown of player's held item for player to 2 minutes
					play sound "entity.generic.explode" with volume 3 and pitch 1 at clicked block
					loop all blocks in radius 3 around clicked block:
						if loop-block is stone:
							break loop-block naturally
							minenew(player, "%clicked block%", clicked block)
							play sound "block.stone.break" with volume 3 and pitch 0 at loop-block
							if {gornictwo::poszumine::%player%} is true:
								chance of 1%:
									set {_czkamien} to a random integer between 1 and 11
									if {_czkamien} = 1:
										set loop-block to red stained glass
									if {_czkamien} = 2:
										set loop-block to lime stained glass
									if {_czkamien} = 3:
										set loop-block to green stained glass
									if {_czkamien} = 4:
										set loop-block to light blue stained glass
									if {_czkamien} = 5:
										set loop-block to orange stained glass
									if {_czkamien} = 6:
										set loop-block to yellow stained glass
									if {_czkamien} = 7:
										set loop-block to magenta stained glass
									if {_czkamien} = 8:
										set loop-block to purple stained glass
									if {_czkamien} = 9:
										set loop-block to white stained glass
									if {_czkamien} = 10:
										set loop-block to light gray stained glass
									if {_czkamien} = 11:
										set loop-block to blue stained glass
									set {czystykamien::%loop-block%} to true
									play sound "entity.player.levelup" with volume 3 and pitch 1 to player
									play sound "block.glass.break" with volume 3 and pitch 1.7 to player
							wait 1 tick
			else:
				send "&8[&6Earthcraft&8] &7Musisz znajdować się poza spawnem, by móc użyć specjalnej umiejętności kilofa." to player
on mine of andesite:
	add 0.5 to {exp::%player%}
	add 0.5 to {expkopanie::%player%}
	UpdateScoreboard(player)
on mine of diorite:
	add 0.5 to {exp::%player%}
	add 0.5 to {expkopanie::%player%}
	UpdateScoreboard(player)
on mine of granite:
	add 0.5 to {exp::%player%}
	add 0.5 to {expkopanie::%player%}
	UpdateScoreboard(player)
on mine of tuff:
	add 0.5 to {exp::%player%}
	add 0.5 to {expkopanie::%player%}
	UpdateScoreboard(player)
on mine of quartz ore:
	add 1.5 to {exp::%player%}
	add 1.5 to {expkopanie::%player%}
	add 1 to {kwarc::%player%}
	UpdateScoreboard(player)
on player pickup xp:
	if {orbbudget::%player%} > 0:
		cancel event
		loop all experience orbs in radius 2 around the player:
			kill loop-value
			stop loop
		remove 1 from {orbbudget::%player%}
		add 1 to {orbcount::%player%}
		play sound "entity.experience_orb.pickup" with volume 2 and pitch 2 to player
	else:
		if {orbbudget::%player%} is set:
			cancel event
			loop all experience orbs in radius 2 around the player:
				kill loop-value
				stop loop
on xp orb merge:
	cancel event
on sign change:
	line 1 is "[Elevator]":
		line 2 is "Lift Up":
			set line 1 to "&1[Elevator]"
			set line 2 to "Lift Up"
	line 1 is "[Elevator]":
		line 2 is "Lift Down":
			set line 1 to "&1[Elevator]"
			set line 2 to "Lift Down"
on rightclick on sign:
	line 1 is "&1[Elevator]":
		line 2 is "Lift Up":
			execute player command "/ascend"
		line 2 is "Lift Down":
			execute player command "/descend"
on leaves decay:
	cancel event
on skript load:
	execute console command "/whitelist on"
command /levelreset:
	trigger:
		send "&8[&aEarthcraft&8] &aZresetowano poziom&7!"
		clear {poziom::%player%}
		clear {exp::%player%}