function TalentLorePad(text: text, length: number, nametext: text) :: text:
	set {_pad} to ""
	loop rounded ((({_length} - length of {_text} + 4))/2) times:
		set {_pad} to "%{_pad}% "
	if {_length} + 1 is divisible by 2:
		set {_return} to "%{_pad}%%{_text}%"
	else:
		set {_return} to "%{_pad}%%{_text}%"
	broadcast length of {_pad}
	return {_return}

on inventory click:
	if event-inventory = (metadata tag "kartagui" of player):
		cancel event
		if index of clicked slot is 15:
			if name of event-slot contains "&6Talents":
				set {_haste} to Haste(player)
				play sound "ui.button.click" with volume 3 and pitch 2 to player
				set {_card} to uncolored name of player's tool
				set {_fix} to ""

				if {_card} = "Ghazan":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Glaceon":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Brother Therold":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Umbreon":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Vaporeon":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Delphox":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Buckshot":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Drogoz":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Cresselia":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Shenhe":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Espeon":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				else if {_card} = "Shaymin":
					set {_name} to "&f%{_fix}%%{_fix}%%{_fix}%&f%{_fix}%%{_fix}%%{_fix}%&fTalents - %{_card}%"
				set metadata tag "talentguispec" of player to chest inventory with 5 rows named {_name}
				set {_gui} to metadata tag "talentguispec" of player
				set {_id} to uncolored line 19 of lore of player's tool
				replace all "Id: " in {_id} with ""
				
				set {_div} to "&8&m-------✤-------&f"
				set {_15} to "&e✨ Level 15 Talent%nl%%{_div}%"
				set {_30} to "&e✨ Level 30 Talent%nl%%{_div}%"
				set {_40} to "&e✨ Level 40 Talent%nl%%{_div}%"
				set {_45} to "&e✨ Level 45 Talent%nl%%{_div}%"
				set {_50} to "&e✨ Level 50 Talent%nl%%{_div}%"
				
				
				set {_slot} to white stained glass pane named "&fRow Locked"
				set {_selected} to white stained glass pane named "&fTalent Learned" with lore "&7A talent in this row has already%nl%&7been learned."

				load yaml "plugins/Skript/playerdata/karty/%uncolored name of {karta::%player%}%/%{_id}%.yml" as "karty-%player%"

				loop 5 times:
					set {_row%loop-number%} to string tag "Talents;Row %loop-number%" of custom nbt of {karta::%player%}

				if {_card} = "Ghazan":
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to red dye named "<##b03228>Advanced Technique" with lore "%{_15}%%nl%&f <##b03228>Mastery: Lava Technique&7's maximum amount%nl%&7of &fstacks &7is increased to &f30&7.%nl% %nl%&f <##b03228>Mastery: Lava Technique&7's base &fdamage%nl%&famplification &7is increased by &f0.1%% &7per &fstack&7." with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
						set slot 3 of {_gui} to orange dye named "<##b03228>Hot Hand" with lore "%{_15}%%nl%&f <##b03228>Molten Lava &7ticks &f8%% &7faster, and your%nl%&7chance to generate &f <##b03228>Lava Surge &7is%nl%&7increased by &f2%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
						set slot 5 of {_gui} to blaze powder named "<##b03228>Unrivaled Finesse" with lore "%{_15}%%nl%&f <##b03228>Rain of Lava &7fires &f3 &7additional &f <##b03228>Lava Bursts&7.%nl%&7The duration of &f <##b03228>Rain of Lava &7is increased%nl%&7by &f1.5 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}	
					#30
					if int tag "Level" of custom nbt of {karta::%player%} >= 30:
						set {_lore} to "%nl%&f <##b03228>Ascendance%nl%&8Ultimate Ability%nl%&fInstant cast%nl%&7Cooldown:  &f{COOLDOWN}%nl%&7Use: &fRMB%nl%<##b03228>Transform into a &f <##d14d43>Lava Ascendant <##b03228>for &f18 sec<##b03228>,%nl%<##b03228>removing the cooldown on &f <##d14d43>Lava Burst <##b03228>and%nl%<##b03228>increasing the damage of &f <##d14d43>Lava Burst <##b03228>by an%nl%<##b03228>amount equal to your <##d14d43> Critical Strike <##b03228>chance.%nl% %nl%<##b03228>When you transform into the &f <##d14d43> Lava Ascendant,%nl%<##b03228>instantly cast a &f <##d14d43>Lava Burst <##b03228>at all enemies%nl%<##b03228>affected by your &f <##d14d43>Molten Lava<##b03228>, and refresh%nl%<##b03228>your &f <##d14d43>Molten Lava <##b03228>durations."
						set {_cdAsc} to "%360/{_haste}% seconds" parsed as timespan
						replace all "{COOLDOWN}" in {_lore} with "%{_cdAsc}%"
						set slot 10 of {_gui} to yellow dye named "<##b03228>Ascendance" with lore "%{_30}%%nl%&7Unlocks a new &fUltimate Ability&7:%nl% %{_lore}%" with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
						replace all "18 sec" in {_lore} with "6 sec"
						replace all "%{_cdAsc}%" in {_lore} with "none"
						set slot 12 of {_gui} to yellow dye named "<##b03228>Flow of Power" with lore "%{_30}%%nl%&7Casting &f <##b03228>Lava Burst &7has a &f4%% &7chance to%nl%&7activate &f <##b03228>Ascendance for &f6 sec&7.%nl% %{_lore}%" with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
						replace all "6 sec" in {_lore} with "8 sec"
						set slot 14 of {_gui} to yellow dye named "<##b03228>Lava Will Rain" with lore "%{_30}%%nl%&7When &f <##b03228>Rain of Lava &7ends, enter &f <##b03228>Ascendance%nl%&7for &f8 sec&7. When you activate &f <##b03228>Rain of Lava &7or%nl%&f <##b03228>Ascendance&7, increase your <##59c1e3> Intellect &7by &f20%nl%&7for the duration of the spell.%nl% %{_lore}%" with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
					else:
						replace all "15" in {_locked} with "30"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 30 on this Card."
						set slot 10 of {_gui} to {_slot} with lore {_locked}
						set slot 12 of {_gui} to {_slot} with lore {_locked}
						set slot 14 of {_gui} to {_slot} with lore {_locked}
					#40
					if int tag "Level" of custom nbt of {karta::%player%} >= 40:
						set {_cast} to 1.5/{_haste}
						set {_lWave} to 3 + ({damage::%player%}/35) + ({versatility::%player%}/105) + ({primarystat::%player%}/17.5)
						set {_lFury} to 5 + ({damage::%player%}/18) + ({versatility::%player%}/36) + ({primarystat::%player%}/9)
						set slot 19 of {_gui} to brown dye named "<##b03228>Lava Wave" with lore "%{_40}%%nl%&7Unlocks a new &fBasic Ability&7:%nl% %nl%&f <##b03228>Lava Wave%nl%&8Basic Ability%nl%&fInstant cast%nl%&7Cooldown: &8 &f1 minute%nl%&7Use: &fRMB%nl%<##b03228>Blast your target with a &f <##d14d43>Lava Wave<##b03228>, which%nl%<##b03228>deals &f%{_lWave}% <##ff3014>Lava <##b03228>damage <##b03228>and applies &f <##d14d43>Molten Lava%nl%<##b03228>upon reaching its target.%nl% %nl%<##b03228>Your next &f <##d14d43>Lava Burst <##b03228>will also hit all targets%nl%<##b03228>affected by &f <##d14d43>Molten Lava <##b03228>for &f80%% <##b03228>of normal%nl%<##b03228>damage." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
						set slot 21 of {_gui} to brown dye named "<##b03228>Lavakeeper" with lore "%{_40}%%nl%&7Unlocks a new &fBasic Ability&7:%nl% %nl%&f <##b03228>Lavakeeper%nl%&8Basic Ability%nl%&f%{_cast}% second cast%nl%&7Cooldown: &8 &f1 minute%nl%&7Use: &fRMB%nl%<##b03228>Charge yourself with heat, causing%nl%<##b03228>your next &f2 &f <##d14d43>Lava Burst <##b03228>casts to deal%nl%&f190%% <##b03228>increased damage." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
						set slot 23 of {_gui} to brown dye named "<##b03228>Lavafury" with lore "%{_40}%%nl%&7Unlocks a new &fBasic Ability&7:%nl% %nl%&f <##b03228>Lavafury%nl%&8Basic Ability%nl%&f%{_cast}% second cast%nl%&7Cooldown: &8 &f1 minute%nl%&7Use: &fRMB%nl%<##b03228>Hurls a hot lava rock at the target,%nl%<##b03228>dealing &f%{_lFury}% <##ff3014>Lava <##b03228>damage and causing your%nl%<##b03228>next &f3 &f <##d14d43>Molten Lava <##b03228>ticks to generate a%nl%&f <##d14d43>Lava Surge <##b03228>and deal &f20%% <##b03228>increased%nl%<##b03228>damage." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
					else:
						replace all "30" in {_locked} with "40"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 40 on this Card."
						set slot 19 of {_gui} to {_slot} with lore {_locked}
						set slot 21 of {_gui} to {_slot} with lore {_locked}
						set slot 23 of {_gui} to {_slot} with lore {_locked}
					#45
					if int tag "Level" of custom nbt of {karta::%player%} >= 45:
						set slot 28 of {_gui} to orange dye named "<##b03228>Magma Shock" with lore "                     %{_45}%%nl%                     %{_div}%%nl%&7Molten Lava no longer melts terrain and has a%nl%&7significantly decreased cooldown. You can now%nl%&7use it on a single target to apply a damage over%nl%&7time effect that lasts &f18 seconds &7and instantly%nl%&7deals &f3 <##ff3014>Lava &7damage. This ability inherits all other%nl%&7Molten Lava traits and has no target cap.%nl% %nl%&8&oPress [SHIFT + MOUSE] to expand tooltip." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
						set slot 30 of {_gui} to orange dye named "<##b03228>Flames of the Siege" with lore "               %{_45}%%nl%               %{_div}%%nl%&7Your Molten Lava gains &f60%% &7additional%nl%&7radius and slows enemies inside by &f30%%%nl% %nl%&8&oPress [SHIFT + MOUSE] to expand tooltip." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
						set slot 32 of {_gui} to orange dye named "<##b03228>Volcanic Tremors" with lore "                      %{_45}%%nl%                      %{_div}%%nl%&7Presing SHIFT while targeting Molten Lava will%nl%&7consume the molten terrain and apply Magma Shock%nl%&7to all enemies in the same radius that Molten Lava%nl%&7covers for the remaining duration of Molten Lava.%nl% %nl%<##b03228>&nMagma Shock%nl%<##b03228>Apply a damage over time effect, that causes%nl%&f3 <##ff3014>Lava <##b03228>damage instantly, <##b03228>and an additional%nl%&f12 <##ff3014>Lava <##b03228>damage over the duration.%nl% %nl%&8&oPress [SHIFT + MOUSE] to expand tooltip." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						replace all "40" in {_locked} with "45"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 45 on this Card."
						set slot 28 of {_gui} to {_slot} with lore {_locked}
						set slot 30 of {_gui} to {_slot} with lore {_locked}
						set slot 32 of {_gui} to {_slot} with lore {_locked}
					#50
					if int tag "Level" of custom nbt of {karta::%player%} >= 50:
						set slot 37 of {_gui} to brown dye named "<##b03228>Rolling Magma" with lore "%{_50}%%nl%&f <##b03228>Lava Burst &7damage &freduces &7the%nl%&fcooldown &7of &f <##b03228>Lava Wave&7, &f <##b03228>Lavakeeper%nl%&7and &f <##b03228>Lavafury &7by &f0.75 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
						set slot 39 of {_gui} to yellow dye named "<##b03228>Further Beyond" with lore "%{_50}%%nl%&7Reduces the &fcooldown &7of &f <##b03228>Ascendance &7by &f30 sec&7.%nl% %nl%&f <##b03228>Flow of Power &7gains an extra &f2%% chance%nl%&7to grant you &f <##b03228>Ascendance&7.%nl% %nl%&f <##b03228>Lava Will Rain &7grants an additional <##59c1e3> 20 Intellect&7.%nl% %nl%&7Additionally, you gain <##19943e> 200 Haste &7while%nl%&f <##b03228>Ascendance &7is active." with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
						set slot 41 of {_gui} to blaze powder named "<##b03228>Skytear" with lore "%{_50}%%nl%&fDoubles &7the amount of &f <##b03228>Lava Bursts &7fired by%nl%&f <##b03228>Rain of Lava &7and &fhalves &7the &frate &7at which%nl%&f <##b03228>Lava Bursts &7are fired." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
					else:
						replace all "45" in {_locked} with "50"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 50 on this Card."
						set slot 37 of {_gui} to {_slot} with lore {_locked}
						set slot 39 of {_gui} to {_slot} with lore {_locked}
						set slot 41 of {_gui} to {_slot} with lore {_locked}
				else if {_card} = "Glaceon":
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to diamond named "<##4bbfe2>Winter's Blessing" with lore "                  %{_15}%%nl%                  %{_div}%%nl%&7Increases your <##19943e> Haste &7rating by &f12&7.%nl%&7You gain &f10%% &7more <##19943e> Haste &7from all sources." with nbt from "{""minecraft:custom_model_data"":{floats:[32.0f]}}"
						set slot 3 of {_gui} to prismarine shard named "<##4bbfe2>Clarity of Thought" with lore "              %{_15}%%nl%              %{_div}%%nl%&7Frostbolt has an additional &f5%% &7chance%nl%&7to activate Brain Freeze." with nbt from "{""minecraft:custom_model_data"":{floats:[12.0f]}}"
						set slot 5 of {_gui} to diamond named "<##4bbfe2>Ice Cycle" with lore "          %{_15}%%nl%           %{_div}%%nl%&7Each fired Icicle has a &f8%% &7chance%nl%&7to not be consumed." with nbt from "{""minecraft:custom_model_data"":{floats:[45.0f]}}"
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}	
					#30
					if int tag "Level" of custom nbt of {karta::%player%} >= 30:
						set slot 10 of {_gui} to lapis lazuli named "<##4bbfe2>Thermal Void" with lore "                    %{_30}%%nl%                    %{_div}%%nl%&7Icy Veins' duration is increased by &f10 sec&7.%nl%&7Your Ice Lances against frozen targets extend%nl%&7your Icy Veins by an additional &f1 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
						set slot 12 of {_gui} to light blue dye named "<##4bbfe2>Lonely Winter" with lore "              %{_30}%%nl%              %{_div}%%nl%&7Frostbolt, Ice Lance, and Flurry deal%nl%&f25%% &7increased damage." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 14 of {_gui} to diamond named "<##4bbfe2>Ice Nine" with lore "     %{_30}%%nl%     %{_div}%%nl%&7Every 9th Icicle deals%nl%&f90%% &7increased damage." with nbt from "{""minecraft:custom_model_data"":{floats:[45.0f]}}"
					else:
						replace all "15" in {_locked} with "30"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 30 on this Card."
						set slot 10 of {_gui} to {_slot} with lore {_locked}
						set slot 12 of {_gui} to {_slot} with lore {_locked}
						set slot 14 of {_gui} to {_slot} with lore {_locked}
					#40
					if int tag "Level" of custom nbt of {karta::%player%} >= 40:
						set slot 19 of {_gui} to prismarine shard named "<##4bbfe2>Frozen Touch" with lore "                  %{_40}%%nl%                  %{_div}%%nl%&7Frostbolt grants you Fingers of Frost &f25%%%nl%&7more often and Brain Freeze &f20%% &7more often." with nbt from "{""minecraft:custom_model_data"":{floats:[12.0f]}}"
						set slot 21 of {_gui} to light blue dye named "<##4bbfe2>Chain Reaction" with lore "                  %{_40}%%nl%                  %{_div}%%nl%&7Your Ice Lances against Frozen targets%nl%&7increase the damage of your Ice Lance by%nl%&f2%% &7for &f10 seconds&7, stacking up to 5 times." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 23 of {_gui} to diamond named "<##4bbfe2>Black Ice" with lore "                  %{_40}%%nl%                  %{_div}%%nl%&7Icicles have a &f30%% &7chance to become%nl%&7empowered and deal &f70%% &7increased damage." with nbt from "{""minecraft:custom_model_data"":{floats:[45.0f]}}"
					else:
						replace all "30" in {_locked} with "40"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 40 on this Card."
						set slot 19 of {_gui} to {_slot} with lore {_locked}
						set slot 21 of {_gui} to {_slot} with lore {_locked}
						set slot 23 of {_gui} to {_slot} with lore {_locked}
					#45
					if int tag "Level" of custom nbt of {karta::%player%} >= 45:
						set slot 28 of {_gui} to blue dye named "<##4bbfe2>Slick Ice" with lore "                  %{_45}%%nl%                  %{_div}%%nl%&7While Icy Veins is active, each Frostbolt you%nl%&7cast reduces the cast time of Frostbolt by%nl%&7&f4%% &7and increases its damage by &f4%%&7, stacking%nl%&7up to 5 times." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
						set slot 30 of {_gui} to light blue dye named "<##4bbfe2>Splitting Ice" with lore "                %{_45}%%nl%                %{_div}%%nl%&7Your Ice Lance, Icicles and Glacial Spike%nl%&7now deal &f5%% &7increased damage, and hit all%nl%&7nearby targets for &f20%% &7of their damage." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 32 of {_gui} to diamond named "<##4bbfe2>Icicle Storm" with lore "                 %{_45}%%nl%                 %{_div}%%nl%&7Casting Icy Veins hurls 5 Icicles with &f40%%%nl%&7effectiveness at your last damaged enemy." with nbt from "{""minecraft:custom_model_data"":{floats:[45.0f]}}"
					else:
						replace all "40" in {_locked} with "45"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 45 on this Card."
						set slot 28 of {_gui} to {_slot} with lore {_locked}
						set slot 30 of {_gui} to {_slot} with lore {_locked}
						set slot 32 of {_gui} to {_slot} with lore {_locked}
					#50
					if int tag "Level" of custom nbt of {karta::%player%} >= 50:
						set slot 37 of {_gui} to lapis lazuli named "<##4bbfe2>Chilled to the Core" with lore "        %{_50}%%nl%        %{_div}%%nl%&7Icy Veins encases you in ice,%nl%&7increasing your Ice damage%nl%&7dealt by &f20%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
						set slot 39 of {_gui} to light blue dye named "<##4bbfe2>Freezing Winds"  with lore "           %{_50}%%nl%          %{_div}%%nl%&7While Icy Veins is active, you gain%nl%&7Fingers of Frost every &f3 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 41 of {_gui} to prismarine crystals named "<##4bbfe2>Glacial Spike" with lore "                   %{_50}%%nl%                   %{_div}%%nl%&f2.75 second cast%nl%&7No cooldown%nl%&7Use: &fRMB%nl%&7Talent Ability%nl%<##4bbfe2>Conjures a massive spike of ice, and merges%nl%<##4bbfe2>your current Icicles into it. It impales your%nl%<##4bbfe2>target, dealing &f%5 + {damage::%player%}/14 + {versatility::%player%}/42 + {primarystat::%player%}/7% <##add8e6>Ice <##4bbfe2>damage plus all of the%nl%<##4bbfe2>damage stored in your Icicles.%nl% %nl%<##4bbfe2>Requires 5 Icicles to cast.%nl% %nl%<##4bbfe2>Passive: Ice Lance no longer launches Icicles.%nl% %nl%&8&oPress [SHIFT + MOUSE] to expand tooltip." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
					else:
						replace all "45" in {_locked} with "50"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 50 on this Card."
						set slot 37 of {_gui} to {_slot} with lore {_locked}
						set slot 39 of {_gui} to {_slot} with lore {_locked}
						set slot 41 of {_gui} to {_slot} with lore {_locked}
				else if {_card} = "Brother Therold":
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to light gray dye named "<##613e82>Fortress of the Mind" with lore "                %{_15}%%nl%                %{_div}%%nl%&7Mind Flay and Mind Blast deal &f10%% &7more%nl%&7damage and generate &f20%% &7more Insanity" with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
						set slot 3 of {_gui} to popped chorus fruit named "<##613e82>Twist of Fate" with lore "                 %{_15}%%nl%                 %{_div}%%nl%&7After damaging a target below &f35%% &7health,%nl%&7you gain &f10%% &7increased damage%nl%&7and healing for &f8 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
						set slot 5 of {_gui} to light gray dye named "<##613e82>Shadow Word: Void" with lore "         %{_15}%%nl%         %{_div}%%nl%&f2 Charges%nl%&f1.5 second cast%nl%&7Cooldown: &f9 seconds%nl%&7Use: &fRMB%nl%&7Talent Ability%nl%<##613e82>Blasts the target's mind for &f%(5 + (({primarystat::%player%}/9) + ({damage::%player%}/18) + ({versatility::%player%}/54)))%%nl%<##431d53>Ghost <##613e82>damage.%nl% %nl%&fGenerates 15 Insanity.%nl% %nl%&7Replaces Mind Blast." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}	
					#30
					if int tag "Level" of custom nbt of {karta::%player%} >= 30:
						set {_mentalFortitude} to (player's max health/4.25)-3 + {primarystat::%player%}/8.75
						set slot 10 of {_gui} to cyan dye named "<##613e82>Mental Fortitude" with lore "                   %{_30}%%nl%                   %{_div}%%nl%&7Healing from Vampiric Touch when you are at%nl%&7maximum health will shield you for the same%nl%&7amount. Shield cannot exceed &f%{_mentalFortitude}% &7damage%nl%&7absorbed." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
						set slot 12 of {_gui} to light gray dye named "<##613e82>Mania" with lore "         %{_30}%%nl%         %{_div}%%nl%&7You move &f1%% &7faster for every%nl%&f5 &7Insanity you have." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
						set slot 14 of {_gui} to popped chorus fruit named "<##613e82>Body and Soul" with lore "       %{_30}%%nl%       %{_div}%%nl%&7Your self-healing done is%nl%&7increased by &f6%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
					else:
						replace all "15" in {_locked} with "30"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 30 on this Card."
						set slot 10 of {_gui} to {_slot} with lore {_locked}
						set slot 12 of {_gui} to {_slot} with lore {_locked}
						set slot 14 of {_gui} to {_slot} with lore {_locked}
					#40
					if int tag "Level" of custom nbt of {karta::%player%} >= 40:
						set slot 19 of {_gui} to purple dye named "<##613e82>Lingering Insanity" with lore "               %{_40}%%nl%               %{_div}%%nl%&7When Voidform ends, its <##19943e> Haste &7bonus%nl%&7fades by &f1%% &7every &f2 sec&7, instead of%nl%&7ending immediately." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 21 of {_gui} to yellow dye named "<##613e82>Reaper of Souls" with lore "               %{_40}%%nl%               %{_div}%%nl%&7Shadow Word: Death is now castable on%nl%&7targets below &f35%% &7health, and always%nl%&7generates Insanity as though it killed%nl%&7the target." with nbt from "{""minecraft:custom_model_data"":{floats:[6.0f]}}"
						set slot 23 of {_gui} to cyan dye named "<##613e82>Void Ray" with lore "                %{_40}%%nl%                %{_div}%%nl%&7Each time your Mind Flay deals damage,%nl%&7you gain &f10%% &7increased Mind Flay damage%nl%&7for &f6 sec&7, stacking up to &f4 &7times." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
					else:
						replace all "30" in {_locked} with "40"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 40 on this Card."
						set slot 19 of {_gui} to {_slot} with lore {_locked}
						set slot 21 of {_gui} to {_slot} with lore {_locked}
						set slot 23 of {_gui} to {_slot} with lore {_locked}
					#45
					if int tag "Level" of custom nbt of {karta::%player%} >= 45:
						set slot 28 of {_gui} to purple dye named "<##613e82>Auspicious Spirits" with lore "                  %{_45}%%nl%                  %{_div}%%nl%&7Your Shadowy Apparitions now deal &f100%%%nl%&7increased damage and generate &f3 &7Insanity." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
						set slot 30 of {_gui} to light gray dye named "<##613e82>Shadowy Insight" with lore "                 %{_45}%%nl%                 %{_div}%%nl%&7Shadow Word: Pain's periodic damage has a%nl%&7a &f4%% &7chance to reset the cooldown on Mind%nl%&7Blast and make your next Mind Blast instant." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
						set slot 32 of {_gui} to gray dye named "<##613e82>San'Layn" with lore "           %{_45}%%nl%           %{_div}%%nl%&7Increases the damage and healing%nl%&7of your Vampiric Touch by &f20%%&7" with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
					else:
						replace all "40" in {_locked} with "45"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 45 on this Card."
						set slot 28 of {_gui} to {_slot} with lore {_locked}
						set slot 30 of {_gui} to {_slot} with lore {_locked}
						set slot 32 of {_gui} to {_slot} with lore {_locked}
					#50
					if int tag "Level" of custom nbt of {karta::%player%} >= 50:
						set slot 37 of {_gui} to purple dye named "<##613e82>Legacy of the Void" with lore "                  %{_50}%%nl%                  %{_div}%%nl%&7Void Eruption's cast time is reduced by &f40%%%nl%&7and may be cast anytime your Insanity level%nl%&7is &f60 &7or higher." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 39 of {_gui} to gray dye named "<##613e82>Misery" with lore "            %{_50}%%nl%            %{_div}%%nl%&7Vampiric Touch also applies Shadow%nl%&7Word: Pain to the target." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
						set slot 41 of {_gui} to popped chorus fruit named "<##613e82>Surrender to Madness" with lore "                    %{_50}%%nl%                    %{_div}%%nl%&7Unlocks a new ability: <##613e82>Surrender to Madness&7.%nl% %nl%<##613e82>Surrender to Madness%nl%&fInstant cast%nl%&7Cooldown: &f10 minutes%nl%&7Use: &fRMB%nl%&7Talent Ability%nl%<##613e82>Surrender your soul to the Old Gods, sacrificing%nl%<##613e82>your soul for ultimate power.%nl% %nl%<##613e82>All your <##8165a6>Insanity<##613e82>-generating abilities generate%nl%&f200%% <##613e82>more <##8165a6>Insanity <##613e82>until you exit <##8165a6>Voidform<##613e82>.%nl% %nl%<##613e82>Then you die. Horribly." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
					else:
						replace all "45" in {_locked} with "50"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 50 on this Card."
						set slot 37 of {_gui} to {_slot} with lore {_locked}
						set slot 39 of {_gui} to {_slot} with lore {_locked}
						set slot 41 of {_gui} to {_slot} with lore {_locked}
				else if {_card} = "Umbreon":
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to blaze rod named "<##555555>Quick Claw" with lore "%{_15}%%nl%&7Night Slash has a &f50%% &7reduced cooldown,%nl%&7but deals &f25%% &7less damage.%nl% %nl%&7Unlocks a new passive ability: <##555555>Moon Strikes&7.%nl% %nl%<##555555>Moon Strikes%nl%&7Night Slash has a &f40%% &7chance to repeat%nl%&7its damage." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
						set slot 3 of {_gui} to blaze rod named "<##555555>Heavy Claw" with lore "%{_15}%%nl%&7Night Slash deals &f87.5%% &7increased damage,%nl%&7but its cooldown is increased by &f25%%&7.%nl% %nl%&7Unlocks a new passive ability: <##555555>Moon Strikes&7.%nl% %nl%<##555555>Moon Strikes%nl%&7Night Slash has a &f40%% &7chance to repeat%nl%&7its damage." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
						set slot 5 of {_gui} to blaze rod named "<##555555>Sharp Claw" with lore "%{_15}%%nl%&7Night Slash deals &f50%% &7increased damage.%nl% %nl%&7Unlocks a new passive ability: <##555555>Moon Strikes&7.%nl% %nl%<##555555>Moon Strikes%nl%&7Night Slash has a &f40%% &7chance to repeat%nl%&7its damage." with nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]}}"
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}
					#Fatal strike
					# middle - Your first Night Slash used on a target deals an additional heavy damage.
					#Garrote - quick row, your ngiht slash has a chance to apply a bleed
					#Deadly precision
					#Shadow Dance
					#utility row Cheat death - avoid death once per x min #Soothing Darkness - heal over max hp when you enter invisibility (cd on this) Shadowrunner - while invisible, your mobility is increased by 100
					#Deathmark
					# Lunar inspiration
					#Bloodtalons

				else if {_card} = "Delphox":
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to blaze rod named "<##fa4420>Firestarter" with lore "%{_15}%%nl%&f <##fa4420>Flamethrower &7always <##fa4420> Critically Strikes &7and%nl%&7inflicts &f50%% &7increased damage when it is%nl%&7used against targets above &f90%% &7health." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 3 of {_gui} to blaze powder named "<##fa4420>Hellcaller" with lore "%{_15}%%nl%&7Detonating an &f <##fa4420>Inferno &7increases the damage%nl%&7of all consecutive &f <##fa4420>Inferno &7detonations by%nl%&f12.5%% &7for &f3 sec&7, stacking &finfinitely&7.%nl% %nl%&7Detonating an &f <##fa4420>Inferno &7does not refresh the%nl%&7duration of the damage amp." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 5 of {_gui} to red dye named "<##fa4420>Pyrotechnics" with lore "%{_15}%%nl%&f <##fa4420>Flamethrower &7has a &f20%% &7to grant%nl%&7you an &fadditional stack &7of &f <##fa4420>Blaze&7." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}
					#30
					if int tag "Level" of custom nbt of {karta::%player%} >= 30:
						set {_haste} to Haste(player)
						set {_flamethrowerCooldown} to 14/{_haste}
						set slot 10 of {_gui} to blaze rod named "<##fa4420>Flame Accelerant" with lore "%{_30}%%nl%&7If you have not cast &f <##fa4420>Flamethrower &7in &f%{_flamethrowerCooldown}% sec&7,%nl%&7your next &f <##fa4420>Flamethrower &7will deal damage &f30%%%nl%&7faster, deal &f120%% &7extra damage and have a%nl%&f50%% &7reduced cooldown." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 12 of {_gui} to blaze powder named "<##fa4420>Convection" with lore "%{_30}%%nl%&7Detonating an &f <##fa4420>Inferno &7has a &f10%% &7chance%nl%&7to automatically cast a &fsecond  <##fa4420>Inferno%nl%&7on the same target." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 14 of {_gui} to red dye named "<##fa4420>Kindling" with lore "%{_30}%%nl%&7Your successful &f <##fa4420>Blaze &7and &f <##fa4420>Inferno%nl%<##fa4420> Critical Strikes &7reduce the remaining%nl%&7cooldown of &f <##fa4420>Heat Snap &7by &f1 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
					else:
						replace all "15" in {_locked} with "30"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 30 on this Card."
						set slot 10 of {_gui} to {_slot} with lore {_locked}
						set slot 12 of {_gui} to {_slot} with lore {_locked}
						set slot 14 of {_gui} to {_slot} with lore {_locked}
					#40
					if int tag "Level" of custom nbt of {karta::%player%} >= 40:
						set slot 19 of {_gui} to blaze rod named "<##fa4420>Oxidizing Flame" with lore "%{_40}%%nl%&f <##fa4420>Flamethrower &7ticks have a &f20%% &7chance to%nl%&7flare up and deal &f30%% &7increased damage." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 21 of {_gui} to blaze powder named "<##fa4420>Fire to the Fuse" with lore "%{_40}%%nl%&f <##fa4420>Inferno &7deals &f50%% &7of its explosion damage%nl%&7to all enemies around the target in a small%nl%&7radius." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 23 of {_gui} to red dye named "<##fa4420>Firespread" with lore "%{_40}%%nl%&7Triggering &f <##fa4420>Blaze &7spreads the effect to%nl%&ftwo &7additional targets, and &f <##fa4420>Blaze &7deals%nl%&f30%% &7extra damage per target hit." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
					else:
						replace all "30" in {_locked} with "40"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 40 on this Card."
						set slot 19 of {_gui} to {_slot} with lore {_locked}
						set slot 21 of {_gui} to {_slot} with lore {_locked}
						set slot 23 of {_gui} to {_slot} with lore {_locked}
					#45
					if int tag "Level" of custom nbt of {karta::%player%} >= 45:
						set {_damage} to 1.25 + ({versatility::%player%}/420) + ({damage::%player%}/140) + {primarystat::%player%}/70
						set slot 28 of {_gui} to blaze rod named "<##fa4420>Will-o-Wisp" with lore "%{_45}%%nl%&f <##fa4420>Flamethrower &7ticks have a &f10%% &7chance%nl%&7to summon a &f <##eb6146>Will-o-Wisp&7.%nl% %nl%&f <##eb6146>Will-o-Wisp%nl%&7Adds an &fadditional tick &7of &f <##fa4420>Flamethrower%nl%&7to the target and deals an instance of%nl%&f%{_damage}% <##ff4d00>Fire &7damage." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 30 of {_gui} to blaze powder named "<##fa4420>Blazing Tricks" with lore "%{_45}%%nl%&7After successfully detonating &f <##fa4420>Inferno &f15 &7times,%nl%&7your next &f <##fa4420>Blaze &7cast will trigger an &f <##fa4420>Inferno%nl%&7explosion with &f150%% &7effectiveness on all%nl%&7affected targets." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 32 of {_gui} to red dye named "<##fa4420>Flame Cascade" with lore "%{_45}%%nl%&f <##fa4420>Heat Snap &7triggers &f <##fa4420>Blaze &7with &f270%%%nl%&7effectiveness on all affected targets." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
					else:
						replace all "40" in {_locked} with "45"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 45 on this Card."
						set slot 28 of {_gui} to {_slot} with lore {_locked}
						set slot 30 of {_gui} to {_slot} with lore {_locked}
						set slot 32 of {_gui} to {_slot} with lore {_locked}
					#50
					if int tag "Level" of custom nbt of {karta::%player%} >= 50:
						set slot 37 of {_gui} to blaze rod named "<##fa4420>Hot Spree" with lore "%{_50}%%nl%&7Unlocks a new &fPassive Ability&7:%nl% %nl%&f <##fa4420>Hot Spree%nl%&8Passive Ability%nl%&fNo cast%nl%&7Cooldown: &8 &fnone%nl%&7Use: &fPASSIVE%nl%<##fa4420>Every third &f <##f2636a>Flamethrower <##fa4420>will not incur%nl%<##fa4420>a cooldown. When a &ffree  <##f2636a>Flamethrower%nl%<##fa4420>is used, its damage is increased by &f50%%<##fa4420>.%nl% %nl%<##fa4420>Damage dealt by &f <##f2636a>Flamethrower <##fa4420>is%nl%<##fa4420>increased by &f60%%<##fa4420>.%nl% %nl%<##fa4420>Replaces &f <##f2636a>Inferno<##fa4420>." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 39 of {_gui} to blaze powder named "<##fa4420>Flaming Finale" with lore "%{_50}%%nl%&f <##fa4420>Heat Snap &7now also flares up all your active%nl%&f <##fa4420>Infernos&7, dealing &f4 <##ff4d00>Fire &7damage to all affected%nl%&7targets and detonating all &f <##fa4420>Infernos &7at once.%nl% %nl%&f <##fa4420>Infernos &7detonated by this effect have their%nl%&7damage increased by &f60%%&7.%nl% %nl%&7Increases the cooldown of &f <##fa4420>Heat Snap &7by &f30 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 41 of {_gui} to red dye named "<##fa4420>Wildfire" with lore "%{_50}%%nl%&7Each &f <##fa4420>Flamethrower &7tick increases the damage%nl%&7dealt by &f <##fa4420>Blaze by &f1%%&7, stacking up to &f600%%&7.%nl% %nl%&7The stack count resets upon leaving combat." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
					else:
						replace all "45" in {_locked} with "50"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 50 on this Card."
						set slot 37 of {_gui} to {_slot} with lore {_locked}
						set slot 39 of {_gui} to {_slot} with lore {_locked}
						set slot 41 of {_gui} to {_slot} with lore {_locked}
					#Heat Snap flares up all your active Inferno's, dealing x damage and detonating them all at once. Inferno Detonation damage dealt by this ability is increased by 130%.
					#

				else if {_card} = "Vaporeon":
					set {_haste} to Haste(player)
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to blue dye named "<##7cafbf>Undulation" with lore "                %{_15}%%nl%                %{_div}%%nl%&7Healing Stream gains &fan additional charge%nl%&7and healing done by Healing Stream is%nl%&7increased by &f15%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
						set slot 3 of {_gui} to clay ball named "<##7cafbf>Undercurrent" with lore "               %{_15}%%nl%               %{_div}%%nl%&7For each Explosive Bubble active on an%nl%&7ally, your heals are &f8%% &7more effective." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
						set slot 5 of {_gui} to cyan dye named "<##7cafbf>Flow of the Tides" with lore "              %{_15}%%nl%              %{_div}%%nl%&7When your Circle of Water scores a%nl%<##fca417> Critical &7heal, your target is healed%nl%&7for an additional &f130%% &7of the amount." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}	
					#30
					if int tag "Level" of custom nbt of {karta::%player%} >= 30:
						set slot 10 of {_gui} to white dye named "<##7cafbf>Tidewaters" with lore "                   %{_30}%%nl%                   %{_div}%%nl%&7Healing Stream sends a second stream of%nl%&7revitalising waters at the affected ally after%nl%&f3 seconds&7, reduced by <##19943e> Haste&7. The second%nl%&7stream restores &f35%% &7of the initial value as HP%nl%&7to the ally.%nl% %nl%&7Unlocks a new passive ability: <##7cafbf>Tidal Waves&7.%nl% %nl%<##7cafbf>Tidal Waves%nl%&7Casting Explosive Bubble grants &f1 &7stack of%nl%&7Tidal Waves. Tidal Waves increase the healing%nl%&7of your next Healing Stream by &f30%%&7. Stacks%nl%&7up to &f2 &7times." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
						set slot 12 of {_gui} to white dye named "<##7cafbf>Downpour" with lore "                   %{_30}%%nl%                   %{_div}%%nl%&7When an Explosive Bubble detonates, a%nl%&7healing rain is summoned above the target,%nl%&7restoring &f25%% &7of the remaining shield value%nl%&7as HP to the ally.%nl% %nl%&7Unlocks a new passive ability: <##7cafbf>Tidal Waves&7.%nl% %nl%<##7cafbf>Tidal Waves%nl%&7Casting Explosive Bubble grants &f1 &7stack of%nl%&7Tidal Waves. Tidal Waves increase the healing%nl%&7of your next Healing Stream by &f30%%&7. Stacks%nl%&7up to &f2 &7times." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"	
						set slot 14 of {_gui} to white dye named "<##7cafbf>Watercycles" with lore "                  %{_30}%%nl%                  %{_div}%%nl%&7Gain a stacking <##e3ebff> 30 Versatility &7for &f4 sec%nl%&7when you successfully detonate a Circle%nl%&7of Water. Additionally, your Circle of Water%nl%&7is &f40%% &7more effective.%nl% %nl%&7Unlocks a new passive ability: <##7cafbf>Tidal Waves&7.%nl% %nl%<##7cafbf>Tidal Waves%nl%&7Casting Explosive Bubble grants &f1 &7stack of%nl%&7Tidal Waves. Tidal Waves increase the healing%nl%&7of your next Healing Stream by &f30%%&7. Stacks%nl%&7up to &f2 &7times." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
					else:
						replace all "15" in {_locked} with "30"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 30 on this Card."
						set slot 10 of {_gui} to {_slot} with lore {_locked}
						set slot 12 of {_gui} to {_slot} with lore {_locked}
						set slot 14 of {_gui} to {_slot} with lore {_locked}
					#40
					if int tag "Level" of custom nbt of {karta::%player%} >= 40:
						set {_cdbubble} to 20/{_haste}
						set {_cdredCurrent} to {_cdbubble}*0.025
						set slot 19 of {_gui} to white dye named "<##7cafbf>High Tide" with lore "          %{_40}%%nl%          %{_div}%%nl%&7Increases the healing bonus%nl%&7provided by <##7cafbf>Tidal Waves &7by &f40%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
						set slot 21 of {_gui} to clay ball named "<##7cafbf>Current Control" with lore "             %{_40}%%nl%             %{_div}%%nl%&7When you successfully &fheal &7an ally,%nl%&7reduce the cooldown of Explosive%nl%&7Bubble on them by &f%{_cdredCurrent}% sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
						set slot 23 of {_gui} to cyan dye named "<##7cafbf>Overflow" with lore "               %{_40}%%nl%               %{_div}%%nl%&7Increases <##f53b98> Mastery &7scaling by &f20%%&7.%nl%&7Circle of Water will now always benefit%nl%&7from Mastery: Water Cycles, regardless%nl%&7of its target's health." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
					else:
						replace all "30" in {_locked} with "40"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 40 on this Card."
						set slot 19 of {_gui} to {_slot} with lore {_locked}
						set slot 21 of {_gui} to {_slot} with lore {_locked}
						set slot 23 of {_gui} to {_slot} with lore {_locked}
					#45
					if int tag "Level" of custom nbt of {karta::%player%} >= 45:
						set slot 28 of {_gui} to white dye named "<##7cafbf>Coalescing Tides" with lore "                 %{_45}%%nl%                 %{_div}%%nl%&7Healing Streams empowered by <##7cafbf>Tidal Waves%nl%&7will heal all allies around the target &7for &f30%%%nl%&7of the heal value. If no additional allies are%nl%&7present, the target will be healed for the%nl%&7bonus value instead.%nl% %nl%<##7cafbf>Tidal Waves &7can now stack up to &f4 &7times.%nl%&7All stacks will be consumed to enhance%nl%&7a single Healing Stream." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
						set slot 30 of {_gui} to light blue dye named "<##7cafbf>Oceanic Unison" with lore "              %{_45}%%nl%              %{_div}%%nl%&7Reversal grants <##f53b98> 1.5 Mastery &7to all%nl%&7affected allies per &f0.5%% &7max health%nl%&7restored. Additionally, healing done%nl%&7by Reversal is increased by &f100%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[10.0f]}}"
						set slot 32 of {_gui} to cyan dye named "<##7cafbf>Searage" with lore "                 %{_45}%%nl%                 %{_div}%%nl%&7When Circle of Water <##fca417> Critically &7heals,%nl%&7you have a &f30%% &7chance to reapply it on%nl%&7the same target.%nl% %nl%&7Circle of Water now creates a riptide when%nl%&7it detonates, dealing the &fheal &7value as%nl%&fdamage &7to nearby enemies&7." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
					else:
						replace all "40" in {_locked} with "45"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 45 on this Card."
						set slot 28 of {_gui} to {_slot} with lore {_locked}
						set slot 30 of {_gui} to {_slot} with lore {_locked}
						set slot 32 of {_gui} to {_slot} with lore {_locked}
					#50
					if int tag "Level" of custom nbt of {karta::%player%} >= 50:
						set slot 37 of {_gui} to blue dye named "<##7cafbf>Tidebringer"  with lore "             %{_50}%%nl%             %{_div}%%nl%&7Healing Stream may be used on an%nl%&7enemy to &finflict damage &7equal to that%nl%&7which would be &fhealed &7to an ally." with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
						set slot 39 of {_gui} to light blue dye named "<##7cafbf>Turn of the Tide" with lore "             %{_50}%%nl%             %{_div}%%nl%&7Reversal wraps all affected allies in%nl%&7an Explosive Bubble and grants them%nl%<##ffef45> 90 Resistance &7for the duration." with nbt from "{""minecraft:custom_model_data"":{floats:[10.0f]}}"
						set slot 41 of {_gui} to iron nugget named "<##7cafbf>Hydrodance" with lore "               %{_50}%%nl%              %{_div}%%nl%&7Overhealing heals the nearest ally%nl%&7by &f30%% &7of the overheal value. If no%nl%&7eligible allies are nearby, overhealing%nl%&7will instead &fdamage &7a nearby enemy%nl%&7by &f20%% &7of the value." with nbt from "{""minecraft:custom_model_data"":{floats:[14.0f]}}"
					else:
						replace all "45" in {_locked} with "50"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 50 on this Card."
						set slot 37 of {_gui} to {_slot} with lore {_locked}
						set slot 39 of {_gui} to {_slot} with lore {_locked}
						set slot 41 of {_gui} to {_slot} with lore {_locked}
				else if {_card} = "Cresselia":
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to pink dye named "<##6a5e9e>Solstice" with lore "%{_15}%%nl%&7During the first &f6 sec &7of &f <##6a5e9e>Celestial Alignment&7,%nl%&f <##6a5e9e>Shooting Stars &7fall &f200%% &7more often." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 3 of {_gui} to white dye named "<##6a5e9e>Umbral Inspiration" with lore "%{_15}%%nl%&7Consuming &f <##cab8e3>Astral Invocation &7increases the%nl%&7damage of your &f <##6a5e9e>Starsurge &7or &f <##6a5e9e>Starfall &7by%nl%&f30%% &7for &f6 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 5 of {_gui} to light blue dye named "<##6a5e9e>Astronomical Impact" with lore "%{_15}%%nl%&7When &f <##6a5e9e>Celestial Alignment &7ends or when%nl%&7you enter combat, reduce the cast time%nl%&7and increase the damage of your next%nl%&f3  <##6a5e9e>Starfires &7by &f60%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}	
					#30
					if int tag "Level" of custom nbt of {karta::%player%} >= 30:
						set {_crashingStar} to (1.8 + (({damage::%player%}/41) + ({versatility::%player%}/123) + {primarystat::%player%}/20.5)) * (1 + (({mastery::%player%}/2.7)/100))
						set slot 10 of {_gui} to pink dye named "<##6a5e9e>Crashing Star" with lore "%{_30}%%nl%&f <##6a5e9e>Shooting Stars &7have a &f15%% &7chance to instead call%nl%&7down a &f <##6a5e9e>Crashing Star&7, causing &f%{_crashingStar}% <##a99afc>Astral &7damage%nl%&7to the target and generating &fdouble  <##6a5e9e>Astral Power&7.%nl% %nl%&f <##6a5e9e>Crashing Stars &7have &fdouble &7the chance of granting%nl%&7you &f <##cab8e3>Astral Invocation&7." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 12 of {_gui} to purple dye named "<##6a5e9e>Stellar Drift" with lore "%{_30}%%nl%&f <##6a5e9e>Starfall's &7damage is increased by &f30%%&7.%nl%&7Additionally, your &f Movement Speed &7while%nl%&f <##6a5e9e>Starfall &7is active is increased &7by &f20%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"	
						set slot 14 of {_gui} to light blue dye named "<##6a5e9e>Astral Communion" with lore "%{_30}%%nl%&7Increases maximum &f <##6a5e9e>Astral Power &7by &f20&7.%nl%&7Entering &f <##6a5e9e>Celestial Alignment &7reduces the%nl%&f <##6a5e9e>Astral Power &7cost of your spells by &f10&7." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						replace all "15" in {_locked} with "30"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 30 on this Card."
						set slot 10 of {_gui} to {_slot} with lore {_locked}
						set slot 12 of {_gui} to {_slot} with lore {_locked}
						set slot 14 of {_gui} to {_slot} with lore {_locked}
					#40
					if int tag "Level" of custom nbt of {karta::%player%} >= 40:
						set slot 19 of {_gui} to pink dye named "<##6a5e9e>Whirling Stars" with lore "%{_40}%%nl%&f <##6a5e9e>Shooting Stars &7now generate &f3  <##6a5e9e>Astral Power&7.%nl%&7Additionally, &f <##6a5e9e>Shooting Stars &7deal &f9%% &7more%nl%&7damage." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 21 of {_gui} to purple dye named "<##6a5e9e>Starweaver" with lore "%{_40}%%nl%&f <##6a5e9e>Starsurge &7has a &f20%% &7chance to make%nl%&f <##6a5e9e>Starfall &7free. &f <##6a5e9e>Starfall &7has a &f40%%%nl%&7chance to make &f <##6a5e9e>Starsurge &7free." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 23 of {_gui} to light blue dye named "<##6a5e9e>Aetherial Kindling" with lore "%{_40}%%nl%&f <##6a5e9e>Celestial Alignment &7increases &f <##6a5e9e>Starfire's%nl%&7damage by &f15%% &7and the damage it deals%nl%&7to nearby enemies by an additional &f30%%&7.%nl% %nl%&7Casting &f <##6a5e9e>Starsurge &7or &f <##6a5e9e>Starfall &7extends%nl%&7the duration of &f <##6a5e9e>Celestial Alignment &7by%nl%&f3 sec&7, up to &f15 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						replace all "30" in {_locked} with "40"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 40 on this Card."
						set slot 19 of {_gui} to {_slot} with lore {_locked}
						set slot 21 of {_gui} to {_slot} with lore {_locked}
						set slot 23 of {_gui} to {_slot} with lore {_locked}
					#45
					if int tag "Level" of custom nbt of {karta::%player%} >= 45:
						set slot 28 of {_gui} to pink dye named "<##6a5e9e>Stellar Collision" with lore "%{_45}%%nl%&f <##6a5e9e>Shooting Stars &7have a &f20%% &7chance to deal%nl%&7damage and &fgenerate resources &7as if they%nl%&7struck the target &ftwice&7. Additionally, the damage%nl%&7of &f <##6a5e9e>Shooting Stars &7is increased by &f15%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 30 of {_gui} to purple dye named "<##6a5e9e>Hail of Stars" with lore "%{_45}%%nl%&7Increases the duration of &f <##6a5e9e>Starfall &7by &f3 sec&7.%nl%&7Additionally, increases the <##19943e> Haste &7scaling%nl%&7of &f <##6a5e9e>Starfall by &f10%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 32 of {_gui} to blue dye named "<##6a5e9e>Innervate"  with lore "%{_45}%%nl%&7Unlocks a new &fUltimate Ability&7:%nl% %nl%&f <##6a5e9e>Innervate%nl%&8Ultimate Ability%nl%&fInstant cast%nl%&7Cooldown: &8 &f3 minutes%nl%&7Use: &fRMB%nl%<##6a5e9e>Infuse a <##b9aeeb>friendly target <##6a5e9e>with energy, reducing%nl%<##6a5e9e>the cooldown of their <##b9aeeb>last used spell <##6a5e9e>by &f40 sec<##6a5e9e>.%nl%<##6a5e9e>If no nearby allies are present, reduce the%nl%<##b9aeeb>cooldown <##6a5e9e>of &f <##b9aeeb>Celestial Alignment <##6a5e9e>by &f30 sec<##6a5e9e>.%nl% %nl%<##6a5e9e>Generates &f100  <##b9aeeb>Astral Power<##6a5e9e>." with nbt from "{""minecraft:custom_model_data"":{floats:[6.0f]}}"
					else:
						replace all "40" in {_locked} with "45"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 45 on this Card."
						set slot 28 of {_gui} to {_slot} with lore {_locked}
						set slot 30 of {_gui} to {_slot} with lore {_locked}
						set slot 32 of {_gui} to {_slot} with lore {_locked}
					#50
					if int tag "Level" of custom nbt of {karta::%player%} >= 50:
						set {_damageFullMoon} to (13 + (({damage::%player%}/6.5) + ({versatility::%player%}/19.5) + {primarystat::%player%}/3.25)) * (1 + (({mastery::%player%}/2.7)/100))
						set slot 37 of {_gui} to pink dye named "<##6a5e9e>Orbit Breaker" with lore "%{_50}%%nl%&7Every &f30th  <##6a5e9e>Shooting Star &7calls down%nl%&7a &f <##6a5e9e>Full Moon &7upon its target.%nl% %nl%&f <##6a5e9e>Full Moon%nl%&7Deals &f%{_damageFullMoon}% <##a99afc>Astral &7damage &7to the target and%nl%&f%{_damageFullMoon}*0.4% <##a99afc>Astral &7damage to all enemies around%nl%&7and generates &f40  <##6a5e9e>Astral Power&7." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 39 of {_gui} to light blue dye named "<##6a5e9e>Touch the Cosmos" with lore "%{_50}%%nl%&7Entering &f <##6a5e9e>Celestial Alignment &7casts a%nl%&7free &f <##6a5e9e>Starfall &7at &f400%% &7effectiveness." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
						set slot 41 of {_gui} to magenta dye named "<##6a5e9e>Primordial Arcanic Pulsar" with lore "%{_50}%%nl%&7Every &f400  <##6a5e9e>Astral Power &7spent grants%nl%&f <##6a5e9e>Celestial Alignment &7for &f9 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
					else:
						replace all "45" in {_locked} with "50"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 50 on this Card."
						set slot 37 of {_gui} to {_slot} with lore {_locked}
						set slot 39 of {_gui} to {_slot} with lore {_locked}
						set slot 41 of {_gui} to {_slot} with lore {_locked}
				else if {_card} = "Buckshot":
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to arrow named "<##866da4>Quickshot" with lore "              %{_15}%%nl%               %{_div}%%nl%&7Single Shot arrows travel &f30%% &7faster." with nbt from "{""minecraft:custom_model_data"":{floats:[2.0f]}}"
						set slot 3 of {_gui} to purple dye named "<##866da4>Enhanced Portals" with lore "                 %{_15}%%nl%                 %{_div}%%nl%&7Magic Portals last &f5 sec &7longer." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
						set slot 5 of {_gui} to magenta dye named "<##866da4>Spreading Shots" with lore "                 %{_15}%%nl%                 %{_div}%%nl%&7Spread Shot fires an &fadditional shot&7." with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}" 
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}	
					#30
					if int tag "Level" of custom nbt of {karta::%player%} >= 30:
						set {_crashingStar} to (1.8 + (({damage::%player%}/41) + ({versatility::%player%}/123) + {primarystat::%player%}/20.5)) * (1 + (({mastery::%player%}/3.2)/100))
						set slot 10 of {_gui} to purple dye named "<##866da4>Masterful Portals" with lore "                 %{_30}%%nl%                 %{_div}%%nl%&7Magic Portals last%nl%&f5 sec &7longer." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
						set slot 12 of {_gui} to purple dye named "<##866da4>Targeted Portals" with lore "                 %{_30}%%nl%                 %{_div}%%nl%&7Magic Portals will always face towards%nl%&7the closest enemy when placed." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
						set slot 14 of {_gui} to purple dye named "<##866da4>Twin Portals" with lore "                 %{_30}%%nl%                 %{_div}%%nl%&7Magic Portals now has &f2 charges&7.%nl%&7Magic Portals last &f2 sec &7longer." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						replace all "15" in {_locked} with "30"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 30 on this Card."
						set slot 10 of {_gui} to {_slot} with lore {_locked}
						set slot 12 of {_gui} to {_slot} with lore {_locked}
						set slot 14 of {_gui} to {_slot} with lore {_locked}
					#40
					if int tag "Level" of custom nbt of {karta::%player%} >= 40:
						set slot 19 of {_gui} to pink dye named "<##6a5e9e>Whirling Stars" with lore "                  %{_40}%%nl%                  %{_div}%%nl%&7Shooting Stars now generate &f3 Astral Power&7.%nl%&7Additionally, Shooting Stars deal &f9%% &7more%nl%&7damage." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 21 of {_gui} to purple dye named "<##6a5e9e>Starweaver" with lore "                %{_40}%%nl%                %{_div}%%nl%&7Starsurge has a &f20%% &7chance to make%nl%&7Starfall free. Starfall has a &f40%% &7chance%nl%&7to make Starsurge free." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 23 of {_gui} to light blue dye named "<##6a5e9e>Aetherial Kindling" with lore "               %{_40}%%nl%                %{_div}%%nl%&7Celestial Alignment increases Starfire's%nl%&7damage by &f15%% &7and the damage it deals%nl%&7to nearby enemies by an additional &f30%%&7.%nl% %nl%&7Casting Starsurge and Starfall extends%nl%&7the duration of Celestial Alignment by%nl%&f3 sec&7, up to &f27 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						replace all "30" in {_locked} with "40"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 40 on this Card."
						set slot 19 of {_gui} to {_slot} with lore {_locked}
						set slot 21 of {_gui} to {_slot} with lore {_locked}
						set slot 23 of {_gui} to {_slot} with lore {_locked}
					#45
					if int tag "Level" of custom nbt of {karta::%player%} >= 45:
						set slot 28 of {_gui} to pink dye named "<##6a5e9e>Stellar Collision" with lore "                    %{_45}%%nl%                    %{_div}%%nl%&7Shooting Stars have a &f20%% &7chance to deal%nl%&7damage and generate resources as if they%nl%&7struck the target twice. Additionally, the damage%nl%&7of Shooting Stars is increased by &f15%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 30 of {_gui} to purple dye named "<##6a5e9e>Hail of Stars" with lore "                  %{_45}%%nl%                   %{_div}%%nl%&7Increases the duration of Starfall by &f3 sec&7.%nl%&7Additionally, increases the <##19943e> Haste &7scaling%nl%&7of Starfall by &f10%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 32 of {_gui} to magenta dye named "<##866da4>Spreading Shots" with lore "                 %{_15}%%nl%                 %{_div}%%nl%&7Spread Shot has a &f20%% &7chance%nl%&7to fire &f2 &7additional shots and%nl%&7deal &f15%% &7increased damage." with nbt from "{""minecraft:custom_model_data"":{floats:[5.0f]}}" 
					else:
						replace all "40" in {_locked} with "45"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 45 on this Card."
						set slot 28 of {_gui} to {_slot} with lore {_locked}
						set slot 30 of {_gui} to {_slot} with lore {_locked}
						set slot 32 of {_gui} to {_slot} with lore {_locked}
					#50
					if int tag "Level" of custom nbt of {karta::%player%} >= 50:
						set {_damageFullMoon} to (13 + (({damage::%player%}/6.5) + ({versatility::%player%}/19.5) + {primarystat::%player%}/3.25))
						set slot 37 of {_gui} to pink dye named "<##6a5e9e>Orbit Breaker" with lore "               %{_50}%%nl%               %{_div}%%nl%&7Every &f30th &7Shooting Star calls down%nl%&7a <##6a5e9e>Full Moon &7upon its target.%nl% %nl%<##6a5e9e>Full Moon%nl%&7Deals &f%{_damageFullMoon}% <##a99afc>Astral &7damage &7to the target and%nl%&f%{_damageFullMoon}*0.4% <##a99afc>Astral &7damage to all enemies around%nl%&7and generates &f40 Astral Power&7." with nbt from "{""minecraft:custom_model_data"":{floats:[7.0f]}}"
						set slot 39 of {_gui} to blue dye named "<##6a5e9e>Innervate"  with lore "                     %{_50}%%nl%                    %{_div}%%nl%&7Unlocks a new ability: <##6a5e9e>Innervate&7.%nl% %nl%<##6a5e9e>Innervate%nl%&fInstant cast%nl%&7Cooldown: &f3 minutes%nl%&7Use: &fRMB%nl%<##6a5e9e>Infuse a friendly target with energy, reducing%nl%<##6a5e9e>the cooldown of their last used spell by &f40 sec<##6a5e9e>.%nl%<##6a5e9e>If no nearby allies are present, reduce the%nl%<##6a5e9e>cooldown of <##b9aeeb>Celestial Alignment <##6a5e9e>by &f20 sec<##6a5e9e>.%nl% %nl%<##6a5e9e>Generates &f100 <##b9aeeb>Astral Power<##6a5e9e>." with nbt from "{""minecraft:custom_model_data"":{floats:[6.0f]}}"
						set slot 41 of {_gui} to magenta dye named "<##6a5e9e>Primordial Arcanic Pulsar" with lore "              %{_50}%%nl%              %{_div}%%nl%&7Every &f400 Astral Power &7spent grants%nl%&7Celestial Alignment for &f9 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
					else:
						replace all "45" in {_locked} with "50"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 50 on this Card."
						set slot 37 of {_gui} to {_slot} with lore {_locked}
						set slot 39 of {_gui} to {_slot} with lore {_locked}
						set slot 41 of {_gui} to {_slot} with lore {_locked}
				else if {_card} = "Espeon":
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to pink dye named "<##d48bc3>Manipulation" with lore "%{_15}%%nl%&7Damage dealt by &f <##d48bc3>Future Sight &7is%nl%&7increased by &f2.5%% &7per active &fstack%nl%&7on the target at the time of detonation." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 3 of {_gui} to purple dye named "<##d48bc3>Clear Mind" with lore "%{_15}%%nl%&7Espeon can hold on to &f15 &7additional%nl%&f <##d48bc3>Future Sight &fstacks &7before losing%nl%&7control through &f <##d48bc3>Mind Transfer&7.%nl% %nl%&f <##d48bc3>Mastery: Mental Agility &7grants an%nl%&7additional &f0.5 <##59c1e3> Intellect &7for each%nl%&7active &f <##d48bc3>Future Sight &7on the map." with nbt from "{""minecraft:custom_model_data"":{floats:[11.0f]}}" 
						set slot 5 of {_gui} to gold nugget named "<##d48bc3>Atticus's Teachings" with lore "%{_15}%%nl%&7Reduces the base &ffall duration%nl%&7of &f <##d48bc3>Future Sight &7by &f10%%&7.%nl% %nl%&7Reduces the base &fcast time &7of%nl%&f <##d48bc3>Mind Transfer &7by &f20%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}	
					#30
					if int tag "Level" of custom nbt of {karta::%player%} >= 30:
						set {_crashingStar} to (1.8 + (({damage::%player%}/41) + ({versatility::%player%}/123) + {primarystat::%player%}/20.5)) * (1 + (({mastery::%player%}/3.2)/100))
						set slot 10 of {_gui} to pink dye named "<##d48bc3>Augury" with lore "%{_30}%%nl%&7Casting &f <##d48bc3>Future Sight &7on a target%nl%&7now always applies &f2 stacks&7." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 12 of {_gui} to purple dye named "<##d48bc3>Wit" with lore "%{_30}%%nl%&7Espeon gains &f2.5 <##f53b98> Mastery &7for each%nl%&7active &f <##d48bc3>Future Sight &7on the field." with nbt from "{""minecraft:custom_model_data"":{floats:[11.0f]}}"
						set slot 14 of {_gui} to purple dye named "<##866da4>Twin Portals" with lore "                 %{_30}%%nl%                 %{_div}%%nl%&7sdada" with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						replace all "15" in {_locked} with "30"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 30 on this Card."
						set slot 10 of {_gui} to {_slot} with lore {_locked}
						set slot 12 of {_gui} to {_slot} with lore {_locked}
						set slot 14 of {_gui} to {_slot} with lore {_locked}
					#40
					if int tag "Level" of custom nbt of {karta::%player%} >= 40:
						set slot 19 of {_gui} to ender pearl named "<##d48bc3>Mindgames" with lore "%{_40}%%nl%&f <##d48bc3>Psy Wave &7will now additionally &finterrupt%nl%&7the spell casts of all enemies affected%nl%&7by &f <##d48bc3>Future Sight&7." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 21 of {_gui} to purple dye named "<##d48bc3>Evasion" with lore "%{_40}%%nl%&f <##d48bc3>Mastery: Mental Agility &7now also%nl%&7grants &f1 <##2154ad> Avoidance &7per active%nl%&f <##d48bc3>Future Sight &7on the map." with nbt from "{""minecraft:custom_model_data"":{floats:[11.0f]}}" 
						set slot 23 of {_gui} to light blue dye named "<##6a5e9e>Aetherial Kindling" with lore "               %{_40}%%nl%                %{_div}%%nl%&7When Espeon transfers &f <##d48bc3>Future Sight &fstacks%nl%&7to themself through &f <##d48bc3>Mind Transfer&7, they gain%nl%&7a &f Shield &7equal to &f0.6 HP &7per &fstack &7collected%nl%&7for the &ffall duration &7of the spell.%nl% %nl%&7The &f Shield &7expires early if &f <##d48bc3>Future Sight%nl%&fstacks &7are relocated to another target." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						replace all "30" in {_locked} with "40"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 40 on this Card."
						set slot 19 of {_gui} to {_slot} with lore {_locked}
						set slot 21 of {_gui} to {_slot} with lore {_locked}
						set slot 23 of {_gui} to {_slot} with lore {_locked}
					#45
					if int tag "Level" of custom nbt of {karta::%player%} >= 45:
						set slot 28 of {_gui} to pink dye named "<##d48bc3>Intellectuality" with lore "%{_45}%%nl%&7&f <##d48bc3>Future Sight &7no longer has a &fcast time&7.%nl%&7Additionally, increase the damage of the%nl%&7spell by &f5%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 30 of {_gui} to purple dye named "<##d48bc3>Mind Over Matter" with lore "%{_45}%%nl%&7Gain &f40 <##f53b98> Mastery&7.%nl% %nl%&f <##d48bc3>Mastery: Mental Agility &7will now also%nl%&7<##fca417> Critical Hit&7, <##d5ff57> Element &7and <##58c3f5> Crowd%nl%<##58c3f5>Control &7by &f1 &7per stack." with nbt from "{""minecraft:custom_model_data"":{floats:[11.0f]}}"
						set slot 32 of {_gui} to magenta dye named "<##d48bc3>???" with lore "%{_45}%%nl%&7???." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
					else:
						replace all "40" in {_locked} with "45"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 45 on this Card."
						set slot 28 of {_gui} to {_slot} with lore {_locked}
						set slot 30 of {_gui} to {_slot} with lore {_locked}
						set slot 32 of {_gui} to {_slot} with lore {_locked}
					#50
					if int tag "Level" of custom nbt of {karta::%player%} >= 50:
						set {_damageFullMoon} to (13 + (({damage::%player%}/6.5) + ({versatility::%player%}/19.5) + {primarystat::%player%}/3.25))
						set slot 37 of {_gui} to pink dye named "<##d48bc3>???" with lore "%{_45}%%nl%&7Damage done by &f <##d48bc3>Future Sight &7will%nl%&7now also &fdamage &7all nearby enemies%nl%&7by &f5%% &7of the value.%nl% %nl%&f <##d48bc3>Mind Transfer &7has a &f20%% &7chance%nl%&7to apply an additional &fstack of%nl%&f <##d48bc3>Future Sight &7to its target." with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"
						set slot 39 of {_gui} to purple dye named "<##d48bc3>Mastermind" with lore "%{_50}%%nl%&7Espeon gains &f12%% &7increased effect%nl%&7from all &fsecondary stats&7." with nbt from "{""minecraft:custom_model_data"":{floats:[11.0f]}}"
						set slot 41 of {_gui} to glass bottle named "<##d48bc3>Time Anomaly" with lore "%{_50}%%nl%&7At any point in time, you have%nl%&7a &fchance &7to gain &f <##d48bc3>Time Warp%nl%&7for &f6 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[6.0f]}}"
					else:
						replace all "45" in {_locked} with "50"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 50 on this Card."
						set slot 37 of {_gui} to {_slot} with lore {_locked}
						set slot 39 of {_gui} to {_slot} with lore {_locked}
						set slot 41 of {_gui} to {_slot} with lore {_locked}
				else if {_card} = "Shaymin":
					#15
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						set slot 1 of {_gui} to slime ball named "<##dbef9e>x" with lore "%{_15}%%nl%&fx <##dbef9e>Seed Barrage &7causes the target to%nl%&7receive &f6%% &7increased <##607c3c>Nature &7damage%nl%&7or &f4%% &7increased healing for &f3 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 3 of {_gui} to sugar named "<##dbef9e>y" with lore "%{_15}%%nl%&7Casting &fAir Slash &7in Sky Forme or Seed Flare%nl%&7in Land Forme &7extends the duration of%nl%&7Serene Grace by &f1.0 sec&7, up to &f15 sec&7." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}" 
						set slot 5 of {_gui} to white dye named "<##dbef9e>z" with lore "%{_15}%%nl%&7Reduces the base &ffall duration%nl%&7of &f <##d48bc3>Future Sight &7by &f10%%&7.%nl% %nl%&7Reduces the base &fcast time &7of%nl%&f <##d48bc3>Mind Transfer &7by &f20%%&7." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
					else:
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 15 on this Card."
						set slot 1 of {_gui} to {_slot} with lore {_locked}
						set slot 3 of {_gui} to {_slot} with lore {_locked}
						set slot 5 of {_gui} to {_slot} with lore {_locked}
					#30
					if int tag "Level" of custom nbt of {karta::%player%} >= 30:
						set {_crashingStar} to (1.8 + (({damage::%player%}/41) + ({versatility::%player%}/123) + {primarystat::%player%}/20.5)) * (1 + (({mastery::%player%}/3.2)/100))
						set slot 10 of {_gui} to purple dye named "<##d48bc3>Wit" with lore "%{_30}%%nl%&7Espeon gains &f2.5 <##f53b98> Mastery &7for each%nl%&7active &f <##d48bc3>Future Sight &7on the field." with nbt from "{""minecraft:custom_model_data"":{floats:[11.0f]}}"
						set slot 12 of {_gui} to sugar named "<##dbef9e>x" with lore "%{_30}%%nl%&7Casting &fAir Slash &7in Sky Forme now%nl%&7has a &f20%% chance to emit a Seed Flare%nl%&7at &f90%% &7effectiveness from the target." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						set slot 14 of {_gui} to purple dye named "<##866da4>Twin Portals" with lore "                 %{_30}%%nl%                 %{_div}%%nl%&7sdada" with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						replace all "15" in {_locked} with "30"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 30 on this Card."
						set slot 10 of {_gui} to {_slot} with lore {_locked}
						set slot 12 of {_gui} to {_slot} with lore {_locked}
						set slot 14 of {_gui} to {_slot} with lore {_locked}
					#40
					if int tag "Level" of custom nbt of {karta::%player%} >= 40:
						set slot 19 of {_gui} to white dye named "<##dbef9e>x" with lore "%{_40}%%nl%&7After using Air Ball, grant 2 stacks of BUFF.%nl%&7BUFF causes your next air slash to not incur%nl%&7a cooldown." with nbt from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
						set slot 21 of {_gui} to slime ball named "<##dbef9e>y" with lore "%{_40}%%nl%&7After changing forme, increase your%nl%&7chance to trigger Seed Barrage by &f600%% &7for%nl%&f4 sec." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}" 
						set slot 23 of {_gui} to light blue dye named "<##6a5e9e>Aetherial Kindling" with lore "               %{_40}%%nl%                %{_div}%%nl%&7When Espeon transfers &f <##d48bc3>Future Sight &fstacks%nl%&7to themself through &f <##d48bc3>Mind Transfer&7, they gain%nl%&7a &f Shield &7equal to &f0.6 HP &7per &fstack &7collected%nl%&7for the &ffall duration &7of the spell.%nl% %nl%&7The &f Shield &7expires early if &f <##d48bc3>Future Sight%nl%&fstacks &7are relocated to another target." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
					else:
						replace all "30" in {_locked} with "40"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 40 on this Card."
						set slot 19 of {_gui} to {_slot} with lore {_locked}
						set slot 21 of {_gui} to {_slot} with lore {_locked}
						set slot 23 of {_gui} to {_slot} with lore {_locked}
					#50
					if int tag "Level" of custom nbt of {karta::%player%} >= 50:
						set {_damageFullMoon} to (13 + (({damage::%player%}/6.5) + ({versatility::%player%}/19.5) + {primarystat::%player%}/3.25))
						set slot 37 of {_gui} to lime dye named "<##dbef9e>?" with lore "%{_45}%%nl%&7Your abilities now deal <##daf2bb>Windswept &7damage.%nl% %nl%&8Windswept damage consists of both <##607c3c>Nature%nl%&8and &fAir &8damage. Effects that strengthen%nl%&8either element also apply to <##daf2bb>Windswept &8damage." with nbt from "{""minecraft:custom_model_data"":{floats:[8.0f]}}"
						set slot 39 of {_gui} to lime dye named "&fx" with lore "&7once per forme swap to land forme, you are%nl%&7allowed to cast leaf blast, works like sky blast but does%nl%&7not knock up, heals allies instead."
					else:
						replace all "45" in {_locked} with "50"
						set {_locked} to "&7This row will unlock once you've%nl%&7reached Level 50 on this Card."
						set slot 37 of {_gui} to {_slot} with lore {_locked}
						set slot 39 of {_gui} to {_slot} with lore {_locked}
						set slot 41 of {_gui} to {_slot} with lore {_locked}
				if int tag "Level" of custom nbt of {karta::%player%} >= 15:	
					if inventory action is not shift move:
						if {_row1} is set:
							loop slots integers between 1 and 5 of {_gui}:
								if loop-value is not air:
									if {_row1} is not (uncolored name of loop-value):
										set loop-value to {_selected}
						if {_row2} is set:
							loop slots integers between 10 and 14 of {_gui}:
								if loop-value is not air:
									if {_row2} is not (uncolored name of loop-value):
										set loop-value to {_selected}
						if {_row3} is set:
							loop slots integers between 19 and 23 of {_gui}:
								if loop-value is not air:
									if {_row3} is not (uncolored name of loop-value):
										set loop-value to {_selected}
						if {_row4} is set:
							loop slots integers between 28 and 32 of {_gui}:
								if loop-value is not air:
									if {_row4} is not (uncolored name of loop-value):
										set loop-value to {_selected}
						if {_row5} is set:
							loop slots integers between 37 and 41 of {_gui}:
								if loop-value is not air:
									if {_row5} is not (uncolored name of loop-value):
										set loop-value to {_selected}

				open {_gui} to player
				save yaml "karty-%player%"
				unload yaml "karty-%player%"

	else if event-inventory = (metadata tag "talentguispec" of player):
		cancel event
		if clicked slot is not air:
			if event-slot is between 0 and 44:
				if player does not have event-slot:
					if clicked slot is not a white stained glass pane:
						if inventory action is not shift move: 
							set {_id} to uncolored line 19 of lore of {karta::%player%}
							replace all "Id: " in {_id} with ""
							load yaml "plugins/Skript/playerdata/karty/%uncolored name of {karta::%player%}%/%{_id}%.yml" as "karty-%player%"

							loop 5 times:
								set {_row%loop-number%} to string tag "Talents;Row %loop-number%" of custom nbt of {karta::%player%}
								
							if event-slot is between 1 and 5:
								if line 1 of lore of event-slot contains "Level 15 Talent":
									if {_row1} is not set:
										set yaml value "Card.Talents.Row 1" in "karty-%player%" to uncolored name of clicked slot
										set {_row} to 1
										set {_talentLevel} to "&eLevel 15 Talent"
										set string tag "Talents;Row 1" of custom nbt of player's tool to uncolored name of clicked slot
							else if event-slot is between 10 and 14:
								if line 1 of lore of event-slot contains "Level 30 Talent":
									if {_row2} is not set:
										set yaml value "Card.Talents.Row 2" in "karty-%player%" to uncolored name of clicked slot
										set {_row} to 2
										set {_talentLevel} to "&eLevel 30 Talent"
										set string tag "Talents;Row 2" of custom nbt of player's tool to uncolored name of clicked slot
							else if event-slot is between 19 and 23:
								if line 1 of lore of event-slot contains "Level 40 Talent":
									if {_row3} is not set:
										set yaml value "Card.Talents.Row 3" in "karty-%player%" to uncolored name of clicked slot
										set {_row} to 3
										set {_talentLevel} to "&eLevel 40 Talent"
										set string tag "Talents;Row 3" of custom nbt of player's tool to uncolored name of clicked slot
							else if event-slot is between 28 and 32:
								if line 1 of lore of event-slot contains "Level 45 Talent":
									if {_row4} is not set:
										set yaml value "Card.Talents.Row 4" in "karty-%player%" to uncolored name of clicked slot
										set {_row} to 4
										set {_talentLevel} to "&eLevel 45 Talent"
										set string tag "Talents;Row 4" of custom nbt of player's tool to uncolored name of clicked slot
							else if event-slot is between 37 and 41:
								if line 1 of lore of event-slot contains "Level 50 Talent":
									if {_row5} is not set:
										set yaml value "Card.Talents.Row 5" in "karty-%player%" to uncolored name of clicked slot
										set {_row} to 5
										set {_talentLevel} to "&eLevel 50 Talent"
										set string tag "Talents;Row 5" of custom nbt of player's tool to uncolored name of clicked slot

							if {_row} is set:
								set {_colorText} to yaml value "Card.Colour" in "karty-%player%"
								set {_color} to formatted "<%{_colorText} in lowercase%>"
								set {_lore::*} to lore of clicked slot
								set {_lore::1} to {_talentLevel}
								set {_tooltip} to join ({_lore::*}) by nl
								play sound "entity.player.levelup" with volume 3 and pitch 0 at player
								if {language::%player%} = "English":
									send formatted "%{_color}%Successfully learned the <tooltip:%{_tooltip}%>&n%uncolored name of clicked slot%<tooltip:>%{_color}% Talent from row %{_row}%!" to player
								else:
									send formatted "%{_color}%Pomyślnie nauczono się Talentu <tooltip:%{_tooltip}%>&n%uncolored name of clicked slot%<tooltip:>%{_color}% z rzędu %{_row}%!" to player
								teleport the player to player's location
								#Individual card default values
								if {kartaname::%player%} = "Vaporeon":
									if {_row} = 1:
										if uncolored name of clicked slot = "Undulation":
											set metadata value "HealingStreamCharges" of player to 3
										else:
											set metadata value "HealingStreamCharges" of player to 2
										set {_charges} to metadata value "HealingStreamCharges" of player
										loop all items in the inventory of player:
											if boolean tag "Healing Stream" of custom nbt of (1 of loop-item) is set:
												if {_charges} > 0:
													set item amount of loop-item to {_charges}
													if {_charges} = 1:
														set line 2 of lore of loop-item to "&f%{_charges}% Charge"
													else:
														set line 2 of lore of loop-item to "&f%{_charges}% Charges"
							else:
								play sound "block.glass.break" with volume 3 and pitch 0 at player
								if {language::%player%} = "English":
									send "&cYou already have learned a Talent from this row." to player
								else:
									send "&cJuż nauczono się Talentu z tego rzędu." to player
							
							set {karta::%player%} to player's tool
							save yaml "karty-%player%"
							unload yaml "karty-%player%"
