function CardCombatYamlAdd(p: player, yamlNode: text, amount: number):
	if {_amount} <= 0:
		stop
	if yaml "activeCard-%{_p}%" is loaded:
		set {_current} to yaml value "%{_yamlNode}%" in "activeCard-%{_p}%"
		if {_current} is not set:
			set {_current} to 0
		add {_amount} to {_current}
		set yaml value "%{_yamlNode}%" in "activeCard-%{_p}%" to {_current}
		save yaml "activeCard-%{_p}%"



on heal:
	if event-entity is player:
		add heal amount to {healtakentotal::%player%}
		if heal reason is unknown:
			set {_id} to line 19 of lore of {karta::%player%}
			if {_id} is set:
				add heal amount to {healtakencard::%{_id}%}

on death:
	if boolean tag "ECMob" of (custom nbt of victim) is set:
		onECMobDeath(victim)
		clear metadata value "ECPulled" of victim
		clear drops

		if {kartaname::%attacker%} = "Umbreon":
			set {_baseDuration} to 5
			if string tag "Talents;Row 2" of custom nbt of {karta::%attacker%} = "Chosen of the Night":
				set {_baseDuration} to {_baseDuration}*1.2

			set {_invisibilityDuration} to "%{_baseDuration}% seconds" parsed as timespan

			apply invisibility 1 without particles to attacker for {_invisibilityDuration}

			clear metadata value "From the Shadows%attacker%" of victim

		if string tag "ECTextAbove" of (custom nbt of victim) is set:
			delete (string tag "ECTextAbove" of (custom nbt of victim) parsed as entity)
			if (string tag "ECTextAboveLevel" of (custom nbt of victim)) is set:
				delete (string tag "ECTextAboveLevel" of (custom nbt of victim) parsed as entity)
		if (string tag "ECCustomName" of (custom nbt of victim) is set):
			delete (string tag "ECCustomName" of (custom nbt of victim) parsed as entity)

	if uuid tag "ECEntityTitle" of (custom nbt of victim) is set:
		set {_entityTitle} to (uuid tag "ECEntityTitle" of (custom nbt of victim)) parsed as entity
		kill {_entityTitle}

	if boolean tag "ECWorldQuestMob" of (custom nbt of victim) is set:
		set {_respawnLoc} to metadata value "ECSpawnLocation" of victim
		WorldQuestRespawnMob(victim, {_respawnLoc})
		if attacker is a player:
			set {_worldQuest} to string tag "WorldQuest" of (custom nbt of victim)
			if yaml list "Completed World Quests" in "WorldQuests%attacker%" does not contain {_worldQuest}:
				WorldQuestMobDefeat(attacker, victim)

			remove uuid of attacker from {asyst::%uuid of victim%::*}
			if size of {asyst::%uuid of victim%::*} > 0:
				loop {asyst::%uuid of victim%::*}:
					set {_player} to loop-value parsed as player
					if yaml list "Completed World Quests" in "WorldQuests%{_player}%" does not contain {_worldQuest}:
						WorldQuestMobDefeat({_player}, victim)

			if string list tag "ECSummons" of (custom nbt of victim) is set:
				set {_summonUuids::*} to string list tag "ECSummons" of (custom nbt of victim)
				loop {_summonUuids::*}:
					set {_summon} to loop-value parsed as entity
					kill {_summon}

	#///Animation section
	if string tag "ECModelName" of (custom nbt of victim) is set:
		setAIState(victim, "death")
		playEntitySound(victim, "Death")

	if victim is not a player:
		if boolean tag "ECExpAreaMayanMob" of (custom nbt of victim) is set:
			if attacker is a player:
				#if {winterDelightPassLEVEL::%attacker%} >= 0:
				#	getMission(attacker, "Sleighing the Mobs", "Pokonywanie Potworów", 1)
				set {_id} to string tag "Id" of custom nbt of {karta::%attacker%}
				set {_cardLevel} to yaml value "Card.Level" in "activeCard-%attacker%"
				set {_maxLevel} to {maxCardLevel}
				set {_xp} to 0.4/1.171 ^ ((({_cardLevel}/{_maxLevel}))+sqrt({_cardLevel}*10)) * sqrt({maxCardLevel} / {baseMaxCardLevel})
				if boolean tag "ECSuperMob" of (custom nbt of victim) is set:
					set {_xp} to {_xp}*2.5
				if boolean tag "ECBoss" of (custom nbt of victim) is set:
					set {_xp} to {_xp}*6
					if {expAreaMayanBoss} = uuid of victim:
						clear {expAreaMayanBoss}
				cardLevelup(attacker, {_xp}, victim)
				remove uuid of attacker from {asyst::%uuid of victim%::*}
				if size of {asyst::%uuid of victim%::*} > 0:
					loop {asyst::%uuid of victim%::*}:
						#if {winterDelightPassLEVEL::%loop-value%} >= 0:
						#	getMission(loop-value, "Sleighing the Mobs", "Pokonywanie Potworów", 1)
						set {_p} to loop-value parsed as a player
						set {_id} to string tag "Id" of (custom nbt of {karta::%{_p}%})
						set {_cardLevel} to yaml value "Card.Level" in "activeCard-%{_p}%"
						set {_maxLevel} to {maxCardLevel}
						set {_xp} to 0.4/1.171 ^ ((({_cardLevel}/{_maxLevel}))+sqrt({_cardLevel}*10)) * sqrt({maxCardLevel} / {baseMaxCardLevel})
						set {_xp} to {_xp}*0.5
						if boolean tag "ECSuperMob" of (custom nbt of victim) is set:
							set {_xp} to {_xp}*2.5
						if boolean tag "ECBoss" of (custom nbt of victim) is set:
							set {_xp} to {_xp}*6
						cardLevelup({_p}, {_xp}, victim)
			if {expAreaMayanMobs} - 1 >= 0:
				set {expAreaMayanMobs} to {expAreaMayanMobs} - 1
				if boolean tag "ECBoss" of (custom nbt of victim) is set:
					set {_multiplier} to 10
					set {_type} to "boss"
				else if boolean tag "ECSuperMob" of (custom nbt of victim) is set:
					set {_multiplier} to 4
					set {_type} to "supermob"
				else:
					set {_multiplier} to 1
					set {_type} to "mob"
				ExpAreaMayanMobDrop(attacker, victim, {_multiplier}, {_type})
				loop {asyst::%uuid of victim%::*}:
					set {_p} to loop-value parsed as a player
					ExpAreaMayanMobDrop({_p}, victim, {_multiplier}, {_type})
					add 1 to {weeklyMobsDefeated::%{_p}%}
					add 1 to {totalMobsDefeated::%{_p}%}
			if boolean tag "ECBoss" of (custom nbt of victim) is set:
				set {_id} to string tag "ECBossBossBar" of (custom nbt of victim)
				remove all players from boss bar with id {_id}

		clear string tag "ECElement" of (custom nbt of victim)
		
		if {testentity::%victim%} is set:
			clear {testentity::%victim%}

	else:
		if "%region at victim%" contains "ExpAreaMayan":
			if {expAreaMayan} - 1 >= 0:
				set {expAreaMayan} to {expAreaMayan}-1
			if {expAreaMayan} = 0:
				clear {expAreaMayan}

		if {kartaname::%victim%} = "Umbreon":
			if boolean tag "Constellation;Cheat Death" of custom nbt of {karta::%victim%} is set:
				if cooldown "Cheat Death%victim%" is finished:
					cancel event
					create cooldown "Cheat Death%victim%" for 30 minutes
					set {_health} to (victim's max health)*0.05
					set victim's health to {_health}
					CheatDeathUmbreon(victim)
					stop

		set {_id} to string tag "Id" of custom nbt of {karta::%victim%}
		add 1 to {deaths::%victim%}
		add 1 to {deaths::%{kartaname::%victim%}%::%{_id}%}
		CardCombatYamlAdd(victim, "Combat Data.Total Deaths", 1)

		clear metadata value "Heartbeat" of victim

	if attacker is a player:
		if boolean tag "ECMob" of (custom nbt of victim) is set:
			set {_id} to string tag "Id" of custom nbt of {karta::%attacker%}
			set {mobskilled::%attacker%} to {mobskilled::%attacker%} + 1
			set {mobkills::%attacker%} to {mobkills::%attacker%} + 1
			set {mobskilled::%{kartaname::%attacker%}%::%{_id}%} to {mobskilled::%{kartaname::%attacker%}%::%{_id}%} + 1

			set {_allTimeMobKills} to yaml value "Player.All Time.Mob Kills" in "data-%attacker%"
			if {_allTimeMobKills} is not set:
				set {_allTimeMobKills} to 0
			set {_allTimeMobKills} to {_allTimeMobKills} + 1
			set yaml value "Player.All Time.Mob Kills" in "data-%attacker%" to {_allTimeMobKills}

			set {_updateMobKills} to yaml value "Player.Per Update.%{currentUpdate}%.Mob Kills" in "data-%attacker%"
			set {_updateMobKills} to {_updateMobKills} + 1
			set yaml value "Player.Per Update.%{currentUpdate}%.Mob Kills" in "data-%attacker%" to {_updateMobKills}

			if yaml "data-%attacker%" is loaded:
				save yaml "data-%attacker%"

			CardCombatYamlAdd(attacker, "Combat Data.Total Killing Blows", 1)
			CardCombatYamlAdd(attacker, "Combat Data.Total Overall Kills", 1)
			remove uuid of attacker from {asyst::%uuid of victim%::*}
			if size of {asyst::%uuid of victim%::*} > 0:
				loop {asyst::%uuid of victim%::*}:
					set {_assistPlayer} to loop-value parsed as player
					CardCombatYamlAdd({_assistPlayer}, "Combat Data.Total Assists", 1)
					CardCombatYamlAdd({_assistPlayer}, "Combat Data.Total Overall Kills", 1)

	if boolean tag "TowerDefenceMob" of (custom nbt of victim) is not set:
		if boolean tag "ECAbility" of (custom nbt of victim) is not set:
			if boolean tag "RemoveOnReset" of (custom nbt of victim) is not set:
				if victim is not an armor stand:
					draw 1 white flash particle at victim
			else:
				clear drops

	if boolean tag "ECMob" of (custom nbt of victim) is set:
		if attacker is a player:
			#if display name of victim is not set:
			add 1 to {%type of victim%::%attacker%}
			if name of victim contains "<##14c8ff>Ice Elemental":
				add 1 to {iceelemental::%attacker%}
				clear {icecubesamount::%victim%}
			if name of victim contains "<##14c8ff>Ice Cube":
				set {_summoner} to metadata value "summoner" of victim
				remove 1 from {icecubesamount::%{_summoner}%}
				add 1 to {icecube::%attacker%}
			if name of victim contains "&fSnow Bombarder":
				set {_summoner} to metadata value "summoner" of victim
				remove 1 from {snowmenamount::%{_summoner}%}
				add 1 to {snowbombarder::%attacker%}
			if {froststrikes::%attacker's uuid%::%victim%} is set:
				clear {froststrikes::%attacker's uuid%::%victim%}
			#else:
				#set {_unc} to uncolored name of victim
				#add 1 to {%{_unc}%::%attacker%}
			set {_id} to line 19 of lore of {karta::%attacker%}
			replace all "&8Id: " in {_id} with ""
			add 1 to {kills::%{kartaname::%attacker%}%::%{_id}%::%metadata value "LastDamageCause" of victim%}
			#if {expyield::%victim%} is set:
			#	wait 1 tick
			#	set {_lloc} to block above victim
			#	set {_xp} to cardLevelup(attacker, {expyield::%victim%}, victim)
			#	display hologram "<##37eb34>+%{_xp}% XP" at {_lloc} to attacker for 2.5 seconds
			#	set {_xpasysta} to (rounded up 0.3*{expyield::%victim%})
			#	if {asyst::%uuid of victim%::*} is set:
			#		loop {asyst::%uuid of victim%::*}:
			#			set {_player} to loop-value parsed as player
			#			if {_player} is not attacker:
			#				add 1 to {asysty::%{_player}%}
			#				add 1 to {asysta::%victim's name%::%{_player}%}
			#				display hologram "<##37eb34>+%{_xpasysta}% XP" at {_lloc} to {_player} for 2.5 seconds
	if victim is not a player:
		clear {expyield::%victim%}
		clear {asyst::%uuid of victim%::*}
		clear {mobdmg::%victim%}
	else:
		if {froststrikes::%attacker's uuid%::%victim%} is set:
			clear {froststrikes::%attacker's uuid%::%victim%}
		add 1 to {%type of attacker%attack::%victim%}
		if name of victim contains "<##14c8ff>Ice Elemental":
			add 1 to {iceelementalattack::%victim%}
		if name of victim contains "<##14c8ff>Ice Cube":
			add 1 to {icecubeattack::%victim%}
		if name of victim contains "&fSnow Bombarder":
			add 1 to {snowbombarderattack::%victim%}
on death:
	if damage cause is attack:
		set death message to ""
		set {_data} to data()
		if metadata value "LastDamageCause" of victim is not set:
			set metadata value "LastDamageCause" of victim to attacker's tool
			if metadata value "LastDamageCause" of victim = air:
				set metadata value "LastDamageCause" of victim to "attack"
			if metadata value "LastDamageCause" of victim is not set:
				set metadata value "LastDamageCause" of victim to " "	
		else:

			if metadata value "LastDamageCause" of victim = "<##555555>End Game":
				if 50 >= metadata value "UmbreonExecutioner" of attacker:
					add 5 to metadata value "UmbreonExecutioner" of attacker
					set {_endGameCd} to cooldown "End Game%attacker%"
					set {_endGameCdSeconds} to (ticks of {_endGameCd})*0.05
					set {_endGameCdSeconds} to "%(0.05*{_endGameCdSeconds})% seconds" parsed as timespan
					remove {_endGameCdSeconds} from cooldown "End Game%attacker%"
				else:
					clear metadata value "UmbreonExecutioner" of attacker
		
		set {_customNbt} to custom nbt of victim

		if boolean tag "TowerDefenceMob" of {_customNbt} is not set:
			if victim's name is set:
				if string tag "IslandEnemyName" of {_customNbt} is set:
					set {_name} to string tag "IslandEnemyName" of {_customNbt}

					if boolean tag "ECIslandEnemy" of {_customNbt} is set:
						set {_attacker} to attacker
						if {_attacker} is a projectile:
							set {_attacker} to shooter of {_attacker}
						if {_attacker} is a player:
							set {_instance} to string tag "IslandExpeditionInstance" of {_customNbt}
							if metadata value "IslandExpeditionInstance" of {_attacker} = {_instance}:
								set {_azerite} to metadata value "IslandEnemyAzerite" of victim
								if {_azerite} > 0:
									if {_azerite} > 190:
										set {_sound} to "azerite.collect"
									else:
										set {_sound} to "azerite.collect_small"

									azeriteAddIslands({_attacker}, {_instance}, "Enemy", {_name}, {_azerite}, "Ally", {_sound})
				else:
					set {_name} to victim's name
					if display name of victim contains "&c♥":
						set {_name::*} to name of victim split at " "
						loop {_name::*}:
							add 1 to {_l}
						clear {_name::%{_l}%}
						set {_name} to join {_name::*} by " "
						if {_name} is not set:
							set {_name} to victim
				loop all players:
					send formatted "%{_name}% &fwas slain by %attacker's name% &fusing <tooltip:%metadata value "LastDamageCauseLore" of victim%>%metadata value "LastDamageCause" of victim%" to loop-player
				log "%{_data}% %uncolored victim's name% was slain by %attacker's name% using %uncolored metadata value "LastDamageCause" of victim%" to "logi/combat/combat %{datatydzien}%-%{datatydzien2}%.log"
			else:
				set {_name} to "%victim%"

				loop all players:
					send formatted "%{_name}% &fwas slain by %attacker's name% using <tooltip:%metadata value "LastDamageCauseLore" of {_name}%>%metadata value "LastDamageCause" of {_name}%" to loop-player
				log "%{_data}% %victim% &fwas slain by %attacker's name% using %uncolored metadata value "LastDamageCause" of victim%" to "logi/combat/combat %{datatydzien}%-%{datatydzien2}%.log"
		else:
			clear drops

	else if damage was caused by a projectile:
		victim is player or a living entity:
			set death message to ""
		if victim's name is set:
			#usuwanie hp przeciwnika z wiadomości
			set {_name} to victim's name
			if display name of victim contains "&c♥":
				set {_name::*} to name of victim split at " "
				loop {_name::*}:
					add 1 to {_l}
				clear {_name::%{_l}%}
				set {_name} to join {_name::*} by " "
				#HP MOBÓW MINECRAFTOWYCH
				if {_name} is not set:
					set {_name} to victim
			loop all players:
				send formatted "%{_name}% &fwas slain by %attacker's name% &fusing <tooltip:%metadata value "LastDamageCauseLore" of victim%>%metadata value "LastDamageCause" of victim%" to loop-player
			log "%{_data}% %victim% &fwas slain by %attacker's name% using %uncolored metadata value "LastDamageCause" of victim%" to "logi/combat/combat %{datatydzien}%-%{datatydzien2}%.log"
		else:
			loop all players:
				send formatted "%victim% &fwas slain by %attacker% using <tooltip:%metadata value "LastDamageCauseLore" of victim%>%metadata value "LastDamageCause" of victim%" to loop-player
			log "%{_data}% %victim% &fwas slain by %attacker% using %uncolored metadata value "LastDamageCause" of victim%" to "logi/combat/combat %{datatydzien}%-%{datatydzien2}%.log"
	clear {circleofwater::%victim%}
	clear {astralpower::%victim%}
	clear drops if boolean tag "RemoveOnReset" of (custom nbt of victim) is true
	wait 1 tick
	clear metadata value "LastDamageCause" of victim
	clear metadata value "LastDamageCauseLore" of victim
	clear metadata value "DamageType" of victim

on projectile hit:
	if shooter is a skeleton:
		if boolean tag "ECMob" of custom nbt of shooter is not set:
			delete event-projectile
	if event-projectile is a trident:
		wait 10 seconds
		kill event-projectile

on join:
	set scaled health of player to 20
	if player's last damage cause is not set:
		set player's last damage cause to attack
on spawn:
	set event-entity's last damage cause to attack
on respawn:
	if player's last damage cause is not set:
		set player's last damage cause to attack
on shoot:
	if shooter is a drowned:
		if cooldown "ShootTrident%uuid of shooter%" is finished:
			create cooldown "ShootTrident%uuid of shooter%" for 5 seconds
		else:
			cancel event
	else if shooter is a blaze:
		if string tag "MobType" of custom nbt of shooter = "Gosha Imitation":
			cancel event
import:
	org.bukkit.entity.LivingEntity
	java.time.ZonedDateTime
	java.time.ZoneId

on damage:
	if attacker is a player:
		if victim is a living entity:
			victim.setMaximumNoDamageTicks(0)
	if "%victim's last damage cause%" is "unknown":
		set victim's last damage cause to attack
	if region at victim is set:
		if damage cause is fall:
			set damage to 0
			cancel event
	if boolean tag "ECMob" of (custom nbt of victim) is set:
		if damage cause is not attack:
			if damage cause is not sweep attack:
				if attacker is not a player:
					if attacker is not a projectile:
						set damage to 0
						cancel event
	if damage cause is fall:
		cancel event
	else if damage cause is suffocation:
		cancel event
	else if damage cause is entity explosion:
		cancel event
	else if damage cause is drown:
		if boolean tag "ECMob" of (custom nbt of victim) is set:
			set damage to 0
			cancel event
		else if "%region at victim%" contains "NewPlayerArea":
			set damage to 0
			cancel event
	else if "%damage cause%" is "wither":
		set damage to 0
		cancel event
	else if "%damage cause%" is "poison":
		set damage to 0
		cancel event
	else if "%damage cause%" is "fire" or "burning":
		set damage to 0
		cancel event
	else if damage cause is fire:
		set damage to 0
		cancel event
	else if damage cause is burn:
		set damage to 0
		cancel event
	if victim is a player:
		if damage cause is contact:
			set damage to 0
			cancel event
	#if victim is a player:
	#	if region at victim is set:
	#		if damage cause is contact:
	#			set damage to 0
	#			cancel event
	#	else:
	#		if damage cause is contact:
	#			if cooldown "damagecontact%victim%" is finished:
	#				create cooldown "damagecontact%victim%" for 0.5 seconds
	#			else:
	#				set damage to 0
	#				cancel event
	if damage cause is magma:
		set damage to 0
		cancel event
	else if damage cause is fire:
		if boolean tag "ECMob" of (custom nbt of victim) is set:
			set damage to 0
			cancel event
	else if damage cause is burn:
		if boolean tag "ECMob" of (custom nbt of victim) is set:
			set damage to 0
			cancel event
	else if damage cause is lava:
		if victim is not a player:
			if victim is a living entity:
				set damage to 0
				cancel event
		else:
			if cooldown "damagelava%victim%" is finished:
				create cooldown "damagelava%victim%" for 0.5 seconds
			else:
				set damage to 0
				cancel event
	#DUNGEON SECTION
	if attacker is a blaze:
		if victim is a player:
			if victim's last damage cause is not sweep attack:
				if int tag "ECDungeonInstance" of custom nbt of attacker is set:
					if name of attacker is "Balthazar" or "Destruction Mage":
						set damage to 0
						cancel event	
	else if attacker is a goat:
		if "%regions at attacker%" contains "spawn":
			cancel event
	if victim is a player:
		set scaled health of victim to 20
	else:
		if boolean tag "ECMob" of (custom nbt of victim) is set:
			if attacker is a player:
				if {asyst::%uuid of victim%::*} does not contain (uuid of attacker):
					add (uuid of attacker) to {asyst::%uuid of victim%::*}
				if metadata value "TutorialTargetDummyDamage" of attacker is set:
					if damage is not 0:
						if victim is not invulnerable:
							set {_damageCount} to metadata value "TutorialTargetDummyDamage" of attacker
							add damage to {_damageCount}
							set metadata value "TutorialTargetDummyDamage" of attacker to {_damageCount}
							if {_damageCount} >= 100:
								clear metadata value "TutorialTargetDummyDamage" of attacker
								CombatTutorial(attacker)
							
	if attacker is not a player:
		if attacker is a living entity:
			if victim's last damage cause is not sweep attack:
				if int tag "ECDungeonInstance" of custom nbt of attacker is set:
					if (int tag "ECDungeonInstance" of custom nbt of attacker) = (metadata value "DungeonInstance" of victim):
						set {_meleeDamage} to long tag "MeleeDamage" of custom nbt of attacker
						DamageProperties(victim, attacker, "&7Melee", "Basic melee attack.", {_meleeDamage})
				if damage cause is projectile:
					if projectile is arrow:
						if boolean tag "ECMob" of custom nbt of attacker is set:
							set damage to damage*0.7
				if victim is a player:
					if cooldown "attack%uuid of attacker%" is finished:
						set {_attackCooldown} to 0.75 seconds
						if string tag "WorldQuest" of custom nbt of attacker is set:

							set {_WQMobType} to string tag "MobType" of custom nbt of attacker
							set {_WQMobAttackCooldown} to yaml value "Mobs.%{_WQMobType}%.Melee Attack Cooldown" in "WorldQuestList"
							if {_WQMobAttackCooldown} is set:
								set {_attackCooldown} to "%{_WQMobAttackCooldown}% seconds" parsed as timespan

						create cooldown "attack%uuid of attacker%" for {_attackCooldown}

						if projectile exists:
							if name of attacker's tool is set:
								set metadata value "LastDamageCause" of victim to name of attacker's tool
							else:
								set metadata value "LastDamageCause" of victim to "%attacker's held item%"
					else:
						set damage to 0
						cancel event
			#Remove if problematic
			if damage = 0:
				stop

			#///Animation section
			if string tag "ECModelName" of custom nbt of attacker is set:
				setAIState(attacker, "attack")
				playEntitySound(attacker, "Attack")
	else:
		set {_customNbt} to custom nbt of victim
		if boolean tag "ECMob" of {_customNbt} is set:
			if boolean tag "ECDungeonMob" of {_customNbt} is set:
				set metadata value "ECPulled" of victim to 1
				UpdateTarget(victim, attacker, "dynamic")
			else:
				if all:
					boolean tag "ECIslandEnemy" of {_customNbt} is set
					string tag "IslandEnemyMovement" of {_customNbt} = "Static"
				then:
					set metadata value "ECPulled" of victim to 1
					UpdateTarget(victim, attacker, "dynamic")
		else:
			if "%region at victim%" contains "WorldQuest_":
				if attacker's gamemode is not creative:
					cancel event

		if victim's last damage cause is attack:
			if projectile does not exist:
				if boolean tag "MeleeAbility" of custom nbt of attacker's tool is not set:
					if boolean tag "Ability" of custom nbt of attacker's tool is not set:
						if cooldown "attack%attacker%" is finished:
							create cooldown "attack%attacker%" for 0.5 seconds
							set damage to damage*0.75
							if name of attacker's tool is set:
								set metadata value "LastDamageCause" of victim to name of attacker's tool
							else:
								set metadata value "LastDamageCause" of victim to "%attacker's tool%"
							if attacker's tool is enchanted:
								set {_lastdmg::*} to "&5Enchants:"
								loop enchantments of attacker's tool:
									set {_level} to enchantment level of enchantment of loop-value
									set {_line} to "&7%enchantment of loop-value% %roman numeral of {_level}%"
									set {_lastdmg::*} to {_lastdmg::*} and {_line}
							if lore of attacker's tool is set:
								if {_level} is set:
									set {_lastdmg::*} to {_lastdmg::*} and " "
								set {_lastdmg::*} to {_lastdmg::*} and lore of attacker's tool
						
							set metadata value "LastDamageCauseLore" of victim to join {_lastdmg::*} by nl
						else:
							set damage to 0
							cancel event
					else:
						set damage to 0
						cancel event
			else:
				if name of attacker's tool is set:
					set metadata value "LastDamageCause" of victim to name of attacker's tool
				else:
					set metadata value "LastDamageCause" of victim to "%attacker's held item%"

		if victim's last damage cause is sweep attack:
			if attacker's tool is tagged with tag "swords":
				if boolean tag "MeleeAbility" of custom nbt of attacker's tool is not set:
					if cooldown "attack%attacker%" is finished:
						create cooldown "attack%attacker%" for 0.5 seconds
						set damage to damage*0.75
						if name of attacker's tool is set:
							set metadata value "LastDamageCause" of victim to name of attacker's tool
						else:
							set metadata value "LastDamageCause" of victim to "%attacker's held item%"
						if attacker's tool is enchanted:
							set {_lastdmg::*} to "&5Enchants:"
							loop enchantments of attacker's tool:
								set {_level} to enchantment level of enchantment of loop-value
								set {_line} to "&7%enchantment of loop-value% %roman numeral of {_level}%"
								set {_lastdmg::*} to {_lastdmg::*} and {_line}
						if lore of attacker's tool is set:
							if {_level} is set:
								set {_lastdmg::*} to {_lastdmg::*} and " "
							set {_lastdmg::*} to {_lastdmg::*} and lore of attacker's tool
					
						set metadata value "LastDamageCauseLore" of victim to join {_lastdmg::*} by nl
					else:
						set damage to 0
						cancel event


	if long tag "MobDamageModifier" of custom nbt of attacker is set:
		set damage to (damage * (long tag "MobDamageModifier" of custom nbt of attacker))

	set {_idV} to string tag "Id" of custom nbt of {karta::%victim%}
	set {_idA} to string tag "Id" of custom nbt of {karta::%attacker%}
	
	set {_elementModifier} to 1

	# This list contains all individual elements in fusions
	set {_elementTypes::*} to getElement(attacker)

	if string tag "ECElement" of (custom nbt of victim) is set:
		if metadata value "Element" of attacker is set:
			set {_attackerElement} to metadata value "Element" of attacker
			set {_elementVictim} to string tag "ECElement" of (custom nbt of victim)
			
			set {_element::*} to Zywiol(attacker, victim)
			set {_elementModifier} to ({_elementModifier} + {_element::1})
			set {_elementEffect} to ElementEffective({_element::2}, {_element::3})

	if victim is a player:
		set {_resistance} to Resistance(victim)
		set {_versatility} to Versatility(victim)
	else:
		set {_resistance} to metadata value "Stats/Resistance" of victim
		set {_versatility} to metadata value "Stats/Versatility" of victim

	if {karta::%attacker%} is set:
		if metadata value "Voidform" of attacker is set:
			if boolean tag "Constellation;Mass Hysteria" of custom nbt of {karta::%attacker%} is set:
				set {_voidformStacks} to metadata value "Voidform Stacks" of attacker
				set {_damageAmp} to 1 + {_voidformStacks}/100
				set damage to damage*{_damageAmp}
				
		if getArtifactSetCount(attacker, "Marksmanship", 2) = true:
			if distance between attacker and victim >= 20:
				set damage to damage*1.12

		if getArtifactSetCount(attacker, "Marksmanship", 4) = true:
			if any:
				metadata value "DamageType" of victim = "Ranged"
				projectile exists
			then:
				set damage to damage*1.35

		if 0.35*(victim's max health) >= victim's health:
			if string tag "Talents;Row 1" of custom nbt of {karta::%attacker%} = "Twist of Fate":
				if metadata value "TwistOfFate" of attacker is not set:
					set metadata value "TwistOfFateDuration" of attacker to 8 seconds
					set metadata value "TwistOfFate" of attacker to true
					TwistOfFate(attacker)
				else:
					set metadata value "TwistOfFateDuration" of attacker to 8 seconds
				set damage to 1.1*damage

		if metadata value "LastDamageCause" of victim = "<##462566>Shadow Word: Death":
			if {kartaname::%attacker%} = "Brother Therold":
				if string tag "Talents;Row 3" of custom nbt of {karta::%attacker%} = "Reaper of Souls":
					GrantInsanity(attacker, 30)
				else:
					if final damage >= health of victim:
						GrantInsanity(attacker, 30)
					else:
						GrantInsanity(attacker, 15)
				UpdateInsanity(attacker)

		if {kartaname::%attacker%} = "Umbreon":

			if metadata value "Garrote%attacker%" of victim is set:
				set damage to damage*1.1

			if metadata value "ShadowstepDamageIncrease%attacker%" of victim is set:
				set damage to damage*1.08

			if (time in world "world") is between 10:00 PM and 4:00 AM:
				set damage to damage*1.1

			if boolean tag "Constellation;On the Prowl" of custom nbt of {karta::%attacker%} is set:
				if string tag "ECElement" of (custom nbt of victim) = "Beast":
					set damage to damage*1.2

			if attacker has invisibility:
				set {_baseDamageBonus} to 0.15
				
				if string tag "Talents;Row 2" of custom nbt of {karta::%attacker%} = "Chosen of the Night":
					set {_baseDamageBonus} to {_baseDamageBonus} + 0.1

				set {_damageBonus} to (1 + ({_baseDamageBonus} + (({mastery::%attacker%}/130))))

				set damage to damage*{_damageBonus}

				if metadata value "LastDamageCause" of victim = "<##555555>Shadow Claws":
					clear metadata value "ShadowstepDamageIncrease%attacker%" of victim
					clear metadata value "Garrote%attacker%" of victim

					if string tag "Talents;Row 5" of custom nbt of {karta::%attacker%} = "Shadow Macabre":
						remove invisibility from attacker
						set damage to damage*1.05

			if string tag "Talents;Row 2" of custom nbt of {karta::%attacker%} = "Moonlight Empowerment":
				set {_darkIncrease} to 1.08
				set {_lightIncrease} to 1.08

				if {_attackerElement} = "Dark":
					set damage to damage*{_darkIncrease}
				else if {_attackerElement} = "Light":
					set damage to damage*{_lightIncrease}
				else if {_attackerElement} = "Moonlight":
					set damage to damage*{_darkIncrease}*{_lightIncrease}

			if string tag "Talents;Row 4" of custom nbt of {karta::%attacker%} = "Midnight":

				if {_attackerElement} != "Moonlight":
					if metadata value "MidnightDamageIncrease%{_attackerElement}%" of attacker is set:
						set {_midnightIncrease} to metadata value "MidnightDamageIncrease%{_attackerElement}%" of attacker 
						set damage to damage*{_midnightIncrease}
				else:
					if metadata value "MidnightDamageIncreaseDark" of attacker is set:
						set {_midnightIncreaseDark} to metadata value "MidnightDamageIncreaseDark" of attacker
					else:
						set {_midnightIncreaseDark} to 1

					if metadata value "MidnightDamageIncreaseLight" of attacker is set:
						set {_midnightIncreaseLight} to metadata value "MidnightDamageIncreaseLight" of attacker
					else:
						set {_midnightIncreaseLight} to 1

					set damage to damage*{_midnightIncreaseDark}*{_midnightIncreaseLight}

				if ("Light", "Dark", "Moonlight") contains {_attackerElement}:
					if {_attackerElement} = "Moonlight":
						MidnightDamageIncrease(attacker, "Dark")
						MidnightDamageIncrease(attacker, "Light")
					else:
						if {_attackerElement} = "Dark":
							MidnightDamageIncrease(attacker, "Light")
						else:
							MidnightDamageIncrease(attacker, "Dark")
				
				MidnightBuff(attacker)

			if string tag "Talents;Row 5" of custom nbt of {karta::%attacker%} = "Moonlight Echo":
				if metadata value "LastDamageCause" of victim != "<##555555>Moonlight Echo":
					if ("Light", "Dark", "Moonlight") contains {_attackerElement}:
						if {_attackerElement} = "Moonlight":
							set {_damageRepeat} to 0.16*damage
							MoonlightEcho(attacker, victim, {_damageRepeat}, "Moonlight")
						else if {_attackerElement} = "Dark":
							set {_damageRepeat} to 0.08*damage
							MoonlightEcho(attacker, victim, {_damageRepeat}, "Light")
						else:
							set {_damageRepeat} to 0.08*damage
							MoonlightEcho(attacker, victim, {_damageRepeat}, "Dark")

		else if {kartaname::%attacker%} = "Cresselia":
			if metadata value "CelestialAlignment" of attacker is set:
				set damage to damage * (1 + getRunePower(attacker, "Moonlit Authority") / 100)

	if int tag "StellarPower" of custom nbt of {karta::%attacker%} > 0:
		set {_stellarPower} to 1 + (int tag "StellarPower" of custom nbt of {karta::%attacker%})/100
		set damage to damage * {_stellarPower}

	if metadata value "IgnoreModifiers" of victim != true:

		set {_damagered} to 1 + (({_resistance}/10) + ({_versatility}/30))/100

		if metadata value "IgnoreResistance%attacker%" of victim is set:
			set {_ignoreResistanceAmount} to metadata value "IgnoreResistance%attacker%" of victim
			clear metadata value "IgnoreResistance%attacker%" of victim
			set {_damagered} to (({_damagered}-1) * (1-{_ignoreResistanceAmount})) + 1

		set damage to damage * {_elementModifier}
		
		if attacker is a player:
			if party of attacker is set:
				set {_partyMembersNames::*} to (party members of (party of attacker)) where [input is online]
				loop {_partyMembersNames::*}:
					set {_partyMembers::%loop-counter%} to "%loop-value%" parsed as player
		
		set {_effectiveDamage::*} to "super strong", "strong", "moderately strong"
		set {_ineffectiveDamage::*} to "super weak", "weak", "mildly weak"

		if {_effectiveDamage::*} contains {_elementEffect}:
			if {kartaname::%attacker%} = "Shaymin":
				if metadata value "LastDamageCause" of victim = "<##f8fff5>Air Slash":
					set damage to damage*1.2
			
			if metadata value "LastDamageCause" of victim != "<#7cafbf>Hydrodance":
				loop {_partyMembers::*}:
					if {kartaname::%loop-value%} = "Vaporeon":
						if boolean tag "Constellation;Restorative Droplets" of (custom nbt of {karta::%loop-value%}):
							if cooldown "RestorativeDroplets%attacker%-%loop-value%" is finished:
								set {_haste} to Haste(loop-value)
								set {_cdDroplets} to "%3/{_haste}% seconds" parsed as timespan
								create cooldown "RestorativeDroplets%attacker%-%loop-value%" for {_cdDroplets}

								set {_mult} to 1
								if {kartaname::%attacker%} is "Vaporeon":
									if boolean tag "Constellation;Restorative Droplets" of (custom nbt of {karta::%attacker%}):
										set {_mult} to 3

								RestorativeDroplets(loop-value, attacker, {_mult}, {_partyMembers::*}, victim)

		else if {_ineffectiveDamage::*} contains {_elementEffect}:
			if {kartaname::%attacker%} = "Buckshot":
				if boolean tag "Constellation;Elemental Bypass" of (custom nbt of {karta::%attacker%}) is set:
					if {_elementTypes::*} contains "Magic":
						ElementalBypassBuckshot(attacker, {_elementVictim})
						set {_elementalBypassBuckshot} to 1 + (getElementalBypassBuckshot(attacker, {_elementVictim})/100)

						set damage to damage * {_elementalBypassBuckshot}
						set {_elementModifier} to {_elementModifier}*{_elementalBypassBuckshot}

		if {_elementTypes::*} contains "Fire" or "Lava":
			if getArtifactSetCount(attacker, "Scorched", 2) = true:
				set {_artifactDamageModifier} to yaml value "Values.Scorched.2SETBONUS" in "ArtifactList"

		else if {_elementTypes::*} contains "Ice":
			if getArtifactSetCount(attacker, "Deepfrost", 2) = true:
				set {_artifactDamageModifier} to yaml value "Values.Deepfrost.2SETBONUS" in "ArtifactList"

		else if {_elementTypes::*} contains "Water":
			loop {_partyMembers::*}:
				set {_partyMember} to loop-value
				if distance between {_partyMember} and attacker < 500:
					if {kartaname::%{_partyMember}%} = "Vaporeon":
						if boolean tag "Constellation;Oceanic Might" of (custom nbt of {karta::%{_partyMember}%}) is set:
							set {_partySizeOceanicMight} to {_partySizeOceanicMight} + 1
			
			if {_partySizeOceanicMight} > 0:
				set {_oceanicMightBonus} to 1.08
				if shieldFind(attacker, attacker, "Explosive Bubble", true) is set:
					set {_oceanicMightBonus} to ({_oceanicMightBonus}*2) - 1

				set damage to damage * ({_oceanicMightBonus}^{_partySizeOceanicMight})

		if {_artifactDamageModifier} is set:
			set damage to damage*(1 + ({_artifactDamageModifier}/100))

		set damage to damage/{_damagered}

		if metadata value "DamageReduction" of victim is set:
			set {_dmgTakenPercentage} to metadata value "DamageReduction" of victim
			set damage to damage*{_dmgTakenPercentage}

		chance of ({avoidance::%victim%}/20)%:
			set damage to 0

	else:
		clear metadata value "IgnoreModifiers" of victim

	if damage != 0:
		if attacker is a player:		
			if metadata value "Crit%attacker%" of victim is true:
				clear metadata value "Crit%attacker%" of victim

				if getArtifactSetCount(attacker, "Deepfrost", 4) = true:
					Deepfrost4Set(attacker)

				set {_crit} to true
			else:
				set {_crit} to false

			damageText(attacker, victim, damage, {_crit}, {_elementEffect}, {_elementModifier})

			if boolean tag "ECMob" of (custom nbt of victim) is set:
				set metadata value "MostRecentlyDamagedEnemy" of attacker to victim

			if {kartaname::%attacker%} = "Umbreon":
				if metadata value "ShadowMark%attacker%" of victim is set:
					add damage to metadata value "ShadowMark%attacker%" of victim

			if boolean tag "TargetableByAllies" of (custom nbt of victim) is true:
				cancel event

		if victim is a player:
			if health of victim < (max health of victim*0.3):
				if metadata value "Heartbeat" of victim is not set:
					set metadata value "Heartbeat" of victim to true
					Heartbeat(victim)
			if health of victim > (max health of victim*0.3):
				clear metadata value "Heartbeat" of victim
	
		if victim is not invulnerable:
			if yaml "Shields%uuid of victim%" is loaded:
				if yaml value "ShieldsActive" in "Shields%uuid of victim%" > 0:
					set {_damageShield} to shieldDamageEvent(victim, damage)
					set damage to {_damageShield}
					if {_damageShield} = 0:
						cancel event
			
			if attacker is not victim:
				if attacker is a player:
					if boolean tag "ECMob" of (custom nbt of victim) is set:
						combatInitiate(attacker, victim)
						if boolean tag "EC5PercentTriggered" of (custom nbt of victim) is not set:
							set {_damageCause} to (uncolored metadata value "LastDamageCause" of victim) in strict proper case
							set {_damage} to damage
							if {_damage} > health of victim:
								set {_damage} to health of victim
							DamageBreakdown(attacker, victim, {_damage})
							if damage > {highestDamage::%attacker%}:
								set {highestDamage::%attacker%} to damage
							if metadata value "DungeonInstance" of attacker is set:
								set {_instanceAttacker} to metadata value "DungeonInstance" of attacker
								set {_instanceVictim} to int tag "ECDungeonInstance" of (custom nbt of victim)
								if {_instanceAttacker} = {_instanceVictim}:
									DungeonPullDamage(attacker, victim, damage, {_damageCause})
							if yaml "activeCard-%attacker%" is loaded:
								set {_totalDamageDealt} to yaml value "Combat Data.Total Damage Dealt" in "activeCard-%attacker%"
								add damage to {_totalDamageDealt}
								set yaml value "Combat Data.Total Damage Dealt" in "activeCard-%attacker%" to {_totalDamageDealt}

								set {_damageDealtSource} to yaml value "Combat Data.By Source.%{_damageCause}%.Damage Dealt" in "activeCard-%attacker%"
								add damage to {_damageDealtSource}
								set yaml value "Combat Data.By Source.%{_damageCause}%.Damage Dealt" in "activeCard-%attacker%" to {_damageDealtSource}
								if {_crit} = true:
									set {_totalCrits} to yaml value "Combat Data.Total Critical Hits" in "activeCard-%attacker%"
									add 1 to {_totalCrits}
									set yaml value "Combat Data.Total Critical Hits" in "activeCard-%attacker%" to {_totalCrits}

									set {_critsSource} to yaml value "Combat Data.By Source.%{_damageCause}%.Critical Hits" in "activeCard-%attacker%"
									add 1 to {_critsSource}
									set yaml value "Combat Data.By Source.%{_damageCause}%.Critical Hits" in "activeCard-%attacker%" to {_critsSource}
								save yaml "activeCard-%attacker%"
								
							if string tag "ECTextAbove" of (custom nbt of victim) is set:
								if int tag "ECDungeonInstance" of (custom nbt of victim) is not set:
									UpdateMobHealthBar(victim)
									if boolean tag "ECBoss" of (custom nbt of victim) is set:
										MobHealthBar(victim)
							set {_health1} to victim's health
							if damage > {_health1}:
								add ({_health1}) to {dmgdealt::%attacker%}
							else:
								add damage to {dmgdealt::%attacker%}
							if boolean tag "ECTestEntity" of (custom nbt of victim) is set:
								set {_idA} to string tag "Id" of custom nbt of {karta::%attacker%}
								if damage > {_health1}:
									set {damage::dealt::%{kartaname::%attacker%}%::%{_idA}%} to {damage::dealt::%{kartaname::%attacker%}%::%{_idA}%} + {_health1}
								else:
									set {damage::dealt::%{kartaname::%attacker%}%::%{_idA}%} to {damage::dealt::%{kartaname::%attacker%}%::%{_idA}%} + damage
								add damage to {damagetotal::%attacker%}
				else:
					if victim is a player:
						if boolean tag "ECMob" of custom nbt of attacker is set:
							combatInitiate(victim, attacker)
							set {_damageCause} to (uncolored metadata value "LastDamageCause" of victim) in strict proper case
							set {_damage} to damage
							if {_damage} > health of victim:
								set {_damage} to health of victim
							if metadata value "DungeonInstance" of victim is set:
								set {_instanceAttacker} to metadata value "DungeonInstance" of victim
								set {_instanceVictim} to int tag "ECDungeonInstance" of custom nbt of attacker
								if {_instanceAttacker} = {_instanceVictim}:
									DungeonDamageTaken(victim, attacker, damage, {_damageCause})
							set {_health1} to victim's health
							if boolean tag "ECTestEntity" of (custom nbt of victim) is not set:
								set {_idV} to string tag "Id" of custom nbt of {karta::%victim%}
								if damage > health of victim:
									set {damage::taken::%{kartaname::%victim%}%::%{_idV}%} to {damage::taken::%{kartaname::%victim%}%::%{_idV}%} + (damage - health of victim)
								else:
									set {damage::taken::%{kartaname::%victim%}%::%{_idV}%} to {damage::taken::%{kartaname::%victim%}%::%{_idV}%} + damage

	#if victim's name contains "<##ffa229>Dyniowy Zombie":
		#wait 1 tick
		#set the display name of victim to "<##ffa229>Dyniowy Zombie (%victim's health%/%victim's max health%)"
	#if victim's name contains "<##74abc4>Podwodny Straszyciel":
		#wait 1 tick
		#set the display name of victim to "<##74abc4>Podwodny Straszyciel (%victim's health%/%victim's max health%)"
	#if victim's name contains "<##bababa>Opętany Holo Zwierzak":
		#wait 1 tick
		#set the display name of victim to "<##bababa>Opętany Holo Zwierzak (%victim's health%/%victim's max health%)"
	#if victim's name contains "<##fa7d7d>Imitacja Goshy":
		#wait 1 tick
		#set the display name of victim to "<##fa7d7d>Imitacja Goshy (%victim's health%/%victim's max health%)"
	#if victim's name contains "<##ededed>Widmowy Wierzchowiec":
		#wait 1 tick
		#set the display name of victim to "<##ededed>Widmowy Wierzchowiec (%victim's health%/%victim's max health%)"
	#if victim's name contains "<##2375e8>Naginacz Rzeczywistości":
		#wait 1 tick
		#set the display name of victim to "<##2375e8>Naginacz Rzeczywistości (%victim's health%/%victim's max health%)"
	#if victim's name contains "&aTarget Dummy":
	#	wait 1 tick
	#	set the name of victim to "&aTarget Dummy &7[&c&l♥&a&l%((victim's health/victim's max health)/100)%%%&7]"

	#if victim's name contains "<##a6a6a6>&lDalekosiężny Strzelec":
	#	wait 1 tick
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "%{_na}% &3&lLVL&7) <##a6a6a6>&lDalekosiężny Strzelec &f(%victim's health%/%victim's max health%)"
	#if victim's name contains "<##4c7ca1>&lPodstępna Kałamarnica":
	#	wait 1 tick
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "%{_na}% &3&lLVL&7) <##4c7ca1>&lPodstępna Kałamarnica &f(%victim's health%/%victim's max health%)"
	#if victim's name contains "<##446b38>&lCiernisty Zombie":
	#	wait 1 tick
	#	set metadata value "LastDamageCause" of attacker to "<##446b38>Ciernie"
	#	set {lastdmgcauselore::%attacker%::*} to "&7Odbija 10%% otrzymywanych obrażeń"
	#	make victim damage the attacker by 2*(0.1*damage)
	#	play sound "enchant.thorns.hit" with volume 2 and pitch 1 at attacker
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "%{_na}% &3&lLVL&7) <##446b38>&lCiernisty Zombie &f(%victim's health%/%victim's max health%)"
	#if victim's name contains "<##4c7ca1>&lMumia":
	#	wait 1 tick
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "%{_na}% &3&lLVL&7) <##4c7ca1>&lMumia &f(%victim's health%/%victim's max health%)"
	#if victim's name contains "<##c7aa5b>&lRuchomy Piasek":
	#	wait 1 tick
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "%{_na}% &3&lLVL&7) <##c7aa5b>&lRuchomy Piasek &f(%victim's health%/%victim's max health%)"
	#if victim's name contains "<##9221cc>Imprezowa":
	#	remove attacker from {asyst::%victim%::*}
	#	add uuid of attacker to {asyst::%victim%::*}
	#	wait 1 tick
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "&a&l%{_na}% LVL<##006415>) <##9221cc>Imprezowa <##e44ecd>Imitacja <##ff66fe>Goshy <##006415>(&a%victim's health%/&a%victim's max health%<##006415>)"
	#if victim's name contains "<##c3bc09>Wystrzałowa":
	#	remove attacker from {asyst::%victim%::*}
	#	add uuid of attacker to {asyst::%victim%::*}
	#	wait 1 tick
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "&a&l%{_na}% LVL<##006415>) <##c3bc09>Wystrzałowa <##d8d122>Owca <##006415>(&a%victim's health%/&a%victim's max health%<##006415>)"
	#if victim's name contains "<##8c929c>Ożywiony":
	#	remove attacker from {asyst::%victim%::*}
	#	add uuid of attacker to {asyst::%victim%::*}
	#	wait 1 tick
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "&a&l%{_na}% LVL<##006415>) <##8c929c>Ożywiony Target Dummy <##006415>(&a%victim's health%/&a%victim's max health%<##006415>)"
	#if victim's name contains "<##fc7703>Iluzjonista":
	#	remove attacker from {asyst::%victim%::*}
	#	add uuid of attacker to {asyst::%victim%::*}
	#	wait 1 tick
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "&a&l%{_na}% LVL<##006415>) <##fc7703>Iluzjonista <##006415>(&a%victim's health%/&a%victim's max health%<##006415>)"
	#if victim's name contains "<##e6e6e6>Głodna Lama":
	#	remove attacker from {asyst::%victim%::*}
	#	add uuid of attacker to {asyst::%victim%::*}
	#	wait 1 tick
	#	set {_n::*} to victim's name split at " "
	#	set {_na} to first element of {_n::*}
	#	set {_na2} to 2nd element of {_n::*}
	#	set the display name of victim to "&a&l%{_na}% LVL<##006415>) <##e6e6e6>Głodna Lama <##006415>(&a%victim's health%/&a%victim's max health%<##006415>)"
	#if {_wytrm} is set:
	#	wait 5 seconds
	#	set {wytrzymalosc::%victim%} to {_wytrm}
on entity knockback:
	if knockback attacker is a player:
		if boolean tag "ECBoss" of custom nbt of knockback victim is set:
			cancel event
	if knockback victim's name contains "&aTarget Dummy":
		cancel event

function Heartbeat(p: entity):
	while (max health of {_p})*0.3 > health of {_p}:
		if {_p}'s gamemode is survival or adventure:
			play sound "misc.heartbeat1" with volume 5 and pitch 0 to {_p}
		wait 5 seconds

on player interact on entity:
	if metadata value "ECEngaged" of player is set:
		set {_entity} to event-entity
		if any:
			metadata value "Lava Technique Stacks%player%" of {_entity} is set
			metadata value "Garrote%player%" of {_entity} is set
			metadata value "Night Slash Vulnerability%player%" of {_entity} is set
		then:
			cancel event

on entity target:
	if target is a player:
		if boolean tag "ECMob" of custom nbt of event-entity is set:
			set {_x} to nearest player in radius 4 around event-entity
			if {_x} is set:
				if boolean tag "ECDungeonMob" of custom nbt of event-entity is set:
					if metadata value "DungeonInstance" of {_x} is set:
						set {_attackerInstance} to metadata value "DungeonInstance" of {_x}
						set {_victimInstance} to int tag "ECDungeonInstance" of custom nbt of event-entity
						if {_attackerInstance} = {_victimInstance}:
							if {_x} does not have invisibility:
								BodyMobPull({_x}, event-entity)
								loop all entities in radius 4 around event-entity:
									if loop-entity is not a player:
										if loop-entity is not event-entity:
											if boolean tag "ECMob" of custom nbt of loop-entity is set:
												if boolean tag "ECDungeonMob" of custom nbt of loop-entity is set:
													if metadata value "ECPulled" of loop-entity is not set:
														BodyMobPull({_x}, loop-entity)
							else:
								cancel event

				else if all:
					boolean tag "ECIslandEnemy" of custom nbt of event-entity is true
					metadata value "IslandExpeditionInstance" of {_x} is set
				then:
					set {_attackerInstance} to metadata value "IslandExpeditionInstance" of {_x}
					set {_victimInstance} to metadata value "IslandExpeditionInstance" of event-entity
					if {_victimInstance} is not set:
						set {_victimInstance} to string tag "IslandExpeditionInstance" of custom nbt of event-entity
					if {_attackerInstance} = {_victimInstance}:
						if {_x} does not have invisibility:
							IslandExpeditionBodyMobPull({_x}, event-entity)
							loop all entities in radius 4 around event-entity:
								if loop-entity is not a player:
									if loop-entity is not event-entity:
										if boolean tag "ECIslandEnemy" of custom nbt of loop-entity is true:
											if metadata value "ECPulled" of loop-entity is not set:
												IslandExpeditionBodyMobPull({_x}, loop-entity)
						else:
							cancel event
			else:
				cancel event

		if boolean tag "ECCantTarget" of custom nbt of event-entity is set:
			cancel event

	else if event-entity is zombie or skeleton:
		if target is a zombie or skeleton:
			cancel event
			
#on heal:
#	if {walka} is true:
#		if heal reason is satiated or regeneration:
#			cancel event
#		#if {ilumark::%player%} is true:
#			#set heal amount to heal amount * 2
#		loop all players:
#			display hologram "<##baff8c>%heal amount% heal" at player to loop-player for 0.75 seconds
#		wait 1 tick
#		set player's tab name to "&8[<##f75e5e>❤<##c8ff61>%player's health%&8] &f%player%"
#		#wait 3 ticks
#		#set player's tab name to "&8[<##f75e5e>❤<##c8ff61>%player's health%&8] &f%player%"
#on respawn:
	#if {walka} = true:
		#set player's tab name to "&8[<##f75e5e>❤<##c8ff61>%player's health%&8] &f%player% %{playerstatus::%player%}%"
	#else:
	#set player's tab name to "&8[<##7c7cff>&l%{poziom::%player%}%<##9494ff>&l⭐&8] &f%player%"
	#set {_name} to name of party of player
	#if metadata value "ECEngaged" of player is set:
	#	if {_name} is set:
	#		set the player's tab name to "&b[%{_name}%] &8(%{kolorek1::%player%}%&l%{poziom::%player%}%%{kolorek1::%player%}%&l⭐&8) &r%player's name% &a%player's health%&c❤"
	#	else:
	#		set the player's tab name to "&8(%{kolorek1::%player%}%&l%{poziom::%player%}%%{kolorek1::%player%}%&l⭐&8) &r%player's name% &a%player's health%&c❤"
	#else:
	#	if {_name} is set:
	#		set the player's tab name to "&b[%{_name}%] &8(%{kolorek1::%player%}%&l%{poziom::%player%}%%{kolorek1::%player%}%&l⭐&8) &r%player's name%"
	#	else:
	#		set the player's tab name to "&8(%{kolorek1::%player%}%&l%{poziom::%player%}%%{kolorek1::%player%}%&l⭐&8) &r%player's name%"

#on any move:
#	if {walka} is true:
#		if {arena} = "arenaburzy":
#			block under player is yellow carpet:
#				push the player upwards at speed 1
#				push the player forwards at speed 1
#				play sound "minecraft:block.ladder.break" with volume 3 and pitch 1 at player
#				stop
	
#do on damage do pvp			
#if {walka} is true:
	#	if victim is a player:
	#		if {ilumark::%victim%} is true:
	#			set damage to damage * 1.25
	#			set {ilumark::%victim%} to false
	#		if {bumbleblastredukcjaobrazen::%victim%} is true:
	#			set damage to damage * 0.9
	#		#set damage to damage - (({wytrzymalosc::%victim%}/100)*damage)
	#		if {critdmg::%victim%} is true:
	#			set {critdmg::%victim%} to false
	#			loop all players:
	#				display hologram "<##ff9e42>%damage% DMG" at victim to loop-player for 0.75 seconds
	#			wait 1 tick 
	#			set victim's tab name to "&8[<##f75e5e>❤<##c8ff61>%victim's health%&8] &f%victim%"
	#		if {tarczavar::%victim%} = true:
	#			loop all players:
	#				display hologram "<##d6dcff>%damage% tarcza" at victim to loop-player for 0.75 seconds
	#			wait 1 tick 
	#			set victim's tab name to "&8[<##f75e5e>❤<##c8ff61>%victim's health%&8] &f%victim%"
	#		else:
	#			loop all players:
	#				display hologram "<##f5aef0>%damage% dmg" at victim to loop-player for 0.75 seconds
	#			wait 1 tick 
	#			set victim's tab name to "&8[<##f75e5e>❤<##c8ff61>%victim's health%&8] &f%victim%"
	#		if {un::%victim%} is true:
	#			set {un::%victim%} to false
	#			loop all players:
	#				display hologram "<##7d90fa>UNIK" at victim to loop-player for 0.75 seconds
	#			wait 1 tick 
	#			set victim's tab name to "&8[<##f75e5e>❤<##c8ff61>%victim's health%&8] &f%victim%"
	#	if attacker is a player:
	#		if victim is a player:
	#			#add damage to {zadanydmg::%attacker%}
	#			if {karta::%attacker%} = "Bumble Blast":
	#				add damage to {bumbleblastzadanydmg::%attacker%}
	#			if {karta::%attacker%} = "Pop Fizz":
	#				add damage to {popfizzzadanydmg::%attacker%}
	#			if {karta::%attacker%} = "Spotlight":
	#				add damage to {spotlightzadanydmg::%attacker%}