function TDSpawnTurret(p: player, turretName: string, radius: number):
    spawn 1 pig at location 0.5 above targetPlatformTowerDefence({_p}, 100)
    set {_turret} to last spawned pig
    set {_uuid} to uuid of {_p}
    add nbt from "{Invulnerable:1b,Silent:1b}" to nbt of {_turret}
    set boolean tag "TowerDefenceTurret" of custom nbt of {_turret} to true
    set {_p} to potion effect of slowness of tier 20 without particles for 1 day
    add {_p} to potion effects of last spawned pig
    set long tag "TurretRadius" of custom nbt of {_turret} to {_radius}
    set string tag "TurretOwner" of custom nbt of {_turret} to {_uuid}
    set {_loc} to location of {_turret}
    increase y-coordinate of {_loc} by 1.55
    spawn 1 armor stand at {_loc} with nbt from "{Marker:1b,Invulnerable:1b,Invisible:1b}"
    set {_titleUuid} to uuid of last spawned armor stand
    set display name of last spawned armor stand to "&e<Rank 1>"
    set string tag "TowerTitle" of custom nbt of {_turret} to {_titleUuid}
    play sound "entity.evoker.cast_spell" with volume 3 and pitch 2 at {_loc}
    if {_turretName} = "Ghazan":
        towerDefenceGhazanTurret({_turret})
    else if {_turretName} = "Graves":
        towerDefenceGravesTurret({_turret})

on inventory click:
    if player's current inventory = metadata tag "TDTurretCatalogue" of player:
        cancel event
        if index of clicked slot = 0:
            TDSpawnTurret(player, "Ghazan", 5.5)
        else if index of clicked slot = 1:
            TDSpawnTurret(player, "Graves", 9)
        close player's inventory
on rightclick:
    if player's name = "Pehrek":
        if player's tool = golden shovel named "TD Test":
            set {_loc} to location(-617.5, 96.5, 530.5, world "areny")
            spawn 1 adult sheep at {_loc}
            set {_mob} to last spawned sheep
            disguise {_mob} as zombie
            set max health of {_mob} to 2
            heal {_mob}
            set the display name of {_mob} to "&fZombie"
            set boolean tag "TowerDefenceMob" of custom nbt of last spawned sheep to true
            set {_locTarget} to location(-643.5, 96.5, 514.5, world "areny")
            towerDefencePathfind({_mob}, {_locTarget})
            mobHealthBarSpawn({_mob})
            clear {_mob}'s target
            #Players have a special options panel or an item they can use to change the displayed title of the select or ALL turrets in range
            #Titles can be rank, upgrade, masteery level, or amount of mob kills
        else if player's tool = book named "TD Turret Catalogue":
            if targetPlatformTowerDefence(player, 100) is set:
                play sound "item.book.page_turn" with volume 3 and pitch 0.5 at player
                set metadata value "TDTurretBlock" of player to {_block}
                set metadata tag "TDTurretCatalogue" of player to chest inventory with 6 rows named "Tower Defense Turret Catalogue"
                set {_wo} to metadata tag "TDTurretCatalogue" of player
                set slot 53 of {_wo} to blaze rod named "&fNext Page" with lore "&7Click here to navigate to%nl%&7the next page."
                set slots (integers between 46 and 52) of {_wo} to black stained glass pane named " "
                set slot 45 of {_wo} to barrier named "&cClose Panel" with lore "&7Click here to close this panel."
                set {_head} to playerHead("ewogICJ0aW1lc3RhbXAiIDogMTU5MDU4Mzk1NjMzNSwKICAicHJvZmlsZUlkIiA6ICI5MWYwNGZlOTBmMzY0M2I1OGYyMGUzMzc1Zjg2ZDM5ZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJTdG9ybVN0b3JteSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS80ZDBhMzk3MTM1Y2E5YTlhODBhN2Y2MzNjNGFhMmQ0MTZkZDRiZDU1OWM4ZThmN2QzZDQyMjE2MzJkNmY3ZmZkIgogICAgfQogIH0KfQ")
                set slot 0 of {_wo} to {_head} named "&fGhazan" with lore "&fLava Burst%nl%&7Ramping damage ability."
                set {_head} to playerHead("ewogICJ0aW1lc3RhbXAiIDogMTcwMjQ0OTkyMDQxOSwKICAicHJvZmlsZUlkIiA6ICI4NmRlYmE5ZjBjNTI0MTA0YWFkMjUyOTdhMTAzNjFmNCIsCiAgInByb2ZpbGVOYW1lIiA6ICJFc2hlSG9yY2hhdGEiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTg5MjBlYTBmMmEwZmY4NzI3MTliZTU5MDIzN2QxNzBmNjk5ZDZlZjFiZmI3NzVjZjU5NjRhNTk3YWZjOWJkNiIKICAgIH0KICB9Cn0")
                set slot 1 of {_wo} to {_head} named "&fGraves" with lore "&fDouble Barrelled Gun%nl%&7Shoots high-damage bullets at two enemies."
                open {_wo} to player

            #Ghazan paths = rain of lava = shoot a couple rain of lava bursts at nearby enemies
            #other path = shoot more pwerful single target lava bursts and faster
        else if player's tool = diamond shovel named "TD Test Cresselia":
            spawn 1 pig at location 0.5 above target block of player
            set {_turret} to last spawned pig
            add nbt from "{Invulnerable:1b,Silent:1b}" to nbt of last spawned pig
            set boolean tag "TowerDefenceTurret" of custom nbt of last spawned pig to true
            set {_p} to potion effect of slowness of tier 20 without particles for 1 day
            add {_p} to potion effects of last spawned pig
            set long tag "TurretRadius" of custom nbt of last spawned pig to 4
            towerDefenceCresseliaTurret(last spawned pig)
            set string tag "TurretOwner" of custom nbt of last spawned pig to uuid of player
            set {_loc} to location of last spawned pig
            increase y-coordinate of {_loc} by 1.55
            spawn 1 armor stand at {_loc} with nbt from "{Marker:1b,Invulnerable:1b,Invisible:1b}"
            set {_titleUuid} to uuid of last spawned armor stand
            set display name of last spawned armor stand to "&e<Rank 1>"
            set string tag "TowerTitle" of custom nbt of {_turret} to {_titleUuid}
            #Cresselia paths dps starfall path (global range) or supportive paths with innervate resetting attack cd
        else if player's tool = diamond shovel named "TD Test Zed":
            if targetPlatformTowerDefence(player, 100) is set:
                spawn 1 pig at location 0.5 above targetPlatformTowerDefence(player, 100)
            play sound "entity.evoker.cast_spell" with volume 3 and pitch 2 to player
            set {_turret} to last spawned pig
            set {_turret}'s held item to iron ingot
            add nbt from "{Invulnerable:1b,Silent:1b}" to nbt of last spawned pig
            set boolean tag "TowerDefenceTurret" of custom nbt of last spawned pig to true
            set {_p} to potion effect of slowness of tier 20 without particles for 1 day
            add {_p} to potion effects of last spawned pig
            set long tag "TurretRadius" of custom nbt of last spawned pig to 3
            towerDefenceZedTurret(last spawned pig, "Zed")
            set string tag "TurretOwner" of custom nbt of last spawned pig to uuid of player
            set {_loc} to location of last spawned pig
            increase y-coordinate of {_loc} by 1.55
            spawn 1 armor stand at {_loc} with nbt from "{Marker:1b,Invulnerable:1b,Invisible:1b}"
            set {_titleUuid} to uuid of last spawned armor stand
            set display name of last spawned armor stand to "&e<Rank 1>"
            set string tag "TowerTitle" of custom nbt of {_turret} to {_titleUuid}

            spawn 1 pig at location 1 right of location 0.5 above target block of player
            play sound "entity.evoker.cast_spell" with volume 3 and pitch 2 to player
            set {_turret} to last spawned pig
            set {_turret}'s held item to iron ingot
            add nbt from "{Invulnerable:1b,Silent:1b}" to nbt of last spawned pig
            set boolean tag "TowerDefenceTurret" of custom nbt of last spawned pig to true
            set {_p} to potion effect of slowness of tier 20 without particles for 1 day
            add {_p} to potion effects of last spawned pig
            set long tag "TurretRadius" of custom nbt of last spawned pig to 3
            towerDefenceZedTurret(last spawned pig, "Shadow")
            set string tag "TurretOwner" of custom nbt of last spawned pig to uuid of player
            set {_loc} to location of last spawned pig
            increase y-coordinate of {_loc} by 1.55
            spawn 1 armor stand at {_loc} with nbt from "{Marker:1b,Invulnerable:1b,Invisible:1b}"
            set {_titleUuid} to uuid of last spawned armor stand
            set display name of last spawned armor stand to "&e<Rank 1>"
            set string tag "TowerTitle" of custom nbt of {_turret} to {_titleUuid}
            set boolean tag "TurretZedShadow" of custom nbt of {_turret} to true

        else if player's tool = iron shovel named "TD Test":
           # set lore of player's tool to "&7Ghazan blah blah blah.%nl% %nl%&7Obtained from the Stellar Chest.%nl%&7Rarity: &d★★★★★"
            if metadata value "TowerDefenceTargetTurret" of player is set:
                set {_turret} to metadata value "TowerDefenceTargetTurret" of player parsed as entity
                if boolean tag "TurretZedShadow" of custom nbt of {_turret} is set:
                    teleport {_turret} to location 0.5 above target block of player
                    set {_title} to (string tag "TowerTitle" of custom nbt of {_turret}) parsed as entity
                    set {_loc} to location of {_turret}
                    increase {_loc}'s y-coordinate by 1.55
                    teleport {_title} to {_loc}
                    play sound "entity.item.pickup" with volume 3 and pitch 1 to player
        else if player's tool = wooden shovel named "TD Test":
            if player is sneaking:
                clear metadata value "TowerDefenceTargetTurret" of player
            else:
                set {_target} to targetTurret(player, 100)
                if {_target} is set:
                    if string tag "TurretOwner" of custom nbt of {_target} = uuid of player:
                        set metadata value "TowerDefenceTargetTurret" of player to uuid of {_target}
                        towerDefenceSelectedTowerRange(player, {_target})
                        play sound "item.bottle.fill_dragonbreath" with volume 3 and pitch 1.2 to player
                        play sound "entity.item.pickup" with volume 3 and pitch 1.2 to player
        else if player's tool = stone shovel named "TD Test":
            set {_target} to targetTurret(player, 100)
            if {_target} is set:
                if string tag "TurretOwner" of custom nbt of {_target} = uuid of player:
                    play sound "entity.enderman.hurt" with volume 3 and pitch 2 to player
                    play sound "entity.item.break" with volume 3 and pitch 1.2 to player
                    set string tag "TowerTitle" of custom nbt of last spawned pig to uuid of last spawned armor stand
                    teleport {_target} to location(-1228, -100, -1792, world "world")
                    set {_title} to (string tag "TowerTitle" of custom nbt of {_target}) parsed as entity
                    teleport {_title} to location(-1228, -100, -1792, world "world")
                    kill {_target}
                    kill {_title}

on entity target:
    if boolean tag "TowerDefenceMob" of custom nbt of event-entity is set:
        cancel event
    else if boolean tag "TowerDefenceTurret" of custom nbt of event-entity is set:
        cancel event

function targetPlatformTowerDefence(p: player, length: number) :: location:
    set {_x} to 0
    set {_l} to 0
    play sound "entity.chicken.egg" with volume 3 and pitch 1 at {_p}
    loop {_length} times:
        add 1 to {_x}
        add 0.25 to {_l}
        set {_rg%{_x}%} to location {_l} meters infront of {_p}
        set {_rg%{_x}%} to location 2 meters above {_rg%{_x}%}
        draw 1 witch particle at {_rg%{_x}%}
        loop blocks in radius 2 around {_rg%{_x}%}:
            if boolean tag "TDTurretPlatform" of custom nbt of loop-block is set:
                set {_block} to loop-block
                return {_block}
                stop
           
    return {_block}

on place of stripped oak log:
    if name of player's tool = "&fBlok Specjalny":
        set boolean tag "TDTurretPlatform" of custom nbt of event-block to true



function towerDefencePathfind(e: entity, loc: location):
    make {_e} pathfind to {_loc}
    while distance between {_e} and {_loc} > 2:
        stop loop if {_e} is not alive
        make {_e} pathfind to {_loc}
        wait 0.5 seconds
    if {_e} is alive:
        broadcast "Target reached"
        kill {_e}
 
function mobHealthBarSpawn(e: entity):
    set {_loc} to location of {_e}
    spawn 1 armor stand at {_loc} with nbt from "{Marker:1b,Invulnerable:1b,Invisible:1b}"
    set display name of last spawned armor stand to "&a|||||||||| &f(100%%)"
    set string tag "ECTextAbove" of custom nbt of {_e} to uuid of last spawned armor stand
    set long tag "ECModelHeight" of custom nbt of {_e} to 1.7

function towerDefenceTurretTarget(e: entity, type: string, radius: number) :: entity:
    if {_type} = "close":
        loop (entities in radius {_radius} around {_e}) sorted by distance from {_e}:
            if boolean tag "TowerDefenceMob" of custom nbt of loop-entity is set:
                set {_target} to loop-entity
                stop loop
    return {_target}

function towerDefenceTurretTargets(e: entity, type: string, radius: number, amount: integer) :: entities:
    set {_targets::*} to ""
    if {_type} = "close":
        loop (entities in radius {_radius} around {_e}) sorted by distance from {_e}:
            if boolean tag "TowerDefenceMob" of custom nbt of loop-entity is set:
                stop loop if size of {_targets::*} = {_amount}
                set {_targets::*} to {_targets::*} and loop-entity              
    return {_targets::*}

function towerDefenceDamage(e: entity, target: entity, damage: number):
    set {_target}'s last damage cause to sweep attack
    make {_e} damage {_target} by {_damage}*2
    UpdateMobHealthBar({_target})

function towerDefenceSelectedTowerRange(p: player, e: entity):
    while metadata value "TowerDefenceTargetTurret" of {_p} = uuid of {_e}:
        if {_e} is not alive:
            clear metadata value "TowerDefenceTargetTurret" of {_p}
            stop loop
        set {_radius} to (long tag "TurretRadius" of custom nbt of {_e})
        if {_radius} is not a number:
            set {_radius} to {_radius} parsed as number
        set {_shape} to circle with radius {_radius}
        set particle of {_shape} to dust particle using dustOption(cyan, 2)
        draw {_shape} at {_e}
        wait 1 second

function targetTurret(p: player, length: number) :: entity:
    set {_x} to 0
    set {_l} to 0
    loop {_length} times:
        add 1 to {_x}
        add 0.25 to {_l}
        set {_rg%{_x}%} to location {_l} meters infront of {_p}
        set {_rg%{_x}%} to location 2 meters above {_rg%{_x}%}
        draw 1 witch particle at {_rg%{_x}%}
        loop entities in radius 3 around {_rg%{_x}%}:
            if boolean tag "TowerDefenceTurret" of custom nbt of loop-entity is set:
                set {_entity} to loop-entity
                return {_entity}
                stop
       
    return {_entity}

function towerDefenceGhazanTurret(e: entity):
    disguise {_e} as "Ghazan"
    set {_radius} to long tag "TurretRadius" of custom nbt of {_e}
    if {_radius} is not a number:
        set {_radius} to {_radius} parsed as number
    while {_e} is alive:
        set {_target} to towerDefenceTurretTarget({_e}, "close", {_radius})
        if {_target} is alive:
            make {_e} look at {_target}
            make {_e} swing their hand
            set {_shape} to a line from {_e} to {_target}
            set particle of {_shape} to lava particle
            draw {_shape} at {_e}
            towerDefenceDamage({_e}, {_target}, 2)
            play sound "skill.ghazan.lava_burst_cast" with volume 4 and pitch 1 at {_e}
            wait 0.4 seconds
            play sound "skill.ghazan.lava_burst_impact" with volume 4 and pitch 1 at {_target}
            wait 4.6 seconds
        else:
            wait 1 tick

function towerDefenceGravesTurret(e: entity):
    disguise {_e} as "Graves"
    set metadata value "GravesTurretBullets" of {_e} to 2
    set {_radius} to long tag "TurretRadius" of custom nbt of {_e}
    if {_radius} is not a number:
        set {_radius} to {_radius} parsed as number
    set {_maxTargets} to 2
    while {_e} is alive: 
        set {_targetCount} to 0
        set {_targets::*} to ""
        loop (entities in radius {_radius} around {_e}) sorted by distance from {_e}:
            if boolean tag "TowerDefenceMob" of custom nbt of loop-entity is set:
                stop loop if {_targetCount} = {_maxTargets}
                add 1 to {_targetCount}
                add loop-entity to {_targets::*}
        if {_targets::*} != "":
            play sound "skill.graves.gunshot" with volume 4 and pitch 1 at {_e}
            loop {_targets::*}:
                make {_e} look at loop-value
                make {_e} swing their hand
                set {_shape} to a line from {_e} to loop-value
                set particle of {_shape} to smoke
                draw {_shape} at {_e}
                set {_shape} to a line from {_e} to loop-value
                set particle of {_shape} to item particle using gold block
                draw {_shape} at {_e}
                towerDefenceDamage({_e}, loop-value, 3) 
            wait 3 seconds  
            play sound "skill.graves.gunshot_reload" with volume 4 and pitch 1 at {_e}              
        else:
            wait 1 tick

function towerDefenceZedTurret(e: entity, type: string):
    if {_type} = "Zed":
        disguise {_e} as "Zed"
    else:
        disguise {_e} as "ZedShadow"
    while {_e} is alive:
        set {_radius} to long tag "TurretRadius" of custom nbt of {_e}
        if {_radius} is not a number:
            set {_radius} to {_radius} parsed as number
        set {_target} to towerDefenceTurretTarget({_e}, "close", {_radius})
        if {_target} is alive:
            make {_e} look at {_target}
            make {_e} swing their hand
            towerDefenceDamage({_e}, {_target}, 1)
            play sound "skill.fury_warrior.slash" with volume 4 and pitch 1 at {_e}
            wait 2 seconds
        else:
            wait 1 tick
#For first, last targeting, assign instance and the goal coordinates for each instance
#Then add mobs to a list and iterate through it to find the closest mob to the goal on turret target