

on region enter:
	if "%region%" contains "PortalDarkMagic1":
		set {_loc} to location(264, 72, 268, world "areny")
		set yaw of {_loc} to 90
		teleport the player to {_loc}
		play sound "entity.enderman.teleport" with volume 5 and pitch 0.2 to player
		set player's yaw to 90
		stop
	if "%region%" contains "PortalDarkMagic2":
		teleport the player to location(200, 84, 315, world "areny")
		play sound "entity.enderman.teleport" with volume 5 and pitch 0.2 to player
		stop
	if "%region%" contains "PortalDarkMagic3":
		set {_loc} to location(237, 95, 272, world "areny")
		set yaw of {_loc} to 37.5
		teleport the player to {_loc}
		play sound "entity.enderman.teleport" with volume 5 and pitch 0.2 to player
		stop
	if "%region%" contains "PortalDarkMagic4":
		teleport the player to location(221, 80, 243, world "areny")
		play sound "entity.enderman.teleport" with volume 5 and pitch 0.2 to player
		stop