variables:
	{poziom::%player%} = 0
	{pseudonim::%player%} = player
on chat:
	if {chatstop} is true:
		cancel event
	else:
		if message contains ":smiling_face_with_3_hearts:" or ":3hearts:":
			replace all ":smiling_face_with_3_hearts:" and ":3hearts:" with "" in message
		if message contains ":sunglasses:":
			replace all ":sunglasses:" with "" in message
		if message contains ":innocent:" or ":halo:":
			replace all ":innocent:" and ":halo:" with "" in message
		if message contains ":grin:":
			replace all ":grin:" with "" in message
		if message contains ":bangbang:":
			replace all ":bangbang:" with "" in message
		if message contains ":blush:":
			replace all ":blush:" with "" in message
		if message contains ":drooling_face:" or ":drool:":
			replace all ":drooling_face:" and ":drool:" with "" in message
		if message contains ":exploding_head:" or ":explode:":
			replace all ":exploding_head:" and ":explode:" with "" in message
		if message contains ":eyes:":
			replace all ":eyes:" with "" in message
		if message contains ":face_with_hand_over_mouth:", ":hand_over_mouth:" or ":hand_mouth:":
			replace all ":face_with_hand_over_mouth:", ":hand_over_mouth:" and ":hand_mouth:" with "" in message
		if message contains ":face_with_monocle:" or ":monocle:":
			replace all ":face_with_monocle:" and ":monocle:" with "" in message
		if message contains ":face_with_raised_eyebrow:" or ":eyebrow:":
			replace all ":face_with_raised_eyebrow:" and ":eyebrow:" with "" in message
		if message contains ":fingers_crossed:":
			replace all ":fingers_crossed:" with "" in message
		if message contains ":flushed:":
			replace all ":flushed:" with "" in message
		if message contains ":frowning:":
			replace all ":frowning:" with "" in message
		if message contains ":grimacing:":
			replace all ":grimacing:" with "" in message
		if message contains ":grinning:":
			replace all ":grinning:" with "" in message
		if message contains ":heart_eyes:":
			replace all ":heart_eyes:" with "" in message
		if message contains ":kiss:":
			replace all ":kiss:" with "" in message
		if message contains ":kissing_heart:" or ":kissing_face:":
			replace all ":kissing_heart:" and ":kissing_face:" with "" in message
		if message contains ":kissing:":
			replace all ":kissing:" with "" in message
		if message contains ":money_mouth:":
			replace all ":money_mouth:" with "" in message
		if message contains ":nauseated_face:" or ":nauseated:":
			replace all ":nauseated_face:" and ":nauseated:" with "" in message
		if message contains ":ok_hand:" or ":ok:":
			replace all ":ok_hand:" and ":ok:" with "" in message
		if message contains ":partying_face:" or ":party:":
			replace all ":partying_face:" and ":party:" with "" in message
		if message contains ":pensive:":
			replace all ":pensive:" with "" in message
		if message contains ":pray:":
			replace all ":pray:" with "" in message
		if message contains ":relieved:":
			replace all ":relieved:" with "" in message
		if message contains ":rolling_eyes:":
			replace all ":rolling_eyes:" with "" in message
		if message contains ":skull:":
			replace all ":skull:" with "" in message
		if message contains ":sleepy:":
			replace all ":sleepy:" with "" in message
		if message contains ":slight_smile:":
			replace all ":slight_smile:" with "" in message
		if message contains ":smile:":
			replace all ":smile:" with "" in message
		if message contains ":smiling_face_with_tear:" or ":smiling_tear:":
			replace all ":smiling_face_with_tear:" and ":smiling_tear:" with "" in message
		if message contains ":smirk:":
			replace all ":smirk:" with "" in message
		if message contains ":sob:":
			replace all ":sob:" with "" in message
		if message contains ":sparkles:":
			replace all ":sparkles:" with "" in message
		if message contains ":star_struck:":
			replace all ":star_struck:" with "" in message
		if message contains ":sweat:":
			replace all ":sweat:" with "" in message
		if message contains ":thinking:":
			replace all ":thinking:" with "" in message
		if message contains ":thumbsdown:" or ":-1:":
			replace all ":thumbsdown:" and ":-1:" with "" in message
		if message contains ":thumbsup:" or ":+1:":
			replace all ":thumbsup:" and ":+1:" with "" in message
		if message contains ":upside_down:":
			replace all ":upside_down:" with "" in message
		if message contains ":wink:":
			replace all ":wink:" with "" in message
		if message contains ":yum:":
			replace all ":yum:" with "" in message
		if message contains ":xdd:":
			replace all ":xdd:" with "" in message
		send " [%{poziom::%player%}% Lvl] %player%: %message%" to console
		set message to formatted message
		set {_data} to data()
		set {_month} to dataConversion()
		log "%{_data}% [%{poziom::%player%}% Lvl] <%player%> %message%" to "logi/czat/.general chat/%{_month}%/czat %{datatydzien}%-%{datatydzien2}%.log"
		log "%{_data}% [%{poziom::%player%}% Lvl] <%player%> %message%" to "logi/czat/%player%/%player%.log"
		if {kanal::%player%} = "admin":
			if player's name = "Pehrek" or "nishikoru":
				loop all players:
					if loop-player's name = "Pehrek" or "nishikoru":
						cancel event
						send "&8[<##e8002b>ADMIN&7/<##6500e8>TEST&8] &8[<##ff1cbf>%{poziom::%player%}%&8] <<##ac93cc>%{pseudonim::%player%}%&8> &f%message%" to loop-player
			else:
				send "&8[<##e8002b>ADMIN&7/<##6500e8>TEST&8] &7Wybacz, ten kanał jest dostępny tylko dla administratorów." to player
		else if {kanal::%player%} is not "admin":
			if {kanal::%player%} is set:
					cancel event
					loop all players:
						if {kanal::%loop-player%} = {kanal::%player%}:
							if {kolorek::%player%} is set:
								send "<##fcbde2>[%{kanal::%player%}%<##fcbde2>] [%{poziom::%player%}%<##fcbde2>] <%{kolorek::%player%}%%{pseudonim::%player%}%<##fcbde2>> &f%message%" to loop-player
							else:
								send "<##fcbde2>[%{kanal::%player%}%<##fcbde2><##fcbde2>] [%{poziom::%player%}%<##fcbde2>] <%{pseudonim::%player%}%<##fcbde2>> &f%message%" to loop-player
		else:
			set the chat format to "&8[%{kolorek::%player%}%%{poziom::%player%}% Lvl&8] <%{kolorek::%player%}%%{pseudonim::%player%}%&8> &f%message%"
		loop all players:
			if {czat.dzwieki::%loop-player%} is true:
				play sound "block.wooden_button.click_on" with volume 5 and pitch 2 to loop-player
			if message contains loop-player's name or {pseudonim::%loop-player%}:
				play sound "block.note_block.cow_bell" with volume 5 and pitch 0 to loop-player
command /ustawkolorek [<text>]:
	aliases: /kolorek, /setcolor
	trigger:
		if {poziom::%player%} is bigger than or equal to 100:
			set {_f} to char at 0 in arg-1
			if {_f} = "##":
				if length of arg-1 = 7:
					loop 7 times:
						if character at loop-number in arg-1 = "0" or "1" or "2" or "3" or "4" or "5" or "6" or "7" or "8" or "9" or "a" or "b" or "c" or "d" or "e" or "f":
							add 1 to {_yes}
					if {_yes} = 6:
						set {kolorek::%player%} to formatted "<%arg-1%>"
						if {language::%player%} = "English":
							send formatted "&8[&6Earthcraft&8] &7Successfully set your chat color. (%{kolorek::%player%}%%{pseudonim::%player%}%&7)" to player
						else:
							send formatted "&8[&6Earthcraft&8] &7Pomyślnie ustawiono kolorek. (%{kolorek::%player%}%%{pseudonim::%player%}%&7)" to player
						play sound "entity.player.levelup" with volume 3 and pitch 1 to player
					else:
						if {language::%player%} = "English":
							send "&8[&6Earthcraft&8] &7Argument must be written in &6##ffffff &7format." to player
						else:
							send "&8[&6Earthcraft&8] &7Wiadomość musi zostać napisana w formacie &6##ffffff&7." to player
						play sound "block.chest.close" with volume 3 and pitch 0 to player
				else:
					if {language::%player%} = "English":
						send "&8[&6Earthcraft&8] &7Argument must be written in &6##ffffff &7format." to player
					else:
						send "&8[&6Earthcraft&8] &7Wiadomość musi zostać napisana w formacie &6##ffffff&7." to player
					play sound "block.chest.close" with volume 3 and pitch 0 to player
			else:
				if {language::%player%} = "English":
					send "&8[&6Earthcraft&8] &7Argument must be written in &6##ffffff &7format." to player
				else:
					send "&8[&6Earthcraft&8] &7Wiadomość musi zostać napisana w formacie &6##ffffff&7." to player
				play sound "block.chest.close" with volume 3 and pitch 0 to player
		else:
			if {language::%player%} = "English":
				send "&8[&6Earthcraft&8] &7You must be at least level 100 to set your chat color." to player
			else:
				send "&8[&6Earthcraft&8] &7Aby ustawić kolorek, musisz mieć przynajmniej setny poziom." to player
			play sound "block.chest.close" with volume 3 and pitch 0 to player
command /kanal [<text>]:
	aliases: /channel
	trigger:
		if arg-1 is "-", "clear", "off" or "":
			loop all players:
				if {kanal::%loop-player%} = arg-1:
					send "&8[<##bdd6fc>&lCZAT&8] <##bdd6fc>%player% &7opuścił/-a kanał." to loop-player
			clear {kanal::%player%}
			send "&8[<##bdd6fc>&lCZAT&8] &7Pomyślnie opuszczono kanał." to player
		else:
			set {kanal::%player%} to arg-1
			send "&8[<##bdd6fc>&lCZAT&8] &7Pomyślnie ustawiono kanał na <##bdd6fc>%arg-1%&7." to player
			loop all players:
				if {kanal::%loop-player%} = arg-1:
					send "&8[<##bdd6fc>&lCZAT&8] <##bdd6fc>%player% &7dołączył/-a do kanału." to loop-player
command /ustawteam [<player>] [<text>]:
	trigger:
		set {teamtag::%arg-1%} to arg-2
		broadcast "&7[<##693699>Earthcraft&7] <##9F05C5>&l%arg-1% <##9570DD>należy teraz do gildii <##693699>%arg-2%!"
command /chatstop:
	trigger:
		if {chatstop} is true:
			set {chatstop} to false
			broadcast "&7[<##693699>Earthcraft&7] <##9F05C5>&l%player% <##9570DD>włączył/-a czat!"
		else:
			set {chatstop} to true
			broadcast "&7[<##693699>Earthcraft&7] <##9F05C5>&l%player% <##9570DD>wyłączył/-a czat!"
command /pseudonim [<text>]:
	aliases: /nick, /nickname
	trigger:
		if arg-1 is "-", "", "usun" or "brak" or "clear" or "remove":
			set {pseudonim::%player%} to player's name
			broadcast "&7[<##693699>Earthcraft&7] <##9F05C5>&l%player%: <##9570DD>Usunięto pseudonim!"
		else:
			if length of arg-1 < 21:
				set {pseudonim::%player%} to arg-1
				loop all players:
					if {language::%loop-player%} = "English":
						send "&8[&6Earthcraft&8] &6&l%player%: &7Set nickname to &6%arg-1%&7!" to loop-player
					else:
						send "&8[&6Earthcraft&8] &6&l%player%: &7Ustawiono pseudonim jako &6%arg-1%&7!" to loop-player
			else:
				if {language::%player%} = "English":
					send "&cNickname can't be longer than 20 characters." to player
					play sound "block.glass.break" with volume 3 and pitch 2 to player
				else:
					send "&cPseudonim nie może być dłuższy niż 20 znaków." to player
					play sound "block.glass.break" with volume 3 and pitch 2 to player

on tab complete of "pseudonim" or "nick" or "nickname":
	set tab completions for position 1 to "-" and "" and "usun" and "brak" and "clear" and "remove"

on command:
	set {_data} to data()
	if command sender is console:
		set {_sender} to console
	if command sender is player:
		set {_sender} to player
	set {_month} to dataConversion()
	set {_full} to full command
	if {_sender} is not console:
		if {_full} does not contain "minecraft:fill":
			log "%{_data}% %{_sender}%: /%full command%" to "logi/komendy/%{_month}%/komendy %{datatydzien}%-%{datatydzien2}%.log"
	else:
		set {_banned::*} to "npc select 6630", "npc select 6632", "npc select 6633", "npc skin"
		if {_banned::*} does not contain {_full}:
			log "%{_data}% %{_sender}%: /%full command%" to "logi/komendy/%{_month}%/console %{datatydzien}%-%{datatydzien2}%.log"

function dataConversion() :: text:
	set {_data::*} to {datatydzien} split at "."
	replace all "01" in {_data::2} with "january"
	replace all "02" in {_data::2} with "february"
	replace all "03" in {_data::2} with "march"
	replace all "04" in {_data::2} with "april"
	replace all "05" in {_data::2} with "may"
	replace all "06" in {_data::2} with "june"
	replace all "07" in {_data::2} with "july"
	replace all "08" in {_data::2} with "august"
	replace all "09" in {_data::2} with "september"
	replace all "10" in {_data::2} with "october"
	replace all "11" in {_data::2} with "november"
	replace all "12" in {_data::2} with "december"
	return {_data::2}
	
command /admin:
	trigger:
		if player's name is "kapoonfleek" or "llamadegree":
			set {admin::%player%} to true
			set {admin::%target player%} to true

command /emotki:
	aliases: /symbole, /emotes, /symbols
	trigger:
		set {_book} to a written book
		set book author of {_book} to "Kapo"
		if {language::%player%} = "English":
			set book title of {_book} to "Emotes and Symbols"
			set {_a} to text component of "          EMOTES"
			set {_h} to text component of "          SYMBOLS"
			set {_i} to text component of "%nl%&f &0- Peridot%nl%&f &0- Ruby%nl%&f &0- Topaz%nl%&f &0- Pearl%nl%&f &0- Amethyst%nl%&f &0- Aquamarine%nl%&f &0- Opal%nl%&f &0- Tourmaline%nl%&f &0- Citrine%nl%&f &0- Jade%nl%&f &0- Sapphire%nl%&f &0- Aventurine%nl%&f &0- Klejnot"
			set {_j} to text component of "&f &0- Peridot Crystal%nl%&f &0- Ruby Crystal%nl%&f &0- Topaz Crystal%nl%&f &0- Pearl Crystal%nl%&f &0- Amethyst Crystal%nl%&f &0- Aquamarine Crystal%nl%&f &0- Opal Crystal%nl%&f &0- Tourmaline Crystal%nl%&f &0- Citrine Crystal%nl%&f &0- Jade Crystal%nl%&f &0- Sapphire Crystal"
			set {_k} to text component of "&f &0- Stardust%nl%&f &0- Star Shard%nl%&f &0- Beezooka%nl%&f &0- Flamethrower%nl%&f &0- Explosive Bubble%nl%&f &0- Night Slash%nl%&f &0- Frostbolt%nl%&f &0- Lava Burst"
		else:
			set book title of {_book} to "Emotki i Symbole"
			set {_a} to text component of "          EMOTKI"
			set {_h} to text component of "          SYMBOLE"
			set {_i} to text component of "%nl%&f &0- Perydot%nl%&f &0- Rubin%nl%&f &0- Topaz%nl%&f &0- Perła%nl%&f &0- Ametyst%nl%&f &0- Akwamaryn%nl%&f &0- Opal%nl%&f &0- Turmalin%nl%&f &0- Cytryn%nl%&f &0- Jadeit%nl%&f &0- Szafir%nl%&f &0- Awenturyn%nl%&f &0- Klejnot"
			set {_j} to text component of "&f &0- Kryształ Peryd.%nl%&f &0- Kryształ Rubinu%nl%&f &0- Kryształ Topazu%nl%&f &0- Kryształ Perły%nl%&f &0- Kryształ Ametys.%nl%&f &0- Kryształ Akwam.%nl%&f &0- Kryształ Opalu%nl%&f &0- Kryształ Turmal.%nl%&f &0- Kryształ Cytrynu%nl%&f &0- Kryształ Jadeitu%nl%&f &0- Kryształ Szafiru"
			set {_k} to text component of "&f &0- Stardust%nl%&f &0- Odłamek Gwiazdy%nl%&f &0- Pszczelozuka%nl%&f &0- Miotacz Płomieni%nl%&f &0- Wybuchowy Bąb.%nl%&f &0- Nocne Cięcie%nl%&f &0- Mroźny Pocisk%nl%&f &0- Wybuch Lawy"
		set {_b} to text component of "%nl%&f &0- :3hearts:,%nl%:smiling_face_with_3_hearts:%nl%&f &0- :sunglasses:%nl%&f &0- :innocent:, :halo:"
		set {_c} to text component of "%nl%&f &0- :grin:%nl%&f &0- :bangbang:%nl%&f &0- :blush:%nl%&f &0- :drooling_face:%nl%:drool:%nl%&f &0- :exploding_head:%nl%:explode%nl%&f &0- :eyes:"
		set {_d} to text component of "&f &0- :hand_mouth:%nl%:hand_over_mouth:%nl%:face_with_hand_over_mouth:%nl%&f &0- :monocle:%nl%:face_with_monocle:%nl%&f &0- :eyebrow:%nl%:face_with_raised_eyebrow:%nl%&f &0- :fingers_crossed:%nl%&f &0- :flushed:%nl%&f &0- :frowning:%nl%&f &0- :grimacing:%nl%&f &0- :grinning:"
		set {_e} to text component of "&f &0- :heart_eyes:%nl%&f &0- :kiss:%nl%&f &0- :kissing_heart%nl%:kissing_face:%nl%&f &0- :kissing:%nl%&f &0- :money_mouth:%nl%&f &0- :nauseated_face:%nl%:nauseated:%nl%&f &0- :ok_hand:, :ok:%nl%&f &0- :partying_face:%nl%:party:%nl%&f &0- :pensive:%nl%&f &0- :pray:%nl%&f &0- :relieved:"
		set {_f} to text component of "&f &0- :rolling_eyes:%nl%&f &0- :skull:%nl%&f &0- :sleepy:%nl%&f &0- :slight_smile:%nl%&f &0- :smile%nl%&f &0- :smiling_tear:%nl%:smiling_face_with_tear:%nl%&f &0- :smirk:%nl%&f &0- :sob:%nl%&f &0- :sparkles:%nl%&f &0- :star_struck:%nl%&f &0- :sweat:%nl%&f &0- :thinking:"
		set {_g} to text component of "&f &0- :thumbsdown:, :-1:%nl%&f &0- :thumbsup:, :+1:%nl%&f &0- :upside_down:%nl%&f &0- :wink:%nl%&f &0- :yum:%nl%&f &0- :xdd:"
		set {_a::*} to {_a}, {_b} and {_c}
		set {_b::*} to {_h} and {_i}
		set page 1 of book {_book} to {_a::*}
		set page 2 of book {_book} to {_d}
		set page 3 of book {_book} to {_e}
		set page 4 of book {_book} to {_f}
		set page 5 of book {_book} to {_g}
		set page 6 of book {_book} to {_b::*}
		set page 7 of book {_book} to {_j}
		set page 8 of book {_book} to {_k}
		give {_book} to player