
on async chat:
	set {_message} to "%async chat message%"
	if {chatstop} is true:
		cancel event
	else:
		if {_message} contains ":":
			replace all ":smiling_face_with_3_hearts:" and ":3hearts:" with "" in {_message}
			replace all ":sunglasses:" with "" in {_message}
			replace all ":innocent:" and ":halo:" with "" in {_message}
			replace all ":grin:" with "" in {_message}
			replace all ":bangbang:" with "" in {_message}
			replace all ":blush:" with "" in {_message}
			replace all ":drooling_face:" and ":drool:" with "" in {_message}
			replace all ":exploding_head:" and ":explode:" with "" in {_message}
			replace all ":eyes:" with "" in {_message}
			replace all ":face_with_hand_over_mouth:", ":hand_over_mouth:" and ":hand_mouth:" with "" in {_message}
			replace all ":face_with_monocle:" and ":monocle:" with "" in {_message}
			replace all ":face_with_raised_eyebrow:" and ":eyebrow:" with "" in {_message}
			replace all ":fingers_crossed:" with "" in {_message}
			replace all ":flushed:" with "" in {_message}
			replace all ":frowning:" with "" in {_message}
			replace all ":grimacing:" with "" in {_message}
			replace all ":grinning:" with "" in {_message}
			replace all ":heart_eyes:" with "" in {_message}
			replace all ":kiss:" with "" in {_message}
			replace all ":kissing_heart:" and ":kissing_face:" with "" in {_message}
			replace all ":kissing:" with "" in {_message}
			replace all ":money_mouth:" with "" in {_message}
			replace all ":nauseated_face:" and ":nauseated:" with "" in {_message}
			replace all ":ok_hand:" and ":ok:" with "" in {_message}
			replace all ":partying_face:" and ":party:" with "" in {_message}
			replace all ":pensive:" with "" in {_message}
			replace all ":pray:" with "" in {_message}
			replace all ":relieved:" with "" in {_message}
			replace all ":rolling_eyes:" with "" in {_message}
			replace all ":skull:" with "" in {_message}
			replace all ":sleepy:" with "" in {_message}
			replace all ":slight_smile:" with "" in {_message}
			replace all ":smile:" with "" in {_message}
			replace all ":smiling_face_with_tear:" and ":smiling_tear:" with "" in {_message}
			replace all ":smirk:" with "" in {_message}
			replace all ":sob:" with "" in {_message}
			replace all ":sparkles:" with "" in {_message}
			replace all ":star_struck:" with "" in {_message}
			replace all ":sweat:" with "" in {_message}
			replace all ":thinking:" with "" in {_message}
			replace all ":thumbsdown:" and ":-1:" with "" in {_message}
			replace all ":thumbsup:" and ":+1:" with "" in {_message}
			replace all ":upside_down:" with "" in {_message}
			replace all ":wink:" with "" in {_message}
			replace all ":yum:" with "" in {_message}
			replace all ":xdd:" with "" in {_message}
			replace all ":smil:" with "" in {_message}
			replace all ":cri:" with "" in {_message}
			replace all ":gasp:" with "" in {_message}
			replace all ":yay:" with "" in {_message}
			replace all ":co:" with "" in {_message}
			replace all ":hrm:" with "" in {_message}
			replace all ":wink1:" with "" in {_message}
			replace all ":niewidze:" with "" in {_message}
			replace all ":okulary:" with "" in {_message}
			replace all ":orgazm:" with "" in {_message}
			replace all ":silly:" with "" in {_message}
			replace all ":sillier:" with "" in {_message}
			replace all ":morderstwo:" with "" in {_message}
			replace all ":yell:" and ":scream:" with "" in {_message}
		if {_message} contains "&":
			set {_message} to colored {_message}
			replace all colored "&a" with "<color:#55FF55>" in {_message}
			replace all colored "&b" with "<color:#55ffff>" in {_message}
			replace all colored "&c" with "<color:#ff5555>" in {_message}
			replace all colored "&d" with "<color:#FF55FF>" in {_message}
			replace all colored "&e" with "<color:#FFFF55>" in {_message}
			replace all colored "&f" with "<color:#FFFFFF>" in {_message}
			replace all colored "&1" with "<color:#0000aa>" in {_message}
			replace all colored "&2" with "<color:#00AA00>" in {_message}
			replace all colored "&3" with "<color:#00AAAA>" in {_message}
			replace all colored "&4" with "<color:#aa0000>" in {_message}
			replace all colored "&5" with "<color:#AA00AA>" in {_message}
			replace all colored "&6" with "<color:#FFAA00>" in {_message}
			replace all colored "&7" with "<color:#AAAAAA>" in {_message}
			replace all colored "&8" with "<color:#555555>" in {_message}
			replace all colored "&9" with "<color:#5555ff>" in {_message}
			replace all colored "&0" with "<color:#000000>" in {_message}
			set {_message} to formatted {_message}
			replace all formatted "&l" with "<bold>" in {_message} 
			replace all colored "&n" with "<underlined>" in {_message} 
			replace all colored "&o" with "<i>" in {_message} 
			replace all colored "&m" with "<strikethrough>" in {_message} 
			replace all colored "&k" with "<obfuscated>" in {_message} 
		if {_message} contains "<#":
			replace all "<#" in {_message} with "<color:#"
		set {_message} to formatted {_message}
		set {_data} to data()
		set {_day} to now formatted as "dd"
		set {_month} to now formatted as "MM"
		set {_year} to now formatted as "yy"
		log "%{_data}% [%{poziom::%player%}% Lvl] <%player%> %{_message}%" to "logi/czat/.general chat/%{_month}%/%{_year}%/czat %{_day}%.log"
		log "%{_data}% [%{poziom::%player%}% Lvl] <%player%> %{_message}%" to "logi/czat/%player%/%{_year}%/%player%.log"
		if {kanal::%player%} = "admin":
			if player's name = "Pehrek" or "nishikoru":
				set chat viewers to all players where [{kanal::%input%} = "admin"]
				set async chat format to mini message from "&8[<##e8002b>ADMIN&7/<##6500e8>TEST&8] &8[<##ff1cbf>%{poziom::%player%}%&8] <<##ac93cc>%{pseudonim::%player%}%&8> <white>%{_message}%"
			else:
				send "&8[<##e8002b>ADMIN&7/<##6500e8>TEST&8] &7Wybacz, ten kanał jest dostępny tylko dla administratorów." to player

		else if {kanal::%player%} is set:
			if {kolorek1::%player%} is set:
				set {_nickname} to "%{kolorek1::%player%}%%{pseudonim::%player%}%"
			else:
				set {_nickname} to {pseudonim::%player%}
			replace all "<#" in {_nickname} with "<color:#"
			set chat viewers to all players where [{kanal::%input%} = {kanal::%player%}]
			set async chat format to mini message from "<##fcbde2>[%{kanal::%player%}%<##fcbde2>] [%{poziom::%player%}%<##fcbde2>] <%{_nickname}%<##fcbde2>> <white>%{_message}%"
		else:
			set {_colourV} to 3
			loop {_colourV} times:
				if {kolorek%loop-number%::%player%} is set:
					set {_c} to {kolorek%loop-number%::%player%}
					if {poziom::%player%} < 100:
						replace all colored "&a" with "#55FF55" in {_c}
						replace all colored "&b" with "#55ffff" in {_c}
						replace all colored "&c" with "#ff5555" in {_c}
						replace all colored "&d" with "#FF55FF" in {_c}
						replace all colored "&e" with "#FFFF55" in {_c}
						replace all colored "&f" with "#FFFFFF" in {_c}
						replace all colored "&1" with "#0000aa" in {_c}
						replace all colored "&2" with "#00AA00" in {_c}
						replace all colored "&3" with "#00AAAA" in {_c}
						replace all colored "&4" with "#aa0000" in {_c}
						replace all colored "&5" with "#AA00AA" in {_c}
						replace all colored "&6" with "#FFAA00" in {_c}
						replace all colored "&7" with "#AAAAAA" in {_c}
						replace all colored "&8" with "#555555" in {_c}
						replace all colored "&9" with "#5555ff" in {_c}
						replace all colored "&0" with "#000000" in {_c}
					else:
						replace all "<" and ">" in {_c} with ""
					if {_colours} is not set:
						set {_colours} to "%{_c}%"
					else:
						set {_colours} to formatted "%{_colours}%:%{_c}%"
				else:
					stop loop
			if {_colours} is not set:
				set {_colours} to "##ffffff:##ffffff"
			else if {kolorek2::%player%} is not set:
				set {_colours} to "%{_colours}%:%{_colours}%"
			
			set async chat format to mini message from "<dark_gray>[</dark_gray><gradient:%{_colours}%>%{poziom::%player%}% Lvl</gradient><dark_gray>] <</dark_gray><gradient:%{_colours}%>%{pseudonim::%player%}%</gradient><dark_gray>></dark_gray> %{_message}%"

			set {_time} to now formatted as "HH:mm:ss"
			post "%{_time}% | %player%: %unformatted {_message}%" to text channel with id "900397064251379752" # earthcraft -> "900397064251379752" # specific channel
		chatBubble(player, mini message from {_message}, chat viewers)
		loop chat viewers:
			if {czat.dzwieki::%loop-value%} is true:
				play sound "block.wooden_button.click_on" with volume 5 and pitch 2 to loop-value
				if {pseudonim::%loop-value%} is set:
					set {_name} to {pseudonim::%loop-value%}
				else:
					set {_name} to loop-value's name
				if {_message} contains {_name}:
					play sound "block.note_block.cow_bell" with volume 5 and pitch 0 to loop-value
		
command /ustawkolorek [<integer>] [<text>]:
	aliases: /kolorek, /setcolor, /setcolour, /colour, /color
	trigger:
		if {poziom::%player%} >= 100*arg-1:
			set {_f} to char at 0 in arg-2
			if {_f} = "#":
				if length of arg-2 = 7:
					set {_chars::*} to "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f"
					loop 7 times:
						if {_chars::*} contains (character at loop-number in arg-2):
							add 1 to {_yes}
					if {_yes} = 6:
						set {kolorek%arg-1%::%player%} to "<%arg-2%>"
						send formatted "&8[&6Earthcraft&8] &7Successfully set your %{kolorek%arg-1%::%player%}%#%arg-1% &7chat color. (%{kolorek%arg-1%::%player%}%%{pseudonim::%player%}%&7)" to player
						play sound "entity.player.levelup" with volume 3 and pitch 1 to player
					else:
						send "&8[&6Earthcraft&8] &7Argument must be written in &6#ffffff &7format." to player
						play sound "block.chest.close" with volume 3 and pitch 0 to player
				else:
					send "&8[&6Earthcraft&8] &7Argument must be written in &6#ffffff &7format." to player
					play sound "block.chest.close" with volume 3 and pitch 0 to player
			else:
				send "&8[&6Earthcraft&8] &7Argument must be written in &6#ffffff &7format." to player
				play sound "block.chest.close" with volume 3 and pitch 0 to player
		else:
			send "&8[&6Earthcraft&8] &7You must be at least level %arg-1*100% to set this chat color." to player
			play sound "block.chest.close" with volume 3 and pitch 0 to player
import:
    java.lang.String

expression %color% as hex:
    get:
        set {_i} to expr-1.asBukkitColor().asRGB()
        return String.format("##%%06X", {_i})


command /clearcolour [<integer>]:
	aliases: /clearcolor
	trigger:
		if {kolorek%arg-1%::%player%} is set:
			clear {kolorek%arg-1%::%player%}
			send "&8[&6Earthcraft&8] &7Successfully cleared your chat colour." to player
			play sound "entity.player.levelup" with volume 3 and pitch 1 to player
		else:
			send "&8[&6Earthcraft&8] &7You do not have this chat colour slot unlocked. Reach level &f%arg-1*100% &7to unlock." to player
			play sound "block.chest.close" with volume 3 and pitch 0 to player

command /kanal [<text>]:
	aliases: /channel
	trigger:
		if arg-1 is "-", "clear", "off" or "":
			send "&8[<##bdd6fc>&lCHAT&8] <##bdd6fc>%player% &7left the channel." to all players where [{kanal::%input%} = {kanal::%player%}]
			clear {kanal::%player%}
			send "&8[<##bdd6fc>&lCHAT&8] &7Successfully left the chat." to player
		else:
			set {kanal::%player%} to arg-1
			send "&8[<##bdd6fc>&lCHAT&8] &7Successfully set the channel to <##bdd6fc>%arg-1%&7." to player
			send "&8[<##bdd6fc>&lCHAT&8] <##bdd6fc>%player% &7joined the channel." to all players where [{kanal::%input%} = {kanal::%player%}]
command /ustawteam [<player>] [<text>]:
	trigger:
		set {teamtag::%arg-1%} to arg-2
		broadcast "&7[<##693699>Earthcraft&7] <##9F05C5>&l%arg-1% <##9570DD>należy teraz do teamu <##693699>%arg-2%!"
command /chatstop:
	trigger:
		if {chatstop} is true:
			set {chatstop} to false
			broadcast "&7[<##693699>Earthcraft&7] <##9F05C5>&l%player% <##9570DD>włączył/-a czat!"
		else:
			set {chatstop} to true
			broadcast "&7[<##693699>Earthcraft&7] <##9F05C5>&l%player% <##9570DD>wyłączył/-a czat!"
command /pseudonim [<text>]:
	aliases: /ecnick, /ecnickname
	trigger:
		if arg-1 is "-", "", "usun" or "brak" or "clear" or "remove":
			set {pseudonim::%player%} to player's name
			broadcast "&7[<##693699>Earthcraft&7] <##9F05C5>&l%player%: <##9570DD>Usunięto pseudonim!"
		else:
			if length of arg-1 < 21:
				set {pseudonim::%player%} to arg-1
				loop all players:
					if {language::%loop-player%} = "English":
						send "&8[&6Earthcraft&8] &6&l%player%: &7Set nickname to &6%arg-1%&7!" to loop-player
					else:
						send "&8[&6Earthcraft&8] &6&l%player%: &7Ustawiono pseudonim jako &6%arg-1%&7!" to loop-player
			else:
				if {language::%player%} = "English":
					send "&cNickname can't be longer than 20 characters." to player
					play sound "block.glass.break" with volume 3 and pitch 2 to player
				else:
					send "&cPseudonim nie może być dłuższy niż 20 znaków." to player
					play sound "block.glass.break" with volume 3 and pitch 2 to player

on tab complete of "pseudonim" or "nick" or "nickname":
	set tab completions for position 1 to "-" and "" and "usun" and "brak" and "clear" and "remove"

on command:
	set {_sender} to "%command sender%"
	if {_sender} != "@":
		set {_data} to data()
		set {_full} to full command
		set {_day} to now formatted as "dd"
		set {_month} to now formatted as "MM"
		set {_year} to now formatted as "yy"
		log "%{_data}% %{_sender}%: /%full command%" to "logi/komendy/%{_month}%/%{_year}%/komendy %{_day}%.log"

function dataConversion() :: text:
	set {_data::*} to {datatydzien} split at "."
	replace all "01" in {_data::2} with "january"
	replace all "02" in {_data::2} with "february"
	replace all "03" in {_data::2} with "march"
	replace all "04" in {_data::2} with "april"
	replace all "05" in {_data::2} with "may"
	replace all "06" in {_data::2} with "june"
	replace all "07" in {_data::2} with "july"
	replace all "08" in {_data::2} with "august"
	replace all "09" in {_data::2} with "september"
	replace all "10" in {_data::2} with "october"
	replace all "11" in {_data::2} with "november"
	replace all "12" in {_data::2} with "december"
	return {_data::2}
	
command /admin:
	trigger:
		if player's name is "kapoonfleek" or "llamadegree":
			set {admin::%player%} to true
			set {admin::%target player%} to true

command /emotki:
	aliases: /symbole, /emotes, /symbols
	trigger:
		set {_book} to a written book
		set book author of {_book} to "Kapo"
		if {language::%player%} = "English":
			set book title of {_book} to "Emotes and Symbols"
			set {_a} to text component of "          EMOTES"
			set {_h} to text component of "          SYMBOLS"
			set {_i} to text component of "%nl%&f &0- Peridot%nl%&f &0- Ruby%nl%&f &0- Topaz%nl%&f &0- Pearl%nl%&f &0- Amethyst%nl%&f &0- Aquamarine%nl%&f &0- Opal%nl%&f &0- Tourmaline%nl%&f &0- Citrine%nl%&f &0- Jade%nl%&f &0- Sapphire%nl%&f &0- Aventurine%nl%&f &0- Klejnot"
			set {_j} to text component of "&f &0- Peridot Crystal%nl%&f &0- Ruby Crystal%nl%&f &0- Topaz Crystal%nl%&f &0- Pearl Crystal%nl%&f &0- Amethyst Crystal%nl%&f &0- Aquamarine Crystal%nl%&f &0- Opal Crystal%nl%&f &0- Tourmaline Crystal%nl%&f &0- Citrine Crystal%nl%&f &0- Jade Crystal%nl%&f &0- Sapphire Crystal"
			set {_k} to text component of "&f &0- Stardust%nl%&f &0- Star Shard%nl%&f &0- Beezooka%nl%&f &0- Flamethrower%nl%&f &0- Explosive Bubble%nl%&f &0- Night Slash%nl%&f &0- Frostbolt%nl%&f &0- Lava Burst"
		else:
			set book title of {_book} to "Emotki i Symbole"
			set {_a} to text component of "          EMOTKI"
			set {_h} to text component of "          SYMBOLE"
			set {_i} to text component of "%nl%&f &0- Perydot%nl%&f &0- Rubin%nl%&f &0- Topaz%nl%&f &0- Perła%nl%&f &0- Ametyst%nl%&f &0- Akwamaryn%nl%&f &0- Opal%nl%&f &0- Turmalin%nl%&f &0- Cytryn%nl%&f &0- Jadeit%nl%&f &0- Szafir%nl%&f &0- Awenturyn%nl%&f &0- Klejnot"
			set {_j} to text component of "&f &0- Kryształ Peryd.%nl%&f &0- Kryształ Rubinu%nl%&f &0- Kryształ Topazu%nl%&f &0- Kryształ Perły%nl%&f &0- Kryształ Ametys.%nl%&f &0- Kryształ Akwam.%nl%&f &0- Kryształ Opalu%nl%&f &0- Kryształ Turmal.%nl%&f &0- Kryształ Cytrynu%nl%&f &0- Kryształ Jadeitu%nl%&f &0- Kryształ Szafiru"
			set {_k} to text component of "&f &0- Stardust%nl%&f &0- Odłamek Gwiazdy%nl%&f &0- Pszczelozuka%nl%&f &0- Miotacz Płomieni%nl%&f &0- Wybuchowy Bąb.%nl%&f &0- Nocne Cięcie%nl%&f &0- Mroźny Pocisk%nl%&f &0- Wybuch Lawy"
		set {_b} to text component of "%nl%&f &0- :3hearts:,%nl%:smiling_face_with_3_hearts:%nl%&f &0- :sunglasses:%nl%&f &0- :innocent:, :halo:"
		set {_c} to text component of "%nl%&f &0- :grin:%nl%&f &0- :bangbang:%nl%&f &0- :blush:%nl%&f &0- :drooling_face:%nl%:drool:%nl%&f &0- :exploding_head:%nl%:explode%nl%&f &0- :eyes:"
		set {_d} to text component of "&f &0- :hand_mouth:%nl%:hand_over_mouth:%nl%:face_with_hand_over_mouth:%nl%&f &0- :monocle:%nl%:face_with_monocle:%nl%&f &0- :eyebrow:%nl%:face_with_raised_eyebrow:%nl%&f &0- :fingers_crossed:%nl%&f &0- :flushed:%nl%&f &0- :frowning:%nl%&f &0- :grimacing:%nl%&f &0- :grinning:"
		set {_e} to text component of "&f &0- :heart_eyes:%nl%&f &0- :kiss:%nl%&f &0- :kissing_heart%nl%:kissing_face:%nl%&f &0- :kissing:%nl%&f &0- :money_mouth:%nl%&f &0- :nauseated_face:%nl%:nauseated:%nl%&f &0- :ok_hand:, :ok:%nl%&f &0- :partying_face:%nl%:party:%nl%&f &0- :pensive:%nl%&f &0- :pray:%nl%&f &0- :relieved:"
		set {_f} to text component of "&f &0- :rolling_eyes:%nl%&f &0- :skull:%nl%&f &0- :sleepy:%nl%&f &0- :slight_smile:%nl%&f &0- :smile%nl%&f &0- :smiling_tear:%nl%:smiling_face_with_tear:%nl%&f &0- :smirk:%nl%&f &0- :sob:%nl%&f &0- :sparkles:%nl%&f &0- :star_struck:%nl%&f &0- :sweat:%nl%&f &0- :thinking:"
		set {_g} to text component of "&f &0- :thumbsdown:, :-1:%nl%&f &0- :thumbsup:, :+1:%nl%&f &0- :upside_down:%nl%&f &0- :wink:%nl%&f &0- :yum:%nl%&f &0- :xdd:"
		set {_a::*} to {_a}, {_b} and {_c}
		set {_b::*} to {_h} and {_i}
		set page 1 of book {_book} to {_a::*}
		set page 2 of book {_book} to {_d}
		set page 3 of book {_book} to {_e}
		set page 4 of book {_book} to {_f}
		set page 5 of book {_book} to {_g}
		set page 6 of book {_book} to {_b::*}
		set page 7 of book {_book} to {_j}
		set page 8 of book {_book} to {_k}
		give {_book} to player