on join:
	if {completionreward::%player%::*} is set:
		wait 6 seconds
		play sound "block.note_block.pling" with volume 3 and pitch 1.6 to player
		if {language::%player%} = "English":
			send "&e> You have %size of {completionreward::%player%::*}% unclaimed completion rewards."
		else:
			send "&e> Masz %size of {completionreward::%player%::*}% nieodebranych nagród za skompletowanie kolekcji."
	else:
		if {secretwonderscomplete::%player%} is not true:
			loop 14 times:
				if {carddrop::sw::%player%::%loop-number%} is set:
					add 1 to {_complete}
			if {_complete} = 14:
				add "Secret Wonders" to {completionreward::%player%::*}
				set {secretwonderscomplete::%player%} to true
		else if {majesticdawncomplete::%player%} is not true:
			loop 14 times:
				if {carddrop::md::%player%::%loop-number%} is set:
					add 1 to {_complete}
			if {_complete} = 14:
				add "Majestic Dawn" to {completionreward::%player%::*}
				set {majesticdawncomplete::%player%} to true
		else if {unseenforcescomplete::%player%} is not true:
			loop 14 times:
				if {carddrop::uf::%player%::%loop-number%} is set:
					add 1 to {_complete}
			if {_complete} = 14:
				add "Unseen Forces" to {completionreward::%player%::*}
				set {unseenforcescomplete::%player%} to true
		else if {plasmafreezecomplete::%player%} is not true:
			loop 14 times:
				if {carddrop::pf::%player%::%loop-number%} is set:
					add 1 to {_complete}
			if {_complete} = 14:
				add "Plasma Freeze" to {completionreward::%player%::*}
				set {plasmafreezecomplete::%player%} to true

on rightclick on a player:
	if clicked player is not online:
			#if "%regions at player%" contains "spawn":
				#if {winterDelightPassLEVEL::%player%} >= 0:
					#getMission(player, "Happy Winter Delight!", "Wesołego Zimowego Zachwytu!", 1)
					
		if clicked player's name = "Maggie":
			set {_x} to a random integer between 1 and 4
			play sound "entity.villager.yes" with volume 4 and pitch 1 to player
			if {language::%player%} = "English":
				if {_x} = 1:
					send "&8[<##b08dff>NPC&8] &8<<##b08dff>Maggie&8> &fIm just reading..." to player
				if {_x} = 2:
					send "&8[<##b08dff>NPC&8] &8<<##b08dff>Maggie&8> &fShhh... We are in a library." to player
				if {_x} = 3:
					send "&8[<##b08dff>NPC&8] &8<<##b08dff>Maggie&8> &fThanks to books, I know that my <##de85d1>Candy &fis actually an artifact!" to player
				if {_x} = 4:
					send "&8[<##b08dff>NPC&8] &8<<##b08dff>Maggie&8> &fDid you know that <##025b95>Sapphire &fwas once the least valuable Gemstone?" to player
			else:
				if {_x} = 1:
					send "&8[<##b08dff>NPC&8] &8<<##b08dff>Maggie&8> &fJa tu tylko czytam..." to player
				if {_x} = 2:
					send "&8[<##b08dff>NPC&8] &8<<##b08dff>Maggie&8> &fCiii... Znajdujemy się w bibliotece." to player
				if {_x} = 3:
					send "&8[<##b08dff>NPC&8] &8<<##b08dff>Maggie&8> &fDzięki książkom wiem, że mój <##de85d1>Cukierek &fto tak właściwie artefakt!" to player
				if {_x} = 4:
					send "&8[<##b08dff>NPC&8] &8<<##b08dff>Maggie&8> &fCzy wiedziałeś/-aś że <##025b95>Szafir &fbył kiedyś najmniej cenionym kamieniem szlachetnym?" to player
			#if x = 5
			#krążą plotki że cress....
		else if clicked player's name = "Krysta":
			play sound "entity.villager.no" with volume 4 and pitch 1 to player
			set {_x} to a random integer between 1 and 4
			if {language::%player%} = "English":
				if {_x} = 1:
					send "&8[<##9a5398>NPC&8] &8<<##9a5398>Krysta&8> &fCome back to me when you've made 543 friends." to player
				else if {_x} = 2:
					send "&8[<##9a5398>NPC&8] &8<<##9a5398>Krysta&8> &fI have 1721 followers on Earthagram." to player
				else if {_x} = 3:
					send "&8[<##9a5398>NPC&8] &8<<##9a5398>Krysta&8> &fHave you heard that Akasaka has a crush on Czarek? How scandalous." to player
				else if {_x} = 4:
					send "&8[<##9a5398>NPC&8] &8<<##9a5398>Krysta&8> &fThey say I have ears and a trunk like an elephant, but I think they are just jealous of my beauty." to player
			else:
				if {_x} = 1:
					send "&8[<##9a5398>NPC&8] &8<<##9a5398>Krysta&8> &fWróć do mnie jak znajdziesz 543 znajomych." to player
				else if {_x} = 2:
					send "&8[<##9a5398>NPC&8] &8<<##9a5398>Krysta&8> &fMam 1721 obserwujących na Earthagramie." to player
				else if {_x} = 3:
					send "&8[<##9a5398>NPC&8] &8<<##9a5398>Krysta&8> &fCzy słyszałeś, że Akasaka się zakochała w Czarku? Skandaliczne." to player
				else if {_x} = 4:
					send "&8[<##9a5398>NPC&8] &8<<##9a5398>Krysta&8> &fMówią że mam uszy i trąbę jak słoń ale myślę, że po prostu zazdroszczą mojej urody." to player
		else if clicked player's name = "Mała Damba":
			play sound "entity.wolf.whine" with volume 4 and pitch 1 to player
			set {_x} to a random integer between 1 and 4
			if {language::%player%} = "English":
				if {_x} = 1:
					send "&8[<##6ce957>NPC&8] &8<<##6ce957>Mała Damba&8> &fOne day I will be like Mal'Damba..." to player
				else if {_x} = 2:
					send "&8[<##6ce957>NPC&8] &8<<##6ce957>Mała Damba&8> &fI know I'm not Mal'Damba... But please treat me the same as you would him......" to player
				else if {_x} = 3:
					send "&8[<##6ce957>NPC&8] &8<<##6ce957>Mała Damba&8> &fDo you also like Mal'Damba...?" to player
				else if {_x} = 4:
					send "&8[<##6ce957>NPC&8] &8<<##6ce957>Mała Damba&8> &fMal'Damba will give me strength..." to player
			else:
				if {_x} = 1:
					send "&8[<##6ce957>NPC&8] &8<<##6ce957>Mała Damba&8> &fKiedyś będę tak jak Mal'Damba..." to player
				else if {_x} = 2:
					send "&8[<##6ce957>NPC&8] &8<<##6ce957>Mała Damba&8> &fWiem, że nie jestem Mal'Dambą... Ale proszę traktuj mnie tak, jak niego..." to player
				else if {_x} = 3:
					send "&8[<##6ce957>NPC&8] &8<<##6ce957>Mała Damba&8> &fCzy też lubisz Mal'Dambę...?" to player
				else if {_x} = 4:
					send "&8[<##6ce957>NPC&8] &8<<##6ce957>Mała Damba&8> &fMal'Damba da mi siłę..." to player
		else if clicked player's name = "Soldier":
			play sound "entity.villager.yes" with volume 4 and pitch 1 to player
			play sound "entity.experience_orb.pickup" with volume 4 and pitch 1 at player
			if {language::%player%} = "English":
				send "&8[<##94683a>NPC&8] &8<<##94683a>Soldier&8> &fGreetings! These are the current chest drops:" to player
				send "&8[ &7&lChests:" to player
				send "&8[ &71x Random Gemstone: <##94683a>25%%" to player
				send "&8[ &73x Random Gemstone: <##94683a>8%%" to player
				send "&8[ &71x Klejnot: <##94683a>28%%" to player
				send "&8[ &71x Losowy Booster: <##94683a>0.6%%" to player
				send "&8[ &73x Losowy Booster: <##94683a>0.2%%" to player
				send "&8[ &71x Star Shard: <##94683a>0.11%%" to player
				send "&8[ &71x Chaotic Potion: <##94683a>0.4%%" to player
				send "&8[ &71x Prismatic Lens: <##94683a>0.18%%" to player
				send "&8[ &71x Jar of Experience: <##94683a>7%%" to player
				send "&8[ &71x Chest: <##94683a>4.5%%" to player
				send "&8[ &71x Luxury Chest: <##94683a>1%%" to player
				send "&8[ &71x Random Essence: <##94683a>3.5%%" to player
				send "&8[ &71x Diamond Shard: <##94683a>0.33%%" to player
				send " " to player
				send "&8[ &7&lLuxurious Chests:" to player
				send "&8[ &71x Random Gemstone: <##94683a>48%%" to player
				send "&8[ &73x Random Gemstone: <##94683a>24%%" to player
				send "&8[ &71x Klejnot: <##94683a>65%%" to player
				send "&8[ &71x Random Booster: <##94683a>2.2%%" to player
				send "&8[ &73x Random Booster: <##94683a>0.7%%" to player
				send "&8[ &71x Star Shard: <##94683a>0.33%%" to player
				send "&8[ &71x Chaotic Potion: <##94683a>1.1%%" to player
				send "&8[ &71x Prismatic Lens: <##94683a>0.39%%" to player
				send "&8[ &71x Jar of Experience: <##94683a>12%%" to player
				send "&8[ &71x Chest: <##94683a>9%%" to player
				send "&8[ &71x Luxury Chest: <##94683a>2.5%%" to player
				send "&8[ &71x Random Essence: <##94683a>8%%" to player
				send "&8[ &73x Random Essence: <##94683a>2.8%%" to player
				send "&8[ &71x Enchanted Prismatic Lens: <##94683a>0.13%%" to player
				send "&8[ &71x Klejnot Rain: <##94683a>0.48%%" to player
				send "&8[ &71x Token of Gratitude: <##94683a>0.6%%" to player
				send "&8[ &71x Diamond Shard: <##94683a>0.99%%" to player
			else:
				send "&8[<##94683a>NPC&8] &8<<##94683a>Soldier&8> &fWitaj! Oto obecne dropy ze skrzynek:" to player
				send "&8[ &7&lSkrzynki:" to player
				send "&8[ &71x Losowy Kamień Szlachetny: <##94683a>25%%" to player
				send "&8[ &73x Losowy Kamień Szlachetny: <##94683a>8%%" to player
				send "&8[ &71x Klejnot: <##94683a>28%%" to player
				send "&8[ &71x Losowy Booster: <##94683a>0.6%%" to player
				send "&8[ &73x Losowy Booster: <##94683a>0.2%%" to player
				send "&8[ &71x Odłamek Gwiazdy: <##94683a>0.11%%" to player
				send "&8[ &71x Chaotyczna Mikstura: <##94683a>0.4%%" to player
				send "&8[ &71x Pryzmatyczna Soczewka: <##94683a>0.18%%" to player
				send "&8[ &71x Słoik z Doświadczeniem: <##94683a>7%%" to player
				send "&8[ &71x Skrzynka: <##94683a>4.5%%" to player
				send "&8[ &71x Luksusowa Skrzynka: <##94683a>1%%" to player
				send "&8[ &71x Losowa Esencja: <##94683a>3.5%%" to player
				send "&8[ &71x Diamentowy Odłamek: <##94683a>0.33%%" to player
				send " " to player
				send "&8[ &7&lLuksusowe Skrzynki:" to player
				send "&8[ &71x Losowy Kamień Szlachetny: <##94683a>48%%" to player
				send "&8[ &73x Losowy Kamień Szlachetny: <##94683a>24%%" to player
				send "&8[ &71x Klejnot: <##94683a>65%%" to player
				send "&8[ &71x Random Booster: <##94683a>2.2%%" to player
				send "&8[ &73x Random Booster: <##94683a>0.7%%" to player
				send "&8[ &71x Odłamek Gwiazdy: <##94683a>0.33%%" to player
				send "&8[ &71x Chaotyczna Mikstura: <##94683a>1.1%%" to player
				send "&8[ &71x Pryzmatyczna Soczewka: <##94683a>0.39%%" to player
				send "&8[ &71x Słoik z Doświadczeniem: <##94683a>12%%" to player
				send "&8[ &71x Skrzynka: <##94683a>9%%" to player
				send "&8[ &71x Luksusowa Skrzynka: <##94683a>2.5%%" to player
				send "&8[ &71x Losowa Esencja: <##94683a>8%%" to player
				send "&8[ &73x Losowa Esencja: <##94683a>2.8%%" to player
				send "&8[ &71x Zaklęta Pryzmatyczna Soczewka: <##94683a>0.13%%" to player
				send "&8[ &71x Deszcz Klejnotów: <##94683a>0.48%%" to player
				send "&8[ &71x Token Wdzięczności: <##94683a>0.06%%" to player
				send "&8[ &71x Diamentowy Odłamek: <##94683a>0.99%%" to player
		else if clicked player's name = "August":
			if {completionreward::%player%::*} is set:
				play sound "entity.villager.ambient" with volume 4 and pitch 1 to player
				play sound "block.note_block.pling" with volume 3 and pitch 2 to player
				if {language::%player%} = "English":
					send "&8[<##00949e>NPC&8] &8<<##00949e>August&8> &fHow can I be of service?" to player
					if {completionreward::%player%::*} contains "Secret Wonders":
						send "<command:/completionclaim espeon><tooltip:&fClick here to claim the reward..>&8(&9Booster&8) &5[Secret Wonders] &oClick here to claim <##d48bc3>&oEspeon&5&o." to player
					else if {completionreward::%player%::*} contains "Majestic Dawn":
						send "<command:/completionclaim shaymin><tooltip:&fClick here to claim the reward..>&8(&9Booster&8) &5[Majestic Dawn] &oClick here to claim <##dbef9e>&oShaymin (Land)&5&o." to player
					else if {completionreward::%player%::*} contains "Unseen Forces":
						send "<command:/completionclaim cynder><tooltip:&fClick here to claim the reward..>&8(&9Booster&8) &5[Unseen Forces] &oClick here to claim <##5b467d>&oCynder&5&o." to player
					else if {completionreward::%player%::*} contains "Plasma Freeze":
						send "<command:/completionclaim leafeon><tooltip:&fClick here to claim the reward..>&8(&9Booster&8) &5[Plasma Freeze] &oClick here to claim <##74ba75>&oLeafeon&5&o." to player
				else:
					send "&8[<##00949e>NPC&8] &8<<##00949e>August&8> &fW czym mogę się przydać?" to player
					if {completionreward::%player%::*} contains "Secret Wonders":
						send "<command:/completionclaim espeon><tooltip:&fKliknij tu, by odebrać nagrodę.>&8(&9Booster&8) &5[Secret Wonders] &oKliknij tutaj, by odebrać <##d48bc3>&oEspeona&5&o." to player
					else if {completionreward::%player%::*} contains "Majestic Dawn":
						send "<command:/completionclaim shaymin><tooltip:&fKliknij tu, by odebrać nagrodę.>&8(&9Booster&8) &5[Majestic Dawn] &oKliknij tutaj, by odebrać <##dbef9e>&oShaymina (Land)&5&o." to player
					else if {completionreward::%player%::*} contains "Unseen Forces":
						send "<command:/completionclaim cynder><tooltip:&fKliknij tu, by odebrać nagrodę.>&8(&9Booster&8) &5[Unseen Forces] &oKliknij tutaj, by odebrać <##5b467d>&oCynder&5&o." to player
					else if {completionreward::%player%::*} contains "Plasma Freeze":
						send "<command:/completionclaim leafeon><tooltip:&fKliknij tu, by odebrać nagrodę.>&8(&9Booster&8) &5[Plasma Freeze] &oKliknij tutaj, by odebrać <##74ba75>&oLeafeon&5&o." to player
			else:
				play sound "block.note_block.pling" with volume 3 and pitch 0 to player
				play sound "entity.villager.no" with volume 4 and pitch 1 to player
				if {language::%player%} = "English":
					send "&8[<##00949e>NPC&8] &8<<##00949e>August&8> &fI am afraid there's currently no completion reward ready for you at the moment." to player
				else:
					send "&8[<##00949e>NPC&8] &8<<##00949e>August&8> &fObawiam się, że nie mam obecnie dla ciebie żadnej nagrody." to player
		else if clicked player's name = "Odyn":
			play sound "entity.villager.ambient" with volume 4 and pitch 0.6 to player
			set {_x} to a random integer between 1 and 2
			if {_x} = 1:
				send "&8[<##9e8672>NPC&8] &8<<##9e8672>Odyn&8> &f..." to player
			else if {_x} = 2:
				send "&8[<##9e8672>NPC&8] &8<<##9e8672>Odyn&8> &fHmm?" to player
		else if clicked player's name = "Archie":
			play sound "entity.villager.yes" with volume 4 and pitch 1 to player
			set {_x} to a random integer between 1 and 2
			if {_x} = 1:
				send "&8[&9NPC&8] &9Archie says: &fGot any orders from the boss?!" to player
			else if {_x} = 2:
				send "&8[&9NPC&8] &9Archie says: &fAye?" to player
		else if clicked player's name = "Castella":
			play sound "entity.villager.yes" with volume 4 and pitch 1 to player
			set {_x} to a random integer between 1 and 4
			if {language::%player%} = "English":
				if {_x} = 1:
					send "&8[<##ffde73>NPC&8] &8<<##ffde73>Castella&8> &fWhat's your favourite card? Mine is <##fae664>Emolga&f!" to player
				if {_x} = 2:
					send "&8[<##ffde73>NPC&8] &8<<##ffde73>Castella&8> &fI have 2632 cards in my collection and I won't hesitate to use them!" to player
				if {_x} = 3:
					send "&8[<##ffde73>NPC&8] &8<<##ffde73>Castella&8> &fWould you like to trade cards?" to player
				else if {_x} = 4:
					send "&8[<##ffde73>NPC&8] &8<<##ffde73>Castella&8> &fDid you know that <##ffde73>%{totalCardsDropped}% &fcards have been dropped on Earthcraft?! WOW!!!" to player
			else:
				if {_x} = 1:
					send "&8[<##ffde73>NPC&8] &8<<##ffde73>Castella&8> &fJaka jest twoja ulubiona karta? Moja to <##fae664>Emolga&f!" to player
				else if {_x} = 2:
					send "&8[<##ffde73>NPC&8] &8<<##ffde73>Castella&8> &fMam 2632 kart w kolekcji i nie zawacham się żadnej z nich użyć!" to player
				else if {_x} = 3:
					send "&8[<##ffde73>NPC&8] &8<<##ffde73>Castella&8> &fChcesz się wymienić kartami?" to player
				else if {_x} = 4:
					send "&8[<##ffde73>NPC&8] &8<<##ffde73>Castella&8> &fCzy wiesz, że na Earthcraft wydropiono ponad <##ffde73>%{totalCardsDropped}% &fkart?! WOW!!!" to player
		else if clicked player's name = "":
			play sound "entity.villager.yes" with volume 4 and pitch 1 to player
			if {language::%player%} = "English":
				send "&8[<##755a49>NPC&8] &8<<##755a49>'Bearded' Zachary&8> &fHello! Can I help you with something?" to player
				set metadata tag "brodatyzachary" of player to chest inventory with 1 row named "What would you like to do?"
				set slot 3 of (metadata tag "brodatyzachary" of player) to iron pickaxe named "&fChoose Pickaxe Skill" with lore "&7Click here to choose%nl%&7a pickaxe skill." with nbt from "{HideFlags:127}"
				set slot 5 of (metadata tag "brodatyzachary" of player) to iron block named "&fCheck Mining Skill" with lore "&7Click to check your proficiency%nl%&7in Mining."
			else:
				send "&8[<##755a49>NPC&8] &8<<##755a49>'Brodaty' brodatyzacharyary&8> &fCześć! Czy mógłbym ci w czymś pomóc?" to player
				set metadata tag "brodatyzachary" of player to chest inventory with 1 row named "Co chcesz zrobić?"
				set slot 3 of (metadata tag "brodatyzachary" of player) to iron pickaxe named "&fWybierz Umiejętność Kilofu" with lore "&7Kliknij tutaj, by wybrać%nl%&7umiejętność kilofu." with nbt from "{HideFlags:127}"
				set slot 5 of (metadata tag "brodatyzachary" of player) to iron block named "&fSprawdź Umiejętności Górnickie" with lore "&7Kliknij tutaj by sprawdzić swoją%nl%&7ekspertyzę w Górnictwie."
			play sound "block.note_block.pling" with volume 4 and pitch 2 to player
			open metadata tag "brodatyzachary" of player to player
		else if clicked player's name = "Dust Star":
			play sound "entity.villager.yes" with volume 4 and pitch 1 to player
		else if clicked player's name = "Ciscra":
			if line 19 of lore of player's tool contains "&8Id: ":
				cancel event
				set metadata tag "Constellation" of player to chest inventory with 3 rows named "Constellation"
				set {_constellation} to Constellation(player, false)
				if {_constellation} is not set:
					set {_constellation} to 0
				set {_constellationName} to name of slot 16 of metadata tag "kartagui" of player
				set {_lore} to (join lore of slot 16 of metadata tag "kartagui" of player by nl)
				set slot 4 of metadata tag "Constellation" of player to nether star named {_constellationName} with lore {_lore}
				loop slots integers between 10 and 15 of metadata tag "kartagui" of player:
					if {_constellation} >= (index of loop-slot) - 9:
						add "%last color of name of player's tool%%uncolored name of loop-value%" to {_constList::*}
					else:
						add "&8%uncolored name of loop-value%" to {_constList::*}
				set {_constList} to join {_constList::*} by "%nl%&7- "
				set slot 11 of metadata tag "Constellation" of player to white stained glass pane named "&fCurrent Constellation" with lore "&7- %{_constList}%"
				if {_constellation} < 6:
					set slot 15 of metadata tag "Constellation" of player to white stained glass pane named "&fUnlock Constellation" with lore "&7Click here to exchange a copy of held%nl%&7card and increase the constellation."
				else:
					set slot 15 of metadata tag "Constellation" of player to white stained glass pane named "&fAll Constellations Unlocked" with lore "&7This card's full potential has been unlocked."
				open metadata tag "Constellation" of player to player
				loop 4 times:
					set {_pitch} to 0.5 + (loop-number*0.2)
					play sound "entity.experience_orb.pickup" with volume 3 and pitch {_pitch} to player
					wait 3 ticks
					if loop-number = 2:
						wait 3 ticks
			else:
				play sound "block.glass.break" with volume 3 and pitch 0.2 to player
				if {language::%player%} = "English":
					send "&c&oYou must hold a card in your hand to interact with this NPC." to player
				else:
					send "&c&oMusisz trzymać kartę, by móc przeprowadzić interakcję z tym NPC." to player
		else if clicked player's name = "Malicia":
			play sound "entity.villager.yes" with volume 4 and pitch 1 to player
			set metadata tag "Teams" of player to chest inventory with 5 rows named "Teams"	
			if {teamPoison::*} is not set:
				set {_membersPoison} to " &fnone"
			else:
				set {_membersPoison} to join {teamPoison::*} by "%nl% &f- "

			if {teamAqua::*} is not set:
				set {_membersAqua} to " &fnone"
			else:
				set {_membersAqua} to join {teamPoison::*} by "%nl% &f- "
			set slot 13 of metadata tag "Teams" of player to black stained glass pane named "&fTeam Count" with lore "&7Team Poison member count: &f%size of {teamPoison::*}%%nl%&7Team Aqua member count: &f&f%size of {teamAqua::*}%%nl%&7Sideless: &f%size of {teamSideless::*}%"
			set slot 20 of metadata tag "Teams" of player to purple wool named "&5Team Poison" with lore "&fTeam Poison needs you!%nl% %nl%&7Description:%nl%&7&oMischievous and sly, Team Poison has a fondness for%nl%&7&omaking all sorts of plans and schemes and misleading%nl%&7&othe opposing team into traps. Their expansive bases%nl%&7&ohave endless corridors and secrets, and the team%nl%&7&ois famously known for their laboratory, where its%nl%&7&omembers find various discoveries and conduct%nl%&7&oresearch on new species found on Earthcraft.%nl% %nl%&7Members:%nl%%{_membersPoison}%"
			
			set slot 24 of metadata tag "Teams" of player to light blue wool named "&bTeam Aqua" with lore "&fTeam Aqua needs you!%nl% %nl%&7&oDescription:%nl%&7&oAdaptible and investigative, Team Aqua has a history%nl%&7&oof finding bases effectively, acquiring and collecting%nl%&7&oevidence and secret items, as well as quickly unfolding%nl%&7&othe opposing team's plans. They are especially known for%nl%&7&onever letting their guard down and being exceptionally%nl%&7&ogood at protecting what must be hidden from the public eye.%nl% %nl%&7Members:%nl%%{_membersAqua}%"
			
			set slot 31 of metadata tag "Teams" of player to white wool named "&fImpartial" with lore "&7Don't feel like joining any team?%nl%&7You can choose to remain impartial%nl%&7by clicking on this panel.%nl% %nl%&fClick here if you want to remain impartial."
			if {team::%player%} is not set:
				add "%nl%&fClick here to join Team Poison." to lore of slot 20 of metadata tag "Teams" of player	
				add "%nl%&fClick here to join Team Aqua." to lore of slot 24 of metadata tag "Teams" of player	
			open metadata tag "Teams" of player to player
		else if clicked player's name = "Guadalupe":
			play sound "entity.villager.yes" with volume 4 and pitch 1 to player
			if {language::%player%} = "English":
				send "&8[<##edf261>NPC&8] &8<<##edf261>Guadalupe&8> &fGood day to you!" to player
				set metadata tag "guadalupe" of player to chest inventory with 5 rows named "Reset Talents"
				if {karta::%player%} is set:
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						if string tag "Talents" of custom nbt of {karta::%player%} is set:
							set slot 20 of (metadata tag "guadalupe" of player) to {karta::%player%} with lore (lore of {karta::%player%}) and "%nl%&f&oThis is your current Card."
							if {cosmicflux::%player%} >= 500:
								set slot 22 of (metadata tag "guadalupe" of player) to lime stained glass pane named "&aReset Talents" with lore "&7Click &o&nhere &7to reset this%nl%&7Card's Talents."
							else:
								set slot 22 of (metadata tag "guadalupe" of player) to red stained glass pane named "&cNot enough currency" with lore "&7You do not have enough Cosmic Flux%nl%&7to reset this Card's Talents."
							set slot 24 of (metadata tag "guadalupe" of player) to iron nugget named "&fCost" with lore "%nl%&f⇏ &7Resetting Talents will cost you &f&n500&r &f&7.%nl%&f⇏ &7All Talents will be reset.%nl% %nl%&8(&f &8= Cosmic Flux)%nl%&8This currency will be subtracted from%nl%&8your Player account upon expenditure." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						else:
							send "&c&oYour Card must be at least Level 15 and have one Talent selected to perform this action." to player
							play sound "entity.villager.no" with volume 3 and pitch 0.8 to player
							teleport player to player's location
					else:
						send "&c&oYour Card must be at least Level 15 and have one Talent selected to perform this action." to player
						play sound "entity.villager.no" with volume 3 and pitch 0.8 to player
						teleport player to player's location
				else:
					send "&c&oYou do not have an active Card selected." to player
					play sound "entity.villager.no" with volume 3 and pitch 0.8 to player
					teleport player to player's location
			else:
				send "&8[<##edf261>NPC&8] &8<<##edf261>Guadalupe&8> &fWitaj!" to player
				set metadata tag "guadalupe" of player to chest inventory with 5 rows named "Resetowanie Talentów"
				if {karta::%player%} = player's tool:
					if int tag "Level" of custom nbt of {karta::%player%} >= 15:
						if string tag "Talents" of custom nbt of {karta::%player%} is set:
							set slot 20 of (metadata tag "guadalupe" of player) to {karta::%player%} with lore (lore of {karta::%player%}) and "%nl%&f&oThis is your current Card."
							if {cosmicflux::%player%} >= 500:
								set slot 22 of (metadata tag "guadalupe" of player) to lime stained glass pane named "&aReset Talents" with lore "&7Click &o&nhere &7to reset this%nl%&7Card's Talents."
							else:
								set slot 22 of (metadata tag "guadalupe" of player) to red stained glass pane named "&cNot enough currency" with lore "&7You do not have enough Cosmic Flux%nl%&7to reset this Card's Talents."
							set slot 24 of (metadata tag "guadalupe" of player) to iron nugget named "&fCost" with lore "%nl%&f⇏ &7Resetting Talents will cost you &f&n500&r &f&7.%nl%&f⇏ &7All Talents will be reset.%nl% %nl%&8(&f &8= Cosmic Flux)%nl%&8This currency will be subtracted from%nl%&8your Player account upon expenditure." with nbt from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
						else:
							send "&c&oYour Card must be at least Level 15 and have one Talent selected to perform this action." to player
							play sound "entity.villager.no" with volume 3 and pitch 0.8 to player
							teleport player to player's location
					else:
						send "&c&oYour Card must be at least Level 15 and have one Talent selected to perform this action." to player
						play sound "entity.villager.no" with volume 3 and pitch 0.8 to player
						teleport player to player's location
				else:
					send "&c&oYou must be holding your &nactive &c&oCard to interact with this NPC." to player
					play sound "entity.villager.no" with volume 3 and pitch 0.8 to player
					teleport player to player's location
			play sound "block.note_block.pling" with volume 4 and pitch 2 to player
			open metadata tag "guadalupe" of player to player
on inventory click:
	if event-inventory = metadata tag "Teams" of player:
		cancel event
	else if event-inventory = metadata tag "guadalupe" of player:
		cancel event
		if index of event-slot = 22:
			if event-slot is a lime stained glass pane:
				teleport player to player's location
				remove 500 from {cosmicflux::%player%}
				clear compound tag "Talents" of custom nbt of player's tool
				play sound "entity.player.levelup" with volume 3 and pitch 1 to player
				set {_l} to int tag "Level" of custom nbt of player's tool
				send "&e&oSuccessfully reset all Talents for %uncolored name of {karta::%player%}% (Level %{_l}%)" to player
	else if event-inventory = metadata tag "brodatyzachary" of player:
		cancel event
		if index of event-slot = 3:
			play sound "entity.bat.takeoff" with volume 5 and pitch 0.92 to player
			if {language::%player%} = "English":
				set metadata tag "brodatyzacharyChoosePickaxe" of player to chest inventory with 1 row named "Pickaxe Skills"
				set {_0} to stone named "&8Standard Mining" with lore "&7Pick this if you want to experience%nl%&7classic mining."
				set {_1} to cobblestone named "&8Helping Hand" with lore "&8Pickaxe Upgrade" and "&7Cooldown: &f10 seconds" and "&7Immediately &fbreaks &7the target block." and "&7Blocks broken in this way behave" and "&7as if mined normally."
				set {_2} to tnt named "&cExplosion" with lore "&8Pickaxe Upgrade" and "&7Cooldown: &f2 minutes" and "&7Detonate all blocks in radius &f3 &7around" and "&7the target block. Blocks broken in this" and "&7way behave as if mined normally."
				set {_3} to beacon named "&bIgnition" with lore "&8Pickaxe Upgrade" and "&7Cooldown: &fNone" and "&7Mining stone or deepslate has a &f8%%" and "&7chance to drop an &fIgnition Orb&7." and "&7Collecting &f20 Orbs &7will grant &f40%%" and "&f Mining Haste &7for &f4 sec&7."
				set {_4} to blast furnace named "&6Heating Systems" with lore "&8Pickaxe Upgrade" and "&7Cooldown: &fNone" and "&7Mining &fore&7, &fstone &7or &fdeepslate%nl%&7automatically smelts the received ore."
				set {_5} to iron block named "&7Magnet" with lore "&8Pickaxe Upgrade" and "&7Cooldown: &fNone" and "&7Mining &fIron &7will automatically mine%nl%&7all adjacent &fIron Ore&7. &7Every &f3 Iron Ore &7mined%nl%&7in this way will grant the player an%nl%&7additional &fIron Ingot&7." and "&7sztabkę żelaza."
				if {umkilof::%player%} = "Brak":
					add "&aSELECTED" to lore of {_0}
				else:
					add "&fClick to select." to lore of {_0}
				set slot 0 and 8 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_0}
				if {poziomgornictwo::%player%} > 0:
					if {umkilof::%player%} = "PomocnaDłoń":
						add "&aSELECTED" to lore of {_1}
					else:
						add "&fClick to select." to lore of {_1}
				else:
					add "&cNOT UNLOCKED" to lore of {_1}
				set slot 2 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_1}
				if {poziomgornictwo::%player%} > 9:
					if {umkilof::%player%} = "Eksplozja":
						add "&aSELECTED" to lore of {_2}
					else:
						add "&fClick to select." to lore of {_2}
				else:
					add "&cNOT UNLOCKED" to lore of {_2}
				set slot 3 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_2}
				if {poziomgornictwo::%player%} > 19:
					if {umkilof::%player%} = "Zapłon":
						add "&aSELECTED" to lore of {_3}
					else:
						add "&fClick to select." to lore of {_3}
				else:
					add "&cNOT UNLOCKED" to lore of {_3}
				set slot 4 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_3}
				if {poziomgornictwo::%player%} > 29:
					if {umkilof::%player%} = "Instalacje Ogrzewcze":
						add "&aSELECTED" to lore of {_4}
					else:
						add "&fClick to select." to lore of {_4}
				else:
					add "&cNOT UNLOCKED" to lore of {_4}
				set slot 5 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_4}
				if {poziomgornictwo::%player%} > 39:
					if {umkilof::%player%} = "Magnes":
						add "&aSELECTED" to lore of {_5}
					else:
						add "&fClick to select." to lore of {_5}
				else:
					add "&cNOT UNLOCKED" to lore of {_5}
				set slot 6 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_5}
			else:
				set metadata tag "brodatyzacharyChoosePickaxe" of player to chest inventory with 1 row named "Umiejętności Kilofu"
				set {_0} to stone named "&8Standardowe Kopanie" with lore "&7Wybierz, jeśli chcesz doświadczyć" and "&7klasycznego kopania."
				set {_1} to cobblestone named "&8Pomocna Dłoń" with lore "&8Ulepszenie Kilofu" and "&7Cooldown: &f10 sekund" and "&7Natychmiastowo wykopuje kliknięty blok." and "&7Zniszczone bloki tym ulepszeniem liczą" and "&7i zachowują się jako wykopane."
				set {_2} to tnt named "&cEksplozja" with lore "&8Ulepszenie Kilofu" and "&7Cooldown: &f2 minuty" and "&7Powoduje eksplozję na obszarze 3 kratek." and "&7Zniszczone bloki liczą się jako" and "&7wykopane i zachowują się jak wykopane."
				set {_3} to beacon named "&bZapłon" with lore "&8Ulepszenie Kilofu" and "&7Cooldown: &fBrak" and "&7Wykopanie kamienia ma 8%% szans na" and "&7wypadnięcie kuli zapłonu." and "&7Zebranie 20 kul zapewnia o 40%%" and "&7szybsze kopanie na 4 sekundy."
				set {_4} to blast furnace named "&6Instalacje Ogrzewcze" with lore "&8Ulepszenie Kilofu" and "&7Cooldown: &fBrak" and "&7Wykopanie kamienia ma 20%% szans" and "&7na automatyczne przepalenie go."
				set {_5} to iron block named "&7Magnes" with lore "&8Ulepszenie Kilofu" and "&7Cooldown: &fBrak" and "&7Wykopanie rudy żelaza automatycznie" and "&7wykopie i przyciągnie sąsiadujące rudy." and "&7Za każde 3 rudy przyciągnięte" and "&7w ten sposób otrzymujesz dodatkową" and "&7sztabkę żelaza."
				if {umkilof::%player%} = "Brak":
					add "&aWYBRANO" to lore of {_0}
				else:
					add "&fKliknij, by wybrać." to lore of {_0}
				set slot 0 and 8 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_0}
				if {poziomgornictwo::%player%} > 0:
					if {umkilof::%player%} = "PomocnaDłoń":
						add "&aWYBRANO" to lore of {_1}
					else:
						add "&fKliknij, by wybrać." to lore of {_1}
				else:
					add "&cNIE ODBLOKOWANO" to lore of {_1}
				set slot 2 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_1}
				if {poziomgornictwo::%player%} > 9:
					if {umkilof::%player%} = "Eksplozja":
						add "&aWYBRANO" to lore of {_2}
					else:
						add "&fKliknij, by wybrać." to lore of {_2}
				else:
					add "&cNIE ODBLOKOWANO" to lore of {_2}
				set slot 3 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_2}
				if {poziomgornictwo::%player%} > 19:
					if {umkilof::%player%} = "Zapłon":
						add "&aWYBRANO" to lore of {_3}
					else:
						add "&fKliknij, by wybrać." to lore of {_3}
				else:
					add "&cNIE ODBLOKOWANO" to lore of {_3}
				set slot 4 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_3}
				if {poziomgornictwo::%player%} > 29:
					if {umkilof::%player%} = "Instalacje Ogrzewcze":
						add "&aWYBRANO" to lore of {_4}
					else:
						add "&fKliknij, by wybrać." to lore of {_4}
				else:
					add "&cNIE ODBLOKOWANO" to lore of {_4}
				set slot 5 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_4}
				if {poziomgornictwo::%player%} > 39:
					if {umkilof::%player%} = "Magnes":
						add "&aWYBRANO" to lore of {_5}
					else:
						add "&fKliknij, by wybrać." to lore of {_5}
				else:
					add "&cNIE ODBLOKOWANO" to lore of {_5}
				set slot 6 of (metadata tag "brodatyzacharyChoosePickaxe" of player) to {_5}
			open metadata tag "brodatyzacharyChoosePickaxe" of player to player
	else if event-inventory = metadata tag "brodatyzacharyChoosePickaxe" of player:
		cancel event
		if {language::%player%} = "English":
			set {_success} to "&a&oSuccessfully selected the %uncolored name of event-slot% pickaxe ability!"
			set {_fail} to "&c&oYou do not have this pickaxe ability unlocked."
			set {_already} to "&e&oYou already have this pickaxe ability selected."
		else:
			set {_success} to "&a&oPomyślnie wybrano umiejętność kilofu %uncolored name of event-slot%!"
			set {_fail} to "&c&oNie odblokowano jeszcze tej umiejętności kilofu."
			set {_already} to "&e&oTa umiejętność kilofu jest już aktywna."
		if index of event-slot = 2:
			if {poziomgornictwo::%player%} > 0:
				if {umkilof::%player%} != "PomocnaDłoń":
					set {umkilof::%player%} to "PomocnaDłoń"
					set {_event} to true
				else:
					send {_already} to player
			else:
				set {_event} to false
		else if index of event-slot = 3:
			if {poziomgornictwo::%player%} >= 9:
				if {umkilof::%player%} != "Eksplozja":
					set {umkilof::%player%} to "Eksplozja"
					set {_event} to true
				else:
					send {_already} to player
			else:
				set {_event} to false
		if {_event} = true:
			send {_success} to player
			play sound "entity.bat.takeoff" with volume 4 and pitch 1.35 at player
		else if {_event} = false:
			send {_fail} to player
			play sound "entity.chest.close" with volume 4 and pitch 0.8 at player
	else if event-inventory = metadata tag "Constellation" of player:
		cancel event
		if index of clicked slot = 15:
			if name of clicked slot != "&fAll Constellations Unlocked":
				teleport the player to player's location
				set metadata tag "ConstellationAdd" of player to chest inventory with 3 rows named "Constellation"
				set {_slotIndex} to 0
				loop all items in the player's inventory:
					if line 19 of lore of loop-item contains "&8Id: ":
						if line 19 of lore of loop-item != line 19 of lore of player's tool:
							if name of loop-item = name of player's tool:
								set slot {_slotIndex} of metadata tag "ConstellationAdd" of player to loop-item
								add "%nl%&c&l(&4&l!&c&l) &f&oClick here to exchange this item." to lore of slot {_slotIndex} of metadata tag "ConstellationAdd" of player
								add 1 to {_slotIndex}
				if {_slotIndex} > 0:
					open metadata tag "ConstellationAdd" of player to player
				else:
					play sound "entity.villager.no" with volume 5 and pitch 0.62 to player
					play sound "block.glass.break" with volume 5 and pitch 1.176 to player
					if {language::%player%} = "English":
						send "&c&oThere are no identical cards in your inventory." to player
					else:
						send "&c&oNie ma identycznych kart w twoim ekwipunku." to player
			else:
				play sound "entity.villager.no" with volume 5 and pitch 0.62 to player
				play sound "block.glass.break" with volume 5 and pitch 1.176 to player
				if {language::%player%} = "English":
					send "&c&oThis card's constellation is at max level." to player
				else:
					send "&c&oKonstelacja tej karty jest na maksymalnym poziomie." to player
	else if event-inventory = metadata tag "ConstellationAdd" of player:
		cancel event
		if index of clicked slot is between 0 and 26:
			if clicked slot is not air:
				set metadata tag "ConstellationAddConfirm" of player to chest inventory with 3 rows named "Constellation - Confirm"
				set slot 11 of metadata tag "ConstellationAddConfirm" of player to clicked slot
				set slot 15 of metadata tag "ConstellationAddConfirm" of player to lime stained glass pane named "&aConfirm?" with lore "&7Click here to confirm the process and%nl%&7advance the constellation level.%nl% %nl%&c&l(&4&l!&c&l) &c&nWarning!&c &oThis action will delete the card."
				open metadata tag "ConstellationAddConfirm" of player to player
	else if event-inventory = metadata tag "ConstellationAddConfirm" of player:
		cancel event
		if index of clicked slot is between 0 and 26:
			if clicked slot is not air:
				if clicked slot is lime stained glass pane named "&aConfirm?":
					loop lore of slot 11 of metadata tag "ConstellationAddConfirm" of player:
						if uncolored loop-value does not contain "(!)":
							add loop-value to {_loreItem::*}
					delete {_loreItem::%size of {_loreItem::*}%}
					set {_card} to slot 11 of metadata tag "ConstellationAddConfirm" of player with lore {_loreItem::*}
					loop all items in player's inventory:
						if loop-item = {_card}:
							set {_id} to uncolored line 19 of lore of loop-item
							replace all "Id: " in {_id} with ""
							set {_name} to uncolored name of loop-item
							unload yaml "plugins/Skript/playerdata/karty/%{_name}%/%{_id}%.yml"
							delete yaml "plugins/Skript/playerdata/karty/%{_name}%/%{_id}%.yml"
							remove loop-item from player
							teleport the player to player's location
							set {_idCard} to string tag "Id" of custom nbt of player's tool
							load yaml "plugins/Skript/playerdata/karty/%uncolored name of player's tool%/%{_idCard}%.yml" as "karta-%player%"
							set {_constellation} to yaml value "Card.Constellation" in "karta-%player%"
							add 1 to {_constellation}
							set yaml value "Card.Constellation" in "karta-%player%" to {_constellation}
							save yaml "karta-%player%"
							unload yaml "karta-%player%"
							if {_constellation} = 1:
								set boolean tag "Constellation;%uncolored name of slot 10 of metadata tag "kartagui" of player%" of nbt of player's tool to true
							else if {_constellation} = 2:
								set boolean tag "Constellation;%uncolored name of slot 11 of metadata tag "kartagui" of player%" of nbt of player's tool to true
							else if {_constellation} = 3:
								set boolean tag "Constellation;%uncolored name of slot 12 of metadata tag "kartagui" of player%" of nbt of player's tool to true
							else if {_constellation} = 4:
								set boolean tag "Constellation;%uncolored name of slot 13 of metadata tag "kartagui" of player%" of nbt of player's tool to true
							else if {_constellation} = 5:
								set boolean tag "Constellation;%uncolored name of slot 14 of metadata tag "kartagui" of player%" of nbt of player's tool to true
							else if {_constellation} = 6:
								set boolean tag "Constellation;%uncolored name of slot 15 of metadata tag "kartagui" of player%" of nbt of player's tool to true
							load yaml "plugins/Skript/playerdata/%uuid of player%.yml" as "playerDataConstellation-%player%"
							set {_constellations} to yaml value "Player.Total Constellations" in "playerDataConstellation-%player%"
							if {_constellations} is not set:
								set {_constellations} to 0
							add 1 to {_constellations}
							set yaml value "Player.Total Constellations" in "playerData-%player%" to {_constellations}
							save yaml "playerDataConstellation-%player%"
							unload yaml "playerDataConstellation-%player%"
							play sound "entity.player.levelup" with volume 3 and pitch 0.1 at player
							play sound "entity.firework_rocket.launch" with volume 3 and pitch 0.42 at player
							send "&b&l&l✨ &b&oSuccesfully advanced the constellation level of %name of player's tool%&b&o." to player
							loop 3 times:
								play sound "block.glass.break" with volume 3 and pitch 1.7+(loop-number*0.1) at player
							stop loop

#	if event-inventory = metadata tag "isabela" of player:
#		cancel event
#		set {_id} to line 19 of lore of {karta::%player%}
#		set {_list::*} to 19, 20, 21, 22, 23, 24, 25, 29, 30, 31, 32 and 33
#		if {_list::*} contains index of event-slot:
#			if {dostepnestaty::%{_id}%} > 0:
#				play sound "entity.player.levelup" with volume 5 and pitch 0.22 at player
#				if index of event-slot = 19:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {zdrowie::%{_id}%}
#					add 1 to {zdrowie::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Health. (Total: %{zdrowie::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 19 of metadata tag "isabela" of player to {perydotEN} named "%last color of name of {perydotEN}%Health" with lore "&7&oClick here to spend a stat" and "&7&opoint on Health." and " " and "&7&oTotal Health: %last color of name of {perydotEN}%%{zdrowie::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Zdrowia. (Łącznie: %{zdrowie::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 19 of metadata tag "isabela" of player to {perydot} named "%last color of name of {perydot}%Zdrowie" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Zdrowie." and " " and "&7&oTotal Zdrowie: %last color of name of {perydot}%%{zdrowie::%{_id}%}%"
#					set max health of player to 25 + ({health::%player%}/5)
#					set scaled health of player to 20
#				if index of event-slot = 20:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {obrazenia::%{_id}%}
#					add 1 to {obrazenia::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Damage. (Total: %{obrazenia::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 20 of metadata tag "isabela" of player to {rubinEN} named "%last color of name of {rubinEN}%Damage" with lore "&7&oClick here to spend a stat" and "&7&opoint on Damage." and " " and "&7&oTotal Damage: %last color of name of {rubinEN}%%{obrazenia::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Obraźeń. (Łącznie: %{obrazenia::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 20 of metadata tag "isabela" of player to {rubin} named "%last color of name of {rubin}%Obrażenia" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Obrażenia." and " " and "&7&oŁączne Obrażenia: %last color of name of {rubin}%%{obrazenia::%{_id}%}%"
#				if index of event-slot = 21:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {wytrzymalosc::%{_id}%}
#					add 1 to {wytrzymalosc::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Resistance. (Total: %{wytrzymalosc::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 21 of metadata tag "isabela" of player to {topazEN} named "%last color of name of {topazEN}%Resistance" with lore "&7&oClick here to spend a stat" and "&7&opoint on Resistance." and " " and "&7&oTotal Resistance: %last color of name of {topazEN}%%{wytrzymalosc::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Wytrzymałości. (Łącznie: %{wytrzymalosc::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 21 of metadata tag "isabela" of player to {topaz} named "%last color of name of {topaz}%Wytrzymałość" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Wytrzymałość." and " " and "&7&oŁączna Wytrzymałość: %last color of name of {topaz}%%{wytrzymalosc::%{_id}%}%"
#				if index of event-slot = 22:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {mobilnosc::%{_id}%}
#					add 1 to {mobilnosc::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Mobility. (Total: %{mobilnosc::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 22 of metadata tag "isabela" of player to {perlaEN} named "%last color of name of {perlaEN}%Mobility" with lore "&7&oClick here to spend a stat" and "&7&opoint on Mobility." and " " and "&7&oTotal Mobility: %last color of name of {topazEN}%%{mobilnosc::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Mobilności. (Łącznie: %{mobilnosc::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 22 of metadata tag "isabela" of player to {perla} named "%last color of name of {perla}%Mobilność" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Mobilność." and " " and "&7&oŁączna Mobilność: %last color of name of {topaz}%%{mobilnosc::%{_id}%}%"
#					set player's walking speed to 0.2 + ({mobility::%player%}/2000)
#				if index of event-slot = 23:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {uzytecznosc::%{_id}%}
#					add 1 to {uzytecznosc::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Utility. (Total: %{uzytecznosc::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 23 of metadata tag "isabela" of player to {ametystEN} named "%last color of name of {ametystEN}%Utility" with lore "&7&oClick here to spend a stat" and "&7&opoint on Utility." and " " and "&7&oTotal Utility: %last color of name of {ametystEN}%%{uzytecznosc::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Użyteczności. (Łącznie: %{uzytecznosc::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 23 of metadata tag "isabela" of player to {ametyst} named "%last color of name of {ametyst}%Użyteczność" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Użyteczność." and " " and "&7&oŁączna Użyteczność: %last color of name of {ametyst}%%{uzytecznosc::%{_id}%}%"
#				if index of event-slot = 24:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {kontrolatlumu::%{_id}%}
#					add 1 to {kontrolatlumu::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Crowd Control. (Total: %{kontrolatlumu::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 24 of metadata tag "isabela" of player to {akwamarynEN} named "%last color of name of {akwamarynEN}%Crowd Control" with lore "&7&oClick here to spend a stat" and "&7&opoint on Crowd Control." and " " and "&7&oTotal Crowd Control: %last color of name of {akwamarynEN}%%{kontrolatlumu::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Kontroli Tłumu. (Łącznie: %{kontrolatlumu::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 24 of metadata tag "isabela" of player to {akwamaryn} named "%last color of name of {akwamaryn}%Kontrola Tłumu" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Kontrolę Tłumu." and " " and "&7&oŁączna Kontrola Tłumu: %last color of name of {akwamaryn}%%{kontrolatlumu::%{_id}%}%"
#				if index of event-slot = 25:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {uniwersalnosc::%{_id}%}
#					add 1 to {uniwersalnosc::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Versatility. (Total: %{uniwersalnosc::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 25 of metadata tag "isabela" of player to {opalEN} named "%last color of name of {opalEN}%Versatility" with lore "&7&oClick here to spend a stat" and "&7&opoint on Versatility." and " " and "&7&oTotal Versatility: %last color of name of {opalEN}%%{uniwersalnosc::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Uniwersalności. (Łącznie: %{uniwersalnosc::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 25 of metadata tag "isabela" of player to {opal} named "%last color of name of {opal}%Uniwersalność" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Uniwersalność." and " " and "&7&oŁączna Uniwersalność: %last color of name of {opal}%%{uniwersalnosc::%{_id}%}%"
#				if index of event-slot = 29:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {mistrzostwo::%{_id}%}
#					add 1 to {mistrzostwo::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Mastery. (Total: %{mistrzostwo::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 29 of metadata tag "isabela" of player to {turmalinEN} named "%last color of name of {turmalinEN}%Mastery" with lore "&7&oClick here to spend a stat" and "&7&opoint on Mastery." and " " and "&7&oTotal Mastery: %last color of name of {turmalinEN}%%{mistrzostwo::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Mistrzostwa. (Łącznie: %{mistrzostwo::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 29 of metadata tag "isabela" of player to {turmalin} named "%last color of name of {turmalin}%Mistrzostwo" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Mistrzostwo." and " " and "&7&oŁączne Mistrzostwo: %last color of name of {turmalin}%%{mistrzostwo::%{_id}%}%"
#				if index of event-slot = 30:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {crit::%{_id}%}
#					add 1 to {crit::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Critical Strike. (Total: %{crit::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 30 of metadata tag "isabela" of player to {cytrynEN} named "%last color of name of {cytrynEN}%Critical Hit" with lore "&7&oClick here to spend a stat" and "&7&opoint on Critical Hit." and " " and "&7&oTotal Critical Hit: %last color of name of {cytrynEN}%%{crit::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Trafienia Krytycznego. (Łącznie: %{crit::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 30 of metadata tag "isabela" of player to {cytryn} named "%last color of name of {cytryn}%Cios Krytyczny" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Cios Krytyczny." and " " and "&7&oŁączny Cios Krytyczny: %last color of name of {cytryn}%%{crit::%{_id}%}%"
#				if index of event-slot = 31:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {zywiol::%{_id}%}
#					add 1 to {zywiol::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Element. (Total: %{zywiol::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 31 of metadata tag "isabela" of player to {awenturynEN} named "%last color of name of {awenturynEN}%Element" with lore "&7&oClick here to spend a stat" and "&7&opoint on Element." and " " and "&7&oTotal Element: %last color of name of {awenturynEN}%%{zywiol::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Żywiołu. (Łącznie: %{zywiol::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 31 of metadata tag "isabela" of player to {awenturyn} named "%last color of name of {awenturyn}%Żywioł" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Żywioł." and " " and "&7&oŁączny Żywioł: %last color of name of {awenturyn}%%{zywiol::%{_id}%}%"
#				if index of event-slot = 32:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {pospiech::%{_id}%}
#					add 1 to {pospiech::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Haste. (Total: %{pospiech::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 32 of metadata tag "isabela" of player to {jadeitEN} named "%last color of name of {jadeitEN}%Haste" with lore "&7&oClick here to spend a stat" and "&7&opoint on Haste." and " " and "&7&oTotal Haste: %last color of name of {jadeitEN}%%{pospiech::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Pośpiechu. (Łącznie: %{pospiech::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 32 of metadata tag "isabela" of player to {jadeit} named "%last color of name of {jadeit}%Pośpiech" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Pośpiech." and " " and "&7&oŁączny Pośpiech: %last color of name of {jadeit}%%{pospiech::%{_id}%}%"
#				if index of event-slot = 33:
#					remove 1 from {dostepnestaty::%{_id}%}
#					add 1 to {unik::%{_id}%}
#					add 1 to {unik::poziom::%{_id}%}
#					if {language::%player%} = "English":
#						send "&bYour card gains +1 in Avoidance. (Total: %{unik::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
#						set slot 33 of metadata tag "isabela" of player to {szafirEN} named "%last color of name of {szafirEN}%Avoidance" with lore "&7&oClick here to spend a stat" and "&7&opoint on Avoidance." and " " and "&7&oTotal Avoidance: %last color of name of {szafirEN}%%{unik::%{_id}%}%"
#					else:
#						send "&bTwoja karta otrzymała +1 do Uniku. (Łącznie: %{unik::%{_id}%}%)" to player
#						set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
#						set slot 33 of metadata tag "isabela" of player to {szafir} named "%last color of name of {szafir}%Unik" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Unik." and " " and "&7&oŁączny Unik: %last color of name of {szafir}%%{unik::%{_id}%}%"
#			else:
#				if {language::%player%} = "English":
#					send "&cYou can't assign any more stat points." to player
#				else:
#					send "&cNie masz żadnych punktów stat do przyznania." to player
#				play sound "block.glass.break" with volume 3 and pitch 2 to player
			
#command /npccreate [<text>] [<text>] [<number>]:
	#description: Tworzy NPC.
	#trigger:
		#if arg-1 is "ilosc":
		#	if arg-2 is "cytatow":
				#if target of player is a player:
					#set {_t} to target of player
				#	set {_x} to arg-3
					#send "ustawiono %{_x}% dialogów dla npc &a%{npcnazwa::%{_t}%}%"
					
#another day another slay period girl


#if clicked player's name = "Isabela":
		#set {_id} to line 19 of lore of {karta::%player%}
		#if {_id} = line 19 of lore of player's tool:
		#	cancel event
		#	play sound "entity.wandering_trader.reappeared" with volume 4 and pitch 1.3 to player
		#	wait 2 ticks
		#	if {language::%player%} = "English":
		#		set metadata tag "isabela" of player to chest inventory with 5 rows named "Stats / Level"
		#		set slot integers between 0 and 53 of metadata tag "isabela" of player to black stained glass pane named " "
		#		set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Stat Points Available" with lore "&7&oYou can assign &3%{dostepnestaty::%{_id}%}% &7&ostats."
		#		set slot 19 of metadata tag "isabela" of player to {perydotEN} named "%last color of name of {perydotEN}%Health" with lore "&7&oClick here to spend a stat" and "&7&opoint on Health." and " " and "&7&oTotal Health: %last color of name of {perydotEN}%%{zdrowie::%{_id}%}%"
		#		set slot 20 of metadata tag "isabela" of player to {rubinEN} named "%last color of name of {rubinEN}%Damage" with lore "&7&oClick here to spend a stat" and "&7&opoint on Damage." and " " and "&7&oTotal Damage: %last color of name of {rubinEN}%%{obrazenia::%{_id}%}%"
		#		set slot 21 of metadata tag "isabela" of player to {topazEN} named "%last color of name of {topazEN}%Resistance" with lore "&7&oClick here to spend a stat" and "&7&opoint on Resistance." and " " and "&7&oTotal Resistance: %last color of name of {topazEN}%%{wytrzymalosc::%{_id}%}%"
		#		set slot 22 of metadata tag "isabela" of player to {perlaEN} named "%last color of name of {perlaEN}%Mobility" with lore "&7&oClick here to spend a stat" and "&7&opoint on Mobility." and " " and "&7&oTotal Mobility: %last color of name of {perlaEN}%%{mobilnosc::%{_id}%}%"
		#		set slot 23 of metadata tag "isabela" of player to {ametystEN} named "%last color of name of {ametystEN}%Utility" with lore "&7&oClick here to spend a stat" and "&7&opoint on Utility." and " " and "&7&oTotal Utility: %last color of name of {ametystEN}%%{uzytecznosc::%{_id}%}%"
		#		set slot 24 of metadata tag "isabela" of player to {akwamarynEN} named "%last color of name of {akwamarynEN}%Crowd Control" with lore "&7&oClick here to spend a stat" and "&7&opoint on Crowd Control." and " " and "&7&oTotal Crowd Control: %last color of name of {akwamarynEN}%%{kontrolatlumu::%{_id}%}%"
		#		set slot 25 of metadata tag "isabela" of player to {opalEN} named "%last color of name of {opalEN}%Versatility" with lore "&7&oClick here to spend a stat" and "&7&opoint on Versatility." and " " and "&7&oTotal Versatility: %last color of name of {opalEN}%%{uniwersalnosc::%{_id}%}%"
		#		set slot 29 of metadata tag "isabela" of player to {turmalinEN} named "%last color of name of {turmalinEN}%Mastery" with lore "&7&oClick here to spend a stat" and "&7&opoint on Mastery." and " " and "&7&oTotal Mastery: %last color of name of {turmalinEN}%%{mistrzostwo::%{_id}%}%"
		#		set slot 30 of metadata tag "isabela" of player to {cytrynEN} named "%last color of name of {cytrynEN}%Critical Hit" with lore "&7&oClick here to spend a stat" and "&7&opoint on Critical Hit." and " " and "&7&oTotal Critical Hit: %last color of name of {cytrynEN}%%{crit::%{_id}%}%"
		#		set slot 31 of metadata tag "isabela" of player to {awenturynEN} named "%last color of name of {awenturynEN}%Element" with lore "&7&oClick here to spend a stat" and "&7&opoint on Element." and " " and "&7&oTotal Element: %last color of name of {awenturynEN}%%{zywiol::%{_id}%}%"
		#		set slot 32 of metadata tag "isabela" of player to {jadeitEN} named "%last color of name of {jadeitEN}%Haste" with lore "&7&oClick here to spend a stat" and "&7&opoint on Haste." and " " and "&7&oTotal Haste: %last color of name of {jadeitEN}%%{pospiech::%{_id}%}%"
		#		set slot 33 of metadata tag "isabela" of player to {szafirEN} named "%last color of name of {szafirEN}%Avoidance" with lore "&7&oClick here to spend a stat" and "&7&opoint on Avoidance." and " " and "&7&oTotal Avoidance: %last color of name of {szafirEN}%%{unik::%{_id}%}%"
		#	else:
		#		set metadata tag "isabela" of player to chest inventory with 5 rows named "Staty / Poziom"
		#		set slot integers between 0 and 53 of metadata tag "isabela" of player to black stained glass pane named " "
		#		set slot 13 of metadata tag "isabela" of player to cyan stained glass pane named "&3Dostępne Punkty Stat" with lore " " and "&7Możesz przyznać &3%{dostepnestaty::%{_id}%}% &7stat."
		#		set slot 19 of metadata tag "isabela" of player to {perydot} named "%last color of name of {perydot}%Zdrowie" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Zdrowie." and " " and "&7&oTotal Zdrowie: %last color of name of {perydot}%%{zdrowie::%{_id}%}%"
		#		set slot 20 of metadata tag "isabela" of player to {rubin} named "%last color of name of {rubin}%Obrażenia" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Obrażenia." and " " and "&7&oŁączne Obrażenia: %last color of name of {rubin}%%{obrazenia::%{_id}%}%"
		#		set slot 21 of metadata tag "isabela" of player to {topaz} named "%last color of name of {topaz}%Wytrzymałość" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Wytrzymałość." and " " and "&7&oŁączna Wytrzymałość: %last color of name of {topaz}%%{wytrzymalosc::%{_id}%}%"
		#		set slot 22 of metadata tag "isabela" of player to {perla} named "%last color of name of {perla}%Mobilność" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Mobilność." and " " and "&7&oŁączna Mobilność: %last color of name of {perla}%%{mobilnosc::%{_id}%}%"
		#		set slot 23 of metadata tag "isabela" of player to {ametyst} named "%last color of name of {ametyst}%Użyteczność" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Użyteczność." and " " and "&7&oŁączna Użyteczność: %last color of name of {ametyst}%%{uzytecznosc::%{_id}%}%"
		#		set slot 24 of metadata tag "isabela" of player to {akwamaryn} named "%last color of name of {akwamaryn}%Kontrola Tłumu" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Kontrolę Tłumu." and " " and "&7&oŁączna Kontrola Tłumu: %last color of name of {akwamaryn}%%{kontrolatlumu::%{_id}%}%"
		#		set slot 25 of metadata tag "isabela" of player to {opal} named "%last color of name of {opal}%Uniwersalność" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Uniwersalność." and " " and "&7&oŁączna Uniwersalność: %last color of name of {opal}%%{uniwersalnosc::%{_id}%}%"
		#		set slot 29 of metadata tag "isabela" of player to {turmalin} named "%last color of name of {turmalin}%Mistrzostwo" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Mistrzostwo." and " " and "&7&oŁączne Mistrzostwo: %last color of name of {turmalin}%%{mistrzostwo::%{_id}%}%"
		#		set slot 30 of metadata tag "isabela" of player to {cytryn} named "%last color of name of {cytryn}%Cios Krytyczny" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Cios Krytyczny." and " " and "&7&oŁączny Cios Krytyczny: %last color of name of {cytryn}%%{crit::%{_id}%}%"
		#		set slot 31 of metadata tag "isabela" of player to {awenturyn} named "%last color of name of {awenturyn}%Żywioł" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Żywioł." and " " and "&7&oŁączny Żywioł: %last color of name of {awenturyn}%%{zywiol::%{_id}%}%"
		#		set slot 32 of metadata tag "isabela" of player to {jadeit} named "%last color of name of {jadeit}%Pośpiech" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Pośpiech." and " " and "&7&oŁączny Pośpiech: %last color of name of {jadeit}%%{pospiech::%{_id}%}%"
		#		set slot 33 of metadata tag "isabela" of player to {szafir} named "%last color of name of {szafir}%Unik" with lore "&7&oKliknij tu, by wydać punkt" and "&7&ostaty na Unik." and " " and "&7&oŁączny Unik: %last color of name of {szafir}%%{unik::%{_id}%}%"
		#	open metadata tag "isabela" of player to player
		#else:
		#	if cooldown "isabelaclick%player%" is finished:
		#		create cooldown "isabelaclick%player%" for 5 seconds
		#		play sound "entity.villager.yes" with volume 4 and pitch 1.3 to player
		#		if {language::%player%} = "English":
		#			send "&8[<##f2b891>NPC&8] &8<<##f2b891>Isabela&8> &fWelcome! I can assist you in adding stats to your card for your efforts." to player
		#			send "&7&o*Right click on &o<##f2b891>Isabela &7&oholding a card to open the card stat menu.*" to player
		#			play sound "block.note_block.pling" with volume 4 and pitch 1.7 to player
		#		else:
		#			send "&8[<##f2b891>NPC&8] &8<<##f2b891>Isabela&8> &fWitaj! Mogę pomóć ci w dodawaniu statystyk dla twojej karty za osiągnięte poziomy." to player
		#			send "&7&o*Kliknij prawym na &o<##f2b891>Isabelę &7&otrzymając kartę w ręce, by otworzyć menu dodawania statystyk.*" to player
		#			play sound "block.note_block.pling" with volume 4 and pitch 1.7 to player