options:
	maxEcs: 6
	
on join:
	load yaml "plugins/Skript/playerdata/%uuid of player%.yml" as "data-%player%"
	load yaml "plugins/Skript/playerdata/enderchesty/Enderchest-%uuid of player%.yml" as "Enderchest%player%"
	load yaml "plugins/Skript/playerdata/variants/%uuid of player%" as "Variants%player%"
	load yaml "plugins/Skript/playerdata/worldquests/%uuid of player%" as "WorldQuests%player%"
	load yaml "plugins/Skript/playerdata/reputation/%uuid of player%" as "Reputation%player%"
	load yaml "plugins/Skript/playerdata/ItemClaim/%uuid of player%" as "ItemClaim-%player%"

	loop {@maxEcs} times:
		load yaml "plugins/Skript/playerdata/enderchesty/contents/%uuid of player%/%loop-number%.yml" as "Enderchest%loop-number%%player%"

	if metadata value "ECEngaged" of player is not set:
		SetPlayerStats(player) #Sets player stats to current selected card's stats (funkcje.sk)
		
	if {karta::%player%} is set:
		set {_primaryStatType} to string tag "PrimaryStat" of (custom nbt of {karta::%player%})
		set metadata value "PrimaryStatType" of player to {_primaryStatType}
		set {_idCard} to string tag "Id" of (custom nbt of {karta::%player%})
		set {_cardName} to uncolored name of {karta::%player%}
		load yaml "plugins/Skript/playerdata/karty/%{_cardName}%/%{_idCard}%.yml" as "activeCard-%player%"

	if {kolorek1::%player%} is set:
		set {_color} to raw {kolorek1::%player%}
		replace all "<" and ">" in {_color} with ""
	else:
		set {_color} to "ffffff"

	loop getActiveWorldQuests():
		set {_worldQuest} to loop-value
		set {_wqType} to yaml value "World Quests.%{_worldQuest}%.Type" in "WorldQuestList"
		loop yaml node keys "Tasks.%{_wqType}%.%{_worldQuest}%" in "WorldQuestList":
			set {_element} to loop-value-2
			if yaml value "%{_wqType}%.%{_worldQuest}%.%{_element}%.Completed" in "WorldQuests%player%" is not set:
				set yaml value "%{_wqType}%.%{_worldQuest}%.%{_element}%.Completed" in "WorldQuests%player%" to 0

	set yaml value "Player.Name" in "data-%player%" to name of player
	set yaml value "Player.Last Login" in "data-%player%" to data()
	set yaml value "Player.Colour" in "data-%player%" to {_color}
	set yaml value "Player.Level" in "data-%player%" to {poziom::%player%}
	set yaml value "Player.Exp" in "data-%player%" to round({exp::%player%}, 2)

	set yaml value "Player.Name" in "data-%player%" to name of player
	set yaml value "Player.UUID" in "data-%player%" to "%uuid of player%"
	set yaml value "Player.Location" in "data-%player%" to location of player

	if yaml list "Player.Name History" in "data-%player%" does not contain player's name:
		add player's name to yaml list "Player.Name History" in "data-%player%" 

	if yaml value "Unlocked Content" in "data-%player%" is not set:
		load yaml "plugins/Skript/lists/ContentList.yml" as "ContentList"
		set {_contentList::*} to yaml list "Content List" in "ContentList"
		loop {_contentList::*}:
			set yaml value "Unlocked Content.%loop-value%" in "data-%player%" to false

	updateAllTimeVariables(player)

	save yaml "data-%player%"
	save yaml "WorldQuests%player%"
	save yaml "ItemClaim-%player%"

	set {playersOnline::*} to all players

	set {_region} to (join "%regions at player%" by "")
	UnfreezeWorldQuestMobsInRegion(player, {_region})

	if boolean tag "HeartOfEarthcraft" of (custom nbt of player's chestplate) is set:
		applyArtifactKnowledge(player)
		if {azeriteStash::%uuid of player%} > 0:
			addAzerite(player, {azeriteStash::%uuid of player%})
			clear {azeriteStash::%uuid of player%}

	set {_size} to size of (yaml list "Player.Item Claim" in "data-%player%")
	if {_size} > 0:
		wait 6 seconds
		play sound "block.note_block.harp" with volume 3 and pitch 1.2 to player
		send "&eYou have &f%{_size}% &eunclaimed items. Type /itemclaim to claim the items." to player

	if party of player is set:
		set {_partymembers::*} to party members of party of player
		loop {_partymembers::*}:
			add (name of loop-value parsed as player) to {_party::*}
		set {_name} to name of party of player

	set {_resetAreas::*} to "groveofimmemorialruins" and "arcticbattlefield"
	loop {_resetAreas::*}:
		if "%world of player%" = "%loop-value%":
			execute player command "spawn"

	
on quit:
	set yaml value "Player.Last Login" in "data-%player%" to now

	save yaml "data-%player%"
	unload yaml "data-%player%"
	save yaml "Enderchest%player%"
	unload yaml "Enderchest%player%"
	unload yaml "Variants%player%"
	save yaml "WorldQuests%player%"
	unload yaml "WorldQuests%player%"
	save yaml "Reputation%player%"
	unload yaml "Reputation%player%"

	save yaml "ItemClaim-%player%"
	unload yaml "ItemClaim-%player%"

	set {playersOnline::*} to all players

	loop {@maxEcs} times:
		save yaml "Enderchest%loop-number%%player%"
		unload yaml "Enderchest%loop-number%%player%"
	if {karta::%player%} is set:
		set {_idCard} to string tag "Id" of (custom nbt of {karta::%player%})
		unload yaml "activeCard-%player%"

	set {_region} to (join "%regions at player%" by "")
	FreezeWorldQuestMobsInRegion(player, {_region})
	
every 1 minute:
	loop all loaded yaml:
		save loop-value
		wait 2 ticks

on skript stop:
	loop all loaded yaml:
		save loop-value
		wait 1 tick

function updateAllTimeVariables(p: player):
	if yaml "data-%{_p}%" is not loaded:
		load yaml "plugins/Skript/playerdata/%uuid of {_p}%.yml" as "data-%{_p}%"
		set {_offline} to true

	set {_allTimeLevel} to yaml value "Player.All Time.Level" in "data-%{_p}%"
	if {_allTimeLevel} is not set:
		set {_allTimeLevel} to 0
	set {alltimelevel::%{_p}%} to {_allTimeLevel}

	set {_allTimeMobKills} to yaml value "Player.All Time.Mob Kills" in "data-%{_p}%"
	if {_allTimeMobKills} is not set:
		set {_allTimeMobKills} to 0
	set {alltimemobkills::%{_p}%} to {_allTimeMobKills}

	set {_allTimeStone} to yaml value "Player.All Time.Stone Mined" in "data-%{_p}%"
	if {_allTimeStone} is not set:
		set {_allTimeStone} to 0
	set {alltimestone::%{_p}%} to {_allTimeStone}

	set {_siegeLevel} to yaml value "Player.Per Update.Siege of Spawn.Level" in "data-%{_p}%"
	if {_siegeLevel} is not set:
		set {_siegeLevel} to 0
	set {historiclevel::siegeofspawn::%{_p}%} to {_siegeLevel}

	set {_siegeMobKills} to yaml value "Player.Per Update.Siege of Spawn.Mob Kills" in "data-%{_p}%"
	if {_siegeMobKills} is not set:
		set {_siegeMobKills} to 0
	set {historicmobkills::siegeofspawn::%{_p}%} to {_siegeMobKills}

	set {_siegeStone} to yaml value "Player.Per Update.Siege of Spawn.Stone Mined" in "data-%{_p}%"
	if {_siegeStone} is not set:
		set {_siegeStone} to 0
	set {historicstonemined::siegeofspawn::%{_p}%} to {_siegeStone}

	save yaml "data-%{_p}%"

	if {_offline} = true:
		unload yaml "data-%{_p}%"