command /targetdummy [<text>] [<text>] [<number>]:
	trigger:
		if player's name is "kapoonfleek" or "llamadegree" or "Pehrek":
			if arg-1 = "zombie":
				spawn 1 adult zombie at player
				silence last spawned zombie
				set boolean tag "ECMob" of (custom nbt of last spawned zombie) to true
				set boolean tag "ECTestEntity" of (custom nbt of last spawned zombie) to true
				set max health of last spawned zombie to 100000
				heal last spawned zombie
				set the display name of last spawned zombie to "&aTarget Dummy &7[&a&l%last spawned zombie's health%&c&l♥&7]"
				add nbt from "{NoAI:1b}" to nbt of last spawned zombie
				onECMobSpawn(last spawned zombie)
			if arg-1 = "spider":
				spawn 1 spider at player
				silence last spawned spider
				set boolean tag "ECMob" of (custom nbt of last spawned spider) to true
				set boolean tag "ECTestEntity" of (custom nbt of last spawned spider) to true
				set max health of last spawned spider to 100000
				heal last spawned spider
				set the display name of last spawned spider to "&aTarget Dummy &7[&a&l%last spawned spider's health%&c&l♥&7]"
				add nbt from "{NoAI:1b}" to nbt of last spawned spider
				onECMobSpawn(last spawned spider)
			if arg-1 = "mob":
				spawn 1 adult zombie at player
				silence last spawned zombie
				set boolean tag "ECMob" of (custom nbt of last spawned zombie) to true
				set boolean tag "ECTestEntity" of (custom nbt of last spawned zombie) to true
				set max health of last spawned zombie to arg-3
				heal last spawned zombie
				set the display name of last spawned zombie to "&aTest Mob &7[&a&l%last spawned zombie's health%&c&l♥&7]"
				set string tag "ECElement" of (custom nbt of last spawned zombie) to arg-2
				onECMobSpawn(last spawned zombie)
on damage:
	if victim is a zombie or a spider:
		if name of victim is "&aTarget Dummy":
			set {_health} to health of victim
			set {_health2} to health of victim - final damage
			wait 1 second
			heal victim
			set the display name of victim to "&aTarget Dummy &7[&a&l%victim's health%&c&l♥&7]"
