on load:
    set {_int} to "&7Poziom: &f0 &7| &7Exp: &f0%nl%&7Statystyki:%nl%&7Intelekt: &7■■■■■■■■■■ &7(<##59c1e3>0&7)"
    set {_intEN} to "&7Level: &f0 &7| &7Exp: &f0%nl%&7Statistics:%nl%&7Intellect: &7■■■■■■■■■■ &7(<##59c1e3>0&7)"
    set {_str} to "&7Poziom: &f0 &7| &7Exp: &f0%nl%&7Statystyki:%nl%&7Siła: &7■■■■■■■■■■ &7(<##e35959>0&7)"
    set {_strEN} to "&7Level: &f0 &7| &7Exp: &f0%nl%&7Statistics:%nl%&7Strength: &7■■■■■■■■■■ &7(<##e35959>0&7)"
    set {_stats} to "&7Zdrowie: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Obrażenia: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Wytrzymałość: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobilność: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Użyteczność: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Kontrola Tłumu: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Uniwersalność: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mistrzostwo: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Cios Krytyczny: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Żywioł: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Pośpiech: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Unik: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
    set {_statsEN} to "&7Health: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Damage: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Resistance: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobility: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Utility: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Crowd Control: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Versatility: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mastery: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Critical Hit: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Element: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Haste: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Avoidance: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)"
    set {glaceonstarter} to light blue stained glass pane named "<##4bbfe2>Glaceon" with lore "&7Świeży Śnieg" and {_int} and {_stats} and "&7Żywioł: <##add8e6>Lód" and "&7Źródło: <##4bbfe2>Starter" with nbt compound from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
    set {vaporeonstarter} to cyan stained glass pane named "<##7cafbf>Vaporeon" with lore "&7Strumień" and {_int} and {_stats} and "&7Żywioł: <##1ebbd7>Woda" and "&7Źródło: <##7cafbf>Starter" with nbt compound from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
    set {umbreonstarter} to black stained glass pane named "<##555555>Umbreon" with lore "&7Blask Księżyca" and {_str} and {_stats} and "&7Żywioł: <##333333>Mrok" and "&7Źródło: <##555555>Starter" with nbt compound from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"
    set {glaceonstarterEN} to light blue stained glass pane named "<##4bbfe2>Glaceon" with lore "&7Fresh Snow" and {_intEN} and {_statsEN} and "&7Element: <##add8e6>Ice" and "&7Source: <##4bbfe2>Starter" with nbt compound from "{""minecraft:custom_model_data"":{floats:[4.0f]}}"
    set {vaporeonstarterEN} to cyan stained glass pane named "<##7cafbf>Vaporeon" with lore "&7Bubble Jet" and {_intEN} and {_statsEN} and "&7Element: <##1ebbd7>Water" and "&7Source: <##7cafbf>Starter" with nbt compound from "{""minecraft:custom_model_data"":{floats:[5.0f]}}"
    set {umbreonstarterEN} to black stained glass pane named "<##555555>Umbreon" with lore "&7Night Huntress" and {_strEN} and {_statsEN} and "&7Element: <##333333>Dark" and "&7Source: <##555555>Starter" with nbt compound from "{""minecraft:custom_model_data"":{floats:[1.0f]}}"

import:
    fr.xephi.authme.events.RegisterEvent
    fr.xephi.authme.api.v3.AuthMeApi

function registerEvent(player: player):
    set {stone::%{_player}%} to 0
    set {poziom::%{_player}%} to 0
    set {cosmicflux::%{_player}%} to 0
    set {stardust::%{_player}%} to 0
    set {exp::%{_player}%} to 0
    set {tutorial::%{_player}%} to true
    set {kartaname::%{_player}%} to "Not set"
    set {sjoin::%{_player}%} to {sjoin::%{_player}%} + 1
    set {_yamlValue} to "Achievement.Player.General.1"
    achievementYaml({_player}, "General", "General+1", 1)
    clear {sjoin::%{_player}%}
    set {pseudonim::%{_player}%} to {_player}'s name
    set {kolorek1::%{_player}%} to "#FFAA00"
    UpdateScoreboard({_player})
    #send "&8[&6Earthcraft&8] &6Witaj, &a%{_player}%&6! Ustaw swój pseudonim komendą /pseudonim. Aby zapoznać się z serwerem, zobacz poradnik, oraz informacje n.t najnowszego update'u na serwerze discord (https://discord.gg/wNVBJjQQ). Udanej gry!" to {_player}
    send "&8[&6Earthcraft&8] &6Welcome, &a%{_player}%&6! You can set your nickname using the /nickname command. If you'd like to learn about the server, please see the tutorial and information about the latest update on our discord server (https://discord.gg/wNVBJjQQ). GLHF!" to {_player}
    set {kartyzalvl::%{_player}%::*} to "Glaceon", "Vaporeon", "Umbreon", "Delphox"
    set {gemhoard::%{_player}%::*} to "Firefox's Gift", "Ghostdragon's Prize", "Harvester's Trophy" and "Siren's Vision"
    set {egems::%{_player}%::*} to "Inscribed Illimited Diamond", "Fierce Illimited Diamond", "Skillful Illimited Diamond" and "Resplendent Illimited Diamond"
    set {_loc} to location(-424.5, 61, -843.5, world "areny")
    set pitch of {_loc} to 0
    set yaw of {_loc} to 0
    set max health of {_player} to 25
    heal {_player}
    set scaled health of {_player} to 20
    teleport {_player} to {_loc}
    Wait({_player}, 1 tick)
    play sound "entity.wandering_trader.reappeared" with volume 5 and pitch 1 to all players
    play sound "block.note_block.bass" with volume 5 and pitch 1 to all players
    set {serverjoins.server} to {serverjoins.server} + 1
    set {players.online} to number of all players
    NewPlayerdata({_player})
    wait 1 tick
    teleport {_player} to {_loc}
    send "&bWe highly recommend playing on GUI scale 3 or less (video settings) for optimal experience." to {_player}

on RegisterEvent:
    set {_player} to event.getPlayer()
    if {poziom::%{_player}%} is not set:
        registerEvent({_player})

on join:
    set the join message to "&8[&6Earthcraft&8] &6%player%&7, welcome to &6Earthcraft&7! :)"
    if {tutorial::%player%} is not set:
        set {tutorial::%player%} to true
        registerEvent(player)

    if {tutorial::%player%} is true:
        send "&aWelcome to Earthcraft 8.3.0, %player%! We hope you'll have fun on the server! :)" to player
        send "&aYou may start the tutorial ahead of you by interacting with &f &eZachary &ato get a brief explanation on the server's mechanics &7(recommended)&a, or head straight through the portal to start your gameplay immediately." to player
        set {_loc} to location(-424.5, 61, -843.5, world "areny")
        teleport the player to {_loc}
        set pitch of {_loc} to 0
        set yaw of {_loc} to 0
        set {tutorial::%player%} to false

        set {_pickaxe} to netherite pickaxe named "&f%player%'s pickaxe"
        enchant {_pickaxe} with efficiency 5
        enchant {_pickaxe} with unbreaking 10
        if player doesn't have {_pickaxe}:
            give player {_pickaxe}

        loop 3 times:
            wait 1 tick 
            teleport the player to {_loc}

        send "&bPick your starter with the /starter comand." to player

    wait 5 seconds
    load yaml "plugins/Skript/playerdata/admin/player/discord/LinkedAccounts.yml" as "Discord"
    if yaml value "Player.Discord Reminders" in "data-%player%" is not "Disabled":
        if yaml value "Player Accounts.%uuid of player%.Discord ID" in "Discord" is not set:
            wait 10 seconds
            play sound "block.note_block.cow_bell" with volume 5 and pitch 1 to player
            send "<##7289da>[EarthCraft Discord] &fYou have not yet linked your <##7289da>Discord &faccount with EarthCraft." to player
            send "<##7289da>[EarthCraft Discord] &fEarthCraft account linking is safe, does not use any external add-on or software to aid with the process and ONLY links the user's <##7289da>Discord &fid and Minecraft UUID." to player
            send "<##7289da>[EarthCraft Discord] &fConnect <##7289da>Discord &fwith EarthCraft &fto receive &c1x Star Shard&f!" to player
            send formatted "<##7289da>[EarthCraft Discord] <command:/discord preferences reminder><tooltip:&fClick here to disable account link messages.>&c[Do not show again]" to player
    unload yaml "Discord"
    #set {_hash} to "da39a3ee5e6b4b0d3255bfef95601890afd80709"
    #send the resource pack from "https://drive.google.com/drive/folders/1wz962-nuD4XAtKwWj4rkGypoDQkgGYAc?usp=drive_link" with hash {_hash} to the player



function NewPlayerdata(p: player):
    if yaml "data-%{_p}%" is not loaded:
        load yaml "plugins/Skript/playerdata/%uuid of {_p}%.yml" as "data-%{_p}%"

    set yaml value "Player.Name" in "data-%{_p}%" to name of {_p}
    set yaml value "Player.Last Login" in "data-%{_p}%" to data()
    set yaml value "Player.Colour" in "data-%{_p}%" to {_color}
    set yaml value "Player.Level" in "data-%{_p}%" to {poziom::%{_p}%}
    set yaml value "Player.Exp" in "data-%{_p}%" to round({exp::%{_p}%}, 2)

    if yaml value "Player.Artifacts Times Upgraded" in "data-%{_p}%" is not set:
        set yaml value "Player.Artifacts Times Upgraded" in "data-%{_p}%" to 0
    if yaml value "Player.Artifacts Times Maxed" in "data-%{_p}%" is not set:
        set yaml value "Player.Artifacts Times Maxed" in "data-%{_p}%" to 0
    if yaml value "Player.Total Constellations" in "data-%{_p}%" is not set:
        set yaml value "Player.Total Constellations" in "data-%{_p}%" to 0
    if yaml value "Player.Stellar Pity" in "data-%{_p}%" is not set:
        set yaml value "Player.Stellar Pity" in "data-%{_p}%" to 0
    if yaml value "Player.Diamond Pity" in "data-%{_p}%" is not set:
        set yaml value "Player.Diamond Pity" in "data-%{_p}%" to 0
    if yaml value "Dungeons.Dungeons Started.Total" in "data-%{_p}%" is not set:
        set yaml value "Dungeons.Dungeons Started.Total" in "data-%{_p}%" to 0
    if yaml value "Dungeons.Dungeons Finished In Time.Total" in "data-%{_p}%" is not set:
        set yaml value "Dungeons.Dungeons Finished In Time.Total" in "data-%{_p}%" to 0
    if yaml value "Dungeons.Dungeons Completed.Total" in "data-%{_p}%" is not set:
        set yaml value "Dungeons.Dungeons Completed.Total" in "data-%{_p}%" to 0
    if yaml value "Dungeons.Dungeons Left.Total" in "data-%{_p}%" is not set:
        set yaml value "Dungeons.Dungeons Left.Total" in "data-%{_p}%" to 0
     
    save yaml "data-%{_p}%"
#Send welcome messages and give players a mini written tutorial
#Ask at the end for gamemode preference and set the {gamemodePreference} variable, or the variable in player yaml

#set everyone's besides wuuzurd gamemodepreerence to creative and survival in test.sk

#ON TUTORIAL COMPLETE, SET SPAWNPOINT TO SPAWN !!!!! IMPORTANT

#You may play through the tutorial, or skip it by stepping through the portal to teleport to spawn and  select your Starter immediately 

#on command:
    #if {tutorial::%player%} is set:
       # send "&c&oYou can not issue any commands while in this area." to player
        #cancel event

on rightclick on a player:
    if name of clicked player = "BrodatyZachary":
        if metadata value "MiningTutorial" of player is not set:
            if cooldown "ZacharyInteract%player%" is finished:
                create cooldown "ZacharyInteract%player%" for 10 seconds 
                make clicked entity swing their hand
                TutorialDialogue(player, " &eZachary &f> &fHello there! Welcome to &6Earthcraft&f!", 0.7, false)
                wait 2.5 seconds
                TutorialDialogue(player, " &eZachary &f> &fMy friends and I have prepared a short introduction for you, where you can learn about the server and its gameplay before you can start your adventure.", 0.9, true)
                wait 5 seconds
                TutorialDialogue(player, " &eZachary &f> &fLet's start with the basics. On &6Earthcraft&f,  mining will be an important part of your experience.", 0.9, true)
                wait 3 seconds
                TutorialDialogue(player, " &eZachary &f> &fThere are 4 different types of items you can obtain from  mining:", 0.9, true)
                wait 1 second
                TutorialDialogue(player, " &eZachary &f> &f-  Klejnots", 1, false)
                wait 1 second
                TutorialDialogue(player, " &eZachary &f> &f-  Gemstones", 1, false)
                wait 1 second
                TutorialDialogue(player, " &eZachary &f> &f-  Essences", 1, false)
                wait 1 second
                TutorialDialogue(player, " &eZachary &f> &f-  Chests", 1, false)
                wait 3 seconds
                TutorialDialogue(player, " &eZachary &f> &fThese items can drop from either eligible blocks, those being  stone and  deepslate. You will also gain EXP and Levels while mining.", 0.9, true)
                wait 4 seconds
                TutorialDialogue(player, " &eZachary &f> &fLet us skip the rest of the pleasantries for now. Simply  mine the  stone to the right of us and I will tell you all about the different types of items you encounter.", 0.9, true)
                if player does not have a stone pickaxe:
                    give player a stone pickaxe named "&fTrusty Pickaxe"
                send " " to player
                send "&a&lGOAL: &fMine the stone behind  &eZachary&f." to player
        else:
            if cooldown "ZacharyInteract%player%" is finished:
                create cooldown "ZacharyInteract%player%" for 5 seconds
                TutorialDialogue(player, " &eZachary &f> &fYour  Mining tutorial is complete, my friends can teach you about other gameplay areas&f! :)", 1, true) 
            #Find the rest of my friends who will teach you about other parts of the server
            #Papito 
    else if name of clicked player = "MalyciaTutorial":
        if metadata value "MiningTutorial" of player is set:
            if cooldown "MalyciaInteract%player%" is finished:
                create cooldown "MalyciaInteract%player%" for 20 seconds
                if metadata value "HasCard" of player is not set:
                    if metadata value "PickStarter" of player is not set:  
                        TutorialDialogue(player, " <##f060af>Malycia &f> &fHey! If you want to learn about  Cards and  Abilities, you've come to the right place!", 1.3, true)
                        wait 3.5 seconds
                        TutorialDialogue(player, " <##f060af>Malycia &f> &fLet's start by having you choose a Starter  Card. Make sure to choose wisely, as you won't be able to change your selection once you pick an option.", 1, true)
                        wait 6 seconds
                        TutorialDialogue(player, " <##f060af>Malycia &f> &fThere are the three Starters:", 1, true)
                        wait 1.75 seconds
                        TutorialDialogue(player, " <##f060af>Malycia &f> &f Glaceon - A ranged caster that specializes in Frost magic.", 1, true)
                        wait 3 seconds
                        TutorialDialogue(player, " <##f060af>Malycia &f> &f Umbreon - A melee assassin who prefers to stay out of sight.", 1.1, false)
                        wait 3.75 seconds
                        TutorialDialogue(player, " <##f060af>Malycia &f> &f Vaporeon - A healer that uses water to shield and restore health to their allies.", 1.2, false)
                        wait 5 seconds
                        TutorialDialogue(player, " <##f060af>Malycia &f> You can read the detailed descriptions of each of the Card's abilities by hovering over an ability in your inventory.", 1, true)
                        wait 5 seconds
                        TutorialDialogue(player, " <##f060af>Malycia &f> &fYou may test the different Starters at your leisure. To select a starter as your active Card, simply right-click while holding the Card.", 1, true)
                        play sound "entity.player.levelup" with volume 3 and pitch 1 to player
                        set {_karta} to {glaceonstarterEN}
                        add nbt from "{Stats:{Intellect:0,Health:0,Damage:0,Resistance:0,Mobility:0,Utility:0,'Crowd Control':0,Versatility:0,Mastery:0,'Critical Hit':0,Element:0,Haste:0,Avoidance:0,Total:0}}" to nbt of {_karta}
                        set {_y} to data()
                        set {_id} to random 8 char string from charset `0-9` `a-z`
                        add "&8Id: 00000000" to lore of {_karta}
                        add "&8Dropped: %{_y}%" to lore of {_karta}
                        give {_karta} to player
                        set metadata value "HasCard" of player to true
                        set {_karta} to {umbreonstarterEN}
                        add nbt from "{Stats:{Strength:0,Health:0,Damage:0,Resistance:0,Mobility:0,Utility:0,'Crowd Control':0,Versatility:0,Mastery:0,'Critical Hit':0,Element:0,Haste:0,Avoidance:0,Total:0}}" to nbt of {_karta}
                        set {_y} to data()
                        set {_id} to random 8 char string from charset `0-9` `a-z`
                        add "&8Id: 10000000" to lore of {_karta}
                        add "&8Dropped: %{_y}%" to lore of {_karta}
                        give {_karta} to player
                        set {_karta} to {vaporeonstarterEN}
                        add nbt from "{Stats:{Intellect:0,Health:0,Damage:0,Resistance:0,Mobility:0,Utility:0,'Crowd Control':0,Versatility:0,Mastery:0,'Critical Hit':0,Element:0,Haste:0,Avoidance:0,Total:0}}" to nbt of {_karta}
                        set {_y} to data()
                        set {_id} to random 8 char string from charset `0-9` `a-z`
                        add "&8Id: 20000000" to lore of {_karta}
                        add "&8Dropped: %{_y}%" to lore of {_karta}
                        give {_karta} to player
                        wait 4 seconds
                        TutorialDialogue(player, " <##f060af>Malycia &f> &fTalk to me again when you've tested the Cards you just received.", 1, true)
                        set metadata value "PickStarter" of player to true
                    else:
                        TutorialDialogue(player, " <##f060af>Malycia &f> &fExcellent! Let's pick you a starter.", 1, true)
                        wait 2 seconds
                        TutorialDialogue(player, " <##f060af>Malycia &f> &fTo pick a Starter, simply click on one of the Cards in chat.", 1, true)
                #clear all cards that are not the select starter card when the player leaves the tutorial area
        else:
            if cooldown "MalyciaInteract%player%" is finished:
                create cooldown "MalyciaInteract%player%" for 5 seconds
                TutorialDialogue(player, " <##f060af>Malycia &f> &fYou must finish the  Mining tutorial first before I can tell you about  Cards and  Abilities.", 1.3, true) 

on region enter:
    if "%region%" contains "TutorialPortalSpawn":
        play sound "block.portal.travel" with volume 2 and pitch 1 at player
        loop 2 times:
            teleport the player to location(9270.5, 69.5, 1587.5, world "world")
        play sound "block.portal.travel" with volume 2 and pitch 1 to player
        clear {tutorial::%player%}

function CombatTutorial(p: player):
    if metadata value "ECEngaged" of {_p} is set:
        set metadata value "ECEngaged" of {_p} to 2
    clear metadata value "HasCard" of {_p}
    set {_card} to metadata value "CurrentCardTesting" of {_p}
    clear metadata value "CurrentCardTesting" of {_p}
    set {_cardsTested} to metadata value "CardsTested" of {_p}
    set {_cardsTested} to {_cardsTested} + 1
    set metadata value "CardsTested" of {_p} to {_cardsTested}
    set metadata value "CannotUseAbilities" of {_p} to true
    if {_cardsTested} < 3:
        TutorialDialogue({_p}, " <##f060af>Malycia &f> Excellent! Let's move on to the next Card.", 1, true)
    else if {_cardsTested} = 3:
        TutorialDialogue({_p}, " <##f060af>Malycia &f> And that was the last Card! Let us wrap the Ability rundown up and pick you a Starter!.", 1, true)
        clear metadata value "CardsTested" of {_p}
    set {_abilityAndCardList::*} to (name of {glaceonstarterEN}), "<##4bbfe2>Shatter", "<##4bbfe2>Frostbolt", "<##4bbfe2>Ice Lance", "<##4bbfe2>Flurry" and "<##4bbfe2>Icy Veins"
    set {_abilityAndCardList::*} to {_abilityAndCardList::*} and (name of {umbreonstarterEN}), "<##555555>Night Hunter", "<##555555>Night Slash", "<##555555>Moonlight Orb" and "<##555555>End Game"
    loop all items in the inventory of {_p}:
        if {_abilityAndCardList::*} contains name of loop-item:
            remove loop-item from the inventory of {_p}

function TutorialDialogue(p: player, dialogueText: string, soundPitch: number, emptyLine: boolean = true):
    if {_emptyLine} = true:
        send "" to {_p}
    send {_dialogueText} to {_p}
    play sound "entity.villager.yes" with volume 3 and pitch {_soundPitch} to {_p}

function StoneRefresh(loc: location):
    wait 5 seconds
    set block at {_loc} to stone

function StoneTutorial(p: player):
    if metadata value "MiningTutorial" of {_p} is not set:
        set {_stoneTutorial} to metadata value "StoneTutorial" of {_p}
        set {_stoneTutorial} to {_stoneTutorial} + 1
        set metadata value "StoneTutorial" of {_p} to {_stoneTutorial}
        if {_stoneTutorial} is divisible by 10:
            if metadata value "KlejnotTutorial" of {_p} is not set:
                set metadata value "KlejnotTutorial" of {_p} to 1
                give {_p} {klejnotEN}
                wait 0.25 seconds
                TutorialDialogue({_p}, " &eZachary &f> &fCongratulations! You have found a  Klejnot.", 1.2, true)
                wait 3 seconds
                TutorialDialogue({_p}, " &eZachary &f> &f Klejnots are the heart of the server and act as a currency. You can buy anything using  Klejnots!", 1.2, true)
                stop
            if metadata value "GemstoneTutorial" of {_p} is not set:
                set metadata value "GemstoneTutorial" of {_p} to 1
                give {_p} {opalEN}
                wait 0.25 seconds
                TutorialDialogue({_p}, " &eZachary &f> &fCongratulations! You have found an  Opal.", 1.2, true)
                wait 3 seconds
                TutorialDialogue({_p}, " &eZachary &f> &f Gemstones are useful in a multitude of crafting recipes. Their main function, however, is to supply players with power.  Gemstones can be exchanged for <##e3ebff> &fstat points, which  Zach will tell you more about later.", 1.2, true)
                stop
            if metadata value "EssenceTutorial" of {_p} is not set:
                set metadata value "EssenceTutorial" of {_p} to 1
                give {_p} {esencjaogniaEN}
                wait 0.25 seconds
                TutorialDialogue({_p}, " &eZachary &f> &fCongratulations! You have found a  Fire Essence.", 1.2, true)
                wait 3 seconds
                TutorialDialogue({_p}, " &eZachary &f> &f Essences can be used to power up the abilities of your  Cards, or in several crafting recipes, most notably in Alchemy.  Malycia will soon tell you more about  Cards and  Abilities.", 1.2, true)
                stop
            if metadata value "ChestTutorial" of {_p} is not set:
                set metadata value "ChestTutorial" of {_p} to 1
                give {_p} {skrzynkaEN}
                wait 0.25 seconds
                TutorialDialogue({_p}, " &eZachary &f> &fCongratulations! You have found a  Chest.", 1.2, true)
                wait 3 seconds
                TutorialDialogue({_p}, " &eZachary &f> &fAnd finally,  Chests are items that may contain treasure ranging from as common as a  Klejnot to as rare and exclusive as a  Star Shard. Give it a try and open the one you just got at your leisure! :)", 1.2, true)
                wait 5 seconds
                TutorialDialogue({_p}, " &eZachary &f> &fAnd there it is. By now, you should know the basics of  Mining! You may keep the items you just obtained. Make sure to stop by my place at spawn and say hello!", 1.2, true)
                set metadata value "MiningTutorial" of {_p} to true
                clear metadata value "ChestTutorial" of {_p}
                clear metadata value "EssenceTutorial" of {_p}
                clear metadata value "GemstoneTutorial" of {_p}
                clear metadata value "KlejnotTutorial" of {_p}
                clear metadata value "StoneTutorial" of {_p}
                wait 5 seconds
                TutorialDialogue({_p}, " &eZachary &f> &fOh, and P.S.", 1.2, true)
                wait 1 second
                TutorialDialogue({_p}, " &eZachary &f> &f Malycia is waiting for you round the corner!", 1.2, false)
                wait 2.5 seconds
                send "" to {_p}
                send "> &f&lMining tutorial &fcompleted &7(&21/1&7)" to {_p}
                play sound "entity.player.levelup" with volume 2 and pitch 0 to {_p}
