on join:
    if {dataurodzin::%player%} is not set:
        send "&d> You have not yet specified your date of birth. You can do so by using the /birthday (day) (month) (year) command." to player
    if {urodzinydzien::%player%} = true:
        send "&dIt's your birthday! Happy birthday!!!" to player
        launch ball large coloured red, yellow and orange fading to white and brown at player's location with duration 0.2

command /birthday [<integer>] [<integer>] [<integer>]:
    aliases: urodziny
    trigger:
        if {dataurodzin::%player%} is set:
            send "&d> Your birthday date is already set to %{dataurodzin::%player%}%." to player
            play sound "entity.villager.no" with volume 5 and pitch 1 to player
            stop
        if arg-1 is not set:
            send "&d> Usage: /birthday <day> <month> <year>." to player
            play sound "entity.villager.no" with volume 5 and pitch 1 to player
            stop
        if arg-2 is not set:
            send "&d> Usage: /birthday <day> <month> <year>." to player
            play sound "entity.villager.no" with volume 5 and pitch 1 to player
            stop
        if arg-3 is not set:
            send "&d> Usage: /birthday <day> <month> <year>." to player
            play sound "entity.villager.no" with volume 5 and pitch 1 to player
            stop
        if any:
            arg-2 < 1
            arg-2 > 12
        then:
            send "&d> Provided month cannot be lower than 1 or higher than 12." to player
            play sound "entity.villager.no" with volume 5 and pitch 1 to player
            stop
        if arg-3 < 1:
            send "&d> Provided year is not valid." to player
            play sound "entity.villager.no" with volume 5 and pitch 1 to player
            stop
        set {_maxDay} to DaysInMonth(arg-2, arg-3)
        if any:
            arg-1 < 1
            arg-1 > {_maxDay}
        then:
            send "&d> Provided day cannot be lower than 1 or higher than %{_maxDay}% for that month." to player
            play sound "entity.villager.no" with volume 5 and pitch 1 to player
            stop
        set {dataurodzin::%player%} to "%arg-1%.%arg-2%.%arg-3%"
        if yaml "data-%player%" is loaded:
            set yaml value "Player.Profile.Birthday" in "data-%player%" to {dataurodzin::%player%}
            save yaml "data-%player%"
        send "&d> Successfully set your birthday date to %arg-1%.%arg-2%.%arg-3%." to player
        play sound "entity.firework_rocket.twinkle" with volume 5 and pitch 1 at player

function DaysInMonth(month: integer, year: integer) :: integer:
    if {_month} = 2:
        if IsLeapYear({_year}):
            return 29
        return 28
    if {_month} = 4 or 6 or 9 or 11:
        return 30
    return 31

function IsLeapYear(year: integer) :: boolean:
    if mod({_year}, 400) = 0:
        return true
    if mod({_year}, 100) = 0:
        return false
    if mod({_year}, 4) = 0:
        return true
    return false