on join:
    if {dataurodzin::%player%} is not set:
        send "&d> You have not yet specified your date of birth. You can do so by using the /birthday (day) (month) (year) command." to player
    if {urodzinydzien::%player%} = true:
        send "&dIt's your birthday! Happy birthday!!!" to player
        launch ball large coloured red, yellow and orange fading to white and brown at player's location with duration 0.2

command /birthday [<integer>] [<integer>] [<integer>]:
    aliases: urodziny
    trigger:
        if {dataurodzin::%player%} is not set:
            set {_intmsg} to "&dOne of the provided arguments is not a number."
            if arg-1 is an integer:
                if arg-2 is an integer:
                    if arg-3 is an integer:
                        if all:
                            arg-1 <= 31
                            arg-1 > 0
                        then:
                            if all:
                                arg-2 <= 12 
                                arg-2 > 0
                            then:
                                set {dataurodzin::%player%} to "%arg-1%.%arg-2%.%arg-3%"
                                if yaml "data-%player%" is loaded:
                                    set yaml value "Player.Profile.Birthday" in "data-%player%" to {dataurodzin::%player%}
                                    save yaml "data-%player%"
                                send "&d> Successfully set your birthday date to %arg-1%.%arg-2%.%arg-3%." to player
                                play sound "entity.firework_rocket.twinkle" with volume 5 and pitch 1 at player
                            else:
                                send "&d> Provided month cannot be lower than 0 or higher than 12." to player
                                play sound "entity.villager.no" with volume 5 and pitch 1 to player
                        else:
                            send "&d> Provided day cannot be lower than 0 or higher than 12." to player
                            play sound "entity.villager.no" with volume 5 and pitch 1 to player
                    else:
                        send {_intmsg} to player
                else:
                    send {_intmsg} to player
            else:
                send {_intmsg} to player
        else:
            send "&d> Your birthday date is already set to %arg-1%.%arg-2%.%arg-3%." to player
            play sound "entity.villager.no" with volume 5 and pitch 1 to player