on load:
	set {boosterplasmafreezeEN} to glass pane of unbreaking 10 named "&5Plasma Freeze &9Booster" with lore "&9Booster" and "&7Booster containing one or more cards." and "&7May contain exclusive" and "&7cards from this set."
	set {boosterplasmafreeze} to glass pane of unbreaking 10 named "&9Booster &5Plasma Freeze" with lore "&9Booster" and "&7Booster z kartami w których znajduje" and "&7się 1 lub więcej kart." and "&7W środku mogą znajdować się także" and "&7ekskluzywne dla tej serii karty."
	
	set {leafeonkartapf} to lime glass pane named "<##74ba75>Leafeon" with lore "&7Zielenisty" and "&7Poziom: &f0 &7| &7Exp: &f0%nl%&7Statystyki:%nl%&7Siła: &7■■■■■■■■■■ &7(<##e35959>0&7)%nl%&7Zdrowie: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Obrażenia: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Wytrzymałość: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobilność: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Użyteczność: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Kontrola Tłumu: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Uniwersalność: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mistrzostwo: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Cios Krytyczny: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Żywioł: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Pośpiech: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Unik: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)" and "&7Żywioł: <##607c3c>Natura" and "&7Źródło: &fPlasma Freeze" with nbt from "{CustomModelData:6}"
	set {leafeonkartapfEN} to lime glass pane named "<##74ba75>Leafeon" with lore "&7Verdant" and "&7Level: &f0 &7| &7Exp: &f0%nl%&7Statistics:%nl%&7Strength: &7■■■■■■■■■■ &7(<##e35959>0&7)%nl%&7Health: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Damage: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Resistance: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobility: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Utility: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Crowd Control: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Versatility: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mastery: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Critical Hit: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Element: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Haste: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Avoidance: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)" and "&7Element: <##607c3c>Nature" and "&7Source: &fPlasma Freeze" with nbt from "{CustomModelData:6}"
	
	set {chandelurekartapf} to newCard("Polski", "<##6d61ff>Chandelure", "&7Ghost Chandelier", "<##79f759>Częsta", "Plasma Freeze", 4, "<##431d53>Duch", purple glass pane, 7, 7, 6, 4, 3, 3, 5, 6, 10, 8, 9, 9)
	set {chandelurekartapfEN} to newCard("English", "<##6d61ff>Chandelure", "&7Ghost Chandelier", "<##79f759>Common", "Plasma Freeze", 4, "<##431d53>Ghost", purple glass pane, 7, 7, 6, 4, 3, 5, 6, 10, 3, 8, 9, 9)
	
	set {beedrillkartapf} to newCard("Polski", "<##e7ad37>Beedrill", "&7Trujący Szerszeń", "<##79f759>Częsta", "Plasma Freeze", 7, "<##9c72b2>Trucizna", yellow glass pane, 4, 9, 1, 9, 3, 4, 4, 7, 9, 6, 8, 6)
	set {beedrillkartapfEN} to newCard("English", "<##e7ad37>Beedrill", "&7Poison Hornet", "<##79f759>Common", "Plasma Freeze", 7, "<##9c72b2>Poison", yellow glass pane, 4, 9, 1, 9, 3, 4, 4, 7, 9, 6, 8, 6)
	
	set {hootloopkartapf} to newCard("Polski", "<##8e73a4>Hoot Loop", "&7Owl Magician", "<##79f759>Częsta", "Plasma Freeze", 11, "<##512989>Magia", purple glass pane, 3, 6, 3, 10, 5, 4, 5, 10, 5, 6, 8, 10)
	set {hootloopkartapfEN} to newCard("English", "<##8e73a4>Hoot Loop", "&7Owl Magician", "<##79f759>Common", "Plasma Freeze", 11, "<##512989>Magic", purple glass pane, 3, 6, 3, 10, 5, 4, 5, 10, 5, 6, 8, 10)
	
	set {glaliekartapfEN} to newCard("Polski", "<##7fbdf9>Glalie", "&7Lodowa Twarz", "<##79f759>Częsta", "Plasma Freeze", 8, "<##add8e6>Lód", light blue glass pane, 7, 5, 8, 7, 3, 10, 10, 5, 1, 4, 5, 5) 
	set {glaliekartapfEN} to newCard("English", "<##7fbdf9>Glalie", "&7Frigid Face", "<##79f759>Common", "Plasma Freeze", 8, "<##add8e6>Ice", light blue glass pane, 7, 5, 8, 7, 3, 10, 10, 5, 1, 4, 5, 5) 
	
	set {leonakartapf} to newCard("Polski", "<##c98c67>Leona", "&7Promyk Jutrzenki", "<##79f759>Częsta", "Plasma Freeze", 3, "<##fffec8>Światło", orange glass pane, 8, 2, 10, 3, 8, 10, 7, 5, 2, 6, 3, 4)
	set {leonakartapfEN} to newCard("English", "<##c98c67>Leona", "&7The Radiant Dawn", "<##79f759>Common", "Plasma Freeze", 3, "<##fffec8>Light", orange glass pane, 8, 2, 10, 3, 8, 10, 7, 5, 2, 6, 3, 4)
	
	set {dianakartapf} to newCard("Polski", "<##6d7fa2>Diana", "&7Pogarda Księżyca", "<##79f759>Częsta", "Plasma Freeze", 42, "<##333333>Mrok", light gray glass pane, 5, 9, 3, 10, 3, 6, 8, 9, 3, 6, 8, 7)
	set {dianakartapfEN} to newCard("English", "<##6d7fa2>Diana", "&7Scorn of the Moon", "<##79f759>Common", "Plasma Freeze", 42, "<##333333>Dark", light gray glass pane, 5, 9, 3, 10, 3, 6, 8, 9, 3, 6, 8, 7)
	
	set {syndrakartapf} to newCard("Polski", "<##bb3bdd>Syndra", "&7Mroczna Władczyni", "<##79f759>Częsta", "Plasma Freeze", 12, "<##512989>Magia", purple glass pane, 3, 10, 3, 5, 4, 7, 4, 10, 6, 9, 10, 2)
	set {syndrakartapfEN} to newCard("English", "<##bb3bdd>Syndra", "&7The Dark Sovereign", "<##79f759>Common", "Plasma Freeze", 12, "<##512989>Magic", purple glass pane, 3, 10, 3, 5, 4, 7, 4, 10, 6, 9, 10, 2)
	
	set {hotdogkartapf} to newCard("Polski", "<##b9161c>Hot Dog", "&7Ognisty Pies", "<##79f759>Częsta", "Plasma Freeze", 16, "<##ff4d00>Ogień", red glass pane, 6, 8, 3, 10, 7, 1, 10, 8, 5, 7, 8, 9)
	set {hotdogkartapfEN} to newCard("English", "<##b9161c>Hot Dog", "&7Fire Dog", "<##79f759>Common", "Plasma Freeze", 16, "<##ff4d00>Fire", red glass pane, 6, 8, 3, 10, 7, 1, 10, 8, 5, 7, 8, 9)
	
	set {doubletroublekartapf} to brown glass pane named "<##623025>Double Trouble" with lore "&7Tiki Szaman" and "&7Statystyki:%nl%&7Zdrowie: <##c0ff02>■■■■■■■&7■■■%nl%&7Obrażenia: <##f74428>■■■■■&7■■■■■%nl%&7Wytrzymałość: <##ffef45>■■■■■■■■■■%nl%&7Mobilność: &f■■■&7■■■■■■■%nl%&7Użyteczność: <##ae78d0>■■■■&7■■■■■■%nl%&7Kontrola Tłumu: <##58c3f5>■■■■■■■■■&7■%nl%&7Uniwersalność: <##e3ebff>■■■■■■■■&7■■%nl%&7Mistrzostwo: <##f53b98>■■■&7■■■■■■■%nl%&7Cios Krytyczny: <##fca417>■■&7■■■■■■■■%nl%&7Żywioł: <##d5ff57>■■■■■&7■■■■■%nl%&7Pośpiech: <##19943e>■■■■&7■■■■■■%nl%&7Unik: <##2154ad>■■■■&7■■■■■■" and "&7Żywioł: <##607c3c>Natura" and "&7Źródło: &fPlasma Freeze" and "&7Rzadkość: <##79f759>Częsta" with nbt from "{CustomModelData:8}"
	set {doubletroublekartapfEN} to brown glass pane named "<##623025>Double Trouble" with lore "&7Tiki Shaman" and "&7Statistics:%nl%&7Health: <##c0ff02>■■■■■■■&7■■■%nl%&7Damage: <##f74428>■■■■■&7■■■■■%nl%&7Resistance: <##ffef45>■■■■■■■■■■%nl%&7Mobility: &f■■■&7■■■■■■■%nl%&7Utility: <##ae78d0>■■■■&7■■■■■■%nl%&7Crowd Control: <##58c3f5>■■■■■■■■■&7■%nl%&7Versatility: <##e3ebff>■■■■■■■■&7■■%nl%&7Mastery: <##f53b98>■■■&7■■■■■■■%nl%&7Critical Hit: <##fca417>■■&7■■■■■■■■%nl%&7Element: <##d5ff57>■■■■■&7■■■■■%nl%&7Haste: <##19943e>■■■■&7■■■■■■%nl%&7Avoidance: <##2154ad>■■■■&7■■■■■■" and "&7Element: <##607c3c>Nature" and "&7Source: &fPlasma Freeze" and "&7Rarity: <##79f759>Common" with nbt from "{CustomModelData:8}"
	
	set {latioskartapf} to light blue glass pane named "<##adb2f3>Latios" with lore "&7Ptakosmok Wieczności" and "&7Statystyki:%nl%&7Zdrowie: <##c0ff02>■■■■■&7■■■■■%nl%&7Obrażenia: <##f74428>■■■■■■■■&7■■%nl%&7Wytrzymałość: <##ffef45>■■■■■■&7■■■■%nl%&7Mobilność: &f■■■■■■■■&&7■■%nl%&7Użyteczność: <##ae78d0>■■■■&7■■■■■■%nl%&7Kontrola Tłumu: <##58c3f5>■■■■■■■&7■■■%nl%&7Uniwersalność: <##e3ebff>■■■■■■■&7■■■%nl%&7Mistrzostwo: <##f53b98>■■■■■■■■■&7■%nl%&7Cios Krytyczny: <##fca417>■■&7■■■■■■■■%nl%&7Żywioł: <##d5ff57>■■■■&7■■■■■■%nl%&7Pośpiech: <##19943e>■■■■■■■■&7■■%nl%&7Unik: <##2154ad>■■■■&7■■■■■■" and "&7Żywioł: <##306844>Smok" and "&7Źródło: &fPlasma Freeze" and "&7Rzadkość: <##bc5ae0>Sekretnie Rzadka" with nbt from "{CustomModelData:11}"
	set {latioskartapfEN} to light blue glass pane named "<##adb2f3>Latios" with lore "&7Dragonbird of Eons" and "&7Statistics:%nl%&7Health: <##c0ff02>■■■■■&7■■■■■%nl%&7Damage: <##f74428>■■■■■■■■&7■■%nl%&7Resistance: <##ffef45>■■■■■■&7■■■■%nl%&7Mobility: &f■■■■■■■■&7■■%nl%&7Utility: <##ae78d0>■■■■&7■■■■■■%nl%&7Crowd Control: <##58c3f5>■■■■■■■&7■■■%nl%&7Versatility: <##e3ebff>■■■■■■■&7■■■%nl%&7Mastery: <##f53b98>■■■■■■■■■&7■%nl%&7Critical Hit: <##fca417>■■&7■■■■■■■■%nl%&7Element: <##d5ff57>■■■■&7■■■■■■%nl%&7Haste: <##19943e>■■■■■■■■&7■■%nl%&7Avoidance: <##2154ad>■■■■&7■■■■■■" and "&7Element: <##306844>Dragon" and "&7Source: &fPlasma Freeze" and "&7Rarity: <##bc5ae0>Secret Rare" with nbt from "{CustomModelData:11}"
	
	set {latiaskartapf} to pink glass pane named "<##ed6080>Latias" with lore "&7Ptakosmok Wieczności" and "&7Statystyki:%nl%&7Zdrowie: <##c0ff02>■■■■■&7■■■■■%nl%&7Obrażenia: <##f74428>■■■■■■&7■■■■%nl%&7Wytrzymałość: <##ffef45>■■■■■■■■&7■■%nl%&7Mobilność: &f■■■■■■■■&7■■%nl%&7Użyteczność: <##ae78d0>■■■■■■■&7■■■%nl%&7Kontrola Tłumu: <##58c3f5>■■■■&7■■■■■■%nl%&7Uniwersalność: <##e3ebff>■■■■■■■&7■■■%nl%&7Mistrzostwo: <##f53b98>■■■■■■■■■&7■%nl%&7Cios Krytyczny: <##fca417>■■&7■■■■■■■■%nl%&7Żywioł: <##d5ff57>■■■■&7■■■■■■%nl%&7Pośpiech: <##19943e>■■■■&7■■■■■■%nl%&7Unik: <##2154ad>■■■■■■■■&7■■" and "&7Żywioł: <##306844>Smok" and "&7Źródło: &fPlasma Freeze" and "&7Rzadkość: <##bc5ae0>Sekretnie Rzadka" with nbt from "{CustomModelData:7}"
	set {latiaskartapfEN} to pink glass pane named "<##ed6080>Latias" with lore "&7Dragonbird of Eons" and "&7Statistics:%nl%&7Health: <##c0ff02>■■■■■&7■■■■■%nl%&7Damage: <##f74428>■■■■■■&7■■■■%nl%&7Resistance: <##ffef45>■■■■■■■■&7■■%nl%&7Mobility: &f■■■■■■■■&7■■%nl%&7Utility: <##ae78d0>■■■■■■■&7■■■%nl%&7Crowd Control: <##58c3f5>■■■■&7■■■■■■%nl%&7Versatility: <##e3ebff>■■■■■■■&7■■■%nl%&7Mastery: <##f53b98>■■■■■■■■■&7■%nl%&7Critical Hit: <##fca417>■■&7■■■■■■■■%nl%&7Element: <##d5ff57>■■■■&7■■■■■■%nl%&7Haste: <##19943e>■■■■&7■■■■■■%nl%&7Avoidance: <##2154ad>■■■■■■■■&7■■" and "&7Element: <##306844>Dragon" and "&7Source: &fPlasma Freeze" and "&7Rarity: <##bc5ae0>Secret Rare" with nbt from "{CustomModelData:7}"
	
	set {rotom-frostkartapf} to light blue glass pane named "<##a79ce5>Rotom-Frost" with lore "&7Plazmozamrażarka" and "&7Statystyki:%nl%&7Zdrowie: <##c0ff02>■■&7■■■■■■■■%nl%&7Obrażenia: <##f74428>■■■■■&7■■■■■%nl%&7Wytrzymałość: <##ffef45>■■■■■■■&7■■■%nl%&7Mobilność: &f■■■■■&7■■■■■%nl%&7Użyteczność: <##ae78d0>■■■■■■■■&7■■%nl%&7Kontrola Tłumu: <##58c3f5>■■■■■■&7■■■■%nl%&7Uniwersalność: <##e3ebff>■■■■■■■■■■%nl%&7Mistrzostwo: <##f53b98>■■■■&7■■■■■■%nl%&7Cios Krytyczny: <##fca417>■■■&7■■■■■■■%nl%&7Żywioł: <##d5ff57>■■■■■■■■■■%nl%&7Pośpiech: <##19943e>■■■■■■&7■■■■%nl%&7Unik: <##2154ad>■■■■■■■■■&7■" and "&7Żywioł: <##add8e6>Lód" and "&7Źródło: &fPlasma Freeze" and "&7Rzadkość: <##f04f9d>Hiper Rzadka" with nbt from "{CustomModelData:12}"
	set {rotom-frostkartapfEN} to light blue glass pane named "<##a79ce5>Rotom-Frost" with lore "&7Plasma Freezer" and "&7Statistics:%nl%&7Health: <##c0ff02>■■&7■■■■■■■■%nl%&7Damage: <##f74428>■■■■■&7■■■■■%nl%&7Resistance: <##ffef45>■■■■■■■&7■■■%nl%&7Mobility: &f■■■■■&7■■■■■%nl%&7Utility: <##ae78d0>■■■■■■■■&7■■%nl%&7Crowd Control: <##58c3f5>■■■■■■&7■■■■%nl%&7Versatility: <##e3ebff>■■■■■■■■■■%nl%&7Mastery: <##f53b98>■■■■&7■■■■■■%nl%&7Critical Hit: <##fca417>■■■&7■■■■■■■%nl%&7Element: <##d5ff57>■■■■■■■■■■%nl%&7Haste: <##19943e>■■■■■■&7■■■■%nl%&7Avoidance: <##2154ad>■■■■■■■■■&7■" and "&7Element: <##add8e6>Ice" and "&7Source: &fPlasma Freeze" and "&7Rarity: <##f04f9d>Hyper Rare" with nbt from "{CustomModelData:12}"
	
	set {vanilluxekartapf} to light blue glass pane named "<##85ceef>Vanilluxe" with lore "&7Burzośnieżny Lód" and "&7Statystyki:%nl%&7Zdrowie: <##c0ff02>■■■■&7■■■■■■%nl%&7Obrażenia: <##f74428>■■■■■■■&7■■■%nl%&7Wytrzymałość: <##ffef45>■■■■■■■■■&7■%nl%&7Mobilność: &f■&7■■■■■■■■■%nl%&7Użyteczność: <##ae78d0>■■■■■■■■&7■■%nl%&7Kontrola Tłumu: <##58c3f5>■■■■■■■&7■■■%nl%&7Uniwersalność: <##e3ebff>■■■■■■&7■■■■%nl%&7Mistrzostwo: <##f53b98>■■■■&7■■■■■■%nl%&7Cios Krytyczny: <##fca417>■■&7■■■■■■■■%nl%&7Żywioł: <##d5ff57>■■■&7■■■■■■■%nl%&7Pośpiech: <##19943e>■■■■■&7■■■■■%nl%&7Unik: <##2154ad>■■■■&7■■■■■■" and "&7Żywioł: <##add8e6>Lód" and "&7Źródło: &fPlasma Freeze" and "&7Rzadkość: <##5996f7>Rzadka" with nbt from "{CustomModelData:9}"
	set {vanilluxekartapfEN} to light blue glass pane named "<##85ceef>Vanilluxe" with lore "&7Snowstorm Ice Cream" and "&7Statistics:%nl%&7Health: <##c0ff02>■■■■&7■■■■■■%nl%&7Damage: <##f74428>■■■■■■■&7■■■%nl%&7Resistance: <##ffef45>■■■■■■■■■&7■%nl%&7Mobility: &f■&7■■■■■■■■■%nl%&7Utility: <##ae78d0>■■■■■■■■&7■■%nl%&7Crowd Control: <##58c3f5>■■■■■■■&7■■■%nl%&7Versatility: <##e3ebff>■■■■■■&7■■■■%nl%&7Mastery: <##f53b98>■■■■&7■■■■■■%nl%&7Critical Hit: <##fca417>■■&7■■■■■■■■%nl%&7Element: <##d5ff57>■■■&7■■■■■■■%nl%&7Haste: <##19943e>■■■■■&7■■■■■%nl%&7Avoidance: <##2154ad>■■■■&7■■■■■■" and "&7Element: <##add8e6>Ice" and "&7Source: &fPlasma Freeze" and "&7Rarity: <##5996f7>Rare" with nbt from "{CustomModelData:9}"
	
	set {glaceonkartapf} to light blue glass pane named "<##64abdc>Glaceon" with lore "&7Świeży Śnieg" and "&7Statystyki:%nl%&7Zdrowie: <##c0ff02>■■■■&7■■■■■■%nl%&7Obrażenia: <##f74428>■■■■■■■■■&7■%nl%&7Wytrzymałość: <##ffef45>■■■■&7■■■■■■%nl%&7Mobilność: &f■■■&7■■■■■■■%nl%&7Użyteczność: <##ae78d0>■&7■■■■■■■■■%nl%&7Kontrola Tłumu: <##58c3f5>■■■■■&7■■■■■%nl%&7Uniwersalność: <##e3ebff>■■&7■■■■■■■■%nl%&7Mistrzostwo: <##f53b98>■■■■■■■&7■■■%nl%&7Cios Krytyczny: <##fca417>■■■■■■&7■■■■%nl%&7Żywioł: <##d5ff57>■■■■■&7■■■■■%nl%&7Pośpiech: <##19943e>■■■■■■■■■■%nl%&7Unik: <##2154ad>■■■&7■■■■■■■" and "&7Żywioł: <##add8e6>Lód" and "&7Źródło: &fPlasma Freeze" and "&7Rzadkość: <##f04f4f>Super Rzadka" with nbt from "{CustomModelData:10}"
	set {glaceonkartapfEN} to light blue glass pane named "<##64abdc>Glaceon" with lore "&7Fresh Snow" and "&7Statistics:%nl%&7Health: <##c0ff02>■■■■&7■■■■■■%nl%&7Damage: <##f74428>■■■■■■■■■&7■%nl%&7Resistance: <##ffef45>■■■■&7■■■■■■%nl%&7Mobility: &f■■■&7■■■■■■■%nl%&7Utility: <##ae78d0>■&7■■■■■■■■■%nl%&7Crowd Control: <##58c3f5>■■■■■&7■■■■■%nl%&7Versatility: <##e3ebff>■■&7■■■■■■■■%nl%&7Mastery: <##f53b98>■■■■■■■&7■■■%nl%&7Critical Hit: <##fca417>■■■■■■&7■■■■%nl%&7Element: <##d5ff57>■■■■■&7■■■■■%nl%&7Haste: <##19943e>■■■■■■■■■■%nl%&7Avoidance: <##2154ad>■■■&7■■■■■■■" and "&7Element: <##add8e6>Ice" and "&7Source: &fPlasma Freeze" and "&7Rarity: <##f04f4f>Super Rare" with nbt from "{CustomModelData:10}"

on rightclick:
	set {_m} to item amount of player's tool
	if player's held item is {_m} of {boosterplasmafreeze} or {boosterplasmafreezeEN}:
		remove 1 of player's held item from player
		add 1 to {otwboostery::pf::%player%}
		add 1 to {otwboostery::%player%}
		achievement("otwboostery", player, 50, "osiagniecie.50booster", "Otwórz 50 boosterów", "Karciarz", "Open 50 boosters", "Card Player")
		achievement("otwboostery", player, 100, "osiagniecie.100booster", "Otwórz 100 boosterów", "Kolekcjoner Kart", "Open 100 boosters", "Card Collector")
		achievement("otwboostery", player, 1000, "osiagniecie.1000booster", "Otwórz 1000 boosterów", "Boosteromaniak", "Open 1000 boosters", "Boostermaniac")
		achievement("otwboostery::pf", player, 50, "osiagniecie.50boosterpf", "Otwórz 50 boosterów Plasma Freeze", "Plasma Freeze: 50", "Open 50 Plasma Freeze boosters", "Plasma Freeze: 50")
		achievement("otwboostery::pf", player, 100, "osiagniecie.100boosterpf", "Otwórz 100 boosterów Plasma Freeze", "Plasma Freeze: 100", "Open 100 Plasma Freeze boosters", "Plasma Freeze: 100")
		achievement("otwboostery::pf", player, 1000, "osiagniecie.1000boosterpf", "Otwórz 1000 boosterów Plasma Freeze", "Plasma Freeze: 1000", "Open 1000 Plasma Freeze boosters", "Plasma Freeze: 1000")
		#CZĘSTE
		chance of 10%:
			BoosterPackDrop(player, "<##6d61ff>Chandelure", "pf", "Plasma Freeze", "common", 1)
		chance of 10%:
			BoosterPackDrop(player, "<##e7ad37>Beedrill", "pf", "Plasma Freeze", "common", 2)
		chance of 10%:
			BoosterPackDrop(player, "<##8e73a4>Hoot Loop", "pf", "Plasma Freeze", "common", 3)
		chance of 10%:		
			BoosterPackDrop(player, "<##7fbdf9>Glalie", "pf", "Plasma Freeze", "common", 4)
		chance of 10%:
			BoosterPackDrop(player, "<##c98c67>Leona", "pf", "Plasma Freeze", "common", 5)
		chance of 10%:
			BoosterPackDrop(player, "<##6d7fa2>Diana", "pf", "Plasma Freeze", "common", 6)
		chance of 10%:
			BoosterPackDrop(player, "<##bb3bdd>Syndra", "pf", "Plasma Freeze", "common", 7)
		chance of 10%:
			BoosterPackDrop(player, "<##b9161c>Hot Dog", "pf", "Plasma Freeze", "common", 8)
		chance of 10%:
			BoosterPackDrop(player, "<##623025>Double Trouble", "pf", "Plasma Freeze", "common", 9)
		#SEKRETNIE RZADKIE
		chance of 0.5%:
			BoosterPackDrop(player, "<##adb2f3>Latios", "pf", "Plasma Freeze", "secretrare", 10)
			set {_droppedRare} to true
		chance of 0.5%:
			BoosterPackDrop(player, "<##ed6080>Latias", "pf", "Plasma Freeze", "secretrare", 11)
			set {_droppedRare} to true
		#HIPER RZADKIE
		chance of 1%:
			BoosterPackDrop(player, "<##a79ce5>Rotom-Frost", "pf", "Plasma Freeze", "hyperrare", 12)
			set {_droppedRare} to true
		#SUPER RZADKIE
		chance of 3%:
			BoosterPackDrop(player, "<##64abdc>Glaceon", "pf", "Plasma Freeze", "superrare", 13)
			set {_droppedRare} to true
		#RZADKIE
		chance of 5%:
			BoosterPackDrop(player, "<##85ceef>Vanilluxe", "pf", "Plasma Freeze", "rare", 14)
			set {_droppedRare} to true

		if {_droppedRare} is not true:
			set {_x} to a random integer between 1 and 9
			if {_x} = 1:
				BoosterPackDrop(player, "<##6d61ff>Chandelure", "pf", "Plasma Freeze", "common", 1)
			else if {_x} = 2:
				BoosterPackDrop(player, "<##e7ad37>Beedrill", "pf", "Plasma Freeze", "common", 2)
			else if {_x} = 3:
				BoosterPackDrop(player, "<##8e73a4>Hoot Loop", "pf", "Plasma Freeze", "common", 3)
			else if {_x} = 4:		
				BoosterPackDrop(player, "<##7fbdf9>Glalie", "pf", "Plasma Freeze", "common", 4)
			else if {_x} = 5:
				BoosterPackDrop(player, "<##c98c67>Leona", "pf", "Plasma Freeze", "common", 5)
			else if {_x} = 6:
				BoosterPackDrop(player, "<##6d7fa2>Diana", "pf", "Plasma Freeze", "common", 6)
			else if {_x} = 7:
				BoosterPackDrop(player, "<##bb3bdd>Syndra", "pf", "Plasma Freeze", "common", 7)
			else if {_x} = 8:
				BoosterPackDrop(player, "<##b9161c>Hot Dog", "pf", "Plasma Freeze", "common", 8)
			else if {_x} = 9:
				BoosterPackDrop(player, "<##623025>Double Trouble", "pf", "Plasma Freeze", "common", 9)

		if {pfBoosterPity::%player%} >= 10:
			remove 10 from {pfBoosterPity::%player%}
			set {_randomRare} to a random integer between 1 and 100
			if {_randomRare} is between 1 and 50:
				BoosterPackDrop(player, "<##85ceef>Vanilluxe", "pf", "Plasma Freeze", "rare", 14)
			else if {_x} is between 51 and 80:
				BoosterPackDrop(player, "<##64abdc>Glaceon", "pf", "Plasma Freeze", "superrare", 13)
			else if {_x} is between 81 and 90:
				BoosterPackDrop(player, "<##a79ce5>Rotom-Frost", "pf", "Plasma Freeze", "hyperrare", 12)
			else if {_x} is between 91 and 95:
				BoosterPackDrop(player, "<##ed6080>Latias", "pf", "Plasma Freeze", "secretrare", 11)
			else if {_x} is between 95 and 100:
				BoosterPackDrop(player, "<##adb2f3>Latios", "pf", "Plasma Freeze", "secretrare", 10)
			if {language::%player%} = "English":
				send formatted "&f[&2Booster&f] &aThis was your 10th booster in a row without at least a Rare rarity drop, meaning that this is a pity drop!" to player
			else:
				send formatted "&f[&2Booster&f] &aTo twój dziesiąty booster z rzędu od ostatniego wydropienia conajmniej Rzadkiej karty, co oznacza że ten drop pochodzi z pity!" to player
			add 1 to {pityDrops::%player%}

		if {plasmafreezecomplete::%player%} is not true:
			loop 14 times:
				if {carddrop::pf::%player%::%loop-number%} is set:
					add 1 to {_complete}
			if {_complete} = 14:
				add "Plasma Freeze" to {completionreward::%player%::*}
				set {plasmafreezecomplete::%player%} to true
	else if player's tool = {plasmafreezeblister1}:
		remove 1 of player's tool from player
		set {_crobatCard} to newCard("Polski", "<##643c71>Crobat", "&7Trujący Nietoperz", "<##75c3eb>Promocyjna", "Plasma Freeze", 13, "<##9c72b2>Trucizna", purple glass pane, 10, 6, 3, 10, 7, 2, 8, 8, 4, 6, 9, 10)
		set {_y} to data()
		add "&8Wydropiono: %{_y}%" to lore of {_crobatCard}

		set {_pfcollectorcoingradient} to mini message from "<gradient:##519e65:##a5c7ae:##e3ecfc:##a5d0f0:##5a7cc4>Plasma Freeze Kolekcjonerska Moneta"
		set {_colCoin} to iron nugget named {_pfcollectorcoingradient} with lore "<##cfcbbc>Kolekcjonerska Moneta" and "&fOpis:%nl%&7Ta premium platynowa moneta odzwierciedlająca%nl%&7zamrożony liść została wydana jako bonusowy%nl%&7przedmiot kolekcjonerski w pre-release%nl%&7Blisterach z serii Plasma Freeze.%nl% %nl%&fWydanie: &7Plasma Freeze%nl%&fData: &7Grudzień 12, 2024" with nbt from "{CustomModelData:15}"
		
		giveItem(player, 3 of {boosterplasmafreeze})
		giveItem(player, {_crobatCard})
		giveItem(player, {_colCoin})

	else if player's tool = {plasmafreezeblister1EN}:
		remove 1 of player's tool from player
		set {_crobatCard} to newCard("English", "<##643c71>Crobat", "&7Poison Bat", "<##75c3eb>Promotional", "Plasma Freeze", 13, "<##9c72b2>Poison", purple glass pane, 10, 6, 3, 10, 7, 2, 8, 8, 4, 6, 9, 10)
		set {_y} to data()
		add "&8Dropped: %{_y}%" to lore of {_crobatCard}
		
		set {_pfcollectorcoingradient} to mini message from "<gradient:##519e65:##a5c7ae:##e3ecfc:##a5d0f0:##5a7cc4>Plasma Freeze Collector Coin"
		set {_colCoin} to iron nugget named {_pfcollectorcoingradient} with lore "<##cfcbbc>Collector Coin" and "&fDescription:%nl%&7This premium platinum coin featuring a frozen leaf%nl%&7released as a bonus collectible item included%nl%&7in the Plasma Freeze pre-release Blister Packs.%nl% %nl%&fRelease: &7Plasma Freeze%nl%&fDate: &7December 12, 2024" with nbt from "{CustomModelData:15}"
		
		giveItem(player, 3 of {boosterplasmafreezeEN})
		giveItem(player, {_crobatCard})
		giveItem(player, {_colCoin})

	else if player's tool = {plasmafreezeblister2}:
		remove 1 of player's tool from player
		set {_blastoiseCard} to newCard("Polski", "<##2e9bd4>Blastoise", "&7Żółw z Armatą Wodną", "<##75c3eb>Promocyjna", "Plasma Freeze", 14, "<##1ebbd7>Woda", light blue glass pane, 7, 6, 10, 5, 3, 4, 10, 7, 9, 9, 8, 4)
		set {_y} to data()
		add "&8Wydropiono: %{_y}%" to lore of {_blastoiseCard}

		set {_pfcollectorcoingradient} to mini message from "<gradient:##519e65:##a5c7ae:##e3ecfc:##a5d0f0:##5a7cc4>Plasma Freeze Kolekcjonerska Moneta"
		set {_colCoin} to iron nugget named {_pfcollectorcoingradient} with lore "<##cfcbbc>Kolekcjonerska Moneta" and "&fOpis:%nl%&7Ta premium platynowa moneta odzwierciedlająca%nl%&7zamrożony liść została wydana jako bonusowy%nl%&7przedmiot kolekcjonerski w pre-release%nl%&7Blisterach z serii Plasma Freeze.%nl% %nl%&fWydanie: &7Plasma Freeze%nl%&fData: &7Grudzień 12, 2024" with nbt from "{CustomModelData:15}"
		
		giveItem(player, 3 of {boosterplasmafreeze})
		giveItem(player, {_blastoiseCard})
		giveItem(player, {_colCoin})

	else if player's tool = {plasmafreezeblister2EN}:
		remove 1 of player's tool from player
		set {_blastoiseCard} to newCard("English", "<##2e9bd4>Blastoise", "&7Water Cannon Turtle", "<##75c3eb>Promotional", "Plasma Freeze", 14, "<##1ebbd7>Water", light blue glass pane, 7, 6, 10, 5, 3, 4, 10, 7, 9, 9, 8, 4)
		set {_y} to data()
		add "&8Dropped: %{_y}%" to lore of {_blastoiseCard}
		
		set {_pfcollectorcoingradient} to mini message from "<gradient:##519e65:##a5c7ae:##e3ecfc:##a5d0f0:##5a7cc4>Plasma Freeze Collector Coin"
		set {_colCoin} to iron nugget named {_pfcollectorcoingradient} with lore "<##cfcbbc>Collector Coin" and "&fDescription:%nl%&7This premium platinum coin featuring a frozen leaf%nl%&7released as a bonus collectible item included%nl%&7in the Plasma Freeze pre-release Blister Packs.%nl% %nl%&fRelease: &7Plasma Freeze%nl%&fDate: &7December 12, 2024" with nbt from "{CustomModelData:15}"
		
		giveItem(player, 3 of {boosterplasmafreezeEN})
		giveItem(player, {_blastoiseCard})
		giveItem(player, {_colCoin})
	else if player's tool = {plasmafreezebox}:
		remove 1 of player's tool from player
		set {_ghetsisCard} to newCard("Polski", "<##8ec5f0>Ghetsis", "&7Kapitan Team Plasma", "<##75c3eb>Promocyjna", "Plasma Freeze", 13, "<##add8e6>Lód", light blue glass pane, 8, 10, 8, 5, 1, 8, 8, 10, 7, 5, 9, 5)
		set {_y} to data()
		add "&8Wydropiono: %{_y}%" to lore of {_ghetsisCard}

		giveItem(player, 6 of {boosterplasmafreeze})
		giveItem(player, {boosterunseenforces})
		giveItem(player, {boostermajesticdawn})
		giveItem(player, {_ghetsisCard})
		giveItem(player, {odlamekgwiazdy})

	else if player's tool = {plasmafreezeboxEN}:
		remove 1 of player's tool from player
		set {_ghetsisCard} to newCard("English", "<##8ec5f0>Ghetsis", "&7Team Plasma Captain", "<##75c3eb>Promotional", "Plasma Freeze", 13, "<##add8e6>Ice", light blue glass pane, 8, 10, 8, 5, 1, 8, 8, 10, 7, 5, 9, 5)
		set {_y} to data()
		add "&8Dropped: %{_y}%" to lore of {_ghetsisCard}
	
		
		giveItem(player, 6 of {boosterplasmafreezeEN})
		giveItem(player, {boosterunseenforcesEN})
		giveItem(player, {boostermajesticdawnEN})
		giveItem(player, {_ghetsisCard})
		giveItem(player, {odlamekgwiazdyEN})

