on load:
	set {_desc} to "&7&o''Something ancient and restless is stirring in the depths of Earthcraft! As shadows grow longer and the air turns cold, the Unseen Forces have crossed the threshold into our world to claim what was once lost. Can you master the strength of these entities before you're consumed by the dark? Step into the shadows and prepare for a spectral assault unlike any other!''"
	set {_desc} to join wrapText({_desc}, 50) by "%nl%&7&o"
	set {boosterunseenforces} to glass pane of unbreaking 10 named "&5Unseen Forces &9Booster" with lore "&9Booster%nl%&7Booster containing one or more cards.%nl%&7Contains exclusive cards from this set.%nl% %nl%%{_desc}%" with nbt from "{""minecraft:custom_data"":{""BoosterName"":""Unseen Forces"",""CardBooster"":1b}}"
	
	set {cynderkartauf} to purple stained glass pane named "<##5b467d>Cynder" with lore "&7Dark Dragoness" and "&7Level: &f0 &7| &7Exp: &f0%nl%&7Statistics:%nl%&7Intellect: &7■■■■■■■■■■ &7(<##59c1e3>0&7)%nl%&7Health: <##c0ff02>&7■■■■■■■■■■ &7(<##c0ff02>0&7)%nl%&7Damage: <##f74428>&7■■■■■■■■■■ &7(<##f74428>0&7)%nl%&7Resistance: <##ffef45>&7■■■■■■■■■■ &7(<##ffef45>0&7)%nl%&7Mobility: &f&7■■■■■■■■■■ &7(&f0&7)%nl%&7Utility: <##ae78d0>&7■■■■■■■■■■ &7(<##ae78d0>0&7)%nl%&7Crowd Control: <##58c3f5>&7■■■■■■■■■■ &7(<##58c3f5>0&7)%nl%&7Versatility: <##e3ebff>&7■■■■■■■■■■ &7(<##e3ebff>0&7)%nl%&7Mastery: <##f53b98>&7■■■■■■■■■■ &7(<##f53b98>0&7)%nl%&7Critical Hit: <##fca417>&7■■■■■■■■■■ &7(<##fca417>0&7)%nl%&7Element: <##d5ff57>&7■■■■■■■■■■ &7(<##d5ff57>0&7)%nl%&7Haste: <##19943e>&7■■■■■■■■■■ &7(<##19943e>0&7)%nl%&7Avoidance: <##2154ad>&7■■■■■■■■■■ &7(<##2154ad>0&7)" and "&7Element: <##431d53>Ghost" and "&7Source: &fUnseen Forces" with nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]}}"

on rightclick:
	set {_item} to 1 of player's held item
	if boolean tag "CardBooster" of custom nbt of {_item} = true:
		if string tag "BoosterName" of custom nbt of {_item} = "Unseen Forces":
			remove 1 of {_item} from player

			if {winterDelightPassLEVEL::%player%} >= 0:
				getMission(player, "Boostermania", "Boosteromania", 1)

			load yaml "plugins/Skript/playerdata/boosters/Unseen Forces/%uuid of player%.yml" as "Unseen Forces-%player%"
			set {_boostersOpened} to yaml value "Booster.Opened" in "Unseen Forces-%player%"
			add 1 to {_boostersOpened}
			set yaml value "Booster.Opened" in "Unseen Forces-%player%" to {_boostersOpened}

			add 1 to {otwboostery::%player%}
			boosterAchievements(player, "Unseen Forces")		

			set {_cardWarnado} to BoosterCardFromYaml("Unseen Forces", "Warnado")

			set {_cardAatrox} to BoosterCardFromYaml("Unseen Forces", "Aatrox")

			set {_cardGiratina} to BoosterCardFromYaml("Unseen Forces", "Giratina")

			set {_cardNami} to BoosterCardFromYaml("Unseen Forces", "Nami")

			set {_cardZed} to BoosterCardFromYaml("Unseen Forces", "Zed")

			set {_cardIvern} to BoosterCardFromYaml("Unseen Forces", "Ivern")

			set {_cardSwarm} to BoosterCardFromYaml("Unseen Forces", "Swarm")

			set {_cardElise} to BoosterCardFromYaml("Unseen Forces", "Elise")

			set {_cardMalDamba} to BoosterCardFromYaml("Unseen Forces", "Mal'Damba")

			set {_cardDeoxys} to BoosterCardFromYaml("Unseen Forces", "Deoxys")

			set {_cardAmumu} to BoosterCardFromYaml("Unseen Forces", "Amumu")

			set {_cardHonchkrow} to BoosterCardFromYaml("Unseen Forces", "Honchkrow")

			set {_cardShroomboom} to BoosterCardFromYaml("Unseen Forces", "Shroomboom")

			set {_cardHex} to BoosterCardFromYaml("Unseen Forces", "Hex")

			chance of 10%:
				BoosterPackDrop(player, {_cardWarnado})
			chance of 10%:
				BoosterPackDrop(player, {_cardAatrox})
			chance of 10%:
				BoosterPackDrop(player, {_cardGiratina})
			chance of 10%:
				BoosterPackDrop(player, {_cardNami})
			chance of 10%:
				BoosterPackDrop(player, {_cardZed})
			chance of 10%:
				BoosterPackDrop(player, {_cardIvern})
			chance of 10%:
				BoosterPackDrop(player, {_cardSwarm})
			chance of 10%:
				BoosterPackDrop(player, {_cardElise})
			chance of 10%:
				BoosterPackDrop(player, {_cardMalDamba})

			#RARE
			chance of 5%:
				set {_droppedRare} to true
				BoosterPackDrop(player, {_cardDeoxys})

			#SUPER RARE
			chance of 3%:
				set {_droppedRare} to true
				BoosterPackDrop(player, {_cardAmumu})

			#HYPER RARE
			chance of 1%:
				set {_droppedRare} to true
				BoosterPackDrop(player, {_cardHonchkrow})

			#SECRET RARE
			chance of 0.5%:
				set {_droppedRare} to true
				BoosterPackDrop(player, {_cardShroomboom})
			chance of 0.5%:
				set {_droppedRare} to true
				BoosterPackDrop(player, {_cardHex})
			
			
			if {_droppedRare} is not true:
				set {_pity} to yaml value "Booster.Pity" in "Unseen Forces-%player%"
				add 1 to {_pity}
				if {_pity} = 10:
					set {_pity} to 0
					set {_pityDrop} to true
				set yaml value "Booster.Pity" in "Unseen Forces-%player%" to {_pity}

				set {_x} to a random integer between 1 and 9
				if {_x} = 1:
					BoosterPackDrop(player, {_cardWarnado})
				else if {_x} = 2:
					BoosterPackDrop(player, {_cardAatrox})
				else if {_x} = 3:
					BoosterPackDrop(player, {_cardGiratina})
				else if {_x} = 4:		
					BoosterPackDrop(player, {_cardNami})
				else if {_x} = 5:
					BoosterPackDrop(player, {_cardZed})
				else if {_x} = 6:
					BoosterPackDrop(player, {_cardIvern})
				else if {_x} = 7:
					BoosterPackDrop(player, {_cardSwarm})
				else if {_x} = 8:
					BoosterPackDrop(player, {_cardElise})
				else if {_x} = 9:
					BoosterPackDrop(player, {_cardMalDamba})
				
			else:
				set yaml value "Booster.Pity" in "Unseen Forces-%player%" to 0

			if {_pityDrop} is true:
				set {_randomRare} to a random integer between 1 and 100
				if {_randomRare} is between 1 and 50:
					set {_pityCard} to {_cardDeoxys}
				else if {_randomRare} is between 51 and 80:
					set {_pityCard} to {_cardAmumu}
				else if {_randomRare} is between 81 and 90:
					set {_pityCard} to {_cardHonchkrow}
				else if {_randomRare} is between 91 and 95:
					set {_pityCard} to {_cardShroomboom}
				else if {_randomRare} is between 95 and 100:
					set {_pityCard} to {_cardHex}
				BoosterPackDrop(player, {_pityCard})

				send formatted "&f[&2Booster&f] &aThis &awas your &510th booster &ain a row without at least a Rare rarity drop, meaning that %name of {_pityCard}% &ais a pity drop!" to player
				set {_pityDrops} to yaml value "Booster.Pity Drops" in "Unseen Forces-%player%"
				add 1 to {_pityDrops}
				set yaml value "Booster.Pity Drops" in "Unseen Forces-%player%" to {_pityDrops}

				add 1 to {pityDrops::%player%}

			save yaml "Unseen Forces-%player%"

	else if player's tool = {unseenforcesblister1}:
		remove 1 of player's tool from player
		set {_gengarCard} to purple stained glass pane named "<##7627b7>Gengar" with lore "&7Shadow" and "&7Statistics:%nl%&7Health: <##c0ff02>■■■■&7■■■■■■%nl%&7Damage: <##f74428>■■■■■■■■&7■■%nl%&7Resistance: <##ffef45>■■■&7■■■■■■■%nl%&7Mobility: &f■■■■■■■■■■%nl%&7Utility: <##ae78d0>■■■&7■■■■■■■%nl%&7Crowd Control: <##58c3f5>■■■■&7■■■■■■%nl%&7Versatility: <##e3ebff>■■■■&7■■■■■■%nl%&7Mastery: <##f53b98>■■■■■■■■&7■■%nl%&7Critical Hit: <##fca417>■■■■■■&7■■■■%nl%&7Element: <##d5ff57>■■■■■■&7■■■■%nl%&7Haste: <##19943e>■■■■■■■&7■■■%nl%&7Avoidance: <##2154ad>■■■■■■■&7■■■" and "&7Element: <##431d53>Ghost" and "&7Source: &fUnseen Forces" and "&7Rarity: <##75c3eb>Promotional" with nbt from "{""minecraft:custom_model_data"":{floats:[10.0f]}}"
		set {_y} to data()
		add "&8Dropped: %{_y}%" to lore of {_gengarCard}
		
		set {_UFcollectorcoingradient} to mini message from "<gradient:##d3449c:##433c3e>Unseen Forces Collector Coin"
		set {_colCoin} to iron nugget named {_UFcollectorcoingradient} with lore "<##cfcbbc>Collector Coin" and "&fDescription:%nl%&7This premium metallic coin featuring Cynder%nl%&7released as a bonus collectible item included%nl%&7in the Unseen Forces pre-release Blister Packs.%nl% %nl%&fRelease: &7Unseen Forces%nl%&fDate: &7June 23, 2024" with nbt from "{""minecraft:custom_model_data"":{floats:[13.0f]}}"
		
		giveItem(player, 3 of {boosterunseenforces})
		giveItem(player, {_gengarCard})
		giveItem(player, {_colCoin})

	else if player's tool = {unseenforcesblister2}:
		remove 1 of player's tool from player
		set {_houndoomCard} to red stained glass pane named "<##9c4242>Houndoom" with lore "&7Dark Hound" and "&7Statistics:%nl%&7Health: <##c0ff02>■■■■■■&7■■■■%nl%&7Damage: <##f74428>■■■■■■■■■&7■%nl%&7Resistance: <##ffef45>■■■■&7■■■■■■%nl%&7Mobility: &f■■■■■■■&7■■■%nl%&7Utility: <##ae78d0>■■&7■■■■■■■■%nl%&7Crowd Control: <##58c3f5>■■&7■■■■■■■■%nl%&7Versatility: <##e3ebff>■■■■■■&7■■■■%nl%&7Mastery: <##f53b98>■■■■■&7■■■■■%nl%&7Critical Hit: <##fca417>■■■■■■■■&7■■%nl%&7Element: <##d5ff57>■■■■■■■&7■■■%nl%&7Haste: <##19943e>■■■■■&7■■■■■%nl%&7Avoidance: <##2154ad>■■■&7■■■■■■■" and "&7Element: <##ff4d00>Fire" and "&7Source: &fUnseen Forces" and "&7Rarity: <##75c3eb>Promotional" with nbt from "{""minecraft:custom_model_data"":{floats:[15.0f]}}"
		set {_y} to data()
		add "&8Dropped: %{_y}%" to lore of {_houndoomCard}
		
		set {_UFcollectorcoingradient} to mini message from "<gradient:##d3449c:##433c3e>Unseen Forces Collector Coin"
		set {_colCoin} to iron nugget named {_UFcollectorcoingradient} with lore "<##cfcbbc>Collector Coin" and "&fDescription:%nl%&7This premium metallic coin featuring Cynder%nl%&7released as a bonus collectible item included%nl%&7in the Unseen Forces pre-release Blister Packs.%nl% %nl%&fRelease: &7Unseen Forces%nl%&fDate: &7June 23, 2024" with nbt from "{""minecraft:custom_model_data"":{floats:[13.0f]}}"
		
		giveItem(player, 3 of {boosterunseenforces})
		giveItem(player, {_houndoomCard})
		giveItem(player, {_colCoin})

	else if player's tool = {unseenforcesbox}:
		remove 1 of player's tool from player
		set {_hoopaCard} to magenta stained glass pane named "<##bb3276>Hoopa-Unbound" with lore "&7Djinn" and "&7Statistics:%nl%&7Health: <##c0ff02>■■■■■■■&7■■■%nl%&7Damage: <##f74428>■■■■■■■&7■■■%nl%&7Resistance: <##ffef45>■■■■■■■&7■■■%nl%&7Mobility: &f■■■&7■■■■■■■%nl%&7Utility: <##ae78d0>■■■&7■■■■■■■%nl%&7Crowd Control: <##58c3f5>■■■■■■■&7■■■%nl%&7Versatility: <##e3ebff>■■■■■■■&7■■■%nl%&7Mastery: <##f53b98>■■■■■■■■■■%nl%&7Critical Hit: <##fca417>■■&7■■■■■■■■%nl%&7Element: <##d5ff57>■■■■■■&7■■■■%nl%&7Haste: <##19943e>■■&7■■■■■■■■%nl%&7Avoidance: <##2154ad>■■■■&7■■■■■■" and "&7Element: <##d84af7>Psychic" and "&7Source: &fUnseen Forces" and "&7Rarity: <##75c3eb>Promotional" with nbt from "{""minecraft:custom_model_data"":{floats:[6.0f]}}"
		set {_y} to data()
		add "&8Dropped: %{_y}%" to lore of {_hoopaCard}
		
		giveItem(player, 6 of {boosterunseenforces})
		giveItem(player, {boostermajesticdawn})
		giveItem(player, {boostersecretwonders})
		giveItem(player, {_hoopaCard})

		if yaml "Unseen Forces-%player%" is not loaded:
			load yaml "plugins/Skript/playerdata/boosters/Unseen Forces/%uuid of player%.yml" as "Unseen Forces-%player%"

		if yaml value "Collectibles.Box.Star Shard Claimed" in "Unseen Forces-%player%" is not set:
			set yaml value "Collectibles.Box.Star Shard Claimed" in "Unseen Forces-%player%" to true
			save yaml "Unseen Forces-%player%"
			
			set {_starShard} to yaml value "Star Shard.Item" in "ItemList"
			giveItem(player, {_starShard})
		