
on rightclick on an animal:
    if player is sneaking:
        if any:
            boolean tag "ECMob" of custom nbt of clicked animal is not set
            boolean tag "ECSummon" of custom nbt of clicked animal is not set
        then:
            if cooldown "Pet%uuid of clicked animal%%player%" is finished:
                create cooldown "Pet%uuid of clicked animal%%player%" for 3 seconds
                send "&7You pet &ethe &f%name of clicked animal%&7." to player
                make player swing their hand

                set {_heartCount} to a random integer between 2 and 8
                set {_eyeLoc} to clicked animal.getEyeLocation()

                play sound "entity.%type of clicked animal%.ambient" with volume 1 and pitch 1 to player
                play sound "entity.horse.armor" with volume 1 and pitch 1 to player

                loop 3 times:
                    set {_randomOffset::%loop-counter%} to a random number between 0.0 and 1.0
                draw {_heartCount} of heart particle with an extra value of 0.01 with offset vector({_randomOffset::1}, {_randomOffset::2}, {_randomOffset::3}) at {_eyeLoc}