import:
    org.dynmap.markers.MarkerAPI
    org.dynmap.markers.MarkerDescription
    org.dynmap.markers.MarkerIcon
    org.dynmap.markers.MarkerSet
    org.dynmap.DynmapCommonAPI
    org.dynmap.DynmapCommonAPIListener
    org.bukkit.Bukkit
    org.dynmap.bukkit.DynmapPlugin
    java.lang.Math
    kr.toxicity.model.api.BetterModel
    kr.toxicity.model.api.tracker.EntityTrackerRegistry

variables:
    {worldQuestCount} = 0

command /testdialogue:
    trigger:
        set {worldQuestCount} to 0
        portraitDialogue(player, "", "Magni Bronzebeard", "Someone's drawin' power from Azerite in this area. Ye need tae stop 'em!")
        set {_dialogue} to "No need tae panic! Though I suppose my entrance was a bit abrupt..."
        #portraitDialogue(player, "", "Magni Bronzebeard", {_dialogue})
        #play sound "npc.magnibronzebeard.heart_introduction" with volume 5 and pitch 1 to player
        set {_citizens} to Bukkit.getPluginManager().getPlugin("Citizens")
        set {_magni} to {_citizens}.getNPCRegistry().getById(6748).getEntity()
        broadcast {_magni}
        

function portraitDialogue(p: player, icon: string, name: string, text: string):
    if length of {_text} > 32:
        set {_length} to (length of {_text})/32
        set {_length} to rounded down {_length}
        set {_counter} to 1
        loop {_length} times:
            set {_min} to 1 + (({_counter}-1)*32)
            if loop-counter = {_length}:
                set {_max} to length of {_text}
            else:
                set {_max} to {_counter}*32
            if {_counter} < 3:
                set {_textAligned::*} to {_textAligned::*} and (subtext of {_text} from character {_min} to character {_max})
            else:
                set {_text::*} to {_text::*} and (subtext of {_text} from character {_min} to character {_max})
            add 1 to {_counter}
    else:
        set {_textAligned::*} to {_text}
    send "" to {_p}
    send "          <##fdd002>%{_name}%" to {_p}
    loop {_textAligned::*}:
        send "          %loop-value%" to {_p}
    if {_text::*} is set:
        loop {_text::*}:
            if loop-counter = (size of {_text::*}):
                send "%{_icon}% %loop-value%" to {_p}
            else:
                send "          %loop-value%" to {_p}
    else:
        send "%{_icon}%" to {_p}
    send " " to {_p}

command /ly:
    trigger:
        if yaml "WorldQuestList" is loaded:
            save yaml "WorldQuestList"
            unload yaml "WorldQuestList"
            broadcast "&cunloaded yaml"
        else:
            load yaml "plugins/Skript/lists/WorldQuestList" as "WorldQuestList"
            broadcast "&bloaded yaml"
#on place of player head:
#    if name of player's tool = "Glass":
 #       cancel event
 #       add event-location to yaml list "Collect Things.Tidying Up.Locations" in "WorldQuestLocations"
 #       save yaml "WorldQuestLocations"
 #       broadcast size of yaml list "Collect Things.Tidying Up.Locations" in "WorldQuestLocations"
command /wq [<text>]:
    trigger:
        if arg-1 = "task":
            set yaml value "Mobs.Drowned.Item" in "WorldQuestList" to player's tool
        if arg-1 = "register":
            set yaml value "World Quests.The Narrow Passage.Location" in "WorldQuestList" to player's location
            set yaml value "World Quests.The Narrow Passage.Location Name" in "WorldQuestList" to "Riptide Reach"
            set yaml value "World Quests.The Narrow Passage.Type" in "WorldQuestList" to "Slay Mobs"
            set yaml value "World Quests.The Narrow Passage.Quest Giver" in "WorldQuestList" to "Philippe 'Rumford'"
            set yaml value "World Quests.The Narrow Passage.EXP" in "WorldQuestList" to 100
            set yaml value "World Quests.The Narrow Passage.Reputation" in "WorldQuestList" to 20
            set yaml list "World Quests.The Narrow Passage.Rewards" in "WorldQuestList" to "Radiant Azerite Fragment"
        if arg-1 = "spawn":
            set {_wq} to "The Narrow Passage"
            WorldQuestSpawn({_wq})
        if arg-1 = "slay":
            loop all entities in radius 70 of player:
                if boolean tag "RemoveOnReset" of custom nbt of loop-entity = true:
                    kill loop-entity

        save yaml "WorldQuestList"
        save yaml "WorldQuestLocations"

#1. Every friday, 10 random World Quests are randomized.
#//2. On init, load chunks around the locations of the world quests.
#3. Spawn mobs, make players see x as y and place things for pick up.
#4. Always 1 "rarer, more difficult world ques, usually slay a boss"
#5. Mobs etc. respawns after some time
#6. Place markers on the map.
#7. Create regions or bounds from min to max. On enter of this area, send a dialogue to player.
#8. Include icon of npc in world marker
#9. Player stats: Completed world quests, completed world quests per category, xp from world quests
#10. On WQ complete, hide all the blocks again
        
function WorldQuestSpawn(wq: string):
    set {_wqType} to yaml value "World Quests.%{_wq}%.Type" in "WorldQuestList"
    if {_wqType} = "Slay Mobs":
        set {_mobTypes::*} to yaml node keys "Tasks.%{_wqType}%.%{_wq}%" in "WorldQuestList"
        loop {_mobTypes::*}:
            set {_mobType} to loop-value
            set {_entity} to (yaml value "Mobs.%{_mobType}%.Entity" in "WorldQuestList")
            set {_entity} to "adult %{_entity}%" parsed as entity type

            set {_health} to yaml value "Mobs.%{_mobType}%.Health" in "WorldQuestList"
            set {_level} to yaml value "Mobs.%{_mobType}%.Level" in "WorldQuestList"
            set {_element} to yaml value "Mobs.%{_mobType}%.Element" in "WorldQuestList"
            set {_modelHeight} to yaml value "Mobs.%{_mobType}%.Model Height" in "WorldQuestList"
            set {_item} to yaml value "Mobs.%{_mobType}%.Item" in "WorldQuestList"

            set {_spawnLocations::*} to yaml list "%{_wqType}%.%{_wq}%.Locations" in "WorldQuestLocations"
            loop {_spawnLocations::*}:
                set {_loc} to loop-value-2
                spawn {_entity} at {_loc}
                set {_mob} to last spawned entity
                set display name of {_mob} to "&f%{_mobType}%"

                set {_mob}'s max health to {_health} * Math.pow(1.072, {_level})
                heal {_mob}

                set boolean tag "ECMob" of custom nbt of {_mob} to true
                set int tag "ECLvl" of custom nbt of {_mob} to {_level}
                set boolean tag "RemoveOnReset" of custom nbt of {_mob} to true
                set string tag "ECElement" of custom nbt of {_mob} to {_element}
                set long tag "ECModelHeight" of custom nbt of {_mob} to {_modelHeight}
                set boolean tag "ECWorldQuestMob" of custom nbt of {_mob} to true
                set boolean tag "Silent" of nbt of {_mob} to true

                set metadata value "ECSpawnLocation" of {_mob} to loop-value-2
                if {_item} is set:
                    set {_mob}'s held item to {_item}
                if yaml list "Mobs.%{_mobType}%.Sounds" in "WorldQuestList" is set:
                    set {_sounds::*} to yaml list "Mobs.%{_mobType}%.Sounds" in "WorldQuestList"
                    WorldQuestMobSounds({_mob}, {_sounds::*})

                set {_scale} to yaml value "Mobs.%{_mobType}%.Scale" in "WorldQuestList"
                set scale attribute of {_mob} to {_scale}

                if yaml value "Mobs.%{_mobType}%.Model" in "WorldQuestList" != "none":
                    set {_modelName} to yaml value "Mobs.%{_mobType}%.Model" in "WorldQuestList"
                    set {_model} to BetterModel.model({_modelName}).get().getOrCreate({_mob})
                    {_model}.registry().reload()

                MobInfoAssignments({_mob}, {_loc})

function WorldQuestRespawnMob(mob: entity):
    broadcast metadata value "ECSpawnLocation" of {_mob}
    clear metadata value "ECSpawnLocation" of {_mob}

function WorldQuestMobSounds(mob: entity, sounds: strings):
    while {_mob} is alive:
        set {_randomCd} to a random number between 5.0 and 10.0
        set {_wait} to "%{_randomCd}% seconds" parsed as timespan
        set {_sound} to a random element of {_sounds::*}
        play sound {_sound} with volume 3 and pitch 1 at location of {_mob}
        wait {_wait}

function MobInfoAssignments(mob: entity, loc: location):
    loop 2 times:
        spawn an armor stand at {_loc}
        set boolean tag "Marker" of nbt of last spawned armor stand to true
        set boolean tag "Invulnerable" of nbt of last spawned armor stand to true
        set boolean tag "Invisible" of nbt of last spawned armor stand to true
        set boolean tag "CustomNameVisible" of nbt of last spawned armor stand to true
        set boolean tag "NoGravity" of nbt of last spawned armor stand to true

        set boolean tag "RemoveOnReset" of custom nbt of last spawned armor stand to true

        if loop-counter = 1:
            set display name of last spawned armor stand to "&a|||||||||| &f(100%%)"
            set string tag "ECTextAbove" of custom nbt of {_mob} to uuid of last spawned armor stand
        else:
            set {_mobLevel} to int tag "ECLvl" of custom nbt of {_mob}
            set display name of last spawned armor stand to "&4Level %{_mobLevel}%"
            set string tag "ECTextAboveLevel" of custom nbt of {_mob} to uuid of last spawned armor stand

        push {_mob} upwards with velocity 0.01

function getActiveWorldQuests() :: strings:
    return {activeWorldQuests::*}

on join:
    loop {activeWorldQuests::*}:
        if yaml value "World Quests.%loop-value%.Type" in "WorldQuestList" = "Collect Things":
            make player see block at location(0, 0, 0,world "world") as stone


function DeleteWorldQuestMarkers():
    loop {worldQuestCount} times:
        execute console command "dmarker delete set:WorldQuests id:%loop-counter%"
    set {worldQuestCount} to 0

function CreateWorldQuest(worldQuests: integer):
    #Remove last week's World Quests
    DeleteWorldQuestMarkers()
    clear {activeWorldQuests::*}

    set {_worldQuestList::*} to yaml node keys "World Quests" in "WorldQuestList"
    loop {_worldQuests} times:
        stop loop if size of {_worldQuestList::*} = 0
        set {_randomWorldQuest} to a random element of {_worldQuestList::*}
        remove {_randomWorldQuest} from {_worldQuestList::*}
        add {_randomWorldQuest} to {activeWorldQuests::*}

        set {_WQLocation} to yaml value "World Quests.%{_randomWorldQuest}%.Location" in "WorldQuestList"
        set {_WQLocationMin} and {_WQLocationMax} to {_WQLocation}

        increase x-coordinate of {_WQLocationMin} by -100
        increase z-coordinate of {_WQLocationMin} by -100
        increase x-coordinate of {_WQLocationMax} by 100
        increase z-coordinate of {_WQLocationMax} by 100

        set {_plugin} to instance of plugin "Skript"
        loop all chunks within {_WQLocationMin} and {_WQLocationMax}:
            set {_chunk} to loop-chunk
            set {_chunkLoc} to block at 0,0,0 in {_chunk}
            {_chunk}.addPluginChunkTicket({_plugin})
            {_chunk}.getWorld().getChunkAtAsync({_chunkLoc})
            wait 1 tick if loop-counter-2 is divisible by 20

        set {_worldQuestRarity} to yaml value "World Quests.%{_randomWorldQuest}%.Rarity" in "WorldQuestList"
        set {_worldQuestGiver} to yaml value "World Quests.%{_randomWorldQuest}%.Quest Giver" in "WorldQuestList"
        set {_worldQuestType} to yaml value "World Quests.%{_randomWorldQuest}%.Type" in "WorldQuestList"
        set {_worldQuestFaction} to yaml value "Quest Givers.%{_worldQuestGiver}%.Faction" in "WorldQuestList"
        set {_npcIcon} to yaml value "Quest Givers.%{_worldQuestGiver}%.Quest Icon" in "WorldQuestList"
        set {_questText} to yaml value "Quest Text.%{_randomWorldQuest}%.Dialogue" in "WorldQuestList"
        set {_rewards::*} to yaml list "World Quests.%{_randomWorldQuest}%.Rewards" in "WorldQuestList"
        set {_reward} to a random element of {_rewards::*}
        set {_rewardImage} to yaml value "Rewards.%{_reward}%.Image link" in "WorldQuestList"
        set {_rewardDescription} to yaml value "Rewards.%{_reward}%.Description" in "WorldQuestList"
        set {_EXP} to yaml value "World Quests.%{_randomWorldQuest}%.EXP" in "WorldQuestList"
        set {_reputation} to yaml value "World Quests.%{_randomWorldQuest}%.Reputation" in "WorldQuestList"

        WorldQuestSpawn({_randomWorldQuest})

        if {_worldQuestRarity} = "Normal":
            set {_colour} to "#00ff00"
        else if {_worldQuestRarity} = "Rare":
            set {_colour} to "#0070dd"
        else if {_worldQuestRarity} = "Epic":
            set {_colour} to "#a335ee"

        set {_objectiveItems::*} to yaml node keys "Tasks.%{_worldQuestType}%.%{_randomWorldQuest}%" in "WorldQuestList"
        loop {_objectiveItems::*}:
            set {_requirement} to yaml value "Tasks.%{_worldQuestType}%.%{_randomWorldQuest}%.%loop-value-2%.Requirement" in "WorldQuestList"
            set {_objective} to yaml value "Tasks.%{_worldQuestType}%.Objective" in "WorldQuestList"
            replace all "{COMPLETED}" in {_objective} with "0"
            replace all "{MOBNAME}" in {_objective} with loop-value-2
            replace all "{REQUIREMENT}" in {_objective} with "%{_requirement}%"
            replace all "{REQUIREMENT}" in {_questText} with "%{_requirement}%"
            replace all "{ITEMNAME}" in {_objective} with "%loop-value-2% retrieved"
            add "- %{_objective}%" to {_objectives::*}

        set {_html} to join (yaml list "HTML" in "WorldQuestHTML") by ""
        replace all "{WORLDQUEST}" in {_html} with {_randomWorldQuest}
        replace all "{FACTION}" in {_html} with {_worldQuestFaction}
        replace all "{NPCNAME}" in {_html} with {_worldQuestGiver}
        replace all "{COLOUR}" in {_html} with {_colour}
        replace all "{OBJECTIVE}" in {_html} with (join {_objectives::*} by "<br>")
        replace all "{QUESTTEXT}" in {_html} with {_questText}
        replace all "{NPCICON}" in {_html} with {_npcIcon}
        replace all "{REWARDNAME}" in {_html} with {_reward}
        replace all "{REWARDIMAGE}" in {_html} with {_rewardImage}
        replace all "{REWARDDESCRIPTION}" in {_html} with {_rewardDescription}
        replace all "{EXP}" in {_html} with "%{_EXP}%"
        replace all "{REPUTATION}" in {_html} with "%{_reputation}%"
        
        set {_y} to y-coordinate of {_WQLocation}

        add 1 to {worldQuestCount}
        addDynmapWorldQuestMarker({_html}, {worldQuestCount}, {_WQLocation})
        clear {_objectives::*}

function addDynmapWorldQuestMarker(label: text, id: integer, WQLocation: location):
    set {_x} to x-coordinate of {_WQLocation}
    set {_y} to y-coordinate of {_WQLocation}
    set {_z} to z-coordinate of {_WQLocation}

    set {_world} to "%world of {_WQLocation}%"

    set {_dynmap} to Bukkit.getPluginManager().getPlugin("dynmap")
    set {_markerApi} to {_dynmap}.getMarkerAPI()

    set {_markerSet} to {_markerApi}.getMarkerSet("WorldQuests")
    set {_icon} to {_markerApi}.getMarkerIcon("questmarker")

    set {_marker} to {_markerSet}.createMarker("%{_id}%", " ", {_world}, {_x}, {_y}, {_z}, {_icon}, true)
    broadcast {_marker}.setLabel({_label}, true)
    
command /ly2:
    trigger:
        if yaml "WorldQuestHTML" is loaded:
            save yaml "WorldQuestHTML"
            unload yaml "WorldQuestHTML"
            broadcast "&cunloaded yaml"
        else:
            load yaml "plugins/Skript/worldquests/WorldQuestHTML" as "WorldQuestHTML"
            broadcast "&bloaded yaml"
command /wqtest:
    trigger:
        #loop all loaded chunks in player's world:
        #    if loop-value.getPluginChunkTickets() is set:
        #        unload loop-value
        
            
        if player's name = "Pehrek":
            CreateWorldQuest(2)
           

            #Magni

            #Replace band aid execute command with API hook later
            #Functional code below - fix .createMarker() later down the line
            #set {_api} to Bukkit.getPluginManager().getPlugin("dynmap")
            #set {_icon} to {_api}.getMarkerAPI().getMarkerIcon("questmarker")

            #set {_markerSet} to {_api}.getMarkerAPI().createMarkerSet("WorldQuests", "World Quests", null, true)
            #set {_randomId} to random 8 char string from charset `0-9` `a-z`

            #{_markerSet}.createMarker({_randomId}, {_randomQuest}, {_x}, {_y}, {_z}, {_icon}, true)

on shoot:
    if shooter is a drowned:
        if cooldown "ShootTrident%uuid of shooter%" is finished:
            create cooldown "ShootTrident%uuid of shooter%" for 5 seconds
        else:
            cancel event
