command /artefakt:
    trigger:
        if name of player = "Pehrek":
            set {_icebreaker} to diamond sword named "<##40e9ff>Icebreaker" with lore "&6Legendary Artifact" and "&7Item lore%nl% %nl%<##add8e6>+24.6%% Ice Damage%nl%<##f74428>+101 Damage%nl%<##fca417>+42 Critical Hit%nl%<##19943e>+30 Haste%nl% %nl%<##40e9ff>Special Effect:%nl%<##40e9ff>Increases critical Ice damage dealt%nl%<##40e9ff>by 12%%.%nl% %nl%&fUpgraded: +0%nl%&m&8---------------------%nl%&7Star Level: <##8cf0ff>★★★★★%nl%&8Unique Equipped" with nbt from "{CustomModelData:1}"
            add nbt from "{HideFlags:2}" to nbt of {_icebreaker}
            give {_icebreaker} to player