function ArtifactSetStats(i: item, eledmg: text, critdmg: number, seconmin: integer, seconmax: integer, heal: number) :: item:
	if {_heal} is not 0:
		set line 3 of lore of {_i} to RelicMainStat("%{_eledmg}%", {_critdmg}, {_heal})
	else:
		set line 3 of lore of {_i} to RelicMainStat("%{_eledmg}%", {_critdmg}, 0)
	set {_secondaries::*} to RelicSecondaries({_seconmin}, {_seconmax})
	set line 4 of lore of {_i} to {_secondaries::1}
	set line 5 of lore of {_i} to {_secondaries::2}
	set line 6 of lore of {_i} to {_secondaries::3}
	return {_i}


function getArtifactDescription(artifactSet: text) :: text:
	set {_description} to yaml value "Artifacts.%{_artifactSet}%.Description" in "ArtifactList"
	set {_valueNames::*} to yaml node keys "Values.%{_artifactSet}%" in "ArtifactList"
	loop {_valueNames::*}:
		set {_value} to yaml value "Values.%{_artifactSet}%.%loop-value%" in "ArtifactList"
		replace all "{%loop-value%}" in {_description} with "%{_value}%"
	return {_description}

function getArtifactIcon(artifactSet: text) :: text:
	set {_icon} to yaml value "Artifact.%{_artifactSet}%.Icon" in "ArtifactList"
	return {_icon}

function getArtifactPieces(artifactSet: text) :: texts:
	set {_pieces::*} to yaml value "Artifact.%{_artifactSet}%.Items" in "ArtifactList"
	return {_pieces::*}

function getArtifactType(artifactSet: text, artifactPiece: text) :: texts:
	set {_type} to yaml value "Artifact Pieces.%{_artifactSet}%.%{_artifactPiece}%.Type" in "ArtifactList"
	return {_type}


