on load:
    #POLISH
    set {kotobalonygadzet} to lightning rod named "<##e187ff>Koto-balony" with lore "<##ff87c9>Gadżet%nl%&7Przywołuje lewitujące koty na lince,%nl%&7a następnie unosi gracza w powietrzu!%nl%&8Gadżet ##1"
    set {kittycannongadzet} to stick named "<##ab87ff>Kitty Cannon" with lore "<##ff87c9>Gadżet%nl%&7Strzela wybuchowymi kociakami!%nl%&8Gadżet ##2" with nbt from "{CustomModelData:8}"

    #ENGLISH
    set {kotobalonygadzetEN} to lightning rod named "<##e187ff>Cat Balloons" with lore "<##ff87c9>Gadget%nl%&7Summons levitating cats on a leash,%nl%&7which lift up the player in the air!%nl%&8Gadget ##1"
    set {kittycannongadzetEN} to stick named "<##ab87ff>Kitty Cannon" with lore "<##ff87c9>Gadget%nl%&7Shoots explosive kittens!%nl%&8Gadget ##2" with nbt from "{CustomModelData:8}"


on rightclick:
    if player's tool is (item amount of player's tool) of {kotobalonygadzet}:
        if cooldown "kotobalony%player%" is finished:
            create cooldown "kotobalony%player%" for 30 seconds
            loop 10 times:
                spawn a cat at player's location with nbt from "{Invulnerable:1b}"
                apply levitation 1 to last spawned cat for 2 minutes
                add uuid of last spawned cat to {-cattycat::*}
                leash the last spawned cat to player
                set {_pitch} to a random number between 0 and 2
                play sound "minecraft:entity.cat.stray_ambient" with volume 3 and pitch {_pitch} at last spawned cat
                wait 0.4 seconds
            apply levitation 1 without particles to player for 7 seconds
            wait 7 seconds
            loop {-cattycat::*}:
                set {_uuid} to loop-value parsed as entity
                kill {_uuid}
            clear {-cattycat::*}
        else:
            cancel event
            if {tekstcd::%player%} = true:
                set {_cdd} to cooldown "kotobalony%player%"
                if {language::%player%} = "English":
                    send "<##ab87ff>You must wait &f%{_cdd}%<##ab87ff> to use this ability." to player
                else:
                    send "<##ab87ff>Musisz odczekać &f%{_cdd}%<##ab87ff>, aby użyć tej umiejętności." to player
    if player's tool is (item amount of player's tool) of {kittycannongadzet}:
        if cooldown "kittycannon%player%" is finished:
            create cooldown "kittycannon%player%" for 0.75 seconds
            spawn a cat at block above player's location with nbt from "{Invulnerable:1b}"
            set {_cat} to last spawned cat
            push last spawned cat in player's direction with speed 2
            set {_pitch} to a random number between 0 and 2
            play sound "minecraft:entity.cat.stray_ambient" with volume 2 and pitch {_pitch} at {_cat}
            wait 2 ticks
            while {_cat} is not on ground:
                wait 2 ticks
            create a fake explosion at {_cat}
            kill {_cat}
        else:
            cancel event
            if {tekstcd::%player%} = true:
                set {_cdd} to cooldown "kittycannon%player%"
                if {language::%player%} = "English":
                    send "<##ab87ff>You must wait &f%{_cdd}%<##ab87ff> to use this ability." to player
                else:
                    send "<##ab87ff>Musisz odczekać &f%{_cdd}%<##ab87ff>, aby użyć tej umiejętności." to player
        
on stop:
    if {-cattycat::*} is set:
        loop {-cattycat::*}:
            set {_uuid} to loop-value parsed as entity
            kill {_uuid}
        clear {-cattycat::*}
