on load:
    #POLISH
    set {kotobalonygadzet} to lightning rod named "<##e187ff>Koto-balony" with lore "<##ff87c9>Gadżet%nl%&f30 sekundowy cooldown%nl%&7Przywołuje lewitujące koty na lince,%nl%&7a następnie unosi gracza w powietrzu!%nl%&8&oOtrzymany z Festynu Księżyca.%nl%&8&oID Gadżetu ##1" with nbt from "{CatBalloonsGadget:1b}"
    set {kittycannongadzet} to stick named "<##ab87ff>Kitty Cannon" with lore "<##ff87c9>Gadżet%nl%&f0.5 sekundowy cooldown%nl%&7Strzela wybuchowymi kociakami!%nl%&8&oOtrzymany z Festynu Księżyca.%nl%&8&oID Gadżetu ##2" with nbt from "{CustomModelData:8,KittyCannonGadget:1b}"
    set {fasiagadzet} to eye of ender named "<##32a852>Fasia" with lore "<##ff87c9>Gadżet%nl%&f8 sekundowy cooldown%nl%&7Wystrzela cię w powietrze, odpalając%nl%&7fajerwerki!%nl%&8&oID Gadżetu ##3" with nbt from "{FasiaGadget:1b}"
    set {playerseatgadzet} to saddle named "<##ff9e21>Siodło na Graczy" with lore "<##ff87c9>Gadżet%nl%&fbrak cooldownu%nl%&7Pozwala na dosiądnięcie wybranego%nl%&7gracza!%nl%&8&oID Gadżetu ##4" with nbt from "{PlayerSaddleGadget:1b}"
    set {grapplinghookgadzetEN} to fishing rod named "<##739ad9>Grappling Hook" with lore "<##ff87c9>Gadżet%nl%&fbrak cooldownu%nl%&7Przymocuj się do powierzchni%nl%&7i przyciągnij się!%nl%&8&oID Gadżetu ##5" with nbt from "{GrapplingHookGadget:1b,Unbreakable:1b}"
    #ENGLISH
    set {kotobalonygadzetEN} to lightning rod named "<##e187ff>Cat-balloons" with lore "<##ff87c9>Gadget%nl%&f30 second cooldown%nl%&7Summons levitating cats on a leash,%nl%&7which lift up the player in the air!%nl%&8&8&oObtained from the Lunar Festival.%nl%&8&oGadget ID ##1" with nbt from "{CatBalloonsGadget:1b}"
    set {kittycannongadzetEN} to stick named "<##ab87ff>Kitty Cannon" with lore "<##ff87c9>Gadget%nl%&f0.5 second cooldown%nl%&7Shoots explosive kittens!%nl%&8&oObtained from the Lunar Festival.%nl%&8&oGadget ID ##2" with nbt from "{CustomModelData:8,KittyCannonGadget:1b}"
    set {fasiagadzetEN} to eye of ender named "<##32a852>Fasia" with lore "<##ff87c9>Gadget%nl%&f8 second cooldown%nl%&7Launches you up in the air while%nl%&7shooting fireworks!%nl%&8&oGadget ID ##3" with nbt from "{FasiaGadget:1b}"
    set {playerseatgadzetEN} to saddle named "<##ff9e21>Player Saddle" with lore "<##ff87c9>Gadget%nl%&fno cooldown%nl%&7Lets you sit on a chosen player!%nl%&8&oGadget ID ##4" with nbt from "{PlayerSaddleGadget:1b}"
    set {grapplinghookgadzetEN} to fishing rod named "<##739ad9>Grappling Hook" with lore "<##ff87c9>Gadget%nl%&fno cooldown%nl%&7Attach to a surface and pull%nl%&7yourself in!%nl%&8&oGadget ID ##5" with nbt from "{GrapplingHookGadget:1b,Unbreakable:1b}"
    #firework craze laucnhes fireworks in a circle around, random colours
    #

on rightclick:
    if tag "CatBalloonsGadget" of nbt of player's tool is set:
        cancel event
        if cooldown "kotobalony%player%" is finished:
            create cooldown "kotobalony%player%" for 30 seconds
            set {_int} to a random integer between 1 and 1
            if {_int} = 1:
                if {language::%player%} = "English":
                    send "&f&oCat-balloons: Hyperspeed!" to player
                else:
                    send "&fKoto-balony: Hyperspeed!" to player
                set {_velocity} to 2
                set {_wait} to 0.1 seconds
                set {_levitation} to 10
            else:
                set {_velocity} to 0.5
                set {_wait} to 0.3 seconds
                set {_levitation} to 1
            loop 10 times:
                spawn a cat at player's location with nbt from "{Invulnerable:1b}"
                push last spawned cat upward with velocity {_velocity}
                apply levitation {_levitation} without particles to last spawned cat for 2 minutes
                add uuid of last spawned cat to {-cattycat::*}
                leash the last spawned cat to player
                set {_pitch} to a random number between 0 and 2
                play sound "minecraft:entity.cat.stray_ambient" with volume 3 and pitch {_pitch} at last spawned cat
                play sound "entity.item.pickup" with volume 3 and pitch {_pitch} at last spawned cat
                wait {_wait}
            apply levitation {_levitation} without particles to player for 7 seconds
            wait 7 seconds
            loop {-cattycat::*}:
                set {_uuid} to loop-value parsed as entity
                kill {_uuid}
                play 1 explosion at {_uuid}
                wait 1 tick
            clear {-cattycat::*}
            play sound "entity.generic.explode" with volume 3 and pitch 1 at player
        else:
            cancel event
            if {tekstcd::%player%} = true:
                set {_cdd} to cooldown "kotobalony%player%"
                if {language::%player%} = "English":
                    send "<##ab87ff>You must wait &f%{_cdd}%<##ab87ff> to use this gadget." to player
                else:
                    send "<##ab87ff>Musisz odczekać &f%{_cdd}%<##ab87ff>, aby użyć tego gadżetu." to player
    else if tag "KittyCannonGadget" of nbt of player's tool is set:
        if cooldown "kittycannon%player%" is finished:
            create cooldown "kittycannon%player%" for 0.5 seconds
            set {_location} to location 0.3 in front of player's location
            set {_location} to location 0.75 above {_location}
            spawn a cat at {_location} with nbt from "{Invulnerable:1b}"
            set {_int} to a random integer between 1 and 10
            set {_cat} to last spawned cat
            if {_int} = 10:
                spawn 1 armor stand at location 1 above {_cat}
                add nbt from "{Invisible:1b,Invulnerable:1b,Small:1b}" to nbt of last spawned armor stand
                set last spawned armor stand's chestplate to elytra
                push last spawned armor stand in player's direction with speed 1
                set {_elytra} to last spawned armor stand
                make {_cat} ride {_elytra}
                set {_p} to potion effect of slow falling of tier 4 without particles for 1 day
                add {_p} to potion effects of last spawned armor stand
                play sound "entity.cat.purreow" with volume 1 and pitch 0 at {_cat}
                send "&f&oKitty Cannon: Pussy game still cold!" to player
            else:
                push last spawned cat in player's direction with speed 1.75
            set {_pitch} to a random number between 0 and 2
            play sound "minecraft:entity.cat.stray_ambient" with volume 2 and pitch {_pitch} at {_cat}
            wait 3 ticks
            if {_elytra} is set:
                while {_elytra} is not on ground:
                    wait 4 ticks
                create a fake explosion at {_elytra}
                kill {_elytra}
                kill {_cat}
            else:
                while {_cat} is not on ground:
                    wait 4 ticks
                create a fake explosion at {_cat}
                kill {_cat}

        else:
            cancel event
            if {tekstcd::%player%} = true:
                set {_cdd} to cooldown "kittycannon%player%"
                if {language::%player%} = "English":
                    send "<##ab87ff>You must wait &f%{_cdd}%<##ab87ff> to use this gadget." to player
                else:
                    send "<##ab87ff>Musisz odczekać &f%{_cdd}%<##ab87ff>, aby użyć tego gadżetu." to player
    else if tag "FasiaGadget" of nbt of player's tool is set:
        cancel event
        if cooldown "fasia%player%" is finished:
            create cooldown "fasia%player%" for 8 seconds
            push player upwards with velocity 3
            wait 3 ticks
            while player is not on ground:
                launch ball large colored red and yellow at player's location with duration 0.1
                wait 2 ticks
        else:
            cancel event
            if {tekstcd::%player%} = true:
                set {_cdd} to cooldown "fasia%player%"
                if {language::%player%} = "English":
                    send "<##ab87ff>You must wait &f%{_cdd}%<##ab87ff> to use this gadget." to player
                else:
                    send "<##ab87ff>Musisz odczekać &f%{_cdd}%<##ab87ff>, aby użyć tego gadżetu." to player
    else if tag "PlayerSaddleGadget" of nbt of player's tool is set:
        cancel event
        if target of player is a player:
            set {_target} to target of player
            if distance between player and {_target} < 10:
                make player mount {_target}
   
on stop:
    if {-cattycat::*} is set:
        loop {-cattycat::*}:
            set {_uuid} to loop-value parsed as entity
            kill {_uuid}
        clear {-cattycat::*}

function catSpin(e: entity):
    while {_e} is alive:
        set {_loc} to {_e}'s location
        set {_yaw} to yaw of {_loc}
        add 30 to {_yaw}
        set yaw of {_loc} to {_yaw}
        teleport {_e} to {_loc}
        wait 3 ticks

on fishing:
    if tag "GrapplingHookGadget" of nbt of player's tool is set:
        if "%fish state%" = "reel_in" or "in_ground":
            if "%fish state%" = "reel_in":
                if block east of fish hook is solid:
                    set {_yes} to true
                else if block east of fish hook is solid:
                    set {_yes} to true
                else if block west of fish hook is solid:
                    set {_yes} to true
                else if block north of fish hook is solid:
                    set {_yes} to true
                else if block south of fish hook is solid:
                    set {_yes} to true
            else:
                set {_yes} to true
            if {_yes} = true:
                set {_loc} to location of fish hook
                push player (vector from player to {_loc}) with speed 2
        