on rightclick:
    if line 1 of lore of player's tool contains "Doświadczenie" or "Experience":
        set {_am} to (item amount of player's tool)
        set {_sloik::*} to {sloikzexpem} and {sloikzexpemEN}
        if {_sloik::*} contains 1 of player's tool:
            cancel event
            remove 1 of player's tool from player
            set {_int} to a random number between 1 and 70
            set {_otxpAfterMultiplier} to addPlayerXP(player, {_int})
            add {_otxpAfterMultiplier} to {exp::sloik::%player%}
            if {_otxpAfterMultiplier} > {_int}:
                set {_xpmsg} to "&6%{_int}% (&fx%{_otxpAfterMultiplier}/{_int}%&7)"
            else:
                set {_xpmsg} to "&6%{_int}%"
            play sound "entity.experience_orb.pickup" with volume 5 and pitch 0.6 at player
            if {language::%player%} = "English":
                send "&8[&6Earthcraft&8] &7You receive &6%{_xpmsg}% &7experience!" to player
            else:
                send "&8[&6Earthcraft&8] &7Otrzymujesz &6%{_xpmsg}% &7punktów doświadczenia!" to player
            UpdateScoreboard(player)
    else if player's tool is an ender pearl:
        if name of player's tool contains "Achroite":
            if name of player's tool = "<##90e0c4>Cut Achroite Case":
                set metadata tag "Achroite Case" of player to chest inventory with 1 row named "&fAchroite Case"
                set {_menu} to metadata tag "Achroite Case" of player
                play sound "block.ender_chest.open" with volume 3 and pitch 1.49 to player
                set slot 3 of {_menu} to ender pearl named "<##90e0c4>Bold Achroite" with lore "<##e35959>+24  Strength%nl% %nl%&fQuality: &e★★★" with nbt from "{GemType:""Rare"",Gem:1b,Stats;""Strength"":24,Quality:""★★★""}"
                set slot 4 of {_menu} to ender pearl named "<##90e0c4>Brilliant Achroite" with lore "<##59c1e3>+24  Intellect%nl% %nl%&fQuality: &e★★★" with nbt from "{GemType:""Rare"",Gem:1b,Stats;""Intellect"":24,Quality:""★★★""}"
                set slot 5 of {_menu} to ender pearl named "<##90e0c4>Delicate Achroite" with lore "<##5ee359>+24  Agility%nl% %nl%&fQuality: &e★★★" with nbt from "{GemType:""Rare"",Gem:1b,Stats;""Agility"":24,Quality:""★★★""}"
                set {_slot} to 3
                loop 3 times:
                    set tag "GemType" of nbt of slot {_slot} of {_menu} to "Rare"
                    set tag "Gem" of nbt of slot {_slot} of {_menu} to true
                    set tag "Quality" of nbt of slot {_slot} of {_menu} to "★★★"
                    set tag "GemIcon" of nbt of slot {_slot} of {_menu} to ""
                    if {_slot} = 3:
                        set tag "Stats;Strength" of nbt of slot {_slot} of {_menu} to 24
                    else if {_slot} = 4:
                        set tag "Stats;Intellect" of nbt of slot {_slot} of {_menu} to 24
                    if {_slot} = 5:
                        set tag "Stats;Agility" of nbt of slot {_slot} of {_menu} to 24
                    add 1 to {_slot}
                open {_menu} to player
            else if name of player's tool = "<##90e0c4>Etui z Oszlifowanym Achroitem":
                set metadata tag "Achroite Case" of player to chest inventory with 1 row named "&fAchroite Case"
                set {_menu} to metadata tag "Achroite Case" of player
                play sound "block.ender_chest.open" with volume 3 and pitch 1.49 to player
                set slot 3 of {_menu} to ender pearl named "<##90e0c4>Odważny Achroit" with lore "<##e35959>+24  Siła%nl% %nl%&fJakość: &e★★★" with nbt from "{GemType:""Rare"",Gem:1b,Stats:""Strength"":24,Quality:""★★★""}"
                set slot 4 of {_menu} to ender pearl named "<##90e0c4>Genialny Achroit" with lore "<##59c1e3>+24  Intelekt%nl% %nl%&fJakość: &e★★★" with nbt from "{GemType:""Rare"",Gem:1b,Stats;""Intellect"":24,Quality:""★★★""}"
                set slot 5 of {_menu} to ender pearl named "<##90e0c4>Delikatny Achroit" with lore "<##5ee359>+24  Zwinność%nl% %nl%&fJakość: &e★★★" with nbt from "{GemType:""Rare"",Gem:1b,Stats;""Agility"":24,Quality:""★★★""}"
                set {_slot} to 3
                loop 3 times:
                    set tag "GemType" of nbt of slot {_slot} of {_menu} to "Rare"
                    set tag "Gem" of nbt of slot {_slot} of {_menu} to true
                    set tag "Quality" of nbt of slot {_slot} of {_menu} to "★★★"
                    set tag "GemIcon" of nbt of slot {_slot} of {_menu} to ""
                    if {_slot} = 3:
                        set tag "Stats;Strength" of nbt of slot {_slot} of {_menu} to 24
                    else if {_slot} = 4:
                        set tag "Stats;Intellect" of nbt of slot {_slot} of {_menu} to 24
                    if {_slot} = 5:
                        set tag "Stats;Agility" of nbt of slot {_slot} of {_menu} to 24
                    add 1 to {_slot}
                open {_menu} to player
    else if tag "EssenceBundle" of nbt of player's tool is set:
        remove 1 of player's tool from player
        if {language::%player%} = "English":
            loop {esencjeEN::*}:
                giveItem(player, 16 of loop-value)
            send "<##8f9ff2>Essence Bundle &f> &oSuccessfully obtained 16 of each Essence!" to player
        else:
            loop {esencje::*}:
                giveItem(player, 16 of loop-value)
            send "<##8f9ff2>Zestaw Esencji &f> &oPomyślnie otrzymano 16 z każdej Esencji!" to player
    else if tag "SapphireDice" of nbt of player's tool is set:
        remove 1 of player's tool from player
        if metadata value "SapphireDice" of player is not set:
            SapphireDice(player)
            set metadata value "SapphireDice" of player to 5 minutes
        else:
            set {_duration} to metadata value "SapphireDice" of player
            add 5 minutes to {_duration}
            set metadata value "SapphireDice" of player to {_duration}
        add 1 to {sapphireDiceUsed::%player%}
        if {language::%player%} = "English":
            if {_duration} is set:
                set {_durationText} to "%{_duration}%"
                send "<##025b95>Activated &f🎲 Triple EXP <##025b95>from &f⛏ Mining <##025b95>and &f💀 Combat <##025b95>for &f5 minutes<##025b95>! (Total: &f%{_duration}%<##025b95>)" to player
            else:
                send "<##025b95>Activated &f🎲 Triple EXP <##025b95>from &f⛏ Mining <##025b95>and &f💀 Combat <##025b95>for &f5 minutes<##025b95>!" to player
        else:
            if {_duration} is set:
                set {_durationText} to "%{_duration}%"
                replace all "minutes" in {_durationText} with "minut"
                replace all "minute" in {_durationText} with "minuta"
                replace all "seconds" in {_durationText} with "sekund"
                replace all "second" in {_durationText} with "sekunda"
                send "<##025b95>Aktywowano &f🎲 Potrójny EXP <##025b95>z &f⛏ Kopania <##025b95>i &f💀 Walk <##025b95>na &f5 minut##025b95>! (Łącznie: &f%{_duration}%<##025b95>)" to player
            else:
                send "<##025b95>Aktywowano &f🎲 Potrójny EXP <##025b95>z &f⛏ Kopania <##025b95>i &f💀 Walk <##025b95>na &f5 minut##025b95>!" to player
        play sound "entity.witch.drink" with volume 4 and pitch 2 at player

function SapphireDice(p: player):
    while metadata value "SapphireDice" of {_p} > 0 seconds:
        wait 1 second
        set {_duration} to metadata value "SapphireDice" of {_p}
        remove 1 second from {_duration}
        set metadata value "SapphireDice" of {_p} to {_duration}
    clear metadata value "SapphireDice" of {_p}
    if {language::%{_p}%} = "English":
        send "&f🎲 <##025b95>Sapphire Dice boost has ended." to {_p}
    else:
        send "&f🎲 <##025b95>Boost Szafirowych Kostek się skończył." to {_p}

on inventory click:
    if event-inventory = metadata tag "Achroite Case" of player:
        cancel event
        if event-slot is not air:
            set {_indexes::*} to 3, 4 and 5
            if {_indexes::*} contains index of clicked slot:
                set {_possibleItemsEN::*} to "<##90e0c4>Bold Achroite", "<##90e0c4>Brilliant Achroite" and "<##90e0c4>Delicate Achroite"
                set {_possibleItems::*} to "<##90e0c4>Odważny Achroit", "<##90e0c4>Genialny Achroit" and "<##90e0c4>Delikatny Achroit"
                if {_possibleItemsEN::*} contains name of event-slot:
                    send "&fSuccessfully picked &e★★★ %name of event-slot% &ffrom the <##90e0c4>Cut Achroite Case&f!" to player
                    set {_success} to true
                else if {_possibleItems::*} contains name of event-slot:
                    send "&fPomyślnie wybrano &e★★★ %name of event-slot% &fz <##90e0c4>Etui z Oszlifowanym Achroitem&f!" to player
                    set {_success} to true
                if {_success} is true:
                    give player 1 of event-slot
                    teleport player to player's location
                    remove ender pearl named "<##90e0c4>Cut Achroite Case" with lore "<##6dadde>Unique Design Gem" and "&7This item contains a &e★★★ <##90e0c4>Cut Achroite&7,%nl%&7a potent <##0070dd>Rare Gem &7that increases a Card's%nl%&7primary stat!%nl%&cThis item is consumed upon use.%nl% %nl%&9(&3&l!&9) &3Right-click to select your preferred%nl%&3version of Cut Achroite." from player's inventory
                    remove ender pearl named "<##90e0c4>Etui z Oszlifowanym Achroitem" with lore "<##6dadde>Gem Unikalnego Wzoru" and "&7Ten przedmiot zawiera &e★★★ <##90e0c4>Oszlifowany%nl%<##90e0c4>Achroit&7, <##0070dd>Rzadki Gem&7, który zwiększa%nl%&7główną statystykę karty!%nl%&cTen przedmiot zużywa się po kliknięciu.%nl% %nl%&9(&3&l!&9) &3Kliknij prawym, by wybrać preferowaną%nl%&3wersję Oszlifowanego Achroitu." from player's inventory
                    play sound "entity.firework_rocket.large_blast_far" with volume 3 and pitch 0.8 to player
                    play sound "entity.firework_rocket.launch" with volume 3 and pitch 1.7 to player
                    play sound "entity.player.levelup" with volume 3 and pitch 1.4 to player

