#<##f0e359>

on load:
	set {traits::Delphox::*} to "Blaster Master", "Controlled Destruction", "Duplicative Incineration", "Fervent Flickering", "Fiery Rush", "Firefall", "Firestarter", "Pyroclasm", "Pyromaniac" and "Pyrotechnics"
	set {Blaster Master} to ""
	set {Controlled Destruction} to ""
	set {Duplicative Incineration} to ""
	set {Fervent Flickering} to ""
	set {Fiery Rush} to ""
	set {Firefall} to ""
	set {Firestarter} to ""
	set {Pyroclasm} to ""
	set {Pyromaniac} to ""
	set {Pyrotechnics} to ""
	
on join:
	if {kolekcja::karty::%player%::*} contains "Delphox":
		loop 10 times:
			set {_r} to {traits::Delphox::%loop-number%}
			set {_x%loop-number%} to {trait::Delphox::%{_r}%::%player%}
		if {language::%player%} = "English":
			set {traits::Delphox::1::opis::%player%} to "<##e53311>Flamethrower &7increases your Mastery by%nl%&f%20*{_x1}% &7for 3 seconds. This effect stacks."
			set {traits::Delphox::2::opis::%player%} to "&7Your first detonated <##e53311>Inferno &7after using%nl%<##e53311>Flame Barrier &7will always critically strike and%nl%&7deal an extra &f%1.5*{_x2}% &7damage."
			set {traits::Delphox::3::opis::%player%} to "<##e53311>Flamethrower &7has &f%1*{_x3}%%% &7chance to ignite%nl%&7your target again after its expiration.%nl%&7Duplicated <##e53311>Flamethrower &7applies all effects from%nl%&7your other abilities and Traits, but deals%nl%&760%% damage."
			set {traits::Delphox::4::opis::%player%} to "<##e53311>Blaze &7damage has a &f%2*{_x4}%%% &7chance per%nl%&7target hit to reduce the cooldown of%nl%<##e53311>Flamethrower &7by 0.5 seconds on all affected%nl%&7targets."
			set {traits::Delphox::5::opis::%player%} to "<##e53311>Flamethrower &7deals damage an additional 2 times%nl%&7and its cooldown is reduced by &f%0.3*{_x5}% seconds&7."
			set {traits::Delphox::6::opis::%player%} to "&7Every fourth detonated <##e53311>Inferno &7calls%nl%&7down a Meteor &7on your target,%nl%&7dealing &f%3*{_x6}% <##ff4d00>Fire &7damage to all enemies nearby."
			set {traits::Delphox::7::opis::%player%} to "<##e53311>Flamethrower &7has a &f%8.25*{_x7}%%% &7increased chance%nl%&7to critically strike and its cooldown is%nl%&7reduced by &f%0.5*{_x7}% seconds &7against targets above%nl%&790%% health."
			set {traits::Delphox::8::opis::%player%} to "&7Detonating <##e53311>Inferno &7has a &f%2.5*{_x8}%%% &7chance%nl%&7to increase the damage of your next <##e53311>Blaze%nl%&7by 230%%."
			set {traits::Delphox::9::opis::%player%} to "&7Each consecutive critical strike you deal increases%nl%&7the critical strike damage you deal by &f%1.5*{_x9}%%%%nl%&7for 6 seconds."
			set {traits::Delphox::10::opis::%player%} to "<##e53311>Flamethrower &7has a &f%5*{_x10}%%% &7chance%nl%&7to grant you an additional stack of <##e53311>Blaze&7."
		else:
			if {_x9} > 1:
				set {_tekst} to "sekundy"
			else:
				set {_tekst} to "sekundę"
			if {_x9} = 4:
				set {_tekst2} to "obrażenia"
			else:
				set {_tekst2} to "obrażeń"
			set {traits::Delphox::1::opis::%player%} to "<##e53311>Miotacz Płomieni &7zwiększa twoje Mistrzostwo o%nl%&f%20*{_x1}% &7na 3 sekundy. Ten efekt nakłada się."
			set {traits::Delphox::2::opis::%player%} to "&7Twoje pierwsze zdetonowane <##e53311>Inferno &7po użyciu%nl%<##e53311>Płomiennej Bariery &7zawsze trafi krytycznie i%nl%&7zada dodatkowe &f%1.5*{_x2}% &7obrażeń."
			set {traits::Delphox::3::opis::%player%} to "<##e53311>Miotacz Płomieni &7ma &f%1*{_x3}%%% &7szans na ponowne%nl%&7podpalenie celu, gdy dobiegnie końca.%nl%&7Zduplikowane <##e53311>Miotacze Płomieni &7aplikują wszystkie efekty%nl%&7z twoich innych umiejętności i Traits, ale%nl%&7zadaja 60%% obrażeń."
			set {traits::Delphox::4::opis::%player%} to "&7Obrażenia <##e53311>Pożaru &7mają &f%2*{_x4}%%% &7szans na%nl%&7uderzony cel, by zredukować cooldown%nl%<##e53311>Miotacza Płomieni &7o 0.5 seconds na wszystkich%nl%&7objętych celach."
			set {traits::Delphox::5::opis::%player%} to "<##e53311>Miotacz Płomieni &7zadaje obrażenia 2 dodatkowe razy%nl%&7i jego cooldown jest zmniejszony o &f%0.3*{_x5}% sekund&7."
			set {traits::Delphox::6::opis::%player%} to "&7Co czwarte zdetonowane<##e53311>Inferno &7przyzywa%nl%&7Meteor &7nad twoim celem.%nl%&7Meteor zada &f%3*{_x6}% <##ff4d00>Ognistych &7obrażeń wszystkim pobliskim wrogom."
			set {traits::Delphox::7::opis::%player%} to "<##e53311>Miotacz Płomieni &7ma o &f%8.25*{_x7}%%% &7zwiększone%nl%&7szanse na trafienie krytyczne i jego cooldown%nl%&7jest zredukowany o &f%0.5*{_x7}% sekund &7przeciwko celom powyżej%nl%&790%% zdrowia."
			set {traits::Delphox::8::opis::%player%} to "&7Zdetonowanie <##e53311>Inferno &7ma &f%2.5*{_x8}%%% &7szans%nl%&7na zwiększenie obrażeń twojego kolejnego <##e53311>Pożaru%nl%&7o 230%%."
			set {traits::Delphox::9::opis::%player%} to "&7Każde trafienie krytyczne z rzędu które zadasz%nl%&7zwiększy obrażenia krytyczne, które zadajesz o &f%1.5*{_x9}%%%%nl%&7na 6 sekund."
			set {traits::Delphox::10::opis::%player%} to "<##e53311>Miotacz Płomieni &7ma &f%5*{_x10}%%% &7szans%nl%&7na przyznanie ci dodatkowego ładunku <##e53311>Pożaru&7."
			
on leave:
	if {kolekcja::karty::%player%::*} contains "Delphox":
		loop 10 times:
			clear {traits::Delphox::%loop-number%::opis::%player%}

on rightclick:
	if name of player's tool = "<##e53311>Miotacz Płomieni" or "<##e53311>Flamethrower":
		cancel event
		if tag "Flamethrower" of nbt of player's tool is set:
			set {_target} to Target(player, 100, false)
			if {_target} is set:
				if {kartaname::%player%} = "Delphox":
					if CanUseAbility(player) != false:
						cancel event
						set {_haste} to 1 + (({haste::%player%}/4))/100 
						set {_cd} to 14/{_haste}
						set {_cd} to "%{_cd}% seconds" parsed as timespan

						if cooldown "Flamethrower%player%-%uuid of {_target}%" is finished:

							Blaze(player, {_target})

							Flamethrower(player, {_target})

							AbilityUse(player, "Flamethrower")

						else:
							cancel event
							if {_target} is set:
								if {tekstcd::%player%} is true:
									if cooldown "FlamethrowerCDText%player%" is finished:
										create cooldown "FlamethrowerCDText%player%" for 1 tick
										set {_cdd} to cooldown "Flamethrower%player%-%uuid of {_target}%"
										if {language::%player%} = "English":
											send "<##d74327>You can't ignite that target for another %{_cdd}%" to player
										else:
											send "<##d74327>Nie można podpalić tego celu przez kolejne %{_cdd}%" to player
						stop
				else:
					if {language::%player%} = "English":
						send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to player
					else:
						send "&8[&6Earthcraft&8] &6Nie masz wybranej wymaganej karty, by móc użyć tej umiejętności." to player
					play sound "block.glass.break" with volume 3 and pitch 0 to player
	else if name of player's tool = "<##e53311>Heat Snap":
		cancel event
		if tag "HeatSnap" of nbt of player's tool is set:
			if {kartaname::%player%} = "Delphox":
				if CanUseAbility(player) != false:
					if cooldown "Heat Snap%player%" is finished:
						set {_haste} to 1 + (({haste::%player%}/4))/100 
						set {_cd} to "%45/{_haste}% seconds" parsed as timespan
						set {_cdd} to 45/{_haste}

						create cooldown "Heat Snap%player%" for {_cd}
						set the cooldown of player's held item for player to {_cd}
						AbilityUse(player, "Heat Snap")

						play sound "skill.delphox.heatsnap" with volume 3 and pitch 1 at player

						set {_lore} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &f%{_cdd}% sekund%nl%&7Użycie: &fPPM&%nl%<##e53311>Otacza cię Płomienną Barierą,%nl%<##e53311>negując wszystkie obrażenia otrzymane przez%nl%<##e53311>kolejne &f%{_barrierDuration}% sekund<##e53311>."
						set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &f%{_cdd}% seconds%nl%&7Use: &fRMB%nl%<##e53311>Surrounds you in a Flame Barrier,%nl%<##e53311>negating any incoming damage for the next%nl%&f%{_blotekst}% seconds<##e53311>."
						
						translateAbility(player, "Heat Snap", "Pstryk Gorąca", "Heat Snap", {_lore}, {_loreEN})
						
						HeatSnap(player)

					else:
						cancel event
						if {tekstcd::%player%} = true:
							set {_cdd} to cooldown "Heat Snap%player%"
							if {language::%player%} = "English":
								send "<##e53311>You must wait &f%{_cdd}% <##e53311>to use this ability." to player
							else:
								send "<##e53311>Musisz odczekać &f%{_cdd}%<##e53311>, aby użyć tej umiejętności." to player
						stop
			else:
				if {language::%player%} = "English":
					send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to player
				else:
					send "&8[&6Earthcraft&8] &6Nie masz wybranej wymaganej karty, by móc użyć tej umiejętności." to player
				play sound "block.glass.break" with volume 3 and pitch 0 to player
							
	else if name of player's tool = "<##e53311>Inferno":
		cancel event
		if tag "Inferno" of nbt of player's tool is set:
			if tag "Talents;Row 5" of nbt of {karta::%player%} != "Hot Spree":
				if {kartaname::%player%} = "Delphox":
					set {_target} to Target(player, 100, false)
					if {_target} is set:
						if CanUseAbility(player) != false:
							Inferno(player, {_target})
							AbilityUse(player, "Inferno")
				else:
					if {language::%player%} = "English":
						send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to player
					else:
						send "&8[&6Earthcraft&8] &6Nie masz wybranej wymaganej karty, by móc użyć tej umiejętności." to player
					play sound "block.glass.break" with volume 3 and pitch 0 to player
			else:
				if {language::%player%} = "English":
					send "&8[&6Earthcraft&8] &6You can not use Inferno when you have Hot Spree talented." to player
				else:
					send "&8[&6Earthcraft&8] &6Nie możesz używać Inferno, gdy masz wybrany talent Hot Spree." to player
				play sound "block.glass.break" with volume 3 and pitch 0 to player

	else if name of player's tool = "<##e53311>Płomienna Bariera" or "<##e53311>Flame Barrier":
		cancel event
		if tag "FlameBarrier" of nbt of player's tool is set:
			if {kartaname::%player%} = "Delphox":
				if CanUseAbility(player) != false:

					set {_haste} to 1 + (({haste::%player%}/4))/100 
					set {_cd} to "%130/{_haste}% seconds" parsed as timespan
					set {_cdd} to 130/{_haste}
					set {_barrierDuration} to 6 + (({resistance::%player%}/25))

					if cooldown "Flame Barrier%player%" is finished:
						create cooldown "Flame Barrier%player%" for {_cd}
						set the cooldown of player's held item for player to {_cd}
						AbilityUse(player, "Flame Barrier")

						set {_lore} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &f%{_cdd}% sekund%nl%&7Użycie: &fPPM&%nl%<##e53311>Otacza cię Płomienną Barierą,%nl%<##e53311>negując wszystkie obrażenia otrzymane przez%nl%<##e53311>kolejne &f%{_barrierDuration}% sekund<##e53311>."
						set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &f%{_cdd}% seconds%nl%&7Use: &fRMB%nl%<##e53311>Surrounds you in a Flame Barrier,%nl%<##e53311>negating any incoming damage for the next%nl%&f%{_blotekst}% seconds<##e53311>."
						
						translateAbility(player, "Flame Barrier", "Płomienna Bariera", "Flame Barrier", {_lore}, {_loreEN})
						
						set {_duration} to "%{_barrierDuration}% seconds" parsed as timespan

						set metadata value "Flame Barrier" of player to true
						make player invulnerable
						FlameBarrierInfo(player, {_duration})

						play sound "block.beacon.power_select" with volume 5 and pitch 1 at player

						wait {_duration}
						make player vulnerable
						clear metadata value "Flame Barrier" of player

					else:
						cancel event
						if {tekstcd::%player%} = true:
							set {_cdd} to cooldown "Flame Barrier%player%"
							if {language::%player%} = "English":
								send "<##e53311>You must wait &f%{_cdd}% <##e53311>to use this ability." to player
							else:
								send "<##e53311>Musisz odczekać &f%{_cdd}%<##e53311>, aby użyć tej umiejętności." to player
						stop
			else:
				if {language::%player%} = "English":
					send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to player
				else:
					send "&8[&6Earthcraft&8] &6Nie masz wybranej wymaganej karty, by móc użyć tej umiejętności." to player
				play sound "block.glass.break" with volume 3 and pitch 0 to player

on sneak toggle:
	if {kartaname::%player%} = "Delphox":
		if CanUseAbility(player) != false:
			set {_target} to Target(player, 100, false)
			if {_target} is set:
				if metadata value "InfernoTarget" of {_target} is true:
					InfernoDetonate(player, {_target})
					AbilityUse(player, "Inferno (Detonate)")

function InfernoParticles(target: entity):
	while metadata value "InfernoTarget" of {_target} is true:
		set {_shape} to sphere with radius 1
		draw {_shape} at block above {_target}
		wait 1 second

function FlameBarrierInfo(p: player, duration: timespan):
	while metadata value "Flame Barrier" of {_p} is set:
		if metadata value "Blaze" of {_p} is set:
			set {_blaze} to metadata value "Blaze" of {_p}
		else:
			set {_blaze} to 0
		send action bar "%{_blaze}%  &f|  %{_duration}%" to {_p}
		draw 40 flame at location above {_p} with offset vector(0.3, 0.4, 0.3) with extra 0.06
		wait 1 second
		remove 1 second from {_duration}

function Blaze(p: player, target: entity, heatSnap: boolean = false):
	set {_blaze} to metadata value "Blaze" of {_p}
	add 1 to {_blaze}
	if tag "Talents;Row 1" of nbt of {karta::%{_p}%} = "Pyrotechnics":
		chance of 20%:
			add 1 to {_blaze}
	if tag "Talents;Row 4" of nbt of {karta::%{_p}%} = "Flame Cascade":
		if {_heatSnap} is true:
			set {_flameCascade} to true

	set metadata value "Blaze" of {_p} to {_blaze}

	set {_pitch} to 0.5 + 0.5*{_blaze}
	play sound "entity.blaze.hurt" with volume 2 and pitch {_pitch} to {_p}

	send action bar "%{_blaze}% " to {_p}

	wait 1 tick
	if metadata value "Blaze" of {_p} >= 3:
		set {_blaze} to metadata value "Blaze" of {_p}
		remove 3 from {_blaze}
		set metadata value "Blaze" of {_p} to {_blaze}
		send action bar "%{_blaze}% " to {_p}

		set {_loopCount} to 0
		set {_targetsAffected} to 3

		play sound "item.firecharge.use" with volume 1 and pitch 1 at {_target}

		set {_loopRadius} to 4 + ({crowdcontrol::%{_p}%}/50)
		set {_entities::*} to LoopEntitiesAroundTarget({_target}, {_loopRadius}, true)

		if tag "Talents;Row 3" of nbt of {karta::%{_p}%} = "Firespread":
			add 2 to {_targetsAffected}
			set {_targetsHit} to size of {_entities::*}
			if {_targetsHit} > 5:
				set {_targetsHit} to 5
			set {_firespread} to 1 + 0.3*{_targetsHit}

		loop {_entities::*}:
			add 1 to {_loopCount}
			set {_dmgBlaze} to 3 + ({versatility::%{_p}%}/180) + ({damage::%{_p}%}/60) + {primarystat::%{_p}%}/30
			set {_mastery} to 2.5 + (({mastery::%{_p}%}/165))

			if {_firespread} is set:
				set {_dmgBlaze} to {_dmgBlaze} * {_firespread}
			if {_flameCascade} is set:
				set {_dmgBlaze} to {_dmgBlaze} * 1.7
			if tag "Talents;Row 5" of nbt of {karta::%{_p}%} = "Wildfire":
				set {_wildfireDamageAmp} to 1 + {wildfireDelphox::%{_p}%}/100
				set {_dmgBlaze} to {_dmgBlaze} * {_wildfireDamageAmp}

			chance of {_crit}%:
				set {_dmgBlaze} to {_dmgBlaze} * {_mastery}
				Kindling({_p})
				CritVisual(loop-value)

			set loop-value's last damage cause to sweep attack
			set metadata value "LastDamageCauseEN" of loop-value to "<##d74327>Blaze"
			set metadata value "LastDamageCause" of loop-value to "<##d74327>Pożar"
			set metadata value "Element" of {_p} to "Fire"
			set metadata value "LastDamageCauseLoreEN" of loop-value to {_lorepozarEN}
			set metadata value "LastDamageCauseLore" of loop-value to {_lorepozar}
			
			make {_p} damage loop-value by ({_dmgBlaze}*2)
			draw 20 flame at location above loop-value with offset vector(0.3, 0.6, 0.3) with extra 0.03
			stop loop if {_loopCount} = {_targetsAffected}

function HeatSnap(p: player):
	set {_haste} to 1 + (({haste::%{_p}%}/4))/100 
	set {_cd} to 14/{_haste}
	set {_cd} to "%{_cd}% seconds" parsed as timespan
	loop all entities in radius 40 around {_p} where [metadata value "RecentlyDamagedDelphox%{_p}%" of input is set]:

		clear cooldown "Flamethrower%{_p}%-%uuid of loop-entity%"
		create cooldown "Flamethrower%{_p}%-%uuid of loop-entity%" for {_cd}
		
		Blaze({_p}, loop-entity, true)

		Flamethrower({_p}, loop-entity)

		Inferno({_p}, loop-entity)

function Kindling(p: player):
	if tag "Talents;Row 2" of nbt of {karta::%{_p}%} = "Kindling":
		remove 1 second from cooldown "Heat Snap%{_p}%"
		loop all items in the inventory of {_p}:
			if tag "HeatSnap" of nbt of loop-item is set:
				set the cooldown of loop-item for {_p} to cooldown "Heat Snap%{_p}%"
				stop loop

function Flamethrower(p: player, target: entity):
	set {_haste} to 1 + (({haste::%{_p}%}/4))/100 
	set {_cd} to 14/{_haste}
	set {_hasteModifier} to 1/{_haste}
	if tag "Talents;Row 2" of nbt of {karta::%{_p}%} = "Flame Accelerant":
		if metadata value "DelphoxFlamethrowerUsed" of {_p} is not set:
			FlameAccelerant({_p}, {_cd})
			set {_cd} to {_cd}*0.5
			set {_flameAccelerant} to true
			set {_hasteModifier} to {_hasteModifier}*0.7
	set {_cdd} to {_cd}
	set {_cd} to "%{_cd}% seconds" parsed as timespan

	set {_damage} to 1.25 + ({versatility::%{_p}%}/360) + ({damage::%{_p}%}/120) + {primarystat::%{_p}%}/60
	set {_dmgBlaze} to 3 + ({versatility::%{_p}%}/180) + ({damage::%{_p}%}/60) + {primarystat::%{_p}%}/30

	if tag "Talents;Row 5" of nbt of {karta::%{_p}%} = "Hot Spree":
		set {_hotSpreeCount} to metadata value "HotSpree" of {_p}
		add 1 to {_hotSpreeCount}
		if {_hotSpreeCount} = 3:
			set {_hotSpree} to true
			set {_damage} to {_damage} * 1.5
			set {_hotSpreeCount} to -1
			play sound "skill.delphox.hotspree" with volume 1.2 and pitch 1 to {_p}
			
		set metadata value "HotSpree" of {_p} to {_hotSpreeCount}
	
	if {_hotSpree} != true:
		create cooldown "Flamethrower%{_p}%-%uuid of {_target}%" for {_cd}

	if tag "Talents;Row 5" of nbt of {karta::%{_p}%} = "Hot Spree":
		set {_damage} to {_damage}*1.6

	set {_baseDuration} to 4
	set {_seconds} to rounded {_baseDuration}/{_hasteModifier}

	set metadata value "FlamethrowerBurn" of {_target} to true

	set {_lore} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fRMB%nl%<##e53311>Ignites the target for &f%{_seconds}% sec<##e53311>, inflicting &f%{_damage}% <##ff4d00>Fire%nl%<##e53311>damage every &f%{_hasteModifier}% sec <##e53311>for a total of &f%{_damage}*{_seconds}% <##ff4d00>Fire <##e53311>damage.%nl%<##e53311>When Flamethrower is used, it cannot be used on%nl%<##e53311>the same target for the next &f%{_cdd}% sec<##e53311>."
	set {_lorepozar} to "&8Passive Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fPassive%nl%<##e53311>Every third Flamethrower used deals%nl%&f3 <##ff4d00>Fire <##e53311>damage to the target and up to%nl%<##e53311>&ftwo <##e53311>nearby enemies around the target."
	
	set {_lorepozarEN} to "&8Passive Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fPassive%nl%<##e53311>Every third Flamethrower used deals%nl%&f%{_dmgBlaze}% <##ff4d00>Fire <##e53311>damage to the target and up to%nl%<##e53311>&ftwo <##e53311>nearby enemies around the target."
	set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fRMB%nl%<##e53311>Ignites the target for &f%{_seconds}% sec<##e53311>, inflicting &f%{_damage}% <##ff4d00>Fire%nl%<##e53311>damage every &f%{_hasteModifier}% sec <##e53311>for a total of &f%{_damage}*{_seconds}% <##ff4d00>Fire <##e53311>damage.%nl%<##e53311>When Flamethrower is used, it cannot be used on%nl%<##e53311>the same target for the next &f%{_cdd}% sec<##e53311>."
	
	translateAbility({_p}, "Blaze", "Pożar", "Blaze", {_lore}, {_loreEN})
	play sound "skill.delphox.flamethrower" with volume 2 and pitch 1 at {_target}
						
	if metadata value "FlamethrowerTicks%{_p}%" of {_target} is not set:
		set metadata value "FlamethrowerTicks%{_p}%" of {_target} to {_seconds}
		if {_flameAccelerant} is true:
			set metadata value "FlameAccelerantTicks" of {_p} to {_seconds}
		if {_hotSpree} is true:
			set metadata value "HotSpreeTicks" of {_p} to {_seconds}
		ignite {_target} for "%{_seconds}% seconds" parsed as timespan
		while metadata value "FlamethrowerTicks%{_p}%" of {_target} > 0:
			if {_target} is alive:
				set {_damage} to 1.25 + ({versatility::%{_p}%}/360) + ({damage::%{_p}%}/120) + {primarystat::%{_p}%}/60
				set {_mastery} to 2.5 + (({mastery::%{_p}%}/165))
				set {_crit} to ({criticalhit::%{_p}%}/10) 
				set {_haste} to  1 + (({haste::%{_p}%}/4))/100 
				set {_wait} to "%1/{_haste}% seconds" parsed as timespan

				set {_ticks} to metadata value "FlamethrowerTicks%{_p}%" of {_target}
				remove 1 from {_ticks}
				set metadata value "FlamethrowerTicks%{_p}%" of {_target} to {_ticks}

				if tag "Talents;Row 5" of nbt of {karta::%{_p}%} = "Hot Spree":
					set {_damage} to {_damage}*1.6

				if tag "Talents;Row 1" of nbt of {karta::%{_p}%} = "Firestarter":
					if health of {_target} >= (0.9 * max health of {_target}):
						set {_crit} to 100
						set {_damage} to {_damage} * 1.5

				if {_flameAccelerant} is true:
					if metadata value "FlameAccelerantTicks" of {_p} > 0:
						set {_flameAccelerantTicks} to metadata value "FlameAccelerantTicks" of {_p}
						remove 1 from {_flameAccelerantTicks}
						set metadata value "FlameAccelerantTicks" of {_p} to {_flameAccelerantTicks}
						set {_damage} to {_damage}*2.2

				if tag "Talents;Row 3" of nbt of {karta::%{_p}%} = "Oxidizing Flame":
					chance of 20%:	
						play sound "entity.creeper.primed" with volume 1 and pitch 2 at {_target}
						set {_damage} to {_damage}*1.3

				if {_hotSpree} is true:
					if metadata value "HotSpreeTicks" of {_p} > 0:
						set {_hotSpreeTicks} to metadata value "HotSpreeTicks" of {_p}
						remove 1 from {_hotSpreeTicks}
						set metadata value "HotSpreeTicks" of {_p} to {_hotSpreeTicks}
						set {_damage} to {_damage}*1.5
						broadcast "Yes"

				chance of {_crit}%:
					set {_damage} to {_damage} * ({_mastery})
					Kindling({_p})
					CritVisual({_target})

				if tag "Talents;Row 5" of nbt of {karta::%{_p}%} = "Wildfire":
					if {wildfireDelphox::%{_p}%} is not set:
						set {wildfireDelphox::%{_p}%} to 0
					if {wildfireDelphox::%{_p}%} < 600:
						add 1 to {wildfireDelphox::%{_p}%}
				
				if tag "Talents;Row 4" of nbt of {karta::%{_p}%} = "Will-o-Wisp":
					chance of 10%:	
						WilloWisp({_p}, {_target})

				set {_target}'s last damage cause to sweep attack
				set metadata value "LastDamageCauseEN" of {_target} to "<##d74327>Flamethrower"
				set metadata value "LastDamageCause" of {_target} to "<##d74327>Miotacz Płomieni"
				set metadata value "Element" of {_p} to "Fire"
				set metadata value "LastDamageCauseLoreEN" of {_target} to {_loreEN}
				set metadata value "LastDamageCauseLore" of {_target} to {_lore}
				make {_p} damage {_target} by {_damage}*2
				DelphoxRecentlyDamaged({_p}, {_target})
			else:
				stop loop
			wait {_wait}

		clear metadata value "FlamethrowerBurn" of {_target}
		clear metadata value "FlamethrowerDuration%{_p}%" of {_target}
		clear metadata value "FlamethrowerTicks%{_p}%" of {_target}

	else:
		set {_ticks} to {_seconds}
		set {_ticksTarget} to metadata value "FlamethrowerTicks%{_p}%" of {_target}
		add {_ticks} to {_ticksTarget}
		set metadata value "FlamethrowerTicks%{_p}%" of {_target} to {_ticksTarget}
		extinguish {_target}
		ignite {_target} for "%{_ticksTarget}% seconds" parsed as timespan			

function Inferno(p: player, target: entity):
	set {_mastery} to 2.5 + (({mastery::%{_p}%}/165))
	set {_crit} to ({criticalhit::%{_p}%}/10)
	if metadata value "FlamethrowerBurn" of {_target} is true:
		set {_damage} to 3.5 + ({versatility::%{_p}%}/114) + ({damage::%{_p}%}/38)  + ({primarystat::%{_p}%}/19)
		set {_stun} to "%2 + (({crowdcontrol::%{_p}%}/60))% seconds" parsed as timespan
		set {_stuntekst} to 2 + (({crowdcontrol::%{_p}%}/60))
		set {_explotekst} to 6 + ({versatility::%{_p}%}/52.5) + ({damage::%{_p}%}/17.5) + ({primarystat::%{_p}%}/8.75)

		clear metadata value "FlamethrowerBurn" of {_target}

		set {_lore} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &fbrak%nl%&7Użycie: &fPPM&7/&fSHIFT%nl%<##e53311>Więzi przeciwnika podpalonego Miotaczem Płomieni%nl%<##e53311>w ognistym więzieniu, ogłuszając go na &f%{_stuntekst}% sekund%nl%<##e53311>i zadajac &f%{_damage}% <##e53311>obrażeń <##ff4d00>Ognia<##e53311>.%nl% %nl%<##e53311>Kliknięcie Shiftem zdetonuje więzienie,%nl%<##e53311>zadając &f%{_explotekst}% <##e53311>damage <##ff4d00>Ognia <##e53311>i podrzucając wroga do góry."
		set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fRMB&7/&fSHIFT%nl%<##e53311>Imprisons the target affected by Flamethrower%nl%<##e53311>in a fiery prison, stunning them for &f%{_stun}%%nl%<##e53311>and inflicting &f%{_damage}% <##ff4d00>Fire <##e53311>damage.%nl% %nl%<##e53311>Pressing Shift will detonate the prison,%nl%<##e53311>dealing &f%{_explotekst}% <##ff4d00>Fire <##e53311>damage and tossing the%nl%<##e53311>enemy into the air."
		
		translateAbility({_p}, "Inferno", "Inferno", "Inferno", {_lore}, {_loreEN})

		if {_target} is alive:
			if canBeCCed({_target}) = true:
				InfernoStun({_p}, {_target})

			set metadata value "InfernoTarget" of {_target} to true

			chance of {_crit}%:
				set {_damage} to {_damage} * {_mastery}
				Kindling({_p})
				CritVisual({_target})

			set {_target}'s last damage cause to sweep attack
			set metadata value "LastDamageCauseEN" of {_target} to "<##d74327>Inferno"
			set metadata value "LastDamageCause" of {_target} to "<##d74327>Inferno"
			set metadata value "Element" of {_p} to "Fire"
			set metadata value "LastDamageCauseLoreEN" of {_target} to {_loreEN}
			set metadata value "LastDamageCauseLore" of {_target} to {_lore}
			make {_p} damage {_target} by {_damage}*2
			play sound "entity.illusioner.mirror_move" with volume 1 and pitch 1 at {_p}
			InfernoParticles({_target})

function InfernoDetonate(p: player, target: entity):
	set {_mastery} to 2.5 + (({mastery::%{_p}%}/165))
	set {_crit} to ({criticalhit::%{_p}%}/10)

	set {_damage} to 6 + ({versatility::%{_p}%}/60) + ({damage::%{_p}%}/20) + ({primarystat::%{_p}%}/10)
	set metadata value "InfernoTarget" of {_target} to false

	clear {stun::%{_target}%}
	clear metadata value "InfernoStun%{_p}%" of {_target}
	
	set {_knock} to 1 + ({crowdcontrol::%{_p}%}/100)

	set {_lore} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &fbrak%nl%&7Użycie: &fPPM&7/&fSHIFT%nl%<##e53311>Więzi przeciwnika podpalonego Miotaczem Płomieni%nl%<##e53311>w ognistym więzieniu, ogłuszając go na &f%{_stuntekst}% sekund%nl%<##e53311>i zadajac &f%{_dmg}% <##e53311>obrażeń <##ff4d00>Ognia<##e53311>.%nl% %nl%<##e53311>Kliknięcie Shiftem zdetonuje więzienie,%nl%<##e53311>zadając &f%{_explotekst}% <##e53311>damage <##ff4d00>Ognia <##e53311>i podrzucając wroga do góry."
	set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fRMB&7/&fSHIFT%nl%<##e53311>Imprisons the target affected by Flamethrower%nl%<##e53311>in a fiery prison, stunning them for &f%{_stun}%%nl%<##e53311>and inflicting &f%{_dmg}% <##ff4d00>Fire <##e53311>damage.%nl% %nl%<##e53311>Pressing Shift will detonate the prison,%nl%<##e53311>dealing &f%{_explotekst}% <##ff4d00>Fire <##e53311>damage and tossing the%nl%<##e53311>enemy into the air."
	
	translateAbility({_p}, "Inferno", "Inferno", "Inferno", {_lore}, {_loreEN})

	play sound "entity.dragon_fireball.explode" with volume 1 and pitch 1 at {_p}
	if canBeCCed({_target}) = true:
		push {_target} upwards with velocity {_knock}

	chance of {_crit}%:
		set {_damage} to {_damage} * {_mastery}
		Kindling({_p})
		CritVisual({_target})

	set {_target}'s last damage cause to sweep attack
	set metadata value "LastDamageCauseEN" of {_target} to "<##d74327>Inferno (Detonate)"
	set metadata value "LastDamageCause" of {_target} to "<##d74327>Inferno (Detonacja)"
	set metadata value "Element" of {_p} to "Fire"
	set metadata value "LastDamageCauseLoreEN" of {_target} to {_loreEN}
	set metadata value "LastDamageCauseLore" of {_target} to {_lore}
	make {_p} damage {_target} by {_damage} * 2
	
function InfernoStun(p: player, target: entity):
	set {_stunDuration} to "%2 + (({crowdcontrol::%{_p}%}/60))% seconds" parsed as timespan
	if metadata value "InfernoStun%{_p}%" of {_target} is not set:
		set metadata value "InfernoStun%{_p}%" of {_target} to {_stunDuration}
		while metadata value "InfernoStun%{_p}%" of {_target} > 0 seconds:
			wait 1 second
			set {_duration} to metadata value "InfernoStun%{_p}%" of {_target}
			remove 1 second from {_duration}
			set metadata value "InfernoStun%{_p}%" of {_target} to {_duration}
			if 0 seconds >= metadata value "InfernoStun%{_p}%" of {_target}:
				clear metadata value "InfernoStun%{_p}%" of {_target}
				clear {stun::%{_target}%}
				clear metadata value "InfernoTarget" of {_target}
				stop loop
	else:
		set metadata value "InfernoStun%{_p}%" of {_target} to {_stunDuration}

function DelphoxRecentlyDamaged(p: player, target: entity):
	if metadata value "RecentlyDamagedDelphox%{_p}%" of {_target} is not set:
		set metadata value "RecentlyDamagedDelphox%{_p}%" of {_target} to 20 seconds
		while metadata value "RecentlyDamagedDelphox%{_p}%" of {_target} > 0 seconds:
			wait 1 second
			set {_duration} to metadata value "RecentlyDamagedDelphox%{_p}%" of {_target}
			remove 1 second from {_duration}
			set metadata value "RecentlyDamagedDelphox%{_p}%" of {_target} to {_duration}
			if 0 seconds >= metadata value "RecentlyDamagedDelphox%{_p}%" of {_target}:
				clear metadata value "RecentlyDamagedDelphox%{_p}%" of {_target}
				stop loop
	else:
		set metadata value "RecentlyDamagedDelphox%{_p}%" of {_target} to 20 seconds

function FlameAccelerant(p: player, cd: number):
	if metadata value "DelphoxFlamethrowerUsed" of {_p} is not set:
		set metadata value "DelphoxFlamethrowerUsed" of {_p} to "%{_cd}% seconds" parsed as timespan
		while metadata value "DelphoxFlamethrowerUsed" of {_p} > 0 seconds:
			wait 1 second
			set {_duration} to metadata value "DelphoxFlamethrowerUsed" of {_p}
			remove 1 second from {_duration}
			set metadata value "DelphoxFlamethrowerUsed" of {_p} to {_duration}
			if 0 seconds >= metadata value "DelphoxFlamethrowerUsed" of {_p}:
				clear metadata value "DelphoxFlamethrowerUsed" of {_p}
				stop loop
	else:
		set metadata value "DelphoxFlamethrowerUsed" of {_p} to "%{_cd}% seconds" parsed as timespan

function WilloWisp(p: player, target: entity):
	play sound "skill.delphox.willowisp" with volume 1.5 and pitch 1 at {_target}
	WilloWispVisual({_p}, {_target})

	if {_target} is alive:
		if metadata value "FlamethrowerTicks%{_p}%" of {_target} is set:
			set {_ticks} to metadata value "FlamethrowerTicks%{_p}%" of {_target}
			add 1 to {_ticks}
			set metadata value "FlamethrowerTicks%{_p}%" of {_target} to {_ticks}

	set {_damage} to 1.25 + ({versatility::%{_p}%}/420) + ({damage::%{_p}%}/140) + {primarystat::%{_p}%}/70
	set {_mastery} to 2.5 + (({mastery::%{_p}%}/165))
	set {_crit} to ({criticalhit::%{_p}%}/10)
	set {_lore} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &fbrak%nl%&7Użycie: &fPPM&7/&fSHIFT%nl%<##e53311>Więzi przeciwnika podpalonego Miotaczem Płomieni%nl%<##e53311>w ognistym więzieniu, ogłuszając go na &f%{_stuntekst}% sekund%nl%<##e53311>i zadajac &f%{_dmg}% <##e53311>obrażeń <##ff4d00>Ognia<##e53311>.%nl% %nl%<##e53311>Kliknięcie Shiftem zdetonuje więzienie,%nl%<##e53311>zadając &f%{_explotekst}% <##e53311>damage <##ff4d00>Ognia <##e53311>i podrzucając wroga do góry."
	set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fRMB&7/&fSHIFT%nl%<##e53311>Imprisons the target affected by Flamethrower%nl%<##e53311>in a fiery prison, stunning them for &f%{_stun}%%nl%<##e53311>and inflicting &f%{_dmg}% <##ff4d00>Fire <##e53311>damage.%nl% %nl%<##e53311>Pressing Shift will detonate the prison,%nl%<##e53311>dealing &f%{_explotekst}% <##ff4d00>Fire <##e53311>damage and tossing the%nl%<##e53311>enemy into the air."
	
	chance of {_crit}%:
		set {_damage} to {_damage} * {_mastery}
		CritVisual({_target})

	wait 1 tick

	set {_target}'s last damage cause to sweep attack
	set metadata value "LastDamageCauseEN" of {_target} to "<##d74327>Will-o-Wisp"
	set metadata value "LastDamageCause" of {_target} to "<##d74327>Ognik"
	set metadata value "Element" of {_p} to "Fire"
	set metadata value "LastDamageCauseLoreEN" of {_target} to {_loreEN}
	set metadata value "LastDamageCauseLore" of {_target} to {_lore}
	make {_p} damage {_target} by {_damage} * 2

function WilloWispVisual(p: player, target: entity):
	set {_where} to a random integer between 1 and 2
	if {_where} = 1:
		if {_p}'s horizontal facing is north or south:
			set {_loc} to location 0.6 left of {_target}
		else:
			set {_loc} to location 0.6 behind {_target}
	else:
		if {_p}'s horizontal facing is north or south:
			set {_loc} to location 0.6 right of {_target}
		else:
			set {_loc} to location 0.6 in front of {_target}
	set {_loc} to location 1.5 above {_loc}
	set {_yaw} to yaw of {_p} - 180
	set yaw of {_loc} to {_yaw}
	spawn armor stand at {_loc} with nbt from "{Invulnerable:1b,NoGravity:1b}"
	set name of last spawned armor stand to "willowisp"
	set {_e} to last spawned armor stand
	add nbt from "{Rotation:[%{_yaw}%.0f,0.0f]}" to nbt of {_e}
	WillowispVisualDelete({_e})

function WillowispVisualDelete(e: entity):
	wait 3 seconds
	kill {_e}

function BlasterMaster(p: player):
	if {blastermasterstacks::%{_p}%} > 0:
		if {_p}'s chestplate is golden nugget:
			if name of {_p}'s chestplate contains "Serce Earthcrafta" or "Heart of Earthcraft":
				if line 30 of lore of {_p}'s chestplate contains {_p}'s name:
					set {_loreheart::*} to lore of {_p}'s chestplate
		#BLASTERMASTER
		loop {_loreheart::*}:
			loop-value contains "Blaster Master":
				add (20*{trait::Delphox::Blaster Master::%{_p}%}) to {_blastermaster}
		wait 3 seconds
		remove 1 from {blastermasterstacks::%{_p}%}
		remove {_blastermaster} from {mastery::%{_p}%}
		if 0 >= {blastermasterstacks::%{_p}%}:
			clear {blastermasterstacks::%{_p}%}
			
function Pyromaniac(p: player):
	if {pyromaniacbonus::%{_p}%} is true:
		set {pyromaniacbonus::%{_p}%} to false
		while {czaspyromaniac::%{_p}%} > 0 seconds:
			if {_p} is alive:
				remove 1 second from {czaspyromaniac::%{_p}%}
				wait 1 second
				if 0 seconds >= {czaspyromaniac::%{_p}%}:
					clear {pyromaniacstacks::%{_p}%}
					clear {czaspyromaniac::%{_p}%}
					clear {pyromaniacbonus::%{_p}%}
					stop loop
			else:
				clear {pyromaniacstacks::%{_p}%}
				stop loop