#<##f0e359>
variables:
	{pcount::%player%} = 0

on load:
	set {traits::Delphox::*} to "Blaster Master", "Controlled Destruction", "Duplicative Incineration", "Fervent Flickering", "Fiery Rush", "Firefall", "Firestarter", "Pyroclasm", "Pyromaniac" and "Pyrotechnics"
	set {Blaster Master} to ""
	set {Controlled Destruction} to ""
	set {Duplicative Incineration} to ""
	set {Fervent Flickering} to ""
	set {Fiery Rush} to ""
	set {Firefall} to ""
	set {Firestarter} to ""
	set {Pyroclasm} to ""
	set {Pyromaniac} to ""
	set {Pyrotechnics} to ""
	
on join:
	if {kolekcja::karty::%player%::*} contains "Delphox":
		loop 10 times:
			set {_r} to {traits::Delphox::%loop-number%}
			set {_x%loop-number%} to {trait::Delphox::%{_r}%::%player%}
		if {language::%player%} = "English":
			set {traits::Delphox::1::opis::%player%} to "<##e53311>Flamethrower &7increases your Mastery by%nl%&f%20*{_x1}% &7for 3 seconds. This effect stacks."
			set {traits::Delphox::2::opis::%player%} to "&7Your first detonated <##e53311>Inferno &7after using%nl%<##e53311>Flame Barrier &7will always critically strike and%nl%&7deal an extra &f%1.5*{_x2}% &7damage."
			set {traits::Delphox::3::opis::%player%} to "<##e53311>Flamethrower &7has &f%1*{_x3}%%% &7chance to ignite%nl%&7your target again after its expiration.%nl%&7Duplicated <##e53311>Flamethrower &7applies all effects from%nl%&7your other abilities and Traits, but deals%nl%&760%% damage."
			set {traits::Delphox::4::opis::%player%} to "<##e53311>Blaze &7damage has a &f%2*{_x4}%%% &7chance per%nl%&7target hit to reduce the cooldown of%nl%<##e53311>Flamethrower &7by 0.5 seconds on all affected%nl%&7targets."
			set {traits::Delphox::5::opis::%player%} to "<##e53311>Flamethrower &7deals damage an additional 2 times%nl%&7and its cooldown is reduced by &f%0.3*{_x5}% seconds&7."
			set {traits::Delphox::6::opis::%player%} to "&7Every fourth detonated <##e53311>Inferno &7calls%nl%&7down a Meteor &7on your target,%nl%&7dealing &f%3*{_x6}% <##ff4d00>Fire &7damage to all enemies nearby."
			set {traits::Delphox::7::opis::%player%} to "<##e53311>Flamethrower &7has a &f%8.25*{_x7}%%% &7increased chance%nl%&7to critically strike and its cooldown is%nl%&7reduced by &f%0.5*{_x7}% seconds &7against targets above%nl%&790%% health."
			set {traits::Delphox::8::opis::%player%} to "&7Detonating <##e53311>Inferno &7has a &f%2.5*{_x8}%%% &7chance%nl%&7to increase the damage of your next <##e53311>Blaze%nl%&7by 230%%."
			set {traits::Delphox::9::opis::%player%} to "&7Each consecutive critical strike you deal increases%nl%&7the critical strike damage you deal by &f%1.5*{_x9}%%%%nl%&7for 6 seconds."
			set {traits::Delphox::10::opis::%player%} to "<##e53311>Flamethrower &7has a &f%5*{_x10}%%% &7chance%nl%&7to grant you an additional stack of <##e53311>Blaze&7."
		else:
			if {_x9} > 1:
				set {_tekst} to "sekundy"
			else:
				set {_tekst} to "sekundę"
			if {_x9} = 4:
				set {_tekst2} to "obrażenia"
			else:
				set {_tekst2} to "obrażeń"
			set {traits::Delphox::1::opis::%player%} to "<##e53311>Miotacz Płomieni &7zwiększa twoje Mistrzostwo o%nl%&f%20*{_x1}% &7na 3 sekundy. Ten efekt nakłada się."
			set {traits::Delphox::2::opis::%player%} to "&7Twoje pierwsze zdetonowane <##e53311>Inferno &7po użyciu%nl%<##e53311>Płomiennej Bariery &7zawsze trafi krytycznie i%nl%&7zada dodatkowe &f%1.5*{_x2}% &7obrażeń."
			set {traits::Delphox::3::opis::%player%} to "<##e53311>Miotacz Płomieni &7ma &f%1*{_x3}%%% &7szans na ponowne%nl%&7podpalenie celu, gdy dobiegnie końca.%nl%&7Zduplikowane <##e53311>Miotacze Płomieni &7aplikują wszystkie efekty%nl%&7z twoich innych umiejętności i Traits, ale%nl%&7zadaja 60%% obrażeń."
			set {traits::Delphox::4::opis::%player%} to "&7Obrażenia <##e53311>Pożaru &7mają &f%2*{_x4}%%% &7szans na%nl%&7uderzony cel, by zredukować cooldown%nl%<##e53311>Miotacza Płomieni &7o 0.5 seconds na wszystkich%nl%&7objętych celach."
			set {traits::Delphox::5::opis::%player%} to "<##e53311>Miotacz Płomieni &7zadaje obrażenia 2 dodatkowe razy%nl%&7i jego cooldown jest zmniejszony o &f%0.3*{_x5}% sekund&7."
			set {traits::Delphox::6::opis::%player%} to "&7Co czwarte zdetonowane<##e53311>Inferno &7przyzywa%nl%&7Meteor &7nad twoim celem.%nl%&7Meteor zada &f%3*{_x6}% <##ff4d00>Ognistych &7obrażeń wszystkim pobliskim wrogom."
			set {traits::Delphox::7::opis::%player%} to "<##e53311>Miotacz Płomieni &7ma o &f%8.25*{_x7}%%% &7zwiększone%nl%&7szanse na trafienie krytyczne i jego cooldown%nl%&7jest zredukowany o &f%0.5*{_x7}% sekund &7przeciwko celom powyżej%nl%&790%% zdrowia."
			set {traits::Delphox::8::opis::%player%} to "&7Zdetonowanie <##e53311>Inferno &7ma &f%2.5*{_x8}%%% &7szans%nl%&7na zwiększenie obrażeń twojego kolejnego <##e53311>Pożaru%nl%&7o 230%%."
			set {traits::Delphox::9::opis::%player%} to "&7Każde trafienie krytyczne z rzędu które zadasz%nl%&7zwiększy obrażenia krytyczne, które zadajesz o &f%1.5*{_x9}%%%%nl%&7na 6 sekund."
			set {traits::Delphox::10::opis::%player%} to "<##e53311>Miotacz Płomieni &7ma &f%5*{_x10}%%% &7szans%nl%&7na przyznanie ci dodatkowego ładunku <##e53311>Pożaru&7."
			
on leave:
	if {kolekcja::karty::%player%::*} contains "Delphox":
		loop 10 times:
			clear {traits::Delphox::%loop-number%::opis::%player%}

on rightclick:
	if name of player's tool = "<##e53311>Miotacz Płomieni" or "<##e53311>Flamethrower":
		cancel event
		set {_target} to Target(player, 100, false)
		if {_target} is set:
			if {kartaname::%player%} = "Delphox":
				if CanUseAbility(player) != false:
					cancel event
					set {_id} to line 19 of lore of {karta::%player%}
					set {_mistr2} to 2.5 + (({mastery::%player%}/200))
					set {_crch} to ({criticalhit::%player%}/10) 
					set {_pospiech} to 1 + (({haste::%player%}/4))/100 
					set {_cd} to 13/{_pospiech}
					set {_cdd} to {_cd}
					set {_cd} to "%{_cd}% seconds" parsed as timespan
					if player's chestplate is golden nugget:
						if name of player's chestplate contains "Serce Earthcrafta" or "Heart of Earthcraft":
							if line 30 of lore of player's chestplate contains player's name:
								set {_loreheart::*} to lore of player's chestplate
					if cooldown "miotaczplomieni%player%-%uuid of {_target}%" is finished:
						#FIERY RUSH
						loop {_loreheart::*}:
							loop-value contains "Fiery Rush":
								add (0.3*{trait::Delphox::Fiery Rush::%player%}) to {_firerush}
						remove ("%{_firerush}% seconds" parsed as timespan) from {_cd}
						create cooldown "miotaczplomieni%player%-%uuid of {_target}%" for {_cd}
						#if target of player is not on fire:
						#set {firstknockback::%{_target}%} to true
						set {_dmg} to 5 + ({versatility::%player%}/90) + ({damage::%player%}/30) + {primarystat::%player%}/15
						set {_dmgexl} to 3 + ({versatility::%player%}/180) + ({damage::%player%}/60) + {primarystat::%player%}/30
						set {miotaczczas::%player%} to 1/((({_pospiech}-1)/1.5)+1)
						set {_loops} to 4 + (rounded down (({haste::%player%}/150)))
						set {_seku} to "%{miotaczczas::%player%} * {_loops}% seconds" parsed as timespan
						set {miotaczburn::%{_target}%} to true
						set {_loopign} to 1	
						if {_firerush} is set:
							add 2 to {_loops}
						set {_lore} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &f%{_cdd}% sekund na cel%nl%&7Użycie: &fPPM%nl%<##e53311>Podpala cel na &f%{miotaczczas::%player%} * {_loops}% sekund<##e53311>,%nl%<##e53311>zadając &f%{_dmg}/{_loops}% <##e53311>obrażeń <##ff4d00>Ognia%nl%<##e53311>co &f%{miotaczczas::%player%}% <##e53311>sekund."
						set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &f%{_cdd}% seconds per target%nl%&7Use: &fRMB%nl%<##e53311>Ignites the target for &f%{miotaczczas::%player%} * {_loops}% seconds<##e53311>,%nl%<##e53311>inflicting &f%{_dmg}/{_loops}% <##ff4d00>Fire <##e53311>damage%nl%<##e53311>every &f%{miotaczczas::%player%}% <##e53311>seconds."
						set {_lorepozar} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &fbrak%nl%&7Użycie: &fPasywnie%nl%<##e53311>Co trzeci użyty Miotacz Płomieni%nl%<##e53311>zada &f%{_dmgexl}% <##e53311>obrażeń <##ff4d00>Ognia%nl%<##e53311>celowi i maksymalnie dwóm pobliskim wrogom."
						set {_lorepozarEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fPassive%nl%<##e53311>Every third Flamethrower used%nl%<##e53311>deals &f%{_dmgexl}% <##ff4d00>Fire <##e53311>damage to the%nl%<##e53311>target and up to two nearby enemies."
						if {language::%player%} = "English":
							if name of player's tool does not contain "Flamethrower":
								replace all "Miotacz Płomieni" in player's tool's name with "Flamethrower"
							set lore of player's tool to {_loreEN}
							loop all items in the inventory of player:
								if name of loop-item contains "<##e53311>Pożar" or "<##e53311>Blaze":
									set the name of loop-item to "<##e53311>Blaze"
									set the lore of loop-item to {_lorepozarEN}
						else:
							if name of player's tool does not contain "Miotacz Płomieni":
								replace all "Flamethrower" in player's tool's name with "Miotacz Płomieni"
							set lore of player's tool to {_lore}
							loop all items in the inventory of player:
								if name of loop-item contains "<##e53311>Pożar" or "<##e53311>Blaze":
									set the name of loop-item to "<##e53311>Pożar"
									set the lore of loop-item to {_lorepozar}
						#PYROMANIAC
						loop {_loreheart::*}:
							loop-value contains "Pyromaniac":
								add (1.5*{trait::Delphox::Pyromaniac::%player%}) to {_pyromaniac}
						#DUPLICATIVE INCINERATION
						loop {_loreheart::*}:
							loop-value contains "Duplicative Incineration":
								add 1 to {_chancedp}
						chance of {_chancedp}*(1*{trait::Delphox::Duplicative Incineration::%player%})%:
							set {_loopign} to 2
						loop {_loopign} times:
							if loop-number = 1:
								if {_loopign} = 2:
									set {_seku} to "%2*({miotaczczas::%player%} * {_loops})% seconds" parsed as timespan
								ignite {_target} for {_seku}
							play sound "skill.delphox.flamethrower" with volume 1 and pitch 1 at player
							add 1 to {pcount::%player%}
							#PYROTECHNICS
							if loop-number = 1:
								loop {_loreheart::*}:
									loop-value-2 contains "Pyrotechnics":
										add 1 to {_chance}
							chance of {_chance}*(5*{trait::Delphox::Pyrotechnics::%player%})%:
								add 1 to {pcount::%player%}
							#BLASTERMASTER
							loop {_loreheart::*}:
								loop-value-2 contains "Blaster Master":
									add (20*{trait::Delphox::Blaster Master::%player%}) to {_blastermaster}
							if {_blastermaster} is set:
								if {blastermasterstacks::%player%} is not set:
									set {blastermasterstacks::%player%} to 0
								else:
									add 1 to {blastermasterstacks::%player%}
									add {_blastermaster} to {mastery::%player%}
									set {_mistr2} to 2.5 + (({mastery::%player%}/200))
									BlasterMaster(player)
							#FIRESTARTER
							if loop-number-1 = 1:
								loop {_loreheart::*}:
									loop-value-2 contains "Firestarter":
										add (0.5*{trait::Delphox::Firestarter::%player%}) to {_firestartercd}
										add (8.25*{trait::Delphox::Firestarter::%player%}) to {_firestartercrit}
							#FERVENT FLICKERING
								if loop-number = 1:
									loop {_loreheart::*}:
										loop-value-2 contains "Fervent Flickering":								
											add (2*{trait::Delphox::Fervent Flickering::%player%}) to {_ferventchance}
							if {pcount::%player%} >= 3:
								#PYROCLASM
								if {pyroclasm::%player%} is true:
									set {_dmgexl} to {_dmgexl}*3.3
									clear {pyroclasm::%player%}
								chance of {_crch}%:
									set {_crit} to true
									set {_dmgexl} to {_dmgexl} * ({_mistr2} + ({pyromaniacstacks::%player%}/100))
									set {critdmg::%{_target}%} to true
									if {_pyromaniac} is set:
										if {pyromaniacstacks::%player%} is not set:
											set {pyromaniacstacks::%player%} to 0
										else:
											add {_pyromaniac} to {pyromaniacstacks::%player%}
											set {czaspyromaniac::%player%} to 6 seconds
											if {pyromaniacbonus::%player%} is not set:
												set {pyromaniacbonus::%player%} to true
								if {_crit} is not true:
									clear {pyromaniacstacks::%player%}
									clear {czaspyromaniac::%player%}
								set {_target}'s last damage cause to sweep attack
								set metadata value "LastDamageCauseEN" of {_target} to "<##d74327>Blaze"
								set metadata value "LastDamageCause" of {_target} to "<##d74327>Pożar"
								set metadata value "Element" of player to "Fire"
								set metadata value "LastDamageCauseLoreEN" of {_target} to {_lorepozarEN}
								set metadata value "LastDamageCauseLore" of {_target} to {_lorepozar}
								make player damage {_target} by ({_dmgexl}*2)
								if {_ferventchance} is set:
									add {_ferventchance} to {_fervent}
									add {_target} to {_ferventtargets::*}
								if {_pyromaniac} is set:
									Pyromaniac(player)
								remove 3 from {pcount::%player%}
								set {_s} to 0
								play sound "item.firecharge.use" with volume 1 and pitch 1 at {_target}
								loop 2 times:
									set {_loop} to 4 + ({kontrolatlumu::%{_id}%}/50)
									loop entities in radius {_loop} around {_target}:
										if loop-entity is not {_target}:
											if tag "custom;ECMob" of nbt of loop-entity is true:
												if {_s} < 2:
													add 1 to {_s}
													set loop-entity's last damage cause to sweep attack
													set metadata value "LastDamageCauseEN" of loop-entity to "<##d74327>Blaze"
													set metadata value "LastDamageCause" of loop-entity to "<##d74327>Pożar"
													set metadata value "Element" of player to "Fire"
													set metadata value "LastDamageCauseLoreEN" of {_target} to {_lorepozarEN}
													set metadata value "LastDamageCauseLore" of {_target} to {_lorepozar}
													make player damage loop-entity by ({_dmgexl}*2)
													if {_pyromaniac} is set:
														Pyromaniac(player)
													if {_ferventchance} is set:
														add {_ferventchance} to {_fervent}
														add loop-entity to {_ferventtargets::*}
													wait 1 tick
												else:
													stop loop
								if {_ferventchance} is set:
									chance of {_fervent}%:
										loop {_ferventtargets::*}:
											remove 0.5 seconds from cooldown "miotaczplomieni%player%-%uuid of loop-value-2%"
							wait 1 tick
							set {_maxh} to max health of {_target}
							set {_health} to health of {_target}
							if {_health} >= (0.9*{_maxh}):	
								if {_firestartercd} is set:
									set {_firestartercd} to "%{_firestartercd}% seconds" parsed as timespan
									if loop-number = 1:
										remove {_firestartercd} from cooldown "miotaczplomieni%player%-%uuid of {_target}%"
							else:
								clear {_firestartercrit}
							loop {_loops} times:
								if {_target} is alive:
									set {miotaczczas::%player%} to "%1/((({_pospiech}-1)/1.5)+1)% seconds" parsed as timespan
									set {_dmg} to 5 + ({versatility::%player%}/90) + ({damage::%player%}/30) + {primarystat::%player%}/15
									if loop-number-1 = 2:
										set {_dmg} to {_dmg}*0.6
									chance of ({_crch} + {_firestartercrit})%:
										set {_crit} to true
										set {_dmg} to {_dmg} * ({_mistr2} + ({pyromaniacstacks::%player%}/100))
										set {critdmg::%{_target}%} to true
										if {_pyromaniac} is set:
											if {pyromaniacstacks::%player%} is not set:
												set {pyromaniacstacks::%player%} to 0
											else:
												add {_pyromaniac} to {pyromaniacstacks::%player%}
												set {czaspyromaniac::%player%} to 6 seconds
												if {pyromaniacbonus::%player%} is not set:
													set {pyromaniacbonus::%player%} to true
									if {_crit} is not true:
										clear {pyromaniacstacks::%player%}
										clear {czaspyromaniac::%player%}
									set {_target}'s last damage cause to sweep attack
									set metadata value "LastDamageCauseEN" of {_target} to "<##d74327>Flamethrower"
									set metadata value "LastDamageCause" of {_target} to "<##d74327>Miotacz Płomieni"
									set metadata value "Element" of player to "Fire"
									set metadata value "LastDamageCauseLoreEN" of {_target} to {_loreEN}
									set metadata value "LastDamageCauseLore" of {_target} to {_lore}
									make player damage {_target} by ({_dmg} * 2) / {_loops}
									if {_pyromaniac} is set:
										Pyromaniac(player) 
									wait {miotaczczas::%player%}
							clear {_fervent}
							clear {_ferventtargets::*}
						clear {miotaczburn::%{_target}%}
						set {_yh} to "%{miotaczczas::%player%}%"
						replace all " seconds" and "second" in {_yh} with ""
						set {_sh} to {_yh} parsed as number
						set {_jh} to {_loops}*{_sh}
						set {_th} to "%{_jh}% seconds" parsed as timespan
						set {czasmiotacza::%player%} to {_th}
						set {_ir} to "%{miotaczczas::%player%}%"
						replace all " seconds" and "second" in {_ir} with ""
						set {miotaczcztekst::%player%} to {_ir}
						stop
					else:
						cancel event
						if {_target} is set:
							if {tekstcd::%player%} is true:
								set {_cdd} to cooldown "miotaczplomieni%player%-%uuid of {_target}%"
								if {language::%player%} = "English":
									send "<##d74327>You can't ignite that target for the next %{_cdd}%" to player
								else:
									send "<##d74327>Nie można podpalić tego celu przez kolejne %{_cdd}%" to player
					stop
			else:
				if {language::%player%} = "English":
					send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to player
				else:
					send "&8[&6Earthcraft&8] &6Nie masz wybranej wymaganej karty, by móc użyć tej umiejętności." to player
				play sound "block.glass.break" with volume 3 and pitch 0 to player
							
on rightclick:
	if name of player's tool = "<##e53311>Miotacz Płomieni" or "<##e53311>Flamethrower":
		if {mob::%target of player%} = true:
			if {kartaname::%player%} = "Delphox":
				if CanUseAbility(player) != false:
					set {_target} to Target(player, 100, false)
					if {_target} is set:
						while cooldown "miotaczplomieni%player%-%uuid of {_target}%" is not finished:
							if {_target} is alive:
								set {_a} to cooldown "miotaczplomieni%player%-%uuid of {_target}%"
								set {_h} to location of block above {_target}
								increase {_h}'s y-coordinate by 1.2
								display hologram "<##d74327>%{_a}%" at {_h} to player for 8 ticks
							wait 32 ticks
			else:
				if {language::%player%} = "English":
					send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to player
				else:
					send "&8[&6Earthcraft&8] &6Nie masz wybranej wymaganej karty, by móc użyć tej umiejętności." to player
				play sound "block.glass.break" with volume 3 and pitch 0 to player
on rightclick:
	if name of player's tool = "<##e53311>Inferno":
		cancel event
		if {kartaname::%player%} = "Delphox":
			set {_target} to Target(player, 100, false)
			if {_target} is set:
				if CanUseAbility(player) != false:
					if CanUseAbility(player) != false:
						set {_id} to line 19 of lore of {karta::%player%}
						if player's chestplate is golden nugget:
							if name of player's chestplate contains "Serce Earthcrafta" or "Heart of Earthcraft":
								if line 30 of lore of player's chestplate contains player's name:
									set {_loreheart::*} to lore of player's chestplate
						set {_mistr2} to 2.5 + (({mastery::%player%}/200))
						set {_crch} to ({criticalhit::%player%}/10)
						if {miotaczburn::%{_target}%} is true:
							set {_dmg} to 3.5 + ({versatility::%player%}/120) + ({damage::%player%}/40)  + ({primarystat::%player%}/20)
							set {_stun} to "%2 + (({crowdcontrol::%player%}/60))% seconds" parsed as timespan
							set {_stuntekst} to 2 + (({crowdcontrol::%player%}/60))
							set {_explotekst} to 6 + ({versatility::%player%}/60) + ({damage::%player%}/20) + ({primarystat::%player%}/10)
							#set {stunintdel::%player%} to 2 + (({crowdcontrol::%player%}/60) + ({kontrolatlumu::%{_id}%}/60))
							#set {infs::%{_target}%::dmgcalc} to now
							set {miotaczburn::%{_target}%} to false
							set {_lore} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &fbrak%nl%&7Użycie: &fPPM&7/&fSHIFT%nl%<##e53311>Więzi przeciwnika podpalonego Miotaczem Płomieni%nl%<##e53311>w ognistym więzieniu, ogłuszając go na &f%{_stuntekst}% sekund%nl%<##e53311>i zadajac &f%{_dmg}% <##e53311>obrażeń <##ff4d00>Ognia<##e53311>.%nl% %nl%<##e53311>Kliknięcie Shiftem zdetonuje więzienie,%nl%<##e53311>zadając &f%{_explotekst}% <##e53311>damage <##ff4d00>Ognia <##e53311>i podrzucając wroga do góry."
							set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fRMB&7/&fSHIFT%nl%<##e53311>Imprisons the target affected by Flamethrower%nl%<##e53311>in a fiery prison, stunning them for &f%{_stun}%%nl%<##e53311>and inflicting &f%{_dmg}% <##ff4d00>Fire <##e53311>damage.%nl% %nl%<##e53311>Pressing Shift will detonate the prison,%nl%<##e53311>dealing &f%{_explotekst}% <##ff4d00>Fire <##e53311>damage and tossing the%nl%<##e53311>enemy into the air."
							if {language::%player%} = "English":
								set lore of player's tool to {_loreEN}
							else:
								set lore of player's tool to {_lore}
							#PYROMANIAC
							loop {_loreheart::*}:
								loop-value contains "Pyromaniac":
									add (1.5*{trait::Delphox::Pyromaniac::%player%}) to {_pyromaniac}
							chance of {_crch}%:
								set {_crit} to true
								set {_dmg} to {_dmg} * ({_mistr2} + ({pyromaniacstacks::%player%}/100))
								set {critdmg::%{_target}%} to true
								if {_pyromaniac} is set:
									if {pyromaniacstacks::%player%} is not set:
										set {pyromaniacstacks::%player%} to 0
									else:
										add {_pyromaniac} to {pyromaniacstacks::%player%}
										set {czaspyromaniac::%player%} to 6 seconds
										if {pyromaniacbonus::%player%} is not set:
											set {pyromaniacbonus::%player%} to true
							if {_crit} is not true:
								clear {pyromaniacstacks::%player%}
								clear {czaspyromaniac::%player%}
							if {_target} is alive:
								if canBeCCed({_target}) = true:
									set {stun::%{_target}%} to true
								set {_target}'s last damage cause to sweep attack
								set metadata value "LastDamageCauseEN" of {_target} to "<##d74327>Inferno"
								set metadata value "LastDamageCause" of {_target} to "<##d74327>Inferno"
								set metadata value "Element" of player to "Fire"
								set metadata value "LastDamageCauseLoreEN" of {_target} to {_loreEN}
								set metadata value "LastDamageCauseLore" of {_target} to {_lore}
								make player damage {_target} by {_dmg}*2
								set {infernotarget::%{_target}%} to true
								play sound "entity.illusioner.mirror_move" with volume 1 and pitch 1 at player
								if {_pyromaniac} is set:
									Pyromaniac(player)
								#drawRings particle "flame", center {_target}, id "%{_target}%-%uuid of {_target}%", rainbowMode false, randomRotation true, animated false, radius 1, ringCount 4, ringDensity 10, visibleRange 100, pulseDelay 1
								InfernoParticles({_target})
								wait {_stun}
								#clear {infs::%{_target}%::dmgcalc}
								clear {infernotarget::%{_target}%}
								clear {stun::%{_target}%}
								stopEffect "%{_target}%-%uuid of {_target}%"
		else:
			if {language::%player%} = "English":
				send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to player
			else:
				send "&8[&6Earthcraft&8] &6Nie masz wybranej wymaganej karty, by móc użyć tej umiejętności." to player
			play sound "block.glass.break" with volume 3 and pitch 0 to player
function InfernoParticles(target: entity):
	while {infernotarget::%{_target}%} is true:
		set {_shape} to sphere with radius 1
		draw {_shape} at block above {_target}
		wait 1 second
on sneak toggle:
	if name of player's tool = "<##e53311>Inferno":
		if {kartaname::%player%} = "Delphox":
			if CanUseAbility(player) != false:
				set {_target} to Target(player, 100, false)
				if {_target} is set:
					set {_id} to line 19 of lore of {karta::%player%}
					set {_mistr2} to 2.5 + (({mastery::%player%}/200))
					set {_crch} to ({criticalhit::%player%}/10)
					if player's chestplate is golden nugget:
						if name of player's chestplate contains "Serce Earthcrafta" or "Heart of Earthcraft":
							if line 30 of lore of player's chestplate contains player's name:
								set {_loreheart::*} to lore of player's chestplate
					if {infernotarget::%{_target}%} is true:
						#SKALOWANIE Z KONTROLĄ TŁUMU
						#set {_c} to "%difference between now and {infs::%{_target}%::dmgcalc}%"
						#set {_d} to "%{_c}%"
						#replace all " seconds" or " second" with "" in {_d}
						#set {_e} to {_d} parsed as number
						#set {_f} to {stunintdel::%player%} - {_e}
						#set {_b} to "%{_f}% seconds" parsed as timespan
						#set {_dmg} to (0.5 + {_uniwersalnosc}/44 + {_obrazenia}/32)*{_f}
						set {_dmg} to 6 + ({versatility::%player%}/60) + ({damage::%player%}/20) + ({primarystat::%player%}/10)
						set {infernotarget::%{_target}%} to false
						clear {stun::%{_target}%}
						stopEffect "%{_target}%-%uuid of {_target}%"
						set {_knock} to 1 + ({crowdcontrol::%player%}/100)
						set {_lore} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &fbrak%nl%&7Użycie: &fPPM&7/&fSHIFT%nl%<##e53311>Więzi przeciwnika podpalonego Miotaczem Płomieni%nl%<##e53311>w ognistym więzieniu, ogłuszając go na &f%{_stuntekst}% sekund%nl%<##e53311>i zadajac &f%{_dmg}% <##e53311>obrażeń <##ff4d00>Ognia<##e53311>.%nl% %nl%<##e53311>Kliknięcie Shiftem zdetonuje więzienie,%nl%<##e53311>zadając &f%{_explotekst}% <##e53311>damage <##ff4d00>Ognia <##e53311>i podrzucając wroga do góry."
						set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &fnone%nl%&7Use: &fRMB&7/&fSHIFT%nl%<##e53311>Imprisons the target affected by Flamethrower%nl%<##e53311>in a fiery prison, stunning them for &f%{_stun}%%nl%<##e53311>and inflicting &f%{_dmg}% <##ff4d00>Fire <##e53311>damage.%nl% %nl%<##e53311>Pressing Shift will detonate the prison,%nl%<##e53311>dealing &f%{_explotekst}% <##ff4d00>Fire <##e53311>damage and tossing the%nl%<##e53311>enemy into the air."
						#PYROMANIAC
						loop {_loreheart::*}:
							loop-value contains "Pyromaniac":
								add (1.5*{trait::Delphox::Pyromaniac::%player%}) to {_pyromaniac}
						if {controlleddestruction::%player%} is set:
							set {_dmg} to {_dmg} + {controlleddestruction::%player%}
							set {_crch} to 100
							clear {controlleddestruction::%player%}
						if {_target} is alive:
							chance of {_crch}%:
								set {_crit} to true
								set {_dmg} to {_dmg} * ({_mistr2} + ({pyromaniacstacks::%player%}/100))
								set {critdmg::%{_target}%} to true
								if {_pyromaniac} is set:
									if {pyromaniacstacks::%player%} is not set:
										set {pyromaniacstacks::%player%} to 0
									else:
										add {_pyromaniac} to {pyromaniacstacks::%player%}
										set {czaspyromaniac::%player%} to 6 seconds
										if {pyromaniacbonus::%player%} is not set:
											set {pyromaniacbonus::%player%} to true
							if {_crit} is not true:
								clear {pyromaniacstacks::%player%}
								clear {czaspyromaniac::%player%}
							play sound "entity.dragon_fireball.explode" with volume 1 and pitch 1 at player
							push {_target} upwards with velocity {_knock}
							set {_target}'s last damage cause to sweep attack
							set metadata value "LastDamageCauseEN" of {_target} to "<##d74327>Inferno (Explosion)"
							set metadata value "LastDamageCause" of {_target} to "<##d74327>Inferno (Eksplozja)"
							set metadata value "Element" of player to "Fire"
							set metadata value "LastDamageCauseLoreEN" of {_target} to {_loreEN}
							set metadata value "LastDamageCauseLore" of {_target} to {_lore}
							make player damage {_target} by {_dmg} * 2
							if {_pyromaniac} is set:
								Pyromaniac(player)
							#PYROCLASM
							loop {_loreheart::*}:
								loop-value contains "Pyroclasm":
									add 1 to {_chance}
							chance of {_chance}*(2.5*{trait::Delphox::Pyroclasm::%player%})%:
								set {pyroclasm::%player%} to true
							#FIREFALL
							loop {_loreheart::*}:
								loop-value contains "Firefall":
									add (3*{trait::Delphox::Firefall::%player%}) to {_firefall}
							if {_firefall} is set:
								add 1 to {meteor::%player%}
								if {meteor::%player%} >= 4:
									remove 4 from {meteor::%player%}
									if {meteor::%player%} = 0:
										clear {meteor::%player%}
									play sound "entity.creeper.primed" with volume 3 and pitch 1.5 at {_target}
									set {_l} to location 20 blocks above {_target}'s head
									set {_v} to vector between {_l} and {_target}'s head
									loop round(distance between {_l} and {_target}) / 0.2 times:
										set {_v} to vector between {_l} and {_target}'s head
										set vector length of {_v} to loop-value * 0.2
										draw 1 of dust using dustOption((rgb 224, 117, 22), 1) at {_l} ~ {_v}
										draw 1 of dust using dustOption((rgb 224, 76, 47), 1) at {_l} ~ {_v}
										draw 1 of dust using dustOption((rgb 135, 76, 65), 1) at {_l} ~ {_v}
										#drawDot count 1, particle "redstone", RGB 224, 117, 22, center {_l} ~ {_v}, rainbowMode false, visibleRange 32, pulseDelay 0, keepFor 5 ticks
										#drawDot count 1, particle "redstone", RGB 224, 76, 47, center {_l} ~ {_v}, rainbowMode false, visibleRange 32, pulseDelay 0, keepFor 5 ticks
										#drawDot count 1, particle "redstone", RGB 135, 76, 65, center {_l} ~ {_v}, rainbowMode false, visibleRange 32, pulseDelay 0, keepFor 5 ticks
										wait 1 tick
									play sound "entity.dragon_fireball.explode" with volume 3 and pitch 0 at {_target}
									chance of {_crch}%:
										set {_crit} to true
										set {_firefall} to {_firefall} * ({_mistr2} + ({pyromaniacstacks::%player%}/100))
										if {_pyromaniac} is set:
											if {pyromaniacstacks::%player%} is not set:
												set {pyromaniacstacks::%player%} to 0
											else:
												add {_pyromaniac} to {pyromaniacstacks::%player%}
												set {czaspyromaniac::%player%} to 6 seconds
												if {pyromaniacbonus::%player%} is not set:
													set {pyromaniacbonus::%player%} to true
									if {_crit} is not true:
										clear {pyromaniacstacks::%player%}
										clear {czaspyromaniac::%player%}
									loop all entities in radius 4 around {_target}:
										if {mob::%loop-entity%} is true:
											set loop-entity's last damage cause to sweep attack
											set metadata value "LastDamageCause" of loop-entity to "<##e53311>Meteor"
											set metadata value "LastDamageCauseEN" of loop-entity to "<##e53311>Meteor"
											set metadata value "Element" of player to "Fire"
											set metadata value "LastDamageCauseLoreEN" of loop-entity to "&7Every fourth detonated <##e53311>Inferno &7calls%nl%&7down a Meteor &7on your target,%nl%&7dealing &f%{_firefall}% <##ff4d00>Fire &7damage to all enemies nearby."
											set metadata value "LastDamageCauseLore" of loop-entity to "&7Co czwarte zdetonowane <##e53311>Inferno &7przywołuje%nl%&7Meteor &7na twój cel, &7zadając &f%3*{_x6}% &7obrażeń%nl%<##ff4d00>Ognia &7wszystkim wrogom w pobliżu."
											if {_crit} = true:
												set {critdmg::%loop-entity%} to true
											make player damage loop-entity by {_firefall}*2
									if {_pyromaniac} is set:
										Pyromaniac(player)
									loop all blocks in radius 4 around {_target}:
										show 1 large explosion at loop-block
			else:
				if {language::%player%} = "English":
					send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to player
				else:
					send "&8[&6Earthcraft&8] &6Nie masz wybranej wymaganej karty, by móc użyć tej umiejętności." to player
				play sound "block.glass.break" with volume 3 and pitch 0 to player

on rightclick:
	if name of player's tool = "<##e53311>Płomienna Bariera" or "<##e53311>Flame Barrier":
		cancel event
		if {kartaname::%player%} = "Delphox":
			if CanUseAbility(player) != false:
				set {_id} to line 19 of lore of {karta::%player%}
				if player's chestplate is golden nugget:
					if name of player's chestplate contains "Serce Earthcrafta" or "Heart of Earthcraft":
						if line 30 of lore of player's chestplate contains player's name:
							set {_loreheart::*} to lore of player's chestplate
				set {_pospiech} to 1 + (({haste::%player%}/4))/100 
				set {_cd} to "%130/{_pospiech}% seconds" parsed as timespan
				set {_cdd} to 130/{_pospiech}
				set {_blotekst} to rounded down 6 + (({resistance::%player%}/45) + ({wytrzymalosc::%{_id}%}/45))
				if cooldown "płomiennabariera%player%" is finished:
					create cooldown "płomiennabariera%player%" for {_cd}
					set the cooldown of player's held item for player to {_cd}
					set {_lore} to "&8Umiejętność%nl%&fInstant cast%nl%&7Cooldown: &f%{_cdd}% sekund%nl%&7Użycie: &fPPM&%nl%<##e53311>Otacza cię Płomienną Barierą,%nl%<##e53311>negując wszystkie obrażenia otrzymane przez%nl%<##e53311>kolejne &f%{_blotekst}% sekund<##e53311>."
					set {_loreEN} to "&8Ability%nl%&fInstant cast%nl%&7Cooldown: &f%{_cdd}% seconds%nl%&7Use: &fRMB%nl%<##e53311>Surrounds you in a Flame Barrier,%nl%<##e53311>negating any incoming damage for the next%nl%&f%{_blotekst}% seconds<##e53311>."
					if {language::%player%} = "English":
						if name of player's tool does not contain "Flame Barrier":
							replace all "Płomienna Bariera" in player's tool's name with "Flame Barrier"
						set lore of player's tool to {_loreEN}
					else:
						if name of player's tool does not contain "Płomienna Bariera":
							replace all "Flame Barrier" in player's tool's name with "Płomienna Bariera"
						set lore of player's tool to {_lore}
					set {_bsek} to "%6 + (({resistance::%player%}/45) + ({wytrzymalosc::%{_id}%}/45))% seconds" parsed as timespan
					set {_bsek2} to {_bsek}
					set {_blo} to rounded down 6 + (({resistance::%player%}/45) + ({wytrzymalosc::%{_id}%}/45))
					#CONTROLLED DESTRUCTION
					loop {_loreheart::*}:
						loop-value contains "Controlled Destruction":
							add (1.5*{trait::Delphox::Controlled Destruction::%player%}) to {_controlleddestruction}
					if {_controlleddestruction} is set:
						set {controlleddestruction::%player%} to {_controlleddestruction}
					loop all blocks in radius 2.5 around the player:
						show 1 flame at loop-block
					replace all " seconds" in {_bsek} with " sekund"
					set {bariera::%player%} to true
					make player invulnerable
					play sound "block.beacon.power_select" with volume 5 and pitch 1 at player
					if {language::%player%} = "English":
						send action bar "<##e53311>BARRIER &7(%{_bsek}%)" to player
					else:
						send action bar "<##e53311>BARIERA &7(%{_bsek}%)" to player
					wait 1 second
					loop {_blo} times:
						remove 1 from {_blo}
						if {language::%player%} = "English":
							send action bar "<##e53311>BARRIER &7(%{_blo}% seconds)" to player
						else:
							send action bar "<##e53311>BARIERA &7(%{_blo}% seconds)" to player
						wait 1 second
					wait {_bsek2}
					clear {bariera::%player%}
					make player vulnerable
				else:
					cancel event
					if {tekstcd::%player%} = true:
						set {_cdd} to cooldown "płomiennabariera%player%"
						if {language::%player%} = "English":
							send "<##e53311>You must wait &f%{_cdd}% <##e53311>to use this ability." to player
						else:
							send "<##e53311>Musisz odczekać &f%{_cdd}%<##e53311>, aby użyć tej umiejętności." to player
					stop
		else:
			if {language::%player%} = "English":
				send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to player
			else:
				send "&8[&6Earthcraft&8] &6Nie masz wybranej wymaganej karty, by móc użyć tej umiejętności." to player
			play sound "block.glass.break" with volume 3 and pitch 0 to player
			
function BlasterMaster(p: player):
	if {blastermasterstacks::%{_p}%} > 0:
		if {_p}'s chestplate is golden nugget:
			if name of {_p}'s chestplate contains "Serce Earthcrafta" or "Heart of Earthcraft":
				if line 30 of lore of {_p}'s chestplate contains {_p}'s name:
					set {_loreheart::*} to lore of {_p}'s chestplate
		#BLASTERMASTER
		loop {_loreheart::*}:
			loop-value contains "Blaster Master":
				add (20*{trait::Delphox::Blaster Master::%{_p}%}) to {_blastermaster}
		wait 3 seconds
		remove 1 from {blastermasterstacks::%{_p}%}
		remove {_blastermaster} from {mastery::%{_p}%}
		if 0 >= {blastermasterstacks::%{_p}%}:
			clear {blastermasterstacks::%{_p}%}
			
function Pyromaniac(p: player):
	if {pyromaniacbonus::%{_p}%} is true:
		set {pyromaniacbonus::%{_p}%} to false
		while {czaspyromaniac::%{_p}%} > 0 seconds:
			if {_p} is alive:
				remove 1 second from {czaspyromaniac::%{_p}%}
				wait 1 second
				if 0 seconds >= {czaspyromaniac::%{_p}%}:
					clear {pyromaniacstacks::%{_p}%}
					clear {czaspyromaniac::%{_p}%}
					clear {pyromaniacbonus::%{_p}%}
					stop loop
			else:
				clear {pyromaniacstacks::%{_p}%}
				stop loop

on damage:
	if damage cause is burn:
		if {miotaczburn::%victim%} is true:
			cancel event
	if {bariera::%victim%} is true:
		set damage to 0
		cancel event
		#if attacker is a player:
		#	set {_h} to location of block above victim
			#if {language::%attacker%} = "English":
			#	display hologram "<##e53311>BLOCK" at {_h} to attacker for 0.75 seconds
			#else:
			#	display hologram "<##e53311>BLOK" at {_h} to attacker for 0.75 seconds

on entity knockback:
	if knockback attacker is a player:
		if {lastdmgcause::%knockback victim%} = "<##d74327>Miotacz Płomieni" or "<##d74327>Inferno (Wybuch)" or "<##d74327>Inferno":
			cancel event