

function VoidEruptionAbilityCast(p: player):
    if {kartaname::%{_p}%} = "Brother Therold":
        if CanUseAbility({_p}) != false:
            if metadata tag "casting" of {_p} is not set:
                if (string tag "Talents;Row 5" of (custom nbt of {karta::%{_p}%})) = "Legacy of the Void":
                    set {_requiredInsanity} to 60
                else:
                    set {_requiredInsanity} to 90
                if {insanity::%{_p}%} >= {_requiredInsanity}:
                    set {_target} to Target({_p}, 100, false)
                    if {_target} is set:
                        if cooldown "Shadow Word: Pain%{_p}%" is finished:
                            if cooldown "Shadow Word: Death%{_p}%" is finished:
                                if cooldown "Global Cooldown Interrupted Cast%{_p}%" is finished:
                                    set {_pospiech} to Haste({_p})
                                    set {_baseCasttime} to 2
                                    if (string tag "Talents;Row 5" of (custom nbt of {karta::%{_p}%})) = "Legacy of the Void":
                                        set {_baseCasttime} to {_baseCasttime}*0.6 
                                    playAnimation({_p}, "voideruption", 2.4, {_pospiech})
                                    set {_casttime} to "%round(({_baseCasttime}/{_pospiech}), 1)% seconds" parsed as timespan
                                    if metadata tag "cast" of {_p} is not set:
                                        set metadata tag "casttimemax" of {_p} to {_casttime}
                                        set metadata tag "lastspellTherold" of {_p} to uncolored {_p}'s tool's name
                                        play sound "skill.therold.void_eruption_precast" with volume 3 and pitch 1 at (location of {_p})
                                        set metadata tag "casting" of {_p} to true
                                        set metadata tag "cast" of {_p} to {_casttime}
                                        while metadata tag "casting" of {_p} = true:
                                            if metadata tag "channeling" of {_p} is set:
                                                clear metadata tag "channeling" of {_p}
                                                stop sound "skill.therold.mindflay_channel_whisper" for (all players in radius 2 around {_p})
                                                stop sound "skill.therold.mindflay_channel" for (all players in radius 2 around {_p})
                                            set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                                            set {_insanityDrain} to 6 + 0.68*{_voidformStacks}
                                            set {_insanityInfo} to "Insanity: %round({insanity::%{_p}%}, 0)%"
                                            if metadata tag "Voidform" of {_p} is set:
                                                set {_insanityInfo} to "%{_insanityInfo}%   %round({_insanityDrain}, 1)%p/s    %{_voidformStacks}%"
                                            if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Lingering Insanity":
                                                if {lingeringInsanityHaste::%{_p}%} is set:
                                                    set {_insanityInfo} to "%{_insanityInfo}% |  %{lingeringInsanityHaste::%{_p}%}/4%%% "
                                            if metadata tag "cast" of {_p} is not set:
                                                clear metadata tag "casting" of {_p}
                                                stop
                                            if {_p} can not see {_target}:
                                                clear metadata tag "casting" of {_p}
                                                stop
                                            if {_casttime} > 0 seconds:
                                                set metadata tag "casttimeleft" of {_p} to {_casttime}
                                                set {_cst} to "%{_casttime}%"
                                                send action bar "Casting... %{_cst}% | %{_insanityInfo}%" to {_p}
                                                wait 0.1 seconds
                                                remove 0.1 seconds from {_casttime}
                                            else:
                                                clear metadata tag "casting" of {_p}
                                                send action bar "" to {_p}
                                    else:
                                        stop
                                    clear metadata tag "casting" of {_p}
                                    clear metadata tag "cast" of {_p}
                                    clear metadata tag "casttime" of {_p}
                                    clear metadata tag "casttimemax" of {_p}
                                    stop sound "skill.therold.void_eruption_precast" for (all players in radius 2 around {_p})
                                    if {_casttime} > 0 seconds:
                                        send action bar "&cInterrupted" to {_p}
                                        stop
                                    set metadata tag "Voidform" of {_p} to true
                                    AbilityUse({_p}, "Void Eruption")
                                    buffRegister({_p}, "Voidform", 5, "", "Value", "active", "-")
                                    play sound "skill.therold.void_eruption_cast" with volume 3 and pitch 1 at (location of {_p})
                                    set {_crit} to CriticalHit({_p})
                                    loop all items in the inventory of {_p}:
                                        if boolean tag "Void Eruption" of (custom nbt of loop-item) = true:
                                            set {_cdVoidbolt} to "%4.5/{_pospiech}% seconds" parsed as timespan
                                            set {_dmgVoidbolt} to (3 + (({damage::%{_p}%}/15) + ({versatility::%{_p}%}/45)))
                                            set {_voidBolt} to (black dye named "<##613e82>Void Bolt") with lore "&8Ultimate Ability%nl%&fInstant cast%nl%&7Cooldown:  &f%{_cdVoidbolt}%%nl%&7Use: &fRMB%nl%<##613e82>Sends a bolt of pure void energy at the%nl%<##613e82>enemy, causing &f%{_dmgVoidbolt}%  <##431d53>Ghost <##613e82>damage and%nl%<##8165a6>extending <##613e82>the duration of &f <##8165a6>Shadow Word:%nl%<##8165a6>Pain <##613e82>and &f <##8165a6>Vampiric Touch <##613e82>to their original%nl%<##613e82>duration.%nl% %nl%<##613e82>Requires &f <##8165a6>Voidform<##613e82>.%nl% %nl%&fGenerates 16 Insanity."
                                            add nbt from "{""minecraft:custom_model_data"":{floats:[3.0f]},""minecraft:custom_data"":{""Void Bolt"":1b}}" to nbt of {_voidBolt}
                                            set loop-item to {_voidBolt}
                                    set {_lore} to join (lore of {_p}'s tool) by nl
                                    set gravity attribute of {_p} to 0
                                    loop all entities in radius 8 around {_target}:
                                        if loop-entity is a living entity:
                                            if loop-entity is alive:
                                                if loop-entity is not a player:
                                                    if boolean tag "ECMob" of (custom nbt of loop-entity) is set:
                                                        if CheckIfDotted({_p}, loop-entity) is true:
                                                            VoidEruptionVisual({_p}, loop-entity)
                                                            set {_damage} to (4 + (({damage::%{_p}%}/9) + ({versatility::%{_p}%}/27) + {primarystat::%{_p}%}/4.5)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
                                                            set loop-entity's last damage cause to sweep attack
                                                            set metadata tag "LastDamageCause" of loop-entity to "<##462566>Void Eruption"
                                                            set metadata tag "LastDamageCauseLore" of loop-entity to {_lore}
                                                            set metadata tag "Element" of {_p} to "Ghost"
                                                            set {_damage} to Crit({_p}, loop-entity, {_crit}, {_damage})
                                                            make {_p} damage loop-entity by {_damage}*2
                                    while metadata tag "Voidform" of {_p} is true:
                                        if {insanity::%{_p}%} > 0:
                                            add 1 to {_voidformStacks}
                                            set metadata tag "Voidform Stacks" of {_p} to {_voidformStacks}
                                            set {_insanityDrain} to 6 + 0.68*{_voidformStacks}
                                            remove {_insanityDrain} from {insanity::%{_p}%}             
                                            draw 20 of (((purple dust particle of size 1) with an extra value of 0.03) with offset vector(0.3, 0.6, 0.3)) at (location above {_p})
                                            set {insanity::%{_p}%} to 0 if {insanity::%{_p}%} < 0
                                            set {hasteVoidform::%{_p}%} to {hasteVoidform::%{_p}%} + 4
                                        Mania({_p})
                                        ExitVoidform({_p}) if {insanity::%{_p}%} = 0
                                        stop if {insanity::%{_p}%} = 0
                                        set {_insanityInfo} to "Insanity: %round({insanity::%{_p}%}, 0)%"
                                        set {_insanityInfo} to "%{_insanityInfo}%   %round({_insanityDrain}, 1)%p/s    %{_voidformStacks}%"
                                        if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Lingering Insanity":
                                            if {lingeringInsanityHaste::%{_p}%} is set:
                                                set {_insanityInfo} to "%{_insanityInfo}% |  %{lingeringInsanityHaste::%{_p}%}/4%%% "
                                        if metadata tag "channeling" of {_p} != true:
                                            send action bar {_insanityInfo} to {_p}
                                        wait 1 second
                            else: 
                                if {tekstcd::%{_p}%} = true:
                                    set {_cdd} to cooldown "Shadow Word: Death%{_p}%"
                                    send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                                stop
                        else: 
                            if {tekstcd::%{_p}%} = true:
                                set {_cdd} to cooldown "Shadow Word: Pain%{_p}%"
                                send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                            stop
    else:
        send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to {_p}
        play sound "block.glass.break" with volume 3 and pitch 0 to {_p}

function VoidBoltCast(p: player, target: entity):
    set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
    set {_cd} to "%4.5/{_pospiech}% seconds" parsed as timespan
    set the cooldown of {_p}'s held item for {_p} to {_cd}
    create cooldown "Void Bolt%{_p}%" for {_cd}
    AbilityUse({_p}, "Void Bolt")
    if metadata tag "channeling" of {_p} is set:
        clear metadata tag "channeling" of {_p}
        StopCastSoundTherold({_p})
    if metadata tag "casting" of {_p} is set:
        clear metadata tag "cast" of {_p}
        StopCastSoundTherold({_p})
        send action bar "&cInterrupted" to {_p}
    set metadata tag "lastspellTherold" of {_p} to "Void Bolt"
    set {_randomLocation} to a random number between -0.40 and 0.40
    set {_l} to location 0.3 blocks below and {_randomLocation} left of {_p}'s head
    set {_vec} to vector between {_p} and {_target}'s head
    play sound "skill.therold.void_bolt_cast" with volume 3 and pitch 1 at (location of {_p})
    play sound "skill.therold.shadowcast" with volume 3 and pitch 1 at (location of {_p})
    loop round(distance between {_l} and {_target}) / 0.5 times:
        set {_vec} to vector between {_l} and {_target}'s head
        set vector length of {_vec} to loop-value * 0.5
        draw 1 of (rgb(65, 46, 115) dust particle of size 1) at ({_l} ~ {_vec})
    play sound "skill.therold.void_bolt_impact" with volume 3 and pitch 1 at (location of {_p})
    GrantInsanity({_p}, 16)
    UpdateInsanity({_p})
    set {_crit} to CriticalHit({_p})
    set {_damage} to (4.5 + (({damage::%{_p}%}/14.5) + ({versatility::%{_p}%}/43.5) + {primarystat::%{_p}%}/7.25)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
    if boolean tag "Constellation;Mass Hysteria" of (custom nbt of {karta::%{_p}%}) is set:
        set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
        set {_damage} to {_damage}*(1 + ({_voidformStacks}/100))

    if metadata tag "Heir to the Darkness" of {_p} > 0:
        set {_heirToTheDarkness} to metadata tag "Heir to the Darkness" of {_p}
        set {_damage} to {_damage}*(1 + ({_heirToTheDarkness}/100))

    if offensiveTrait({_p}, "Brother Therold", "Sinister Thoughts") > 0:
        add offensiveTrait({_p}, "Brother Therold", "Sinister Thoughts") to {_damage}
        chance of 3%:
            if metadata tag "Voidform" of {_p} is set:
                clear cooldown "Void Bolt%{_p}%"
                loop all items in {_p}'s inventory:
                    if boolean tag "Void Bolt" of (custom nbt of loop-item) is set:
                        clear cooldown of loop-item for {_p}
    if metadata tag "Voidform" of {_p} is set:
        set {_damage} to {_damage}*1.2
    set {_target}'s last damage cause to sweep attack
    set {_lore} to "&8Ultimate Ability%nl%&fInstant cast%nl%&7Cooldown:  &f%{_cd}% seconds%nl%&7Use: &fRMB%nl%<##613e82>Sends a bolt of pure void energy at the%nl%<##613e82>enemy, causing &f%{_damage}%  <##431d53>Ghost <##613e82>damage and%nl%<##8165a6>extending <##613e82>the duration of &f <##8165a6>Shadow Word:%nl%<##8165a6>Pain <##613e82>and &f <##8165a6>Vampiric Touch <##613e82>to their original%nl%<##613e82>duration.%nl% %nl%<##613e82>Requires &f <##8165a6>Voidform<##613e82>.%nl% %nl%&fGenerates 16 Insanity."
    set metadata tag "LastDamageCause" of {_target} to "<##462566>Void Bolt"
    set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
    set metadata tag "Element" of {_p} to "Ghost"
    set lore of {_p}'s tool to {_lore}
    set {_damage} to Crit({_p}, {_target}, {_crit}, {_damage})
    make {_p} damage {_target} by {_damage}*2

    if boolean tag "Constellation;Unleash the Shadows" of (custom nbt of {karta::%{_p}%}) is set:
        ShadowyApparitionSpawn({_p}, {_target})

    loop all entities in radius 4 around {_target}:
        if metadata tag "Shadow Word: Pain-%{_p}%" of loop-entity is set:
            ShadowWordPainRefresh({_p}, loop-entity)
        if metadata tag "Vampiric Touch-%{_p}%" of loop-entity is set:
            VampiricTouchRefresh({_p}, loop-entity)

function VoidBoltAbilityCast(p: player):
    if {kartaname::%{_p}%} = "Brother Therold":
        if CanUseAbility({_p}) != false:
            set {_target} to Target({_p}, 100, false)
            if {_target} is set:
                if cooldown "Void Bolt%{_p}%" is finished:
                    if cooldown "Shadow Word: Pain%{_p}%" is finished:
                        if cooldown "Shadow Word: Death%{_p}%" is finished:
                            if cooldown "Global Cooldown Interrupted Cast%{_p}%" is finished:
                                if metadata tag "Voidform" of {_p} is set:
                                    VoidBoltCast({_p}, {_target})
                                else:
                                    if metadata tag "SinisterThoughts" of {_p} is set:
                                        VoidBoltCast({_p}, {_target})
                                        clear metadata tag "SinisterThoughts" of {_p}
                                        loop all items in the inventory of {_p}:
                                            if boolean tag "Void Bolt" of (custom nbt of loop-item) = true:
                                                if (string tag "Talents;Row 5" of (custom nbt of {karta::%{_p}%})) = "Legacy of the Void":
                                                    set {_requiredInsanity} to 60
                                                else:
                                                    set {_requiredInsanity} to 90
                                                set {_damage} to (4 + (({damage::%{_p}%}/9) + ({versatility::%{_p}%}/27) + {primarystat::%{_p}%}/4.5)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
                                                set {_pospiech} to Haste({_p})
                                                set {_baseCasttime} to 2
                                                if (string tag "Talents;Row 5" of (custom nbt of {karta::%{_p}%})) = "Legacy of the Void":
                                                    set {_baseCasttime} to {_baseCasttime}*0.6 
                                                set {_casttime} to "%round(({_baseCasttime}/{_pospiech}), 1)% seconds" parsed as timespan
                                                set {_lore} to "&8Ultimate Ability%nl%&f%{_casttime}% cast%nl%&7No cooldown%nl%&7Use: &fRMB%nl%<##613e82>Releases an explosive blast of pure void%nl%<##613e82>energy, activating &f<##8165a6>Voidform <##613e82>and causing%nl%&f%{_damage}% <##431d53>Ghost <##613e82>damage to all enemies afflicted by%nl%<##613e82>your &f<##8165a6>Shadow Word: Pain <##613e82>or &f<##8165a6>Vampiric Touch.%nl% %nl%<##613e82>During &f<##8165a6>Voidform<##613e82>, this ability is replaced%nl%<##613e82>by &f<##8165a6>Void Bolt<##613e82>.%nl% %nl%&fRequires %{_requiredInsanity}% Insanity to activate."
                                                set {_voidEruption} to (purple dye named "<##613e82>Void Eruption") with lore {_lore}
                                                add nbt from ("{""minecraft:custom_model_data"":{floats:[9.0f]},""minecraft:custom_data"":{""Void Eruption"":1b}}") to (nbt of {_voidEruption})
                                                set loop-item to {_voidEruption}
                                    else:
                                        send "<##462566>You must be in Voidform to use this ability." to {_p}
                                    stop
                        else: 
                            if {tekstcd::%{_p}%} = true:
                                set {_cdd} to cooldown "Shadow Word: Death%{_p}%"
                                send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                            stop
                    else: 
                        if {tekstcd::%{_p}%} = true:
                            set {_cdd} to cooldown "Shadow Word: Pain%{_p}%"
                            send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                        stop
                else: 
                    if {tekstcd::%{_p}%} = true:
                        set {_cdd} to cooldown "Void Bolt%{_p}%"
                        send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                    stop
    else:
        send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to {_p}
        play sound "block.glass.break" with volume 3 and pitch 0 to {_p}

function MindBlastAbilityCast(p: player):
    if {kartaname::%{_p}%} = "Brother Therold":
        if string tag "Talents;Row 1" of (custom nbt of {karta::%{_p}%}) != "Shadow Word: Void":
            if CanUseAbility({_p}) != false:
                if metadata tag "casting" of {_p} is not set:
                    set {_target} to Target({_p}, 100, false)
                    if {_target} is set:
                        if isCastableTherold({_p}) = true:
                            if cooldown "Shadow Word: Pain%{_p}%" is finished:
                                if cooldown "Shadow Word: Death%{_p}%" is finished:
                                    if cooldown "Global Cooldown Interrupted Cast%{_p}%" is finished:
                                        set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
                                        set {_casttime} to "%round((1.5/{_pospiech}), 1)% seconds" parsed as timespan
                                        set {_casttimeText} to {_casttime}
                                        set {_cd} to "%9/{_pospiech}% seconds" parsed as timespan
                                        if metadata tag "ShadowyInsight" of {_p} != true:
                                            if metadata tag "cast" of {_p} is not set:
                                                set metadata tag "casttimemax" of {_p} to {_casttime}
                                                play sound "skill.therold.mindblast_precast" with volume 3 and pitch 1 at (location of {_p})
                                                set metadata tag "casting" of {_p} to true
                                                if metadata tag "channeling" of {_p} is set:
                                                    clear metadata tag "channeling" of {_p}
                                                    StopCastSoundTherold({_p})
                                                set metadata tag "lastspellTherold" of {_p} to uncolored {_p}'s tool's name
                                                set metadata tag "cast" of {_p} to {_casttime}
                                                while metadata tag "casting" of {_p} = true:
                                                    set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                                                    set {_insanityDrain} to 6 + 0.68*{_voidformStacks}
                                                    set {_insanityInfo} to "Insanity: %round({insanity::%{_p}%}, 0)%"
                                                    if metadata tag "Voidform" of {_p} is set:
                                                        set {_insanityInfo} to "%{_insanityInfo}%   %round({_insanityDrain}, 1)%p/s    %{_voidformStacks}%"
                                                    if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Lingering Insanity":
                                                        if {lingeringInsanityHaste::%{_p}%} is set:
                                                            set {_insanityInfo} to "%{_insanityInfo}% |  %{lingeringInsanityHaste::%{_p}%}/4%%% "
                                                    if metadata tag "cast" of {_p} is not set:
                                                        clear metadata tag "casting" of {_p}
                                                        stop sound "skill.therold.mindblast_precast" for (all players in radius 2 around {_p})
                                                        stop
                                                    if {_p} can not see {_target}:
                                                        clear metadata tag "casting" of {_p}
                                                        stop
                                                    if {_casttime} > 0 seconds:
                                                        set metadata tag "casttimeleft" of {_p} to {_casttime}
                                                        set {_cst} to "%{_casttime}%"
                                                        send action bar "Casting... %{_cst}% | %{_insanityInfo}%" to {_p}
                                                        wait 0.1 seconds
                                                        remove 0.1 seconds from {_casttime}
                                                    else:
                                                        clear metadata tag "casting" of {_p}
                                                        send action bar "" to {_p}
                                            else:
                                                stop
                                            clear metadata tag "casting" of {_p}
                                            clear metadata tag "cast" of {_p}
                                            clear metadata tag "casttimeleft" of {_p}
                                            clear metadata tag "casttimemax" of {_p}
                                            stop sound "skill.therold.mindblast_precast" for (all players in radius 2 around {_p})
                                            if {_casttime} > 0 seconds:
                                                send action bar "&cInterrupted" to {_p}
                                                stop
                                            set {_charges} to metadata tag "MindBlastCharges" of {_p}
                                            remove 1 from {_charges}
                                            set metadata tag "MindBlastCharges" of {_p} to {_charges}
                                            if boolean tag "Constellation;Thought Harvester" of (custom nbt of {karta::%{_p}%}) is not set:
                                                create cooldown "Mind Blast%{_p}%" for {_cd}
                                            MindBlastRecharge({_p}, {_cd})
                                        else:
                                            clear metadata tag "ShadowyInsight" of {_p}
                                            set {_charges} to metadata tag "MindBlastCharges" of {_p}
                                            send title " " with subtitle " " to {_p} for 1 second with fade in 0.0 second and fade out 0.0 second
                                        AbilityUse({_p}, "Mind Blast")
                                        set {_insanity} to 12
                                        if (string tag "Talents;Row 1" of (custom nbt of {karta::%{_p}%})) = "Fortress of the Mind":
                                            set {_insanity} to {_insanity}*1.2
                                        GrantInsanity({_p}, {_insanity})
                                        UpdateInsanity({_p})
                                        play sound "skill.therold.mindblast_impact" with volume 3 and pitch 1 at (location of {_p})
                                        play sound "skill.therold.shadowcast" with volume 3 and pitch 1 at (location of {_p})
                                        draw 20 of (((rgb(95, 72, 156) dust particle of size 1) with an extra value of 0.03) with offset vector(0.4, 0.5, 0.4)) at ({_target}'s head)
                                        draw 20 of (((rgb(41, 22, 92) dust particle of size 1) with an extra value of 0.03) with offset vector(0.35, 0.45, 0.35)) at ({_target}'s head)
                                        if {_target} is alive:
                                            set {_crit} to CriticalHit({_p})
                                            set {_damage} to (4.5 + (({damage::%{_p}%}/24) + ({versatility::%{_p}%}/72) + {primarystat::%{_p}%}/12)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
                                            if boolean tag "Constellation;Mass Hysteria" of (custom nbt of {karta::%{_p}%}) is set:
                                                set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                                                set {_damage} to {_damage}*(1 + ({_voidformStacks}/100))
                                            add offensiveTrait({_p}, "Brother Therold", "Whispers of the Damned") to {_damage}
                                            if metadata tag "Voidform" of {_p} is set:
                                                set {_damage} to {_damage}*1.2
                                            if (string tag "Talents;Row 1" of (custom nbt of {karta::%{_p}%})) = "Fortress of the Mind":
                                                set {_damage} to {_damage}*1.1
                                            if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
                                                if metadata tag "Vampiric Touch-%{_p}%" of {_target} is set:
                                                    if metadata tag "Shadow Word: Pain-%{_p}%" of {_target} is set:
                                                        set {_damage} to {_damage}*1.55
                                            if {_charges} = 1:
                                                set {_chargesLore} to "%{_charges}% Charge"
                                            else:
                                                set {_chargesLore} to "%{_charges}% Charges"
                                            if boolean tag "Constellation;Thought Harvester" of (custom nbt of {karta::%{_p}%}) is set:
                                                set {_mindBlastLore} to "&8Basic Ability%nl%&f%{_chargesLore}%%nl%&f%1.5/{_pospiech}% second cast%nl%&7Recharge time:  &f%{_cd}%"
                                            else:
                                                set {_mindBlastLore} to "&8Basic Ability%nl%&f%{_chargesLore}%%nl%&f%1.5/{_pospiech}% second cast%nl%&7Cooldown:  &f%{_cd}%"
                                            set {_lore} to "%{_mindBlastLore}%%nl%&7Use: &fRMB%nl%<##613e82>Blasts the target's mind for &f%{_damage}%%nl%&f <##431d53>Ghost damage.%nl% %nl%&fGenerates %{_insanity}% Insanity."
                                            loop all items in the inventory of {_p}:
                                                if boolean tag "Mind Blast" of (custom nbt of loop-item) = true:
                                                    set lore of loop-item to {_lore}
                                                    if {_charges} > 0:
                                                        set item amount of loop-item to {_charges}
                                                    else:
                                                        set the cooldown of loop-item for {_p} to {_cd}
                                                    stop loop
                                            set {_target}'s last damage cause to sweep attack
                                            set metadata tag "Element" of {_p} to "Ghost"
                                            set metadata tag "LastDamageCause" of {_target} to "<##462566>Mind Blast"
                                            set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
                                            chance of {_crit}%:
                                                set {_damage} to {_damage}*2
                                                CritVisual({_target})
                                                set metadata tag "Crit%{_p}%" of {_target} to true
                                                if offensiveTrait({_p}, "Brother Therold", "Whispers of the Damned") > 0:
                                                    GrantInsanity({_p}, 20)
                                                    UpdateInsanity({_p})
                                            make {_p} damage {_target} by {_damage}*2

                                            if boolean tag "Constellation;Unleash the Shadows" of (custom nbt of {karta::%{_p}%}) is set:
                                                ShadowyApparitionSpawn({_p}, {_target})
                                else: 
                                    if {tekstcd::%{_p}%} = true:
                                        set {_cdd} to cooldown "Shadow Word: Death%{_p}%"
                                        send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                                    stop
                            else: 
                                if {tekstcd::%{_p}%} = true:
                                    set {_cdd} to cooldown "Shadow Word: Pain%{_p}%"
                                    send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                                stop
                        else:
                            if {tekstcd::%{_p}%} = true:
                                if cooldown "Mind Blast%{_p}%" is set:
                                    set {_cdd} to cooldown "Mind Blast%{_p}%"
                                    send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                                else:
                                    send "<##462566>You must wait for this ability to recharge to be able to use it again." to {_p}
                            stop
        else:
            send "&8[&6Earthcraft&8] &6You can not use Mind Blast when you have Shadow Word: Void talented." to {_p}
            play sound "block.glass.break" with volume 3 and pitch 0 to {_p}
    else:
        send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to {_p}
        play sound "block.glass.break" with volume 3 and pitch 0 to {_p}

function ShadowWordPainAbilityCast(p: player):
    if {kartaname::%{_p}%} = "Brother Therold":
        if CanUseAbility({_p}) != false:
            set {_target} to Target({_p}, 100, false)
            if {_target} is set:
                if cooldown "Shadow Word: Pain%{_p}%" is finished:
                    if cooldown "Shadow Word: Death%{_p}%" is finished:
                        if cooldown "Global Cooldown Interrupted Cast%{_p}%" is finished:
                            set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
                            set {_cd} to "%1.5/{_pospiech}% seconds" parsed as timespan
                            set the cooldown of {_p}'s held item for {_p} to {_cd}
                            create cooldown "Shadow Word: Pain%{_p}%" for {_cd}
                            AbilityUse({_p}, "Shadow Word: Pain")
                            if metadata tag "channeling" of {_p} is set:
                                clear metadata tag "channeling" of {_p}
                                StopCastSoundTherold({_p})
                            if metadata tag "casting" of {_p} is set:
                                clear metadata tag "cast" of {_p}
                                StopCastSoundTherold({_p})
                                send action bar "&cInterrupted" to {_p}
                            set metadata tag "lastspellTherold" of {_p} to (uncolored {_p}'s tool's name)
                            set {_crit} to CriticalHit({_p})
                            set {_damage} to (0.6 + (({damage::%{_p}%}/45) + ({versatility::%{_p}%}/135) + {primarystat::%{_p}%}/22.5)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
                            if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
                                set {_SWPDuration} to 18
                            else:
                                set {_SWPDuration} to 14
                            set {_damageSWPTicks} to (1 + (({damage::%{_p}%}/68) + ({versatility::%{_p}%}/204) + {primarystat::%{_p}%}/34)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
                            set {_totalTicks} to (round({_SWPDuration}/(2/{_pospiech}), 0))
                            if offensiveTrait({_p}, "Brother Therold", "Death Throes") > 0:
                                set {_deathThroes} to offensiveTrait({_p}, "Brother Therold", "Death Throes")
                                add {_deathThroes}/{_totalTicks} to {_damageSWPTicks}
                            if metadata tag "Voidform" of {_p} is set:
                                set {_damage} to {_damage}*1.2
                                set {_damageSWPTicks} to {_damageSWPTicks}*1.2
                            if boolean tag "Constellation;Mass Hysteria" of (custom nbt of {karta::%{_p}%}) is set:
                                set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                                set {_damage} to {_damage}*(1 + ({_voidformStacks}/100))
                                set {_damageSWPTicks} to {_damageSWPTicks}*(1 + ({_voidformStacks}/100))
                            set {_target}'s last damage cause to sweep attack
                            set {_lore} to "&8Basic Ability%nl%&fInstant cast%nl%&7Global Cooldown:  &f%{_cd}%%nl%&7Use: &fRMB%nl%<##613e82>A word of darkness that causes%nl%&f%{_damage}%  <##431d53>Ghost <##613e82>damage instantly, and%nl%<##613e82>an additional &f%(round({_SWPDuration}/(2/{_pospiech}), 0))*{_damageSWPTicks}%  <##431d53>Ghost <##613e82>damage%nl%<##613e82>over &f%{_SWPDuration}% sec<##613e82>.%nl% %nl%&fGenerates 3 Insanity."
                            set metadata tag "LastDamageCause" of {_target} to "<##462566>Shadow Word: Pain"
                            set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
                            set metadata tag "Element" of {_p} to "Ghost"
                            set {_damage} to Crit({_p}, {_target}, {_crit}, {_damage})
                            make {_p} damage {_target} by {_damage}*2
                            GrantInsanity({_p}, 3)
                            UpdateInsanity({_p})
                            play sound "skill.therold.shadow_word_pain" with volume 3 and pitch 1 at (location of {_p})
                            play sound "skill.therold.shadowcast" with volume 3 and pitch 1 at (location of {_p})
                            draw 10 of (((rgb(77, 54, 138) dust particle of size 1) with an extra value of 0.03) with offset vector(0.4, 0.5, 0.4)) at (location above {_target})
                            if metadata tag "Shadow Word: Pain-%{_p}%" of {_target} is not set:
                                set metadata tag "Shadow Word: Pain-%{_p}%" of {_target} to {_SWPDuration}
                                amountOfDotsSet({_p}, {_target})
                                ShadowWordPain({_p}, {_target})
                                ShadowWordPainExpire({_p}, {_target})
                            else:
                                ShadowWordPainRefresh({_p}, {_target})
                            set {_abilities::*} to "Mind Blast", "Shadow Word: Pain", "Vampiric Touch", "Mind Flay", "Void Eruption", "Void Bolt", "Shadow Word: Void", "Shadow Word: Death"
                            set {_abilitiesItems::*} to light gray dye, orange dye, gray dye, cyan dye, purple dye, black dye, light gray dye and yellow dye
                            GlobalCooldownSpells({_p}, {_abilities::*}, {_abilitiesItems::*}, {_cd})
                    else: 
                        if {tekstcd::%{_p}%} = true:
                            set {_cdd} to cooldown "Shadow Word: Death%{_p}%"
                            send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                        stop
                else: 
                    if {tekstcd::%{_p}%} = true:
                        set {_cdd} to cooldown "Shadow Word: Pain%{_p}%"
                        send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                    stop
    else:
        send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to {_p}
        play sound "block.glass.break" with volume 3 and pitch 0 to {_p}

function MindFlayAbilityCast(p: player):
    if {kartaname::%{_p}%} = "Brother Therold":
        if CanUseAbility({_p}) != false:
            set {_target} to Target({_p}, 100, false)
            if {_target} is set:
                if cooldown "Mind Flay%{_p}%" is finished:
                    if cooldown "Shadow Word: Pain%{_p}%" is finished:
                        if cooldown "Shadow Word: Death%{_p}%" is finished:
                            if cooldown "Global Cooldown Interrupted Cast%{_p}%" is finished:
                                if metadata tag "channeling" of {_p} is not set:
                                    set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
                                    #set {_casttime} to (3/{_pospiech})
                                    set {_casttime} to 3
                                    if metadata tag "cast" of {_p} is set:
                                        set {_maxCastTime} to seconds of metadata tag "casttimemax" of {_p}
                                        set {_currentCastTime} to seconds of metadata tag "casttimeleft" of {_p}
                                        if {_currentCastTime} > 0.4*{_maxCastTime}:
                                            clear metadata tag "cast" of {_p}
                                            clear metadata tag "casttimemax" of {_p}
                                            clear metadata tag "casttimeleft" of {_p}
                                            StopCastSoundTherold({_p})
                                            send action bar "&cInterrupted" to {_p}
                                        else:
                                            stop
                                        set {_pospiech} to (Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100))/1.5
                                        set {_cd} to 3/2/{_pospiech}
                                        set {_sec} to "%{_cd}% seconds" parsed as timespan
                                        create cooldown "Global Cooldown Interrupted Cast%{_p}%" for {_sec}
                                        set the cooldown of player's held item for {_p} to {_sec}
                                        set {_abilities::*} to "Mind Blast", "Shadow Word: Pain", "Vampiric Touch", "Mind Flay", "Void Eruption", "Void Bolt", "Shadow Word: Void", "Shadow Word: Death"
                                        set {_abilitiesItems::*} to light gray dye, orange dye, gray dye, cyan dye, purple dye, black dye, light gray dye and yellow dye
                                        GlobalCooldownSpells({_p}, {_abilities::*}, {_abilitiesItems::*}, {_cd})
                                    create cooldown "Mind Flay%{_p}%" for 1 tick
                                    set metadata tag "lastspellTherold" of {_p} to (uncolored {_p}'s tool's name)
                                    set metadata tag "channeling" of {_p} to true
                                    MindFlay({_p}, {_target}, {_casttime})
                                    AbilityUse({_p}, "Mind Flay")
                                    #set the cooldown of {_p}'s held item for {_p} to ("%{_casttime}% seconds" parsed as timespan)
                                    play sound "skill.therold.mindflay_channel" with volume 3 and pitch 1 at (location of {_p})
                                    play sound "skill.therold.mindflay_channel_whisper" with volume 3 and pitch 1 at (location of {_p})
                                    play sound "skill.therold.shadowcast" with volume 3 and pitch 1 at (location of {_p})
                        else: 
                            if {tekstcd::%{_p}%} = true:
                                set {_cdd} to cooldown "Shadow Word: Death%{_p}%"
                                send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                            stop
                    else: 
                        if {tekstcd::%{_p}%} = true:
                            set {_cdd} to cooldown "Shadow Word: Pain%{_p}%"
                            send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                        stop
                else:
                    if {tekstcd::%{_p}%} = true:
                        set {_cdd} to cooldown "Mind Flay%{_p}%"
                        send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                    stop
    else:
        send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to {_p}
        play sound "block.glass.break" with volume 3 and pitch 0 to {_p}

function VampiricTouchAbilityCast(p: player):
    if {kartaname::%{_p}%} = "Brother Therold":
        if CanUseAbility({_p}) != false:
            if metadata tag "casting" of {_p} is not set:
                set {_target} to Target({_p}, 100, false)
                if {_target} is set:
                    if cooldown "Vampiric Touch%{_p}%" is finished:
                        if cooldown "Shadow Word: Pain%{_p}%" is finished:
                            if cooldown "Shadow Word: Death%{_p}%" is finished:
                                if cooldown "Global Cooldown Interrupted Cast%{_p}%" is finished:
                                    set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
                                    set {_casttime} to "%round((1.5/{_pospiech}), 1)% seconds" parsed as timespan
                                    if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
                                        set {_VPTDuration} to 21
                                    else:
                                        set {_VPTDuration} to 18
                                    if metadata tag "cast" of {_p} is not set:
                                        set metadata tag "casttimemax" of {_p} to {_casttime}
                                        play sound "skill.therold.mindflay_channel_whisper" with volume 3 and pitch 1 at (location of {_p})
                                        set metadata tag "casting" of {_p} to true
                                        if metadata tag "channeling" of {_p} is set:
                                            clear metadata tag "channeling" of {_p}
                                            StopCastSoundTherold({_p})
                                        set metadata tag "lastspellTherold" of {_p} to uncolored {_p}'s tool's name
                                        set metadata tag "cast" of {_p} to {_casttime}
                                        while metadata tag "casting" of {_p} = true:
                                            set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                                            set {_insanityDrain} to 6 + 0.68*{_voidformStacks}
                                            set {_insanityInfo} to "Insanity: %round({insanity::%{_p}%}, 0)%"
                                            if metadata tag "Voidform" of {_p} is set:
                                                set {_insanityInfo} to "%{_insanityInfo}%   %round({_insanityDrain}, 1)%p/s    %{_voidformStacks}%"
                                            if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Lingering Insanity":
                                                if {lingeringInsanityHaste::%{_p}%} is set:
                                                    set {_insanityInfo} to "%{_insanityInfo}% |  %{lingeringInsanityHaste::%{_p}%}/4%%% "
                                            if metadata tag "cast" of {_p} is not set:
                                                clear metadata tag "casting" of {_p}
                                                stop sound "skill.therold.mindflay_channel_whisper" for (all players in radius 2 around {_p})
                                                stop
                                            if {_p} can not see {_target}:
                                                clear metadata tag "casting" of {_p}
                                                stop
                                            if {_casttime} > 0 seconds:
                                                set {_cst} to "%{_casttime}%"
                                                set metadata tag "casttimeleft" of {_p} to {_casttime}
                                                send action bar "Casting... %{_cst}% | %{_insanityInfo}%" to {_p}
                                                wait 0.1 seconds
                                                remove 0.1 seconds from {_casttime}
                                            else:
                                                clear metadata tag "casting" of {_p}
                                                send action bar "" to {_p}
                                    else:
                                        stop
                                    clear metadata tag "casting" of {_p}
                                    clear metadata tag "cast" of {_p}
                                    clear metadata tag "casttimeleft" of {_p}
                                    clear metadata tag "casttimemax" of {_p}
                                    stop sound "skill.therold.mindflay_channel_whisper" for (all players in radius 2 around {_p})
                                    if {_casttime} > 0 seconds:
                                        send action bar "&cInterrupted" to {_p}
                                        stop
                                    GrantInsanity({_p}, 6)
                                    UpdateInsanity({_p})
                                    AbilityUse({_p}, "Vampiric Touch")
                                    play sound "skill.therold.vampirictouch" with volume 3 and pitch 1 at (location of {_p})
                                    play sound "skill.therold.shadowcast" with volume 3 and pitch 1 at (location of {_p})
                                    draw 15 of (((rgb(44, 30, 77) dust particle of size 1) with an extra value of 0.05) with offset vector(0.5, 0.5, 0.5)) at ({_loc} ~ {_v})
                                    if (string tag "Talents;Row 5" of (custom nbt of {karta::%{_p}%})) = "Misery":
                                        ShadowWordPainAbilityCast({_p})
                                    if metadata tag "Vampiric Touch-%{_p}%" of {_target} is not set:
                                        set metadata tag "Vampiric Touch-%{_p}%" of {_target} to {_VPTDuration}
                                        amountOfDotsSet({_p}, {_target})
                                        VampiricTouch({_p}, {_target})
                                        VampiricTouchExpire({_p}, {_target})
                                    else:
                                        VampiricTouchRefresh({_p}, {_target})
                            else: 
                                if {tekstcd::%{_p}%} = true:
                                    set {_cdd} to cooldown "Shadow Word: Death%{_p}%"
                                    send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                                stop
                        else: 
                            if {tekstcd::%{_p}%} = true:
                                set {_cdd} to cooldown "Shadow Word: Pain%{_p}%"
                                send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                            stop
                    else:
                        if {tekstcd::%{_p}%} = true:
                            set {_cdd} to cooldown "Vampiric Touch%{_p}%"
                            send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                        stop
    else:
        send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to {_p}
        play sound "block.glass.break" with volume 3 and pitch 0 to {_p}

function ShadowWordVoidAbilityCast(p: player):
    if {kartaname::%{_p}%} = "Brother Therold":
        if (string tag "Talents;Row 1" of (custom nbt of {karta::%{_p}%})) = "Shadow Word: Void":
            if CanUseAbility({_p}) != false:
                if metadata tag "casting" of {_p} is not set:
                    set {_target} to Target({_p}, 100, false)
                    if {_target} is set:
                        if isCastableTherold({_p}) = true:
                            if cooldown "Shadow Word: Pain%{_p}%" is finished:
                                if cooldown "Shadow Word: Death%{_p}%" is finished:
                                    if cooldown "Global Cooldown Interrupted Cast%{_p}%" is finished:
                                        set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
                                        set {_casttime} to "%round((1.5/{_pospiech}), 1)% seconds" parsed as timespan
                                        set {_casttimeText} to {_casttime}
                                        set {_cd} to "%9/{_pospiech}% seconds" parsed as timespan
                                        if metadata tag "ShadowyInsight" of {_p} != true:
                                            if metadata tag "cast" of {_p} is not set:
                                                set metadata tag "casttimemax" of {_p} to {_casttime}
                                                play sound "skill.therold.shadow_word_void_precast" with volume 3 and pitch 1 at (location of {_p})
                                                set metadata tag "casting" of {_p} to true
                                                if metadata tag "channeling" of {_p} is set:
                                                    clear metadata tag "channeling" of {_p}
                                                    StopCastSoundTherold({_p})
                                                set metadata tag "lastspellTherold" of {_p} to uncolored {_p}'s tool's name
                                                set metadata tag "cast" of {_p} to {_casttime}
                                                while metadata tag "casting" of {_p} = true:
                                                    set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                                                    set {_insanityDrain} to 6 + 0.68*{_voidformStacks}
                                                    set {_insanityInfo} to "Insanity: %round({insanity::%{_p}%}, 0)%"
                                                    if metadata tag "Voidform" of {_p} is set:
                                                        set {_insanityInfo} to "%{_insanityInfo}%   %round({_insanityDrain}, 1)%p/s    %{_voidformStacks}%"
                                                    if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Lingering Insanity":
                                                        if {lingeringInsanityHaste::%{_p}%} is set:
                                                            set {_insanityInfo} to "%{_insanityInfo}% |  %{lingeringInsanityHaste::%{_p}%}/4%%% "
                                                    if metadata tag "cast" of {_p} is not set:
                                                        clear metadata tag "casting" of {_p}
                                                        stop sound "skill.therold.mindblast_precast" for (all players in radius 2 around {_p})
                                                        stop
                                                    if {_p} can not see {_target}:
                                                        clear metadata tag "casting" of {_p}
                                                        stop
                                                    if {_casttime} > 0 seconds:
                                                        set metadata tag "casttimeleft" of {_p} to {_casttime}
                                                        set {_cst} to "%{_casttime}%"
                                                        send action bar "Casting... %{_cst}% | %{_insanityInfo}%" to {_p}
                                                        wait 0.1 seconds
                                                        remove 0.1 seconds from {_casttime}
                                                    else:
                                                        clear metadata tag "casting" of {_p}
                                                        send action bar "" to {_p}
                                            else:
                                                stop
                                            clear metadata tag "casting" of {_p}
                                            clear metadata tag "cast" of {_p}
                                            clear metadata tag "casttimeleft" of {_p}
                                            clear metadata tag "casttimemax" of {_p}
                                            stop sound "skill.therold.shadow_word_void_precast" for (all players in radius 2 around {_p})
                                            if {_casttime} > 0 seconds:
                                                send action bar "&cInterrupted" to {_p}
                                                stop
                                            set {_charges} to metadata tag "ShadowWordVoidCharges" of {_p}
                                            remove 1 from {_charges}
                                            set metadata tag "ShadowWordVoidCharges" of {_p} to {_charges}
                                            ShadowWordVoidRecharge({_p}, {_cd})
                                        else:
                                            clear metadata tag "ShadowyInsight" of {_p}
                                            set {_charges} to metadata tag "ShadowWordVoidCharges" of {_p}
                                            send title " " with subtitle " " to {_p} for 1 second with fade in 0.0 second and fade out 0.0 second
                                        AbilityUse({_p}, "Shadow Word: Void")
                                        set {_insanity} to 15
                                        if (string tag "Talents;Row 1" of (custom nbt of {karta::%{_p}%})) = "Fortress of the Mind":
                                            set {_insanity} to {_insanity}*1.2
                                        GrantInsanity({_p}, {_insanity})
                                        UpdateInsanity({_p})
                                        play sound "skill.therold.shadow_word_void_cast" with volume 3 and pitch 1 at (location of {_p})
                                        play sound "skill.therold.shadow_word_void_impact" with volume 3 and pitch 1 at (location of {_p})
                                        play sound "skill.therold.shadowcast" with volume 3 and pitch 1 at (location of {_p})
                                        draw 24 of (((rgb(95, 72, 156) dust particle of size 1) with an extra value of 0.04) with offset vector(0.42, 0.5, 0.42)) at ({_target}'s head)
                                        draw 24 of (((rgb(41, 22, 92) dust particle of size 1) with an extra value of 0.04) with offset vector(0.37, 0.45, 0.37)) at ({_target}'s head)
                                        if {_target} is alive:
                                            set {_crit} to CriticalHit({_p})
                                            set {_damage} to (5 + (({damage::%{_p}%}/22) + ({versatility::%{_p}%}/66)) + ({primarystat::%{_p}%}/11)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
                                            add offensiveTrait({_p}, "Brother Therold", "Whispers of the Damned") to {_damage}
                                            if metadata tag "Voidform" of {_p} is set:
                                                set {_damage} to {_damage}*1.2
                                            if (string tag "Talents;Row 1" of (custom nbt of {karta::%{_p}%})) = "Fortress of the Mind":
                                                set {_damage} to {_damage}*1.1
                                            if boolean tag "Constellation;Mass Hysteria" of (custom nbt of {karta::%{_p}%}) is set:
                                                set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                                                set {_damage} to {_damage}*(1 + ({_voidformStacks}/100))
                                            if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
                                                if metadata tag "Vampiric Touch-%{_p}%" of {_target} is set:
                                                    if metadata tag "Shadow Word: Pain-%{_p}%" of {_target} is set:
                                                        set {_damage} to {_damage}*1.55
                                            if {_charges} = 1:
                                                set {_chargesLore} to "%{_charges}% Charge"
                                            else:
                                                set {_chargesLore} to "%{_charges}% Charges"
                                            set {_shadowWordVoidLore} to "&8Basic Ability%nl%&f%{_chargesLore}%%nl%&f%1.5/{_pospiech}% second cast%nl%&7Recharge time:  &f%{_cd}%"
                                            set {_lore} to "%{_shadowWordVoidLore}%%nl%&7Use: &fRMB%nl%<##613e82>Blasts the target's mind for &f%{_damage}%%nl%&f <##431d53>Ghost <##613e82>damage.%nl% %nl%&fGenerates %{_insanity}% Insanity."
                                            loop all items in the inventory of {_p}:
                                                if boolean tag "Shadow Word: Void" of (custom nbt of (1 of loop-item)) = true:
                                                    set lore of loop-item to {_lore}
                                                    if {_charges} > 0:
                                                        set item amount of loop-item to {_charges}
                                                        create cooldown "Shadow Word: Void%{_p}%" for {_cd}
                                                    else:
                                                        set the cooldown of loop-item for {_p} to {_cd}
                                                    stop loop
                                            set {_target}'s last damage cause to sweep attack
                                            set metadata tag "Element" of {_p} to "Ghost"
                                            set metadata tag "LastDamageCause" of {_target} to "<##462566>Shadow Word: Void"
                                            set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
                                            chance of {_crit}%:
                                                set {_damage} to {_damage}*2
                                                CritVisual({_target})
                                                set metadata tag "Crit%{_p}%" of {_target} to true
                                                if offensiveTrait({_p}, "Brother Therold", "Whispers of the Damned") > 0:
                                                    GrantInsanity({_p}, 20)
                                                    UpdateInsanity({_p})
                                            make {_p} damage {_target} by {_damage}*2

                                            if boolean tag "Constellation;Unleash the Shadows" of (custom nbt of {karta::%{_p}%}) is set:
                                                ShadowyApparitionSpawn({_p}, {_target})
                                else: 
                                    if {tekstcd::%{_p}%} = true:
                                        set {_cdd} to cooldown "Shadow Word: Death%{_p}%"
                                        send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                                    stop
                            else: 
                                if {tekstcd::%{_p}%} = true:
                                    set {_cdd} to cooldown "Shadow Word: Pain%{_p}%"
                                    send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                                stop
                        else:
                            if {tekstcd::%{_p}%} = true:
                                send "<##462566>You must wait for this ability to recharge to be able to use it again." to {_p}
                            stop
        else:
            send "&8[&6Earthcraft&8] &6You don't have the required talent to use this ability." to {_p}
            play sound "block.glass.break" with volume 3 and pitch 0 to {_p}
    else:
        send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to {_p}
        play sound "block.glass.break" with volume 3 and pitch 0 to {_p}

function ShadowWordDeathAbilityCast(p: player):
    if {kartaname::%{_p}%} = "Brother Therold":
        if CanUseAbility({_p}) != false:
            set {_target} to Target({_p}, 100, false)
            if {_target} is set:
                if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Reaper of Souls":
                    set {_hpRequired} to 0.35
                else:
                    set {_hpRequired} to 0.2
                if {_hpRequired}*({_target}'s max health) >= {_target}'s health:
                    if metadata tag "ShadowWordDeathCharges" of {_p} > 0:
                        if cooldown "Shadow Word: Pain%{_p}%" is finished:
                            if cooldown "Shadow Word: Death%{_p}%" is finished:
                                if cooldown "Global Cooldown Interrupted Cast%{_p}%" is finished:
                                    set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
                                    set {_globalcd} to "%1.5/{_pospiech}% seconds" parsed as timespan
                                    set {_cd} to "%9/{_pospiech}% seconds" parsed as timespan
                                    set the cooldown of {_p}'s held item for {_p} to {_globalcd}
                                    create cooldown "Shadow Word: Death%{_p}%" for {_globalcd}
                                    AbilityUse({_p}, "Shadow Word: Death")
                                    if metadata tag "channeling" of {_p} is set:
                                        clear metadata tag "channeling" of {_p}
                                        StopCastSoundTherold({_p})
                                    if metadata tag "casting" of {_p} is set:
                                        clear metadata tag "cast" of {_p}
                                        StopCastSoundTherold({_p})
                                        send action bar "&cInterrupted" to {_p}
                                    set metadata tag "lastspellTherold" of {_p} to uncolored {_p}'s tool's name
                                    set {_charges} to metadata tag "ShadowWordDeathCharges" of {_p}
                                    remove 1 from {_charges}
                                    set metadata tag "ShadowWordDeathCharges" of {_p} to {_charges}
                                    ShadowWordDeathRecharge({_p}, {_cd})
                                    set {_crit} to CriticalHit({_p})
                                    set {_damage} to (6 + (({primarystat::%{_p}%}/7.5) + ({damage::%{_p}%}/15) + ({versatility::%{_p}%}/22.5)))
                                    if metadata tag "Voidform" of {_p} is set:
                                        set {_damage} to {_damage}*1.2
                                    if boolean tag "Constellation;Mass Hysteria" of (custom nbt of {karta::%{_p}%}) is set:
                                        set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                                        set {_damage} to {_damage}*(1 + ({_voidformStacks}/100))
                                    set {_target}'s last damage cause to sweep attack
                                    if {_charges} = 1:
                                        set {_chargesLore} to "%{_charges}% Charge"
                                    else:
                                        set {_chargesLore} to "%{_charges}% Charges"
                                    set {_lore} to "&8Basic Ability%nl%&f%{_chargesLore}%%nl%&fInstant Cast%nl%&7Global Cooldown:  &f%{_globalcd}%%nl%&7Recharge Time:  &f%{_cd}%%nl%&7Use: &fRMB%nl%<##613e82>A word of dark binding that inflicts%nl%&f%{_damage}%  <##431d53>Ghost <##613e82>damage to the target. Only%nl%<##613e82>usable on enemies that have less%nl%<##613e82>than &f%{_hpRequired}*100%%% <##8165a6>health<##613e82>.%nl% %nl%&fGenerates 15 Insanity, or 30 Insanity%nl%&fif the target dies."
                                    loop all items in the inventory of {_p}:
                                        if boolean tag "Shadow Word: Death" of (custom nbt of loop-item) = true:
                                            set lore of loop-item to {_lore}
                                            if {_charges} > 0:
                                                set item amount of loop-item to {_charges}
                                            else:
                                                set the cooldown of loop-item for {_p} to {_cd}
                                            stop loop
                                    set metadata tag "LastDamageCause" of {_target} to "<##462566>Shadow Word: Death"
                                    set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
                                    set metadata tag "Element" of {_p} to "Ghost"
                                    set {_damage} to Crit({_p}, {_target}, {_crit}, {_damage})
                                    make {_p} damage {_target} by {_damage}*2
                                    play sound "skill.therold.shadow_word_death" with volume 3 and pitch 1 at (location of {_p})
                                    play sound "skill.therold.shadow_word_death_cast" with volume 3 and pitch 1 at (location of {_p})
                                    play sound "skill.therold.shadow_word_death_impact" with volume 3 and pitch 1 at (location of {_p})
                                    play sound "skill.therold.shadowcast" with volume 3 and pitch 1 at (location of {_p})
                                    draw 10 of (((rgb(77, 54, 138) dust particle of size 1) with an extra value of 0.03) with offset vector(0.4, 0.5, 0.4)) at (location above {_target})
                                    if {_charges} > 0:
                                        set {_abilities::*} to "Mind Blast", "Shadow Word: Pain", "Vampiric Touch", "Mind Flay", "Void Eruption", "Void Bolt", "Shadow Word: Void", "Shadow Word: Death"
                                        set {_abilitiesItems::*} to light gray dye, orange dye, gray dye, cyan dye, purple dye, black dye, light gray dye and yellow dye
                                    else:
                                        set {_abilities::*} to "Mind Blast", "Shadow Word: Pain", "Vampiric Touch", "Mind Flay", "Void Eruption", "Void Bolt", "Shadow Word: Void"
                                        set {_abilitiesItems::*} to light gray dye, orange dye, gray dye, cyan dye, purple dye, black dye, light gray dye
                                    GlobalCooldownSpells({_p}, {_abilities::*}, {_abilitiesItems::*}, {_globalcd})
                            else: 
                                if {tekstcd::%{_p}%} = true:
                                    set {_cdd} to cooldown "Shadow Word: Death%{_p}%"
                                    send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                                stop
                        else: 
                            if {tekstcd::%{_p}%} = true:
                                set {_cdd} to cooldown "Shadow Word: Pain%{_p}%"
                                send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                            stop
                    else:
                        if {tekstcd::%{_p}%} = true:
                            send "<##462566>You must wait for this ability to recharge to be able to use it again." to {_p}
                        stop
                else:
                    if {tekstcd::%{_p}%} = true:
                        send "<##462566>Target's health must be &f<%{_hpRequired}%%% <##462566>to use this ability." to {_p}
                        play sound "block.glass.break" with volume 2 and pitch 0 to {_p}
                    stop
    else:
        send "&8[&6Earthcraft&8] &6You don't have the required card selected to use this ability." to {_p}
        play sound "block.glass.break" with volume 3 and pitch 0 to {_p}

function SurrenderToMadnessAbilityCast(p: player):
    if {kartaname::%{_p}%} = "Brother Therold":
        if CanUseAbility({_p}) != false:
            set {_target} to Target({_p}, 100, false)
            if {_target} is set:
                if metadata tag "Voidform" of {_p} is set:
                    if cooldown "Shadow Word: Pain%{_p}%" is finished:
                        if cooldown "Surrender To Madness%{_p}%" is finished:
                            if cooldown "Shadow Word: Death%{_p}%" is finished:
                                if cooldown "Global Cooldown Interrupted Cast%{_p}%" is finished:
                                    set {_cd} to 10 minutes
                                    set the cooldown of {_p}'s held item for {_p} to {_cd}
                                    create cooldown "Surrender To Madness%{_p}%" for {_cd}
                                    AbilityUse({_p}, "Surrender to Madness")
                                    set metadata tag "SurrenderToMadness" of {_p} to true
                                    play sound "skill.therold.void_eruption_cast" with volume 3 and pitch 1 at (location of {_p})
                                    play sound "skill.therold.surrender_to_madness" with volume 3 and pitch 1 at (location of {_p})
                                    play sound "entity.wither.spawn" with volume 3 and pitch 0 at {_p}
                            else: 
                                if {tekstcd::%{_p}%} = true:
                                    set {_cdd} to cooldown "Shadow Word: Death%{_p}%"
                                    send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                                stop
                        else: 
                            if {tekstcd::%{_p}%} = true:
                                set {_cdd} to cooldown "Shadow Word: Pain%{_p}%"
                                send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                            stop
                    else: 
                        if {tekstcd::%{_p}%} = true:
                            set {_cdd} to cooldown "Surrender To Madness%{_p}%"
                            send "<##462566>You must wait &f%{_cdd}%<##462566> to use this ability." to {_p}
                        stop
                else:
                    if {tekstcd::%{_p}%} = true:
                        set {_cdd} to cooldown "Surrender To Madness%{_p}%"
                        send "<##462566>You must be in <##8165a6>Voidform <##462566>to use this ability." to {_p}
                    stop

on right click:
    if boolean tag "Void Eruption" of ((custom nbt of player's tool)) = true:
        cancel event
        VoidEruptionAbilityCast(player)
    else if boolean tag "Void Bolt" of ((custom nbt of player's tool)) = true:
        cancel event
        VoidBoltAbilityCast(player)
    else if boolean tag "Shadow Word: Pain" of ((custom nbt of player's tool)) = true:
        cancel event
        ShadowWordPainAbilityCast(player)
    else if boolean tag "Mind Flay" of ((custom nbt of player's tool)) = true:
        cancel event
        MindFlayAbilityCast(player)
    else if boolean tag "Mind Blast" of (custom nbt of 1 of player's tool) = true:
        cancel event
        MindBlastAbilityCast(player)
        if metadata tag "MindBlastCharges" of player is not set:
            if boolean tag "Constellation;Thought Harvester" of (custom nbt of {karta::%player%}) is set:
                set metadata tag "MindBlastCharges" of player to 2
            else:
                set metadata tag "MindBlastCharges" of player to 1
    else if boolean tag "Vampiric Touch" of ((custom nbt of player's tool)) = true:
        cancel event
        VampiricTouchAbilityCast(player)
    else if boolean tag "Shadow Word: Void" of (custom nbt of 1 of player's tool) = true:
        cancel event
        ShadowWordVoidAbilityCast(player)
        if metadata tag "ShadowWordVoidCharges" of player is not set:
            if boolean tag "Constellation;Thought Harvester" of (custom nbt of {karta::%player%}) is set:
                set metadata tag "ShadowWordVoidCharges" of player to 3
            else:
                set metadata tag "ShadowWordVoidCharges" of player to 2
    else if boolean tag "Shadow Word: Death" of (custom nbt of 1 of player's tool) = true:
        cancel event
        ShadowWordDeathAbilityCast(player)
        if metadata tag "ShadowWordDeathCharges" of player is not set:
            set metadata tag "ShadowWordDeathCharges" of player to 2
    else if boolean tag "Surrender to Madness" of ((custom nbt of player's tool)) = true:
        cancel event
        SurrenderToMadnessAbilityCast(player)

function ExitVoidform(p: player):
    clear metadata tag "Voidform" of {_p}
    set gravity attribute of {_p} to 0.08
    buffClear({_p}, "Voidform")
    if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Lingering Insanity":
        set {lingeringInsanityHaste::%{_p}%} to (metadata tag "Voidform Stacks" of {_p})*4
        set {hasteVoidform::%{_p}%} to (metadata tag "Voidform Stacks" of {_p})*4
        if metadata tag "LingeringInsanity" of {_p} is not set:
            set metadata tag "LingeringInsanity" of {_p} to true
            LingeringInsanity({_p})
    else:
        clear {hasteVoidform::%{_p}%}
    send "&fYou exit  Voidform with %metadata tag "Voidform Stacks" of {_p}% stacks." to {_p}
    chorusOfInsanity({_p}, metadata tag "Voidform Stacks" of {_p})
    clear metadata tag "Voidform Stacks" of {_p}
    set {_pospiech} to Haste({_p})
    set {_baseCasttime} to 2
    if (string tag "Talents;Row 5" of (custom nbt of {karta::%{_p}%})) = "Legacy of the Void":
        set {_baseCasttime} to {_baseCasttime}*0.6 
    set {_casttime} to "%round(({_baseCasttime}/{_pospiech}), 1)% seconds" parsed as timespan
    set {_damage} to (4 + (({damage::%{_p}%}/10) + ({versatility::%{_p}%}/30) + {primarystat::%{_p}%}/5)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
    if (string tag "Talents;Row 5" of (custom nbt of {karta::%{_p}%})) = "Legacy of the Void":
        set {_requiredInsanity} to 60
    else:
        set {_requiredInsanity} to 90
    loop all items in the inventory of {_p}:
        if boolean tag "Void Bolt" of (custom nbt of loop-item) = true:
            set {_voidEruption} to (purple dye named "<##613e82>Void Eruption") with lore "&8Ultimate Ability%nl%&f%{_casttime}% cast%nl%&7No cooldown%nl%&7Use: &fRMB%nl%<##613e82>Releases an explosive blast of pure void%nl%<##613e82>energy, activating &f <##8165a6>Voidform <##613e82>and causing%nl%&f%{_damage}%  <##431d53>Ghost <##613e82>damage to all enemies afflicted by%nl%<##613e82>your &f <##8165a6>Shadow Word: Pain <##613e82>or &f <##8165a6>Vampiric Touch.%nl% %nl%<##613e82>During &f <##8165a6>Voidform<##613e82>, this ability is replaced%nl%<##613e82>by &f <##8165a6>Void Bolt<##613e82>.%nl% %nl%&fRequires %{_requiredInsanity}% Insanity to activate."
            add nbt from "{""minecraft:custom_model_data"":{floats:[9.0f]},""minecraft:custom_data"":{""Void Eruption"":1b}}" to nbt of {_voidEruption}
            set loop-item to {_voidEruption}
    if metadata tag "SurrenderToMadness" of {_p} = true:
        clear metadata tag "SurrenderToMadness" of {_p}
        set {_lore} to "&8Ultimate Ability%nl%&fInstant cast%nl%&7Cooldown: &8 &f10 minutes%nl%&7Use: &fRMB%nl%<##613e82>Surrender your soul to the <##8165a6>Old Gods<##613e82>, sacrificing%nl%<##613e82>your soul for <##8165a6>ultimate power<##613e82>.%nl% %nl%<##613e82>All your &f <##8165a6>Insanity-generating <##613e82>abilities generate%nl%&f200%% <##613e82>more &f <##8165a6>Insanity <##613e82>until you exit &f <##8165a6>Voidform<##613e82>.%nl% %nl%<##613e82>Then you die. Horribly."
        set {_p}'s last damage cause to sweep attack
        set metadata tag "Element" of {_p} to "Ghost"
        set metadata tag "LastDamageCause" of {_p} to "<##462566>Surrender to Madness"
        set metadata tag "LastDamageCauseLore" of {_p} to {_lore}
        set metadata tag "IgnoreModifiers" of {_p} to true
        make {_p} damage {_p} by ({_p}'s max health*2)
        send " %{_p}% fell to madness." to all players
        #send " %{_p}% poddał się szaleństwu." to loop-player


function GrantInsanity(p: player, num: number):
    if metadata tag "SurrenderToMadness" of {_p} is true:
        set {_num} to {_num}*3
    set {insanity::%{_p}%} to {insanity::%{_p}%} + {_num}
    if {insanity::%{_p}%} > 100:
        set {insanity::%{_p}%} to 100
    Mania({_p})

function UpdateInsanity(p: player):
    set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
    set {_insanityDrain} to 6 + 0.68*{_voidformStacks}
    set {_insanityText} to "Insanity: %round({insanity::%{_p}%}, 0)%"
    if metadata tag "Voidform" of {_p} is set:
        set {_insanityText} to "%{_insanityText}%   %round({_insanityDrain}, 1)%p/s    %{_voidformStacks}%"
    if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Lingering Insanity":
        if {lingeringInsanityHaste::%{_p}%} is set:
            set {_insanityText} to "%{_insanityText}%   |  %{lingeringInsanityHaste::%{_p}%}/4%%% "
    send action bar {_insanityText} to {_p}

function VoidEruptionVisual(p: player, target: entity):
    set {_offX} to a random number between -4 and 4
    set {_offY} to a random number between -0.6 and 2
    set {_offZ} to a random number between -4 and 4
    set {_vec} to vector {_offX}, {_offY}, {_offZ}
    set {_loc} to location of {_p}'s head offset by {_vec}
    set {_v} to vector between {_loc} and {_target}'s head
    loop round(distance between {_loc} and {_target}) / 0.4 times:
        set {_v} to vector between {_loc} and {_target}'s head
        set vector length of {_v} to loop-value-2 * 0.4
        draw 1 of (rgb(70, 56, 107) dust particle of size 1) with offset (random vector) at ({_loc} ~ {_v})
        wait 1 tick

function ShadowWordPain(p: player, target: entity):
    while metadata tag "Shadow Word: Pain-%{_p}%" of {_target} is set:
        if {_target} is alive:
            set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
            set {_crit} to CriticalHit({_p})
            if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
                set {_SWPDuration} to 18
            else:
                set {_SWPDuration} to 14
            set {_damage} to (1 + (({damage::%{_p}%}/68) + ({versatility::%{_p}%}/204) + {primarystat::%{_p}%}/34)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
            set {_totalTicks} to (round({_SWPDuration}/(2/{_pospiech}), 0))
            if offensiveTrait({_p}, "Brother Therold", "Death Throes") > 0:
                set {_deathThroes} to offensiveTrait({_p}, "Brother Therold", "Death Throes")
                add {_deathThroes}/{_totalTicks} to {_damage}
            if metadata tag "Voidform" of {_p} is set:
                set {_damage} to {_damage}*1.2
            if boolean tag "Constellation;Mass Hysteria" of (custom nbt of {karta::%{_p}%}) is set:
                set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                set {_damage} to {_damage}*(1 + ({_voidformStacks}/100))
            loop all items in the inventory of {_p}:
                if boolean tag "Shadow Word: Pain" of (custom nbt of loop-item) = true:
                    set {_instantDamage} to (0.6 + ({damage::%{_p}%}/45) + ({versatility::%{_p}%}/135) + ({primarystat::%{_p}%}/22.5)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
                    if metadata tag "Voidform" of {_p} is set:
                        set {_instantDamage} to {_instantDamage}*1.2
                    set {_gcd} to "%1.5/{_pospiech}% seconds" parsed as timespan
                    set {_lore} to "&8Basic Ability%nl%&fInstant cast%nl%&7Global Cooldown:  &f%{_gcd}%%nl%&7Use: &fRMB%nl%<##613e82>A word of darkness that causes%nl%&f%{_instantDamage}%  <##431d53>Ghost <##613e82>damage instantly, and%nl%<##613e82>an additional &f%(round({_SWPDuration}/(2/{_pospiech}), 0))*{_damage}%  <##431d53>Ghost <##613e82>damage%nl%<##613e82>over &f%{_SWPDuration}% sec<##613e82>.%nl% %nl%&fGenerates 3 Insanity."
                    set lore of loop-item to {_lore}
                else if boolean tag "Shadowy Apparitions" of (custom nbt of loop-item) = true:
                    set {_shadowyApparitionsDamage} to (0.8 + (({damage::%{_p}%}/65.5) + ({versatility::%{_p}%}/196.5) + {primarystat::%{_p}%}/32.75))
                    if boolean tag "Constellation;Haunting Apparitions" of (custom nbt of {karta::%{_p}%}) is set:
                        set {_shadowyApparitionsDamage} to {_shadowyApparitionsDamage} * (1.096 + (({mastery::%{_p}%}/6.25)/100))
                    if (string tag "Talents;Row 4" of (custom nbt of {karta::%{_p}%})) = "Auspicious Spirits":
                        set {_shadowyApparitionsDamage} to {_shadowyApparitionsDamage}*2
                    if metadata tag "Voidform" of {_p} is set:
                        set {_shadowyApparitionsDamage} to {_shadowyApparitionsDamage}*1.2
                    set lore of loop-item to "&8Passive Ability%nl%&fNo cast%nl%&7Cooldown: &8 &fnone%nl%&7Use: &fPASSIVE%nl%<##613e82>When your &f <##8165a6>Shadow Word: Pain <##613e82>damage%nl%<##613e82>over time <##8165a6> Critically Strikes<##613e82>, you also create%nl%<##613e82>a shadowy version of yourself that floats%nl%<##613e82>towards the target and deals &f%{_shadowyApparitionsDamage}%  <##431d53>Ghost%nl%<##613e82>damage."
            set {_target}'s last damage cause to sweep attack
            chance of {_crit}%:
                set {_damage} to {_damage}*2
                CritVisual({_target})
                set metadata tag "Crit%{_p}%" of {_target} to true
                ShadowyApparitionSpawn({_p}, {_target})
            set metadata tag "Element" of {_p} to "Ghost"
            set metadata tag "LastDamageCause" of {_target} to "<##462566>Shadow Word: Pain"
            set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
            make {_p} damage {_target} by {_damage}*2
            if (string tag "Talents;Row 4" of (custom nbt of {karta::%{_p}%})) = "Shadowy Insight":
                chance of 4%:
                    ShadowyInsight({_p})
            set {_tickTime} to "%2/{_pospiech}% seconds" parsed as timespan
            wait {_tickTime}
        else:
            clear metadata tag "Shadow Word: Pain-%{_p}%" of {_target}
            stop loop
function ShadowWordPainExpire(p: player, target: entity):
    if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
        set {_duration} to 18
    else:
        set {_duration} to 14
    set {_height} to amountOfDots({_p}, {_target})
    set {_dots} to metadata tag "AmountOfDots%{_p}%" of {_target}
    while {_duration} > 0:
        if {_target} is alive:
            set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
            set {_tickTime} to "1 seconds" parsed as timespan
            if metadata tag "AmountOfDots%{_p}%" of {_target} < {_dots}:
                set {_height} to amountOfDots({_p}, {_target})
            dotsText(" %{_duration}%", {_p}, {_target}, (location {_height} above {_target}'s head), 0 seconds, {_tickTime})
            wait 1 second
            remove 1 from {_duration}
            if metadata tag "Shadow Word: Pain - Refresh-%{_p}%" of {_target} is set:
                if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
                    set {_duration} to 18
                else:
                    set {_duration} to 14
                clear metadata tag "Shadow Word: Pain - Refresh-%{_p}%" of {_target}
        else:
            if offensiveTrait({_p}, "Brother Therold", "Death Throes") > 0:
                GrantInsanity({_p}, 5)
                UpdateInsanity({_p})
            stop loop
    clear metadata tag "Shadow Word: Pain-%{_p}%" of {_target}
    amountOfDotsSubtract({_p}, {_target})

function ShadowWordPainRefresh(p: player, target: entity):
    if {_target} is alive:
        if metadata tag "Shadow Word: Pain-%{_p}%" of {_target} is set:
            set metadata tag "Shadow Word: Pain - Refresh-%{_p}%" of {_target} to true

function MindFlayVisual(p: player, target: entity):
    set {_l} to location 0.5 blocks below {_p}'s head
    set {_vec} to vector between {_p} and {_target}'s head
    loop round(distance between {_l} and {_target}) / 0.5 times:
        set {_vec} to vector between {_l} and {_target}'s head
        set vector length of {_vec} to loop-value * 0.5
        draw 1 of (rgb(78, 68, 102) dust particle of size 1) at ({_l} ~ {_vec})

function MindFlay(p: player, target: entity, cast: number):
    while metadata tag "channeling" of {_p} is set:
        set {_pospiech} to (Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100))/1.5 #Scale with haste 0.67x as effectively
        set {_crit} to CriticalHit({_p})
        set {_casttime} to ({_cast}/4)/{_pospiech}
        set {_tickTime} to "%{_casttime}% seconds" parsed as timespan
        set metadata tag "channeltime" of {_p} to {_cast}
        if {_target} is alive:
            set {_damage} to (0.6 + (({damage::%{_p}%}/120) + ({versatility::%{_p}%}/360) + {primarystat::%{_p}%}/60)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
            if metadata tag "VoidRayStacks" of {_p} is set:
                set {_voidRayStacksDamageBonus} to 1 + (0.1*metadata tag "VoidRayStacks" of {_p})
                set {_damage} to {_damage}*{_voidRayStacksDamageBonus}
            if metadata tag "TouchOfDarkness" of {_p} is set:
                set {_damage} to {_damage}*1.5
                add 1 to metadata tag "TouchOfDarknessTicks" of {_p}
                set {_fullCast} to round(({_cast}/{_casttime}), 0)
                if metadata tag "TouchOfDarknessTicks" of {_p} = {_fullCast}:
                    clear metadata tag "TouchOfDarkness" of {_p}
                    clear metadata tag "TouchOfDarknessTicks" of {_p}
                    buffClear({_p}, "Touch")
            if boolean tag "Constellation;Mass Hysteria" of (custom nbt of {karta::%{_p}%}) is set:
                set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                set {_damage} to {_damage}*(1 + ({_voidformStacks}/100))
            set {_insanity} to 2
            if metadata tag "Voidform" of {_p} is set:
                set {_damage} to {_damage}*1.2
            if (string tag "Talents;Row 1" of (custom nbt of {karta::%{_p}%})) = "Fortress of the Mind":
                set {_damage} to {_damage}*1.1
                set {_insanity} to {_insanity}*1.2
            GrantInsanity({_p}, {_insanity})
            chance of 4.5%:
                if offensiveTrait({_p}, "Brother Therold", "Sinister Thoughts") > 0:
                    sinisterThoughts({_p})
            set {_lore} to "&8Basic Ability%nl%&fChanneled%nl%&7No cooldown%nl%&7Use: &fRMB%nl%<##613e82>Assaults the target's mind with shadow%nl%<##613e82>energy, causing &f%{_damage}*(rounded up 3/(({_cast}/4)/{_pospiech}))%  <##431d53>Ghost <##613e82>damage over%nl%&f%{_cast}% sec <##613e82>and <##8165a6>slowing <##613e82>their movement speed%nl%<##613e82>by &f50%%<##613e82>.%nl% %nl%&fGenerates %2*(rounded up 3/(({_cast}/4)/{_pospiech}))% Insanity over the duration."
            loop all items in the inventory of {_p}:
                if boolean tag "Mind Flay" of (custom nbt of loop-item) = true:
                    set lore of loop-item to {_lore}
                    stop loop
            set {_target}'s last damage cause to sweep attack
            set metadata tag "Element" of {_p} to "Ghost"
            set metadata tag "LastDamageCause" of {_target} to "<##462566>Mind Flay"
            set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
            set {_damage} to Crit({_p}, {_target}, {_crit}, {_damage})
            make {_p} damage {_target} by {_damage}*2
            if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Void Ray":
                if metadata tag "VoidRayStacks" of {_p} is not set:
                    set metadata tag "VoidRayDuration" of {_p} to 6 seconds
                    set metadata tag "VoidRayStacks" of {_p} to 1
                    VoidRay({_p})
                else:
                    set metadata tag "VoidRayDuration" of {_p} to 6 seconds
                    if 4 > metadata tag "VoidRayStacks" of {_p}:
                        set {_voidRayStacks} to metadata tag "VoidRayStacks" of {_p}
                        add 1 to {_voidRayStacks}
                        set metadata tag "VoidRayStacks" of {_p} to {_voidRayStacks}
                set {_voidRayStacks} to "%metadata tag "VoidRayStacks" of {_p}%"
                set {_voidRayDuration} to "%metadata tag "VoidRayDuration" of {_p}%"
                buffRegister({_p}, "Void Ray", 1, "", "Stacks", {_voidRayStacks}, durationShort({_voidRayDuration}))
            if canBeCCed({_target}) = true:
                apply an ambient potion effect of slowness of tier 3.34 to {_target} for {_tickTime}:
                    hide the particles
        set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
        set {_insanityDrain} to 6 + 0.68*{_voidformStacks}
        set {_insanityInfo} to "Insanity: %round({insanity::%{_p}%}, 0)%"
        if metadata tag "Voidform" of {_p} is set:
            set {_insanityInfo} to "%{_insanityInfo}%   %round({_insanityDrain}, 1)%p/s    %{_voidformStacks}%"
        if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Lingering Insanity":
            if {lingeringInsanityHaste::%{_p}%} is set:
                set {_insanityInfo} to "%{_insanityInfo}% |  %{lingeringInsanityHaste::%{_p}%}/4%%% "
        if {_castBar} is not set:
            MindFlayCast({_p}, 3 seconds, {_target})
            set {_castBar} to true

        set {_ticks} to 0 seconds
        while {_tickTime} > {_ticks}:
            if {_totalTime} >= 3 seconds:
                stop sound "skill.therold.mindflay_channel" for (all players in radius 2 around {_p})
                stop sound "skill.therold.mindflay_channel_whisper" for (all players in radius 2 around {_p})
                clear metadata tag "channeling" of {_p}
                stop
            if {_target} is not alive:
                stop sound "skill.therold.mindflay_channel" for (all players in radius 2 around {_p})
                stop sound "skill.therold.mindflay_channel_whisper" for (all players in radius 2 around {_p})
                clear metadata tag "channeling" of {_p}
                stop
            wait 1 tick
            add 1 tick to {_ticks}
            add 1 tick to {_totalTime}
            if loop-counter-2 is divisible by 3:
                MindFlayVisual({_p}, {_target})

        clear {_ticks}
        add 1 to {_totalTicks}
            
function MindFlayCast(p: player, seconds: timespan, target: entity):
    while metadata tag "channeling" of {_p} is set:
        set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
        set {_insanityDrain} to 6 + 0.68*{_voidformStacks}
        set {_insanityInfo} to "Insanity: %round({insanity::%{_p}%}, 0)%"
        if metadata tag "Voidform" of {_p} is set:
            set {_insanityInfo} to "%{_insanityInfo}%   %round({_insanityDrain}, 1)%p/s    %{_voidformStacks}%"
        if (string tag "Talents;Row 3" of (custom nbt of {karta::%{_p}%})) = "Lingering Insanity":
            if {lingeringInsanityHaste::%{_p}%} is set:
                set {_insanityInfo} to "%{_insanityInfo}% |  %{lingeringInsanityHaste::%{_p}%}/4%%% "
        set {_sec} to "%{_seconds}%"
        replace all " seconds" and " second" in {_sec} with ""
        set {_sec} to {_sec} parsed as number
        send action bar "Channeling... %round({_sec}, 1)% sec | %{_insanityInfo}%" to {_p}
        wait 1 tick
        remove 1 tick from {_seconds}
        stop loop if {_target} is not alive
    #send action bar "Channeling... 0 seconds | %{_insanityInfo}%" to {_p}

function VampiricTouch(p: player, target: entity):
    while metadata tag "Vampiric Touch-%{_p}%" of {_target} is set:
        if {_target} is alive:
            set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
            if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
                set {_VPTDuration} to 21
            else:
                set {_VPTDuration} to 18
            set {_crit} to CriticalHit({_p})
            set {_damage} to (1.5 + (({damage::%{_p}%}/62) + ({versatility::%{_p}%}/186) + {primarystat::%{_p}%}/31)) * (1.096 + (({mastery::%{_p}%}/6.25)/100))
            set {_casttimeVT} to 1.5/{_pospiech}
            set {_totalTicks} to (round({_VPTDuration}/(3/{_pospiech}), 0))
            if offensiveTrait({_p}, "Brother Therold", "Touch of Darkness") > 0:
                set {_touchOfDarkness} to offensiveTrait({_p}, "Brother Therold", "Touch of Darkness")
                add {_touchOfDarkness}/{_totalTicks} to {_damage}
                chance of 8%:
                    touchOfDarkness({_p})
            if (string tag "Talents;Row 4" of (custom nbt of {karta::%{_p}%})) = "San'Layn":
                set {_damage} to {_damage}*1.2
            if metadata tag "Voidform" of {_p} is set:
                set {_damage} to {_damage}*1.2
            if boolean tag "Constellation;Mass Hysteria" of (custom nbt of {karta::%{_p}%}) is set:
                set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
                set {_damage} to {_damage}*(1 + ({_voidformStacks}/100))
            loop all items in the inventory of {_p}:
                if boolean tag "Vampiric Touch" of (custom nbt of loop-item) = true:
                    set {_lore} to "&8Basic Ability%nl%&f%{_casttimeVT}% second cast%nl%&7No cooldown%nl%&7Use: &fRMB%nl%<##613e82>A touch of darkness that causes &f%(1 + {_totalTicks})*{_damage}%  <##431d53>Ghost%nl%<##613e82>damage over &f%{_VPTDuration}% sec<##613e82>, and <##8165a6>heals <##613e82>the priest for%nl%&f10%% <##613e82>of damage dealt.%nl% %nl%&fGenerates 6 Insanity."
                    set lore of loop-item to {_lore}
            set {_target}'s last damage cause to sweep attack
            set metadata tag "Element" of {_p} to "Ghost"
            set metadata tag "LastDamageCause" of {_target} to "<##462566>Vampiric Touch"
            set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
            set {_damage} to Crit({_p}, {_target}, {_crit}, {_damage})
            make {_p} damage {_target} by {_damage}*2
            set {_heal} to 0.1*{_damage}
            set {_heal} to selfHealModifiers({_p}, {_heal})
            if {_p} is alive:
                Heal({_p}, {_p}, {_heal}, "Vampiric Touch", "<##613e82>", {_lore}, false)
                if {_heal} > 0:
                    add {_heal} to {_healTotal}
            set {_tickTime} to "%3/{_pospiech}% seconds" parsed as timespan
            wait {_tickTime}
        else:
            clear metadata tag "Vampiric Touch-%{_p}%" of {_target}
            stop loop
    if {_healTotal} > 0:
        send formatted "%{kartacolor::%{_p}%}%%{_p}% &fhealed you. <tooltip:<##613e82>Vampiric Touch%nl%%{_lore}%>(<##baff8c>+%{_healTotal}% HP&f)" to {_p}

function VampiricTouchExpire(p: player, target: entity):
    if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
        set {_duration} to 21
    else:
        set {_duration} to 18
    set {_height} to amountOfDots({_p}, {_target})
    set {_dots} to metadata tag "AmountOfDots%{_p}%" of {_target}
    while {_duration} > 0:
        if {_target} is alive:
            set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
            set {_tickTime} to "1 seconds" parsed as timespan
            if metadata tag "AmountOfDots%{_p}%" of {_target} < {_dots}:
                set {_height} to amountOfDots({_p}, {_target})
            dotsText(" %{_duration}%", {_p}, {_target}, (location {_height} above {_target}'s head), 0 seconds, {_tickTime})
            wait 1 second
            remove 1 from {_duration}
            if metadata tag "Vampiric Touch - Refresh-%{_p}%" of {_target} is set:
                if boolean tag "Constellation;Dark Evangelism" of (custom nbt of {karta::%{_p}%}) is set:
                    set {_duration} to 21
                else:
                    set {_duration} to 18
                clear metadata tag "Vampiric Touch - Refresh-%{_p}%" of {_target}
        else:
            stop loop
    clear metadata tag "Vampiric Touch-%{_p}%" of {_target}
    amountOfDotsSubtract({_p}, {_target})

function VampiricTouchRefresh(p: player, target: entity):
    if {_target} is alive:
        if metadata tag "Vampiric Touch-%{_p}%" of {_target} is set:
            set metadata tag "Vampiric Touch - Refresh-%{_p}%" of {_target} to true

function ShadowyApparitionSpawn(p: player, target: entity):
    if {_p}'s world = {_target}'s world:
        if distance between {_p} and {_target} < 300:
            spawn 1 bee at {_p}
            set boolean tag "Silent" of nbt of last spawned bee to true
            set the name of last spawned bee to "Shadowy Apparition"
            set string tag "ECSummoned" of (custom nbt of last spawned bee) to uuid of {_p}
            set boolean tag "TargetableByAllies" of (custom nbt of last spawned bee) to false
            set boolean tag "RemoveOnReset" of (custom nbt of last spawned bee) to true
            set {_shadowyApparition} to last spawned bee
            ShadowyApparitionFloat({_p}, {_shadowyApparition}, {_target})
            ShadowyApparitionVisual({_shadowyApparition})
            play sound "skill.therold.shadowy_apparitions" with volume 2 and pitch 1 at (location of {_p})
            if cooldown "Shadowy Apparition Sound-%{_p}%" is finished:
                set {_pitch} to a random number between 0.8 and 1.1
                play sound "skill.therold.shadowy_apparitions_whisper" with volume 2 and pitch {_pitch} at {_p}
                set {_random} to a random number between 1 and 1.5
                create cooldown "Shadowy Apparition Sound-%{_p}%" for ("%{_random}% seconds" parsed as timespan)
    #stop
    #set {_l} to location 0.3 blocks below {_p}'s head
    #set {_l} to location 0.4 blocks right of {_l}
    #set {_v} to vector between {_l} and {_target}'s head
    #loop round(distance between {_l} and {_target}) / 0.2 times:
    #    set {_v} to vector between {_l} and {_target}'s head
    #    set vector length of {_v} to loop-value * 0.2
    #    draw 1 of dust using dustOption(rgb(70, 56, 107), 1) at {_l} ~ {_v} with offset vector(0.125, 0.125, 0.125) with extra 0.02
    #    wait 1 tick
    #if {_target} is alive:
    #    set {_damage} to 1 + {mastery::%{_p}%/32}
    #    set {_target}'s last damage cause to sweep attack
    #    set {_lore}
    #    set metadata tag "LastDamageCauseEN" of {_target} to "<##462566>Shadowy Apparitions"
    #    set metadata tag "LastDamageCause" of {_target} to "<##462566>Cieniste Aparycje"
    #    set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
    #    set metadata tag "LastDamageCauseLoreEN" of {_target} to {_lore}
    #    make {_p} damage {_target} by {_damage}*2

function ShadowyApparitionFloat(p: player, apparition: entity, target: entity):
    while distance between {_apparition} and {_target} > 2:
        make {_apparition} pathfind to {_target}
        {_apparition}.setFlower(null)
        wait 5 ticks
        stop loop if {_target} is not alive
    if {_target} is alive:
        set {_damage} to (0.8 + (({damage::%{_p}%}/65.5) + ({versatility::%{_p}%}/196.5) + {primarystat::%{_p}%}/32.75))
        if metadata tag "Vampiric Touch-%{_p}%" of {_target} is set:
            add offensiveTrait({_p}, "Brother Therold", "Spiteful Apparitions") to {_damage}
        if (string tag "Talents;Row 4" of (custom nbt of {karta::%{_p}%})) = "Auspicious Spirits":
            set {_damage} to {_damage}*2
            GrantInsanity({_p}, 3)
            UpdateInsanity({_p})
        if metadata tag "Voidform" of {_p} is set:
            set {_damage} to {_damage}*1.2
        if boolean tag "Constellation;Haunting Apparitions" of (custom nbt of {karta::%{_p}%}) is set:
            set {_damage} to {_damage} * (1.096 + (({mastery::%{_p}%}/6.25)/100))
            set {_crit} to CriticalHit({_p})
        if boolean tag "Constellation;Mass Hysteria" of (custom nbt of {karta::%{_p}%}) is set:
            set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
            set {_damage} to {_damage}*(1 + ({_voidformStacks}/100))
        if boolean tag "Constellation;Unleash the Shadows" of (custom nbt of {karta::%{_p}%}) is set:
            set {_voidformStacks} to metadata tag "Voidform Stacks" of {_p}
            set {_damage} to {_damage}*(1 + (({_voidformStacks}/100)*3))
        set {_target}'s last damage cause to sweep attack
        set {_lore} to "&8Passive Ability%nl%&fNo cast%nl%&7Cooldown: &8 &fnone%nl%&7Use: &fPASSIVE%nl%<##613e82>When your &f <##8165a6>Shadow Word: Pain <##613e82>damage%nl%<##613e82>over time <##8165a6> Critically Strikes<##613e82>, you also create%nl%<##613e82>a shadowy version of yourself that floats%nl%<##613e82>towards the target and deals &f%{_damage}%  <##431d53>Ghost%nl%<##613e82>damage."
        set metadata tag "Element" of {_p} to "Ghost"
        set metadata tag "LastDamageCause" of {_target} to "<##462566>Shadowy Apparitions"
        set metadata tag "LastDamageCauseLore" of {_target} to {_lore}
        if {_crit} is set:
            set {_damage} to Crit({_p}, {_target}, {_crit}, {_damage})
        make {_p} damage {_target} by {_damage}*2
        if boolean tag "Constellation;Heir to the Darkness" of (custom nbt of {karta::%{_p}%}) is set:
            if metadata tag "Heir to the Darkness" of {_p} < 300:
                add 1 to metadata tag "Heir to the Darkness" of {_p}
                buffRegister({_p}, "Heir", 4, "", "Stacks", "%(metadata tag "Heir to the Darkness" of {_p})%%%", "-")
        loop all items in the inventory of {_p}:
            if boolean tag "Shadowy Apparitions" of (custom nbt of loop-item) = true:
                set lore of loop-item to {_lore}
    teleport {_apparition} to location(0, -100, 0)
    kill {_apparition}

function ShadowyApparitionVisual(apparition: entity):
    while {_apparition} is alive:
        draw 2 of (((rgb(77, 54, 138) dust particle of size 1) with an extra value of 0.03) with offset vector(0.125, 0.125, 0.125)) at (location 0.3 above {_apparition})
        wait 1 tick

function StopCastSoundTherold(p: player):
    set {_ability} to metadata tag "lastspellTherold" of {_p}
    if {_ability} = "Mind Blast":
        stop sound "skill.therold.mind_blast_precast" for (all players in radius 2 around {_p})
    else if {_ability} = "Void Eruption":
        stop sound "skill.therold.void_eruption_precast" for (all players in radius 2 around {_p})
    else if {_ability} = "Mind Flay":
        stop sound "skill.therold.mindflay_channel" for all players
        stop sound "skill.therold.mindflay_channel_whisper" for (all players in radius 2 around {_p})
    else if {_ability} = "Vampiric Touch":
        stop sound "skill.therold.mindflay_channel_whisper" for (all players in radius 2 around {_p})
    else if {_ability} = "Shadow Word: Void":
        stop sound "skill.therold.shadow_word_void_precast" for (all players in radius 2 around {_p})

function TheroldDamage(p: player, basevalue: number, damageStat: number, damageScaling: number, versStat: number, versScaling: number) :: number:
    set {_damage} to {_basevalue} + ({damage::%{_p}%}/{_damageScaling}) + ({versatility::%{_p}%}/{_versScaling})
    if metadata tag "Voidform" of {_p} is set:
        set {_damage} to {_damage}*1.2
    return {_damage}

function CheckIfDotted(p: player, target: entity) :: boolean:
    if metadata tag "Shadow Word: Pain-%{_p}%" of {_target} is set:
        set {_bool} to true
    if metadata tag "Vampiric Touch-%{_p}%" of {_target} is set:
        set {_bool} to true
    if {_bool} is not set:
        set {_bool} to false
    return {_bool}

function TwistOfFate(p: player):
    if metadata tag "TwistOfFate" of {_p} is true:
        set metadata tag "TwistOfFate" of {_p} to false
        while metadata tag "TwistOfFateDuration" of {_p} > 0 seconds:
            set {_duration} to metadata tag "TwistOfFateDuration" of {_p}
            buffRegister({_p}, "Twist", 1, "", "-", "-", durationShort("%{_duration}%"))
            remove 1 second from {_duration}
            set metadata tag "TwistOfFateDuration" of {_p} to {_duration}
            wait 1 second
            if 0 seconds >= metadata tag "TwistOfFateDuration" of {_p}:
                clear metadata tag "TwistOfFateDuration" of {_p}
                clear metadata tag "TwistOfFate" of {_p}
                buffClear({_p}, "Twist")
                stop loop

function ShadowWordVoidRecharge(p: player, cd: timespan):
    wait {_cd}
    set {_charges} to metadata tag "ShadowWordVoidCharges" of {_p}
    add 1 to {_charges}
    set metadata tag "ShadowWordVoidCharges" of {_p} to {_charges}
    loop all items in the inventory of {_p}:
        if boolean tag "Shadow Word: Void" of (custom nbt of (1 of loop-item)) = true:
            if {_charges} > 0:
                set item amount of loop-item to {_charges}
                if {_charges} = 1:
                    set line 2 of lore of loop-item to "&f%{_charges}% Charge"
                else:
                    set line 2 of lore of loop-item to "&f%{_charges}% Charges"
                reset item cooldown of loop-item for {_p}
                clear cooldown "Shadow Word: Void%{_p}%"
            else:
                set line 2 of lore of loop-item to "&f%{_charges}% Charges"
            stop loop

function MindBlastRecharge(p: player, cd: timespan):
    wait {_cd}
    set {_charges} to metadata tag "MindBlastCharges" of {_p}
    add 1 to {_charges}
    set metadata tag "MindBlastCharges" of {_p} to {_charges}
    loop all items in the inventory of {_p}:
        if boolean tag "Mind Blast" of (custom nbt of (1 of loop-item)) = true:
            if {_charges} > 0:
                set item amount of loop-item to {_charges}
                if {_charges} = 1:
                    set line 2 of lore of loop-item to "&f%{_charges}% Charge"
                else:
                    set line 2 of lore of loop-item to "&f%{_charges}% Charges"
                reset item cooldown of loop-item for {_p}
                clear cooldown "Mind Blast%{_p}%"
            else:
                set line 2 of lore of loop-item to "&f%{_charges}% Charges"
            stop loop

function VoidRay(p: player):
    if metadata tag "VoidRayStacks" of {_p} is set:
        while metadata tag "VoidRayDuration" of {_p} > 0 seconds:
            set {_duration} to metadata tag "VoidRayDuration" of {_p}
            buffRegister({_p}, "Void Ray", 1, "", "Stacks", "%metadata tag "VoidRayStacks" of {_p}%", durationShort("%{_duration}%"))
            remove 1 second from {_duration}
            set metadata tag "VoidRayDuration" of {_p} to {_duration}
            wait 1 second
            if 0 seconds >= metadata tag "VoidRayDuration" of {_p}:
                clear metadata tag "VoidRayDuration" of {_p}
                clear metadata tag "VoidRayStacks" of {_p}
                buffClear({_p}, "Void Ray")
                stop loop 

function Mania(p: player):
    if (string tag "Talents;Row 2" of (custom nbt of {karta::%{_p}%})) = "Mania":
        set {_speedBuff} to 1 + ({insanity::%{_p}%}/5)/100
        playerMoveSpeedUpdate({_p})
        set {_p}'s walking speed to ({_p}'s walking speed)*{_speedBuff}
        set {_p}'s flying speed to ({_p}'s walking speed)*{_speedBuff}
        buffRegister({_p}, "Mania", 1, "", "Value", "%{insanity::%{_p}%}/5%%% ", "-")
            
function LingeringInsanity(p: player):
    while {lingeringInsanityHaste::%{_p}%} > 0:
        buffRegister({_p}, "Lingering", 2, "", "Value", "%{lingeringInsanityHaste::%{_p}%}% ", "-")
        wait 2 seconds
        if {hasteVoidform::%{_p}%} - 4 > 0:
            set {hasteVoidform::%{_p}%} to {hasteVoidform::%{_p}%} - 4
        else:
            set {hasteVoidform::%{_p}%} to 0
        set {lingeringInsanityHaste::%{_p}%} to {lingeringInsanityHaste::%{_p}%} - 4
    clear metadata tag "LingeringInsanity" of {_p}
    clear {lingeringInsanityHaste::%{_p}%}
    buffClear({_p}, "Lingering")

function ShadowWordDeathRecharge(p: player, cd: timespan):
    wait {_cd}
    set {_charges} to metadata tag "ShadowWordDeathCharges" of {_p}
    add 1 to {_charges}
    set metadata tag "ShadowWordDeathCharges" of {_p} to {_charges}
    loop all items in the inventory of {_p}:
        if boolean tag "Shadow Word: Death" of (custom nbt of (1 of loop-item)) = true:
            if {_charges} > 0:
                set item amount of loop-item to {_charges}
                if {_charges} = 1:
                    set line 2 of lore of loop-item to "&f%{_charges}% Charge"
                else:
                    set line 2 of lore of loop-item to "&f%{_charges}% Charges"
                reset item cooldown of loop-item for {_p}
            else:
                set line 2 of lore of loop-item to "&f%{_charges}% Charges"
            stop loop
    
function ShadowyInsight(p: player):
    send title " " with subtitle "" to {_p} for 1 minute with fade in 0.25 second and fade out 0 second
    set metadata tag "ShadowyInsight" of {_p} to true
    play sound "skill.therold.shadowy_insight_proc" with volume 2 and pitch 1 at (location of {_p})
    clear cooldown "Mind Blast%{_p}%"
    clear cooldown "Shadow Word: Void%{_p}%"
    set {_time} to 60 seconds
    loop all items in the inventory of {_p}:
        if boolean tag "Mind Blast" of (custom nbt of (1 of loop-item)) = true:
            reset item cooldown of loop-item for {_p}
        else if boolean tag "Shadow Word: Void" of (custom nbt of (1 of loop-item)) = true:
            reset item cooldown of loop-item for {_p}
    while metadata tag "ShadowyInsight" of {_p} = true:
        wait 1 second
        remove 1 second from {_time}
        stop loop if 0 seconds >= {_time}
    send title " " with subtitle " " to {_p} for 1 second with fade in 0.0 second and fade out 0.0 second

function isCastableTherold(p: player) :: boolean:
    if metadata tag "ShadowyInsight" of {_p} = true:
        set {_castable} to true
    else:
        if (string tag "Talents;Row 1" of (custom nbt of {karta::%{_p}%})) = "Shadow Word: Void":
            if metadata tag "ShadowWordVoidCharges" of {_p} > 0:
                set {_castable} to true
        else:
            if metadata tag "MindBlastCharges" of {_p} > 0:
                set {_castable} to true
    if {_castable} is not set:
        set {_castable} to false
    return {_castable}

function chorusOfInsanity(p: player, voidformStacks: integer):
    set {_itemLevels::*} to getTrait({_p}, "Chorus of Insanity")
    if {_itemLevels::*} is set:
        set {_voidformStacks} to 20 if {_voidformStacks} > 20
        if metadata tag "ChorusOfInsanity" of {_p} is not set:
            set {_crit} to chorusOfInsanityCrit({_p}, {_itemLevels::*}, {_voidformStacks})
            while metadata tag "ChorusOfInsanity" of {_p} > 0 seconds:
                set {_duration} to "%metadata tag "ChorusOfInsanity" of {_p}%"
                set {_roundedCrit} to round(metadata tag "ChorusOfInsanityCrit" of {_p}, 0)
                buffRegister({_p}, "Chorus", 1, "", "Stacks", "%{_roundedCrit}% ", durationShort({_duration}))
                wait 1 second
                remove {_crit}/20 from metadata tag "ChorusOfInsanityCrit" of {_p}
                remove 1 second from metadata tag "ChorusOfInsanity" of {_p}
            clear metadata tag "ChorusOfInsanity" of {_p}
            clear metadata tag "ChorusOfInsanityCrit" of {_p}
            buffClear({_p}, "Chorus")
        else:
            chorusOfInsanityCrit({_p}, {_itemLevels::*}, {_voidformStacks})

function chorusOfInsanityCrit(p: player, itemLevels: integers, voidformStacks: integer) :: integer:
    set {_critPerStack} to yaml value "Brother Therold.Offensive.Chorus of Insanity.Stat" in "TraitList"
    set {_scaling} to yaml value "Brother Therold.Offensive.Chorus of Insanity.Stat Scaling" in "TraitList"
    set {_lowestIlvl} to yaml value "Azerite Armor.Minimum Values.Item Level" in "AzeriteArmorSources"
    loop {_itemLevels::*}:
        if loop-value > {_lowestIlvl}:
            add ((loop-value-{_lowestIlvl})*{_scaling}) to {_critPerStack}
    set {_crit} to round(({_critPerStack}*{_voidformStacks}), 0)
    set metadata tag "ChorusOfInsanity" of {_p} to 20 seconds
    set metadata tag "ChorusOfInsanityCrit" of {_p} to {_crit}
    return {_crit}

function touchOfDarkness(p: player):
    set metadata tag "TouchOfDarknessTicks" of {_p} to 0
    if metadata tag "TouchOfDarkness" of {_p} is not set:
        set metadata tag "TouchOfDarkness" of {_p} to 20 seconds
        while metadata tag "TouchOfDarkness" of {_p} > 0 seconds:
            set {_duration} to "%metadata tag "TouchOfDarkness" of {_p}%"
            buffRegister({_p}, "Touch", 2, "", "Value", "-", durationShort({_duration}))
            wait 1 second
            stop if metadata tag "TouchOfDarkness" of {_p} is not set
            remove 1 second from (metadata tag "TouchOfDarkness" of {_p})
        clear metadata tag "TouchOfDarknessTicks" of {_p}
    else:
        set metadata tag "TouchOfDarkness" of {_p} to 20 seconds

function sinisterThoughts(p: player):
    if metadata tag "Voidform" of {_p} is not set:
        set metadata tag "SinisterThoughts" of {_p} to true
        set {_pospiech} to Haste({_p}) + (({hasteVoidform::%{_p}%}/4)/100)
        loop all items in the inventory of {_p}:
            if boolean tag "Void Eruption" of (custom nbt of loop-item) = true:
                set {_cd} to "%4.5/{_pospiech}% seconds" parsed as timespan
                set {_damage} to (3 + (({damage::%{_p}%}/15) + ({versatility::%{_p}%}/45)))
                set {_lore} to "&8Ultimate Ability%nl%&fInstant cast%nl%&7Cooldown:  &f%{_cd}%%nl%&7Use: &fRMB%nl%<##613e82>Sends a bolt of pure void energy at the%nl%<##613e82>enemy, causing &f%{_damage}%  <##431d53>Ghost <##613e82>damage and%nl%<##8165a6>extending <##613e82>the duration of &f <##8165a6>Shadow Word:%nl%<##8165a6>Pain <##613e82>and &f <##8165a6>Vampiric Touch <##613e82>to their original%nl%<##613e82>duration.%nl% %nl%<##613e82>Requires &f <##8165a6>Voidform<##613e82>.%nl% %nl%&fGenerates 16 Insanity."
                set {_voidBolt} to (black dye named "<##613e82>Void Bolt") with lore {_lore}
                add nbt from ("{""minecraft:custom_model_data"":{floats:[3.0f]},""minecraft:custom_data"":{""Void Bolt"":1b}}") to (nbt of {_voidBolt})
                set loop-item to {_voidBolt}

function dotsText(t: text, p: player, e: entity, loc: location, wait: timespan, waitDelete: timespan):
    wait {_wait}

    set {_id} to a random integer between 1 and 999999999999999999

    spawn fake text display at (location 0.25 above {_loc}) for {_p} with id {_id}

    set {_packet} to new metadata packet with id {_id}:
        display text: {_t}
        display billboard: center
        display brightness block: 15
        display brightness sky: 15
        display seethrough: true
    send packet {_packet} to {_p}

    wait ({_waitDelete})
    remove fake entity with id {_id} for {_p}

on inventory click:
    if metadata tag "Voidform" of player is set:
        if boolean tag "Void Bolt" of (custom nbt of event-slot) is set:
            cancel event
on drop:
    if boolean tag "Void Bolt" of (custom nbt of event-item) is set:
        cancel event