- uses: sarisia/actions-status-discord@v1
  if: always()
  with:
    webhook: ${{ secrets.DISCORD_WEBHOOK }}
    nodetail: true
    title: "Test"
    description: |
      Test (${{ github.event.push.commits[][message] }})
    color: 0xff91a4
